### ISSUE TITLE
Excel: autofitColumns() autofits the width according to the whole column's content's length rather than current page's

### ISSUE THREAD

**Issue by hyzhang** [OfficeDev/office-js#1017]
autofitColumns's doc is Changes the width of the columns of the current range to achieve the best fit, based on the current data in the columns. Although it's based on data in the columns, but it also says changes the width of the current range

Example: if I input a long string 'aaaaaaaaaaaaa' in A1, and input 'aa' in A2, and ctx.workbook.worksheets.getActiveWorksheet().getRange(`A2`).format.autofitColumns(); but the width is autofit by the width of A1 because A1 and A2 are both in A column, what I want is it autofits the width by A2, namely the range I specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef68ce74-1a4a-eadf-83a6-4c5dabcf7e0d
* Version Independent ID: 70e47dac-a221-9025-7cfe-8e442cb08c73
* Content: [Excel.RangeFormat class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.rangeformat?view=excel-js-preview#methods)
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.rangeformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.rangeformat.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Moving this issue to the office-js repo because it is really a technical issue, rather than an error in the documentation.

**Comment by lumine2008** [comment]
Thanks, I can repro this issue, I think our behavior API aligned with when double click the resizable button in column, it will resize according to the content of the whole column.

A bug(#3984867) was created to track this issue, Team is investigation on it.

**Comment by lumine2008** [comment]
We convert this bug as feature backlog

**Comment by theboyknowsclass** [comment]
Hi is there any update on this issue... it's quite important

**Comment by donlvMSFT** [comment]
Hi there, sorry for delay response on this channel. We had internal investigation for this issue and found this should be a by-design behavior, as currently the auto-fit would follow the entire row/column behavior in Excel.

@theboyknowsclass , could you share more about your scenario and impact? That would help us learn more information. I'd also suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question for the feature request.

Thanks!

**Comment by wh1t3cAt1k** [comment]
@donlvMSFT we are also affected and it's quite inconvenient!

Consider this scenario:

![image](https://github.com/OfficeDev/office-js/assets/5159662/26e87d99-2abc-4c45-acd0-863857407fc1)

We dynamically generate the table in a user-specified cell in the workbook and want to auto-fit only according to the table contents, ignoring everything else. We select just the table for auto-fitting but in the example above, because of another text on the worksheet (which we don't even care about) the first column is ugly & wide.

I would object against calling this a feature request, but rather an inconsistency bug. The equivalent VBA method clearly distinguishes its behaviour based on whether you selected entire columns or a particular range: https://learn.microsoft.com/en-us/office/vba/api/excel.range.autofit

[Velixo internal reference](https://3.basecamp.com/3496385/buckets/16689259/card_tables/cards/7009158011)

**Comment by adrianwu8516** [comment]
Hi @hyzhang, @wh1t3cAt1k , 

Since this is a by-design behavior and changing it will cause behavior changes that break scenarios that already use this feature, I have added [a feature request (4217532)](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/add-parameter-to-autofitcolumns-for-aligning-to-current-or/idi-p/4217532#M2665) to the tech community for tracking. For people who have similar requests, please help us vote in the Tech Community so that more people can join the discussion and share their feedback.

**Comment by FelipeCostaGualberto** [comment]
Hello, this functionality has a bug, please reopen it.
VSTO and VBA behaves as expected. Office JS should also work.

**Comment by RuizhiSunMS** [comment]
Hi @FelipeCostaGualberto , here we suggest you open a new one and link this case in yours. Please attach enough information (filling out our template is the best practice) if you really open your own one.
