### ISSUE TITLE
SecurityError when working with websockets

### ISSUE THREAD

**Issue by technicallyty** [OfficeDev/office-js#1018]
I'm creating an excel addin using officejs. I am trying to build something that uses websockets to receive data. I am getting an ambiguous error when doing so though. All it says is Error: Security error. I believe this is happening due to implicit SSL/TLS requirements by the IE/Edge browser process that runs in officejs taskpane addins. With many other programs such as electron - you are able to disable websecurity. Is there an option similar to this? I'm simple using websockets to make excel talk to my other application over localhost. Is there a reason for the strict SSL/TLS requirement on this?  
## Expected Behavior

I expected a more fleshed out error message, or at least a conenction.
## Current Behavior

I get the Error: SecuirtyError.

## Steps to Reproduce, or Live Example

create an excel addin and create a websocket. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Windows 7
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: newest
* Operating System: win7

I would direct this to stackoverflow as it's more of a question but upon searching for questions tagged with office-js i notice "737 questions with no answers." 

Edit: i noticed you can right click your task pane and select security info. It brings up the dialog in the image below. This leads me to believe there must be a way to disable to SSL so i can allow my unsecure websocket to talk to excel. 
![image](https://user-images.githubusercontent.com/48813565/75595006-a5d72000-5a3f-11ea-90de-c3e0aae88612.png)

**Comment by gujacob** [comment]
Hi,

I'm also trying to open a websocket from my addin, but the sample you provide on the page only logs the data received to the console, while what i need is to use the messages cumming from the socket as responses for customFunctions.. 

Suppose i'm developing a addin that will stream real time data from a server to excel. The idea is that the user will use functions like `=MYDOMAIN.SUBSCRIBE(channel1, itemName)` an a cell.
He can have the same item subscribed in more than one cell.

If the channel is already subscribed,  i just want  to register a handler so that if a message for this item arrives, i will forward it to  the custom function using the invocation.setResult().

If  the channel is not subscribed i need to subscribe the channel and register the same handler..

Can someone help me with this?

Thanks a lot!!

**Comment by devilwacause** [comment]
Also have this problem.  The websocket cannot be accessed.  And right clicking the error and selecting  security info always displays the azureedge.net connection for script-lab rather than the actual ws connection I'm trying to make.

**Comment by juangburgos** [comment]
Having this same issue. Can enable SSL, but complicates matters in debug environment.
