### ISSUE TITLE
Remove script filename check

### ISSUE THREAD

**Issue by markb-trustifi** [OfficeDev/office-js#11]
## Expected Behavior
The "office.debug.js" should work as a part of a large file bundle.

## Current Behavior
I concat all scripts in one bundle file "lib.js" for a traffic optimization.
Because of that the script file name validation fails:
_Uncaught Office Web Extension script library file name should be office.js or office.debug.js._

## Steps to Reproduce, or Live Example
Change the script file name.

## Context
I concat all scripts in one bundle file "lib.js" for a network traffic optimization.
The solution is to remove the script filename check.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 365

**Comment by dylanjt** [comment]
Second this. Seems like an arbitrary check, and this really throws a wedge in a variety of dev environments (e.g. I'm using Webpack).

**Comment by kcthota** [comment]
+1

**Comment by dmahugh** [comment]
Closing this issue because it's a feature request, and feature requests are now being handled on User Voice here: [https://officespdev.uservoice.com/](https://officespdev.uservoice.com/). If you'd like to post a feature request there, others can upvote it and we're addressing those feature requests based on the number of upvotes.
