### ISSUE TITLE
Passing auth data from Add-in to Power BI without persistent storage in Worksheet

### ISSUE THREAD

**Issue by mike-code** [OfficeDev/office-js#1102]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
Thank you for your understanding and continued feedback.

I've put up a question on SO with bounty but unfortunately it didn't get any attention and I think it's a valid use case

**tl;dr version** : I have OAuth flow in my Add-In that returns bearer token. Now I want to use this bearer token in my PowerBI/PowerQuery connections. 

The only solution I managed to figure out was to create custom Excel function which I can then call inside a Cell and make powerBI read token from this cell. This is crappy solution because bearer token will remain in the workbook. Also those custom functions are async and dunno how powerBI will react to it in some cases. 

Another, yet very crude method would be to spin up a webserver using VBA and make Add-In send this token to that webserver and then make powerBI query that server for the token. Sounds like there'll be tons of permissions problems on some unprivileged windows accounts, macro workbooks triggering AV rules and whatnot.

Original question:
https://stackoverflow.com/questions/61001991/passing-data-from-office-js-storage-to-queries-and-connections

**Comment by mike-code** [comment]
@gergzk could you link docs or PR that resolved this issue?

**Comment by gergzk** [comment]
Hi @mike-code - this issue was closed because it had been inactive for a long time. I'm actually not sure if it was fixed or not. We're doing this to try and get a handle on the issue volume in this repo so we can be more responsive to the issues that are open. 

If the issue has been fixed, I'm not sure what useful link I could give you to a PR. The code for office.js is not worked on in this public repo, this is just a mirror of the final built js files.
