### ISSUE TITLE
Refreshing conditional formatting

### ISSUE THREAD

**Issue by redcirkle** [OfficeDev/office-js#1157]
## Article URL
https://docs.microsoft.com/en-us/javascript/api/excel/excel.application?view=excel-js-preview

## Issue
We are building an Excel add-in that applies conditional formatting to some columns. Depending on input data, we shade the cells green. However, we notice that, if we copy-and-paste data into the sheet, the conditional formatting doesn't calculate right away. Here's an example artifact:
![image](https://user-images.githubusercontent.com/19576266/81242111-23c82200-8fc1-11ea-8dc5-2cd176b75b22.png)

The white portion of the column is visible as the user copies the data, and when we scroll over we see the rest of the column in green. It seems like the off-screen columns are formatting correctly, but not the on-screen part.

_Note: My issue is **not** with this artifacting. It's just to highlight how the conditional formatting doesn't update automatically, and our need for a programmatic solution._

We'd like to update the conditional formatting programmatically. In general, here are the solutions we've found:

- Switch context to another application (not sure why this one works, and definitely not an ideal solution, but interesting to note)
- run `app.suspendScreenUpdatingUntilNextSync();`

`app.suspendScreenUpdatingUntilNextSync();` does update the in-sheet conditional formatting, but it causes a "flicker" in our taskpane (because it suspends the screen update for a moment, hiding what was on the pane). Is there a different method we should call to update all in-sheet conditional formatting?

**Comment by AlexJerabek** [comment]
Hi @lumine2008 and @MandytMSFT,
Could either of you please take a look at this conditional formatting issue? It seems like the conditional formatting is not being reliably re-applied when new data is copy-and-pasted. 
Thanks!

**Comment by lumine2008** [comment]
@redcirkle could you kindly share us the scriptlab gist/snippet?  thanks

**Comment by lumine2008** [comment]
i am closing this issue, due to not repro in our side, please reopen, if you still observe this issue, thanks

**Comment by stenly311** [comment]
I ran into a very similar issue a couple of days back and I can confirm that still happening. 

The only detail I found to be crucial for being able to replicate this issue is to bulk-paste data into the cell which then makes the table exceed the current number of rows.

<img width="840" alt="conditional formatting rules - appendix to issue" src="https://user-images.githubusercontent.com/8539921/162118267-67258e20-0664-4a57-a115-893542a42ac0.png">

https://user-images.githubusercontent.com/8539921/162118304-334eb255-0be6-4a97-a863-7d536a9c2943.mp4

Any idea why this is happening? 
Is there any way how to "listen" to what the Excel app currently doing when it comes to conditional formatting?
Is there any way how to force the Worksheet to re-calculate with conditional formatting (I tried all options I found in the Office.js documentation in MSDN and none of them worked for me. Btw. clicking on "Calculate Worksheet" button in the "Formulas" tab in the Excel ribbon did the trick )?

**Comment by AlexJerabek** [comment]
Hi @stenly311,

Thanks you the details. I'll reopen this issue. @guliums, could you please take a look?

**Comment by stenly311** [comment]
No worries. Thanks guys for taking a second look at this.

However, this may actually be an issue caused by Excel itself as demonstrated in the video.
Moreover, I am able to run into the same faulty behaviour by populating new rows into the worksheet table from the code in Web Add-in app (Task pane).

Any help on codebases of how to force the worksheet to re-calculate conditional formatting is appreciated.

**Comment by AlexJerabek** [comment]
If you're able to recreate the issue in Excel alone, I'd recommend using Excel's "Send Feedback" mechanism. That'll capture some product data and route it to the right people.

**Comment by stenly311** [comment]
I will do. Thanks.
However, I still do think that there must be an issue in Office.js lib because of the inconsistency of how the button in Excel ribbon works compering to the function called by using Office.js (I am assuming that the same logic should be invoked).
Clicking on "Calculate Sheet" button in the ribbon fixes the conditional formatting issue.

`
let sheet = context.workbook.worksheets.getActiveWorksheet();
sheet.calculate()`

 vs

![image](https://user-images.githubusercontent.com/8539921/162339585-cdedbcf8-3af9-44d4-b7b4-a23941a4414f.png)

**Comment by JinghuiMS** [comment]
@stenly311 Could you provide your Excel workbook and steps to reproduce this issue by using sheet.calculate() API to help us repro this issue? Better to attach a repo video which used sheet.calculate() API. Thanks!

**Comment by stenly311** [comment]
Hi @JinghuiMS thanks for taking a look at this issue. 
I will appreciate any working idea of how to get over it :)

**Video how to replicate**: https://youtu.be/dD036p72Psc 
**Task pane UI**: Calculations solution from default github repo has been used in Script Lab
The workbook is attached.
[UI Spreadsheet 1 016-MS version 2.xlsx](https://github.com/OfficeDev/office-js/files/8518569/UI.Spreadsheet.1.016-MS.version.2.xlsx)

Let me know if having more questions. 
Martin.

**Comment by JinghuiMS** [comment]
@stenly311  
Thanks for reporting. BUG 5990610 has opened for internal track.

**Comment by stenly311** [comment]
Hi @JinghuiMS how are you? Just following up on this issue, any luck with the issue investigation?

Thank you. M.

**Comment by guliums** [comment]
Hi @stenly311 sorry for late response. Thanks very much for the detailed repro video and file, that is very helpful for us to confirm a bug that conditional format is not refreshed in some case. For your scenario, could you try worksheet.calculate(true) API which should work like the calculate button in ribbon. Please let me know if it does not work. Thanks!

async function run() {
  await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getActiveWorksheet();
    sheet.calculate(true);
    await context.sync();
  });
}

**Comment by stenly311** [comment]
Hi @guliums , 
thanks for sharing this script with me. 

However, the background colours of conditional formatting seem not to be working consistently after running it on the same workbook provided here initially.

Here is the vid of the test running by myself:

https://user-images.githubusercontent.com/8539921/168729562-c51ab735-afe6-4c96-85cd-c159e7be7284.mp4

Source code to use for ScriptLab: https://gist.github.com/stenly311/4c242adb32b9f1f62d4083469131ccf2

I was expecting to see conditional formatting working in the case of using this approach in the event of new rows in the worksheet table inserted/created. 

A new row added in the table seems to me to be the trigger of this issue.

Otherwise, there is no way how to detect when to call a sheet.calculate(true) function programmatically. 

Obviously doing it on every cell value commit would be a very bad design to follow.

Were you anyhow successful with the case investigation?

Thank you, Martin.

**Comment by stenly311** [comment]
Hi @guliums  any luck with the investigation? thanks

**Comment by stenly311** [comment]
Hi @guliums any luck with the investigation? thanks

**Comment by guliums** [comment]
Hi @stenly311 , sorry for late response. Excel team are actively working on the bug you reported that conditional format does not refresh automatically in this case, internally tracked by VSO 6043693. I will follow up and let you know when there are update. From API side, unfortunately I currently don't have a better solution other than call worksheet.calculate(true) every time on worksheet data change event... I agree it is not a good design but you could use it as temporary workaround before the bug fixed. Thanks for your support!

**Comment by stenly311** [comment]
Thanks @guliums . Looking forward to hearing from you on the ticket update.

**Comment by stenly311** [comment]
hi @guliums , I thought I am going to give you a short update on how using "worksheet.calculate(true)" works for us. 

Firstly, I was surprised by the Excel application performance lagging after calling this function in the Task pane app compared to the Excel native calculate sheet feature found upon this UI:
![image](https://user-images.githubusercontent.com/8539921/175187980-2c92c4c4-87de-4ad0-863b-4cb1b79a9bf6.png)
Calling "worksheet.calculate(true)" in web addin application (Task pane) takes between 5-15s, but (I am assuming this button invokes the same business logic behind the scenes) getting the active worksheet refreshed via clicking the button from the Excel ribbon only 1s.

Secondly, "worksheet.calculate(true)" does not fix the conditional formating issue every time compared to "calculate sheet" button in Excel.

Am I experiencing two separate on each other issues in the Office.js framework and the Excel application:
1. conditional formatting 
2. "worksheet.calculate(true)" does not re-calculate the whole worksheet the same way as the functionality attached to the UI button "Calculate Sheet" from the Excel ribbon (Formulas tab)?

Either way, the proposed solution for this issue does not fix the problem but brought the inconsistency into the feature behavior (based on end-user experience, using Task pane web Add-in as a product).

Could you assist and help me to find a better solution for this issue, please? 

Thank you, Martin.

**Comment by guliums** [comment]
Hi @stenly311 , sorry for the inconvenience. Do you have an example file that shows the worksheet.calculate(true) different with UI "Calculate Sheet"?

**Comment by sndurkin** [comment]
Hi @guliums, it looks like this issue was closed due to inactivity but it still seems to be a problem. Is there any update on when this will be fixed?
