### ISSUE TITLE
Content with tables inserted with insertOoxml() is sometimes altered

### ISSUE THREAD

**Issue by macote** [OfficeDev/office-js#116]
Content with tables inserted in a content control with insertOoxml() is sometimes altered in the end result. For example, if a single row, single cell, single paragraph table is inserted, a new paragraph gets inserted in the cell.

## Expected Behavior
The inserted content should be preserved as is when inserted in the target content control.

## Current Behavior
An undesirable paragraph is added to the inserted content.

## Steps to Reproduce, or Live Example
[Script Lab](https://gist.github.com/macote/cad281664cd3cff42eee6f066e065047)
  1. Click "Setup" to initialize the document with the desired result.
  2. Click "Run" to replace the content with corresponding OOXML.
  3. Inspect the content of the content control.

## Context
I'm developing a tool that replaces content control content. Dealing with documents having this structure represents a blocker for me, since I don't know how to workaround this problem.

## Your Environment
* Platform: PC desktop
* Host: Word
* Office version number: Office Click-to-Run Version 1804 (9226.2114)
* Operating System: Windows 10

## Useful logs
No errors are generated while experiencing this issue.

**Comment by hjkim-MSFT** [comment]
The issue is that the table intersects with the content control. Once this happens, the results of following operations are unpredictable. You could achieve the same goal without using content control. Here is a gist to demonstrate that.
https://gist.github.com/hjkim71/500d6a42187d6d9936112427fc22be39

I've noticed that the ooxml definition contains a table. If you want to use content control, the table should be inside the content control in setup phase. Here is a gist to do that.
https://gist.github.com/hjkim71/100fc760afac8df38c020e530f5a8a8d

Please let me know if either of the workarounds works for you.
