### ISSUE TITLE
How to use MSAL.js in Excel add-in using Officejs

### ISSUE THREAD

**Issue by Murugananths** [OfficeDev/office-js#1190]
Hi Team,

As of now we have been using office js helpers for authentication in Excel add-in login screen. Now we are planning move into MSAL.js integration since it can be achieved refresh token and all.

Below are the clarifications:
1) We used to refer the link **https://github.com/OfficeDev/PnP-OfficeAddins/blob/master/Samples/auth/Office-Add-in-Microsoft-Graph-React/login/login.ts** where configurations are there. Shall we use the sama parameters how it is used in office js helper?
2) We are having our own custom identity server for client id, and authority on which can it be used in MSAL as we dont have any registration in AAD.

**Comment by Rick-Kirkham** [comment]
This issue seems identical to the Stack issue: [/how-to-implement-msal-js-in-excel-add-in-using-officejs](https://stackoverflow.com/questions/62048722/how-to-implement-msal-js-in-excel-add-in-using-officejs). Please see my answer and the following comments there. In particular: 

> If you are implementing your own Identity service, then all we can offer is the general advice in the article [Authorize external services ...](https://docs.microsoft.com/office/dev/add-ins/develop/auth-external-add-ins), especially the section about Libraries, some of which are libraries for implementing an Identity service. Also, if you design the service to allow it's login page to open in an iframe, then users can login directly in the task pane. You don't need a login dialog.

Let's continue handling this in Stack because its really more of a programming question than a bug in the Office.js. I'll close this issue.
