### ISSUE TITLE
[Excel] [worksheet.table.add][Invalid argument] Getting generic error code with locale specific error message

### ISSUE THREAD

**Issue by arpit974** [OfficeDev/office-js#1199]
## Expected Behavior
We should get a distinct error code to handle the scenario on our end.

## Current Behavior
Currently on calling worksheet.table.add sometimes we get Invalid argument error with the error message a a table can't overlap another table(locale specific), we were trying to handle this scenario on our end but since this is specific to every language, are unable to.

## Steps to Reproduce, or Live Example
1. Try Calling worksheet.table.add on an empty cell which is already part of another table
2. Excel APi will return invalid argument error, with the error message as "A table can't overlap another table". Instead if there was a proper error code returned this could have been handled

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Desktop, Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Irrelavent
* Operating System: Windows 10
* Browser (if using Office Online): IE, Edge, Chrome, Firefox.

**Comment by lumine2008** [comment]
Thanks @arpit974, 
It looks like that you are asking to change from InvalidArgument to a new error type. i have logged an item `#4214632` to track this issue. 
Meanwhile, in order to support your scenario, here are 2 workarounds:
1) Travel `Worksheet.tableCollection` and figure out whether current selection is with in the `table.getRange()` or not 
2) Check the current selection and see whether it is overlap with a table by `range.getTables() `API

Please let me know if it can unblock with your scenario, thanks.
