### ISSUE TITLE
Office addin icon not visible for gmail account

### ISSUE THREAD

**Issue by Herz3h** [OfficeDev/office-js#1202]
## Expected Behavior
See the office-addin icon on Outlook for Windows when using a gmail account
## Current Behavior
The addin icon only appears for office account, never for gmail on Windows. On mac it appears for both.

## Steps to Reproduce, or Live Example
Install any addin.
Use a gmail account on Outlook Desktop for Windows 10.
No addin icon appears.

## Context
It should work the same way it does on Outlook Desktop for mac.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.12730.20252 64 bit (subscription outlook)
* Operating System: Windows 10

## Useful logs
No logs

**Comment by exextoc** [comment]
Add-ins are only supported on Exchange, Office 365, or Outlook.com account types. Gmail accounts are configured to connect with IMAP, which is why [add-ins will not load](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/add-in-requirements).

We track Outlook add-in feature requests on our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). Please add your request there. Feature requests on user-voice are considered, when we go through our planning process.
