### ISSUE TITLE
Setting 'From' address is Office 365 AddIn - Outlook (Web, MacOS, Android etc.)

### ISSUE THREAD

**Issue by aantimengocom** [OfficeDev/office-js#1235]
Hi,

I am working on an Outlook 365 Office Add In solution where it would be a great enhancement to the functionality and to the end product, if the Office Add-In API could set the ‘From’ address – in the same way as the “To, CC and BCC” is set. 

As of now; my findings are; that the current API does not support setting the ‘From’ value on the mailbox items.:
![image](https://user-images.githubusercontent.com/67316229/85388007-233b1900-b578-11ea-967a-e838abebad21.png)

My question is: Are there any way to enable me to set the ‘From’ address in order to send mails on behalf of another mailbox – and how is this achieved ? 

FYI: I have tried using the Graph API, to Patch the draft version of an email with a new “From” address – but it works only on a Draft version of the email – and the current mail in Compose view is not updated currently.

If there is no way to do this right now – will this then be possible in a later version of the API ?

**Comment by exextoc** [comment]
@aantimengocom this is not possible today because the add-in might not be installed for the account you're switching to. Changing the "from" address implies that you are switching to a different account. Add-ins that are not installed for an account will not be able to access its emails.

It is possible to change the "from" address _only_ if the add-in is installed for that account as well. Feel free to suggest this feature on our [user voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins).
