### ISSUE TITLE
Outlook: User is able to edit the email after sending till OnSend Addin is working

### ISSUE THREAD

**Issue by Premsagar-lab** [OfficeDev/office-js#1249]
OnSend addin is invoked when user tries to send email. OnSend addin tries to fetch data from compose mail using Office JS API which works asynchronously. In the mean time on main thread user is able to edit the email. 
Because of this OnSend addin worked on old body and updated email is sent through email

### Steps to reproduce issue:
1. Launch outlook and start composing email 
2. Add few attachments to email body 
![EmailCreation](https://user-images.githubusercontent.com/67500503/86437059-4789b900-bd21-11ea-976c-dbad77a0bb0a.png)
3. Send the email by adding recipient 
4. While Outlookaddin is working on files, remove few files from the email body and add new ones. (Please check below screenshot in which we removed attachment 1.xlsx before the email send and addin is in progress)
![AttachmentsUpdated](https://user-images.githubusercontent.com/67500503/86437118-6be59580-bd21-11ea-91ea-d6a4b74f9dbd.png)

### Current Behaviour
Mail is sent with new data without invoking onsend addin again.
We are able to edit email body, subject, recipients, attachments in the email. Email is sent with updated details. But onsend addin didn't get invoked again.

## Expected Behaviour
Behaviour shall be one of the following:
1. User should not be able to edit the email body till onsend addin is in progress  
2. Onsend addin should get be invoked everytime the user edits the email.

**Comment by lindalu-MSFT** [comment]
Hi @Premsagar-lab Please provide repro steps, files, platform details, screen shots, whatever you can so we can triage this issue!

**Comment by Premsagar-lab** [comment]
> Hi @Premsagar-lab Please provide repro steps, files, platform details, screen shots, whatever you can so we can triage this issue!

Updated the issue with screenshots and repro steps.

**Comment by exextoc** [comment]
Hi @Premsagar-lab , from your screenshots we presume the issue is on Outlook Mac. We are currently investigating this.

**Comment by Premsagar-lab** [comment]
Hi exextoc, Issue is on both OWA as well as Outlook for Mac.

**Comment by exextoc** [comment]
Hi @Premsagar-lab , from your screenshots it looks like the issue is on Mac Outlook. We are able to reproduce this and have copied it to our backlog. Thank you for reporting this. Unfortunately, we don't have timelines to share at this point.

**Comment by exextoc** [comment]
Thanks for the input. We will investigate this on OWA as well.

**Comment by exextoc** [comment]
**Correction :** This has been discovered to be the design of the feature. The user can interact with the form while any add-in is running. This is true of TaskPane, ExecuteFunction and OnSend Add-ins. However, OnSend Add-ins have an additional feature where, while the displayDialogAsync dialog is on the screen, the user will not be able to edit the original mail form. (clicks and keystrokes are disabled). This can be used if this functionality is desired. Please be sure to close the dialog when you have finished, and also account for what happens when the user closes the dialog. The close event can be captured and handled in your code.
**Note :**  For OWA there is an exception that if [displayInIframe](https://docs.microsoft.com/en-us/javascript/api/office/office.dialogoptions?view=word-js-preview#displayiniframe) is set to false , the dialog will open in new window and user can interact with the existing form. So displayInIframe should be set true for OWA.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding OnSend. We have put this issue in out backlog and are tracking work to improve the behavior. We unfortunately have no timelines to share at this point.

**Comment by Premsagar-lab** [comment]
Thanks @ElizabethSamuel-MSFT for answering. But user can still close the window and go for handling. It seems ShowDialogAsync does no more then js window.open(). There is no option to disable the close button on the displayed dialog.
