### ISSUE TITLE
Ribbon icon looks blurry in Windows at 175% scale

### ISSUE THREAD

**Issue by macote** [OfficeDev/office-js#128]
In the documentation, we found that it is possible to define [multiple sizes for icons](https://dev.office.com/reference/add-ins/manifest/icon) to support multiple display resolutions and scaling modes. However, according to this [post](https://stackoverflow.com/a/38443813), when the scaling mode is set to 175%, it is expected that Office will use a 56x56 icon (32 * 1.75), but it is not supported.

## Expected Behavior
Office JS ribbon support 56x56 icons.

## Current Behavior
Office JS ribbon doesn't support 56x56 icons.

## Environment
* Platform: PC desktop
* Host: Word
* Office version number: Office Click-to-Run Version 1804 (9226.2114)
* Operating System: Windows 10

**Comment by mlafleur** [comment]
This is because `56x56` isn't a supported icon size. Add-in commands support the following sizes (bolded are required):

- **`16x16`**
- `20x20`
- `24x24`
- **`32x32`**
- `40x40`
- `48x48`
- `64x64`
- **`80x80`**

Since there isn't an icon that matches, Office will attempt to scale one of the other icons your defined which is why it looks a little blurry.  

Which image sizes are you referencing in your manifest today?

**Comment by macote** [comment]
I defined all of them, with 56x56 as an extra hoping that Office was unofficially supporting it.

Is there any plans to support it or should I simply accept that my icons will look blurry at 175%?

Thanks.

**Comment by lliu113** [comment]
@macote so sorry for the late response. We currently do not have plans to support 56x56 icons. 

If 175% scale is a common user scenario for your add-in, feel free to submit a feature request for 56x56 icon support at https://officespdev.uservoice.com/

Thanks!
