### ISSUE TITLE
Office.context.mailbox.item.getSelectedRegExMatches() is not giving correct results.

### ISSUE THREAD

**Issue by niteeshkr20** [OfficeDev/office-js#1305]
In Contextual add in after defining a RegExp, if there is two or more matching strings are there in that case **Office.context.mailbox.item.getSelectedRegExMatches()** functions gives same result for selected matches for all the cases
## Expected Behavior

**Office.context.mailbox.item.getSelectedRegExMatches()** should give correct selected value on each case.
## Current Behavior

**Office.context.mailbox.item.getSelectedRegExMatches()** is giving same selected value for all the highlighted strings in one line.

## Steps to Reproduce, or Live Example

* Link to live example: https://github.com/OfficeDev/Outlook-Add-In-Contextual-Regex
## Context

I want correct selected value when I click on highlighted value.

## Your Environment

* Platform [Mac Desktop App]
* Host [Outlook]
* Office version number: @microsoft/office-js 1.1.43 

## Useful logs

- [ ] Console errors
- [ ] Screenshot
<img width="827" alt="Screenshot 2020-07-23 at 4 17 46 PM" src="https://user-images.githubusercontent.com/24302315/89015874-6d60a880-d335-11ea-9265-a4ddef0fd5c6.png">
s
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
We are able to reproduce this from our side. Thanks for reporting this issue regarding getSelectedRegExMatches. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by armukh** [comment]
@niteeshkr20 
Our engineers were not able to repro this issue using the Add-in shared by you. Can you please confirm if the issue is still there, is so please share the Mac Outlook version number? Also, it would be helpful if you can provide the exact text you are using that will help us to repro the bug.

**Comment by exextoc** [comment]
@niteeshkr20 
Our engineers were not able to repro this issue using the Add-in shared by you. Can you please confirm if the issue is still there, is so please share the Mac Outlook version number? Also, it would be helpful if you can provide the exact text you are using that will help us to repro the bug.

**Comment by niteeshkr20** [comment]
Hi @exextoc,

Not able to reproduce the issue anymore.

Thanks for the fix 👍
