### ISSUE TITLE
Deployment: Admin Center: Cannot un/install the add-in

### ISSUE THREAD

**Issue by sarea** [OfficeDev/office-js#1311]
I have add-in A which is hosted in `xyz.com/A/manifest.xml` and add-in B which is hosted in the same host but with another route `xyz.com/B/manifest.xml`. **Both** of those manifests use the same GUID.

I have installed the add-in A by URL from the admin center as 'optional' option, that works fine (after 12h), but then I was unable to uninstall it and install the add-in B as a user from the URL, so I removed the add-in A from the admin center, wait for 12h, that works, so don't see the add-in in the admin center add-ins list anymore, but I still have the add-in as user and I'm unable to uninstall it, to be specific when I go Get add-ins -> My add-ins, in the custom add-in section I click on the add-in and click remove, I see this error:

![Screenshot 2020-08-04 at 15 11 05](https://user-images.githubusercontent.com/16371285/89298285-699a9200-d665-11ea-8a67-18899a51518f.png)
and I see this in the console:

```
{
   "anonUID":"3ee12e36-652e-45fa-b1ae-760e11e918f7",
   "BillingRegion":"GB",
   "Browser":"Chrome84",
   "CID":"",
   "SourceClient":"WAC_Outlook",
   "OfficeVersion":"16.2130.0.9999",
   "ContentCulture":"en-GB",
   "CorrelationID":"11280613-d71f-49ce-a0e6-30aaf661b06e",
   "Domain":"store.office.com",
   "GateHashes":"282052946,1039894021,86226609",
   "GeographicRegion":"GB",
   "OperatingSystem":"MacOS",
   "ReferralUrl":"",
   "ServiceScope":"OutlookStoreService",
   "StateScope":"OutlookStore",
   "UICulture":"en-US",
   "UserAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
   "User_HashID":"2_BFcrieM9906eqQLbAqQJHu97wmEIi9X5deQbSkvF1lM=",
   "VerboseEnabled":"False",
   "OmexSession":"d4f9a970-3f62-4927-8458-a446e243929d",
   "NecessaryServiceDataEventTypes":[
      "ONREADY",
      "ONCLICK",
      "INCLIENTADDINSTATECHANGE",
      "PERFORMANCE",
      "TIMEMETRIC"
   ],
   "PageUrl":"https://store.office.com/gyro/client?client=WAC_Outlook&cv=16.2130.0.9999&ui=en-GB&rs=en-GB&timestamp=1596534477917&ep=ma&exchver=15.20.3239.22&privateenabled=true&cb=x&ClientSessionId=016baeaa-2f28-8432-327d-dd4060e890d2&userPuid=0&gates=Marketplace.Outlook.Pin.Addin.Options,Marketplace.Outlook.Pin.Addin.Calendar.Options#/privatedetails/8a612bdb-28b4-4cf5-ab69-100d0511cece",
   "BTS":"2020-08-04T09:51:10.059Z",
   "EventType":"Call to UninstallOutlookWebExt failed with response code: -1 and result: An internal server error occurred. The operation failed.,ErrorInternalServerError"
}
```
- Knowing that I was able to un/install add-in by URL with different manifest GUID.
- Those add-ins are not in the store as they have the on-send functionality
- I can install other add-ins that have a different ID and in another host.
### Env: 
Mac, Chrome, Outlook on web (modern), the minVersion of the manifest is 1.5

And I already did all "turn it off and on" stuff:) hard reload, clear cash, logout, etc.

**Comment by lindalu-MSFT** [comment]
Hi Lillian, I don't know if this is your area or Anil's. Do you know his Github handle? If so, please add him to the assignees. THANKS

**Comment by sarea** [comment]
Any news on this? we are blocked to perform our work:(

**Comment by exextoc** [comment]
Hi Sarea,
 
If addin A using GUID G1 and version say 1.0.0 is already installed and then you are trying to install addin B using same GUID and same version 1.0.0,it is expected that installation call will fail.This is because you can't deploy the same addin(with same GUID and same version)twice.Either you should upgrade the same addin.In this case you have to upgrade the version of already installed addin.
Here is the solution for your first problem
1. You deployed an addin A hosted at url XYZ.com using GUID G1 having version 1.0.0.0 (version is specified in manifest).
2. Now you can only deploy addin B hosted at URL ABC.com using GUID G1 if you upgrade the version of addin e.g 1.0.0.1 .
 
For your second problem, where you are not able to remove the addin,It seems you have deployed this addin as user addin also.
1. Could you let us know when did you last try removing this addin ?
2. Kindly share the organisation name and affected user id on addin-help@outlook.com to look into this issue further.
 
Thanks

**Comment by sarea** [comment]
Hi @exextoc
The issue seems to be solved now, same as what happened the time before, it goes away by itself, but now I know that I have to change the add-in version as well
Answering your question, I really can't remember that, I have been shuffling between both for quite some time.
Many thanks:)

**Comment by lliu113** [comment]
@sarea - it appears that the issue has been resolved, I'm going to go ahead and close this. Please reactivate if you need any further assistance, thanks!
