### ISSUE TITLE
[Outlook] Add `Recipients.RemoveAsync` API

### ISSUE THREAD

**Issue by ArashMotamedi** [OfficeDev/office-js#1322]
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/get-set-or-add-recipients

Currently, the `Recipients` interface offers `getAsync`, `addAsync`, and `setAsync` APIs. Ask is to add a new `removeAsync` API allowing removal of one or more recipients. 

While I can simulate removal of a recipient by first getting the current recipients and then setting a new array minus the recipients I'd like to remove, this approach is at best clunky, and at worst impossible. It turns out that Outlook limits the number of recipients/emails you can `setAsync` to 100. So, if I need to remove a single recipient from a list of 300, this is not currently possible. 

Please support `Recipients.removeAsync` to allow removal of one or more (array) recipients via a single API call.

>>> PLEASE USE USER VOICE FOR FEATURE REQUESTS <<<

Post feature requests at https://officespdev.uservoice.com/

**Comment by alison-mk** [comment]
Hi @ArashMotamedi, thanks for using add-ins! We use Github issues to report bugs with the product, and it looks like you are requesting a feature. For feature requests, I recommend submitting via [UserVoice](https://officespdev.uservoice.com/). We use UserVoice to prioritize community requests for addition to the product. If the community also needs the feature and upvotes your request, it'll be more likely to be added to the add-ins platform.

Since this isn't a bug, I will close this issue. Let me know if you have any questions!

Thanks again, 
Alison
