### ISSUE TITLE
How to open excel from word using office.js

### ISSUE THREAD

**Issue by libjosep** [OfficeDev/office-js#1324]
I have the contents for an excel file in base64 format in word. How can I create and open an excel file with this content using office.js

**Comment by alison-mk** [comment]
Hi @Libinjoseph, thank you for submitting! We use Github issues to report bugs with the product, and it looks like you are asking a more general programming question. For programming questions, we suggest you go to [Stack Overflow](https://stackoverflow.com/questions/tagged/office-js) and see if your question has already been asked or ask a new question. Stack Overflow has an active community of developers that regularly provide feedback and guidance. 

Since this isn't a bug, I will close this issue. Let me know if you have any questions!

Alison
