### ISSUE TITLE
When hosted officeaddin site is down.

### ISSUE THREAD

**Issue by aantimengocom** [OfficeDev/office-js#1326]
Hi,

In a scenario that an Outlook Addin needs triggering the "OnSend" event - the manifest looks for the configured implementation.. but what happens if the implementation for the Command URL is not available -say the site hosting the implementation is not available? at the moment for me it looks like it will no longer be possible to send emails unless you disable the office addin. - what would be nice would be to be given the option to not proceed with the office addin implementation if the hosted implementation is not available. - what do we do in such scenarios?

**Comment by exextoc** [comment]
Unfortunately this is by design. OnSend was developed for mission critical scenarios where say you didn't want the email to be sent out without being validated first. At the same time we do understand the need for a so called "soft" on send feature that allows other scenarios like what you are trying to achieve. This feature is currently not available in the product. We track Outlook add-in feature requests on our [user-voice](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins ) page. Please add your request there. Feature requests on user-voice are considered, when we go through our planning process.

**Comment by muratkuru** [comment]
Hi, is there any progress for "soft on send" feature or is there any workaround?

**Comment by JuaneloJuanelo** [comment]
Hello @muratkuru happy to claim that we shipped it in the context of Ignite 2022 just a couple of days ago. It has also been a while in preview.  here are the details of the announcement, it was branded as "Smart Alert" and is included in our Mailbox 1.12 release.  https://devblogs.microsoft.com/microsoft365dev/whats-new-for-office-add-ins-at-ignite-2022/#:~:text=At%20Ignite%202022%2C%20we%20introduce%20three%20partner%20add-ins,from%20an%20existing%20content%20library%20into%20the%20document.

**Comment by muratkuru** [comment]
That's good to hear! Thank you for the update @JuaneloJuanelo
