### ISSUE TITLE
How set PR_SECURITY_FLAGS  MAPI properties in outlook add-in 

### ISSUE THREAD

**Issue by PrashanthReddy7** [OfficeDev/office-js#1331]
How to set emails PR_SECURITY_FLAGS (http://schemas.microsoft.com/mapi/proptag/0x6E010003) property with any of the below values.

NONE | 0x0000 | Message has no security
ENCRYPTED | 0x0001 | Message is encrypted
SIGNED | 0x0002 | Message is signed
SIGNED \| ENCRYPTED | 0x0003 | Message is signed and encrypted

Used Custome properties , but didnt work out.
Please help me here

**Comment by alison-mk** [comment]
Hi @PrashanthReddy7, thank you for using add-ins! We use Github issues to report bugs with the product, and it looks like you are asking a more general Outlook add-ins programming question. For programming questions, we suggest you go to [Stack Overflow](https://stackoverflow.com/questions/tagged/office-js) and see if your question has already been asked or ask a new question. Stack Overflow has an active community of developers that regularly provide feedback and guidance. 

Since this isn't a bug, I will close this issue. Let me know if you have any questions!

Alison
