### ISSUE TITLE
Disabling Connected Experiences and OfficeJs add-ins

### ISSUE THREAD

**Issue by malsabbagh** [OfficeDev/office-js#1351]
Is there a way to enable outlook add-ins to appear in Outlook Desktop clients without enabling "Connected Experiences"? 

Is this based on the permissions we request in the manifest? Or are all Office add-ins hidden when this option is disabled?

It looks like "Connected Experiences" is not fully GDPR compliant, so we have some clients disabling this option, but because of this the add-in icon won't be visible in Desktop Clients. (They are visible in the browser clients.)

**Comment by JuaneloJuanelo** [comment]
Good question.  The answer it not yet.
Right now if Connected Experiences is disabled, the "Get Add-ins Button" is not even visible (and hence compliant since add-ins and the store cannot be used).

We are making a few adjustments to enable Add-ins IF "Optional Connected Experiences" is disabled,  the idea in such condition is to enable the Add-ins deployed by IT using Microsoft 365 Centralized Deployment. (in other words, only add-ins pre-approved by IT will be enabled, the store will remain disabled, unless again the Admin deploys them within the org.

There is not formal ETA for this but should be relatively soon live.

Note that as per the document [here ](https://docs.microsoft.com/en-us/deployoffice/privacy/overview-privacy-controls) privacy controls including Connected Experience is not supported yet in Outlook on the Web.

Hope this info helps. 

Closing the issue as this is an answered question.

**Comment by vpx23** [comment]
Was this feature added in the meantime? If yes, where exactly can you allow an Add-In if connected experiences are disabled?
