### ISSUE TITLE
Unable to retrieve attachment with EWS request 

### ISSUE THREAD

**Issue by mug-cat** [OfficeDev/office-js#1374]
I am writing an Outlook add-in that will retrieve a mail's attachment.
(I am not simply using item.attachments because I want to be able to retrieve the S/MIME attachment and item.attachments will not include that)

My code:
https://gist.github.com/hthjthtrh/9627d2731be3aebbfddb4d8dc26e6fe2

Response:
https://gist.github.com/hthjthtrh/4ea1521052936b9ee187e7a5456623dd

In the email that I'm testing, I have pdf, jpg and xlsx files attached. I am able to retrieve the attachmentId but can't use that ID to retrieve the content. How can I gain access to perform the request?

**Comment by AlexJerabek** [comment]
Thanks for reporting this @hthjthtrh.

@exextoc, can you please investigate?

**Comment by mug-cat** [comment]
PS, I am doing this on my personal Outlook account so I assume the server is Exchange Online.

**Comment by mug-cat** [comment]
Okay it's my fault for not noticing that for add-in, I only have a reduced set of EWS operations to use.
https://docs.microsoft.com/en-sg/office/dev/add-ins/outlook/web-services#ews-operations-that-add-ins-support

Guess I'll have to either do it the REST API way or to delegate the role to a remote service.
Can I clarify if I can use REST API for Exchange on-premise servers?

**Comment by exextoc** [comment]
If you are on-premise, REST APIs are supported in an [Exchange hybrid deployment](https://docs.microsoft.com/en-us/graph/hybrid-rest-support) environment. Also, please note that this feature is in preview.

**Comment by mug-cat** [comment]
I see. That's all I need for now. Thanks!

**Comment by exextoc** [comment]
Just to clarify our last comment. For using [REST in Exchange on-premise](https://techcommunity.microsoft.com/t5/exchange-team-blog/on-premises-architectural-requirements-for-the-rest-api/ba-p/605609), the [Outlook add-in REST token](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/use-rest-api) can be used from an add-in's backend. The limitation is CORS is not supported by the on-premise Exchange server.

For a mailbox in O365, the REST token can be used either directly from the add-in client code (since CORS is supported in this scenario), or passed to an add-in's backend.
