### ISSUE TITLE
unable to get an unique identifier from outlook

### ISSUE THREAD

**Issue by LovikaJain** [OfficeDev/office-js#1376]
I have posted the question on outlook as well. 
I am looking for a unique identifier like `GlobalAppointmentID` in VBA. 
https://stackoverflow.com/questions/63811514/how-to-get-an-unique-identifier-to-identify-an-appointment-in-outlook-appointme

**Comment by AlexJerabek** [comment]
Thanks for the question @LovikaJain. 

@exextoc, could you please assist here?

**Comment by exextoc** [comment]
From API set 1.8, the API [getItemIdAsync ](https://docs.microsoft.com/en-us/javascript/api/outlook/office.appointmentcompose?view=outlook-js-preview#getitemidasync-options--callback-) is available in Appointment Organizer and provides the item id, which can be used to identify the appointment.

**Comment by LovikaJain** [comment]
I am getting "The id can't be retrieved until the item is saved." I am trying to get the Item Id in the calendar event. The item is not getting saved till the time. won't the itemId change when I edit the meeting?

**Comment by exextoc** [comment]
Since this is the same issue as on [Stack Overflow](https://stackoverflow.com/questions/63811514/how-to-get-an-unique-identifier-to-identify-an-appointment-in-outlook-appointme) and to avoid duplicating answers between Github and StackOverflow, closing this issue here and following up on Stack Overflow.
