### ISSUE TITLE
Excel: my excel addin can focused？(How to keep ribbon section persistent when running add-in)

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#1387]
>>> PLEASE USE USER VOICE FOR FEATURE REQUESTS <<<

in excel  if user clicks on the cell or chart generated by the plugin, the excel ribbon menu will switch to 'Home' section automatically , user need switch back to plugin section again and again,is there a way to keep the plugin menu section always on top?

we use office.js  ,we found it will publish ribbonapi. but it only have enable and disable button event. it will have focus event?

thanks

**Comment by lindalu-MSFT** [comment]
Hi @dinglicoding I assigned this to triage but we need to know more about your environment. Please fill in the following template:


## Expected Behavior


## Current Behavior



## Steps to Reproduce, or Live Example



* Link to live example: ______


* Additional details:
  1. ______
  2. ______
  3. ______

## Context



## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by dinglicoding** [comment]
@lindalu-MSFT 

Expected Behavior
after create char, we need  switch to our excel ribbon menu

Current Behavior
excel will auto switch the menu

Steps to Reproduce, or Live Example
Link to live example: ______
Additional details:
Context
Your Environment 
Platform [PC desktop, Mac, iOS, Office on the web]: ____desktop__
Host [Excel, Word, PowerPoint, etc.]: __excel____
Office version number: ___version 2008(build 13127)___
Operating System: ___windows 10___
Browser (if using Office on the web): ______

**Comment by lindalu-MSFT** [comment]
@lliu113 Can you help me understand what this issue is?

**Comment by yinzixin** [comment]
Hi  @lindalu-MSFT 

This is not a issue. It's a feature request.

Currently if user clicks a cell or chart generated by the plugin, the ribbon menu will automatically show the 'Home' tab, user need switch back to plugin tab again and again. We'd like to have a way that can programmatically show the plugin tab.

Noticed there will be a new Ribbon API, but it only has  enable/disable function, is it possible to also include a focus function, that we can show the plugin tab on top?

**Comment by lliu113** [comment]
@dinglicoding @yinzixin - sorry for the very late response to this. We currently do not have any "focus" style APIs in the backlog. 

For feature requests, please submit these to [Microsoft 365 Developer Platform Ideas](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). 

I'm going to close this issue as it's not a product bug, feel free to reactivate if you have any additional questions. Thanks!
