### ISSUE TITLE
Displaying appointment form not working in Safari

### ISSUE THREAD

**Issue by Dizzzlectic** [OfficeDev/office-js#1421]
## Expected Behavior

When executing the following function, to open the new appointment dialog message:
```javascript
Office.context.mailbox.displayNewAppointmentForm({ ... });
```

## Current Behavior

While testing my plugin, running the following in Safari does not open the new appointment dialog, while its working just fine in Chrome, Firefox and the Outlook app.
```javascript
Office.context.mailbox.displayNewAppointmentForm({
  location: `https://${settings.domain}.easymeeting.net/${settings.number}`,
  subject: 'Easymeeting videomøte',
  requiredAttendees: [],
  optionalAttendees: [],
  resources: [Office.context.mailbox.userProfile.emailAddress],
  body: messageBody,
});
```

## Steps to Reproduce, or Live Example

* Link to live example: https://github.com/SpellCraft/em-office-addin

* Additional details:
  1. https://i.imgur.com/jBdElpK.png Shown working just fine in Firefox
  2. https://i.imgur.com/TYfhZ8P.png Shown working just fine in Outlook app
  3. No error messages generated. Console-logging of Office.context.mailbox.displayNewAppointmentForm shows that it is present

## Context
I've attempted getting my plugin submitted to the office add-in store, but it keeps getting declined because of this issue. I've also tried setting up a barebones project with only this function, while it works on the native Outlook client on both Windows and Mac, and in Chrome/Firefox on either OS, it won't work in Safari.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: macOS Catalina 10.15.6
* Browser (if using Office on the web): Safari 14.0 (15610.1.28.1.9, 15610)

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
No errors reported during testing. It just doesn't do anything it seems.

**Comment by exextoc** [comment]
@SpellCraft The add-in you have shared works on fine on our end on Safari browser as well. Can you make sure settings for Safari browser does NOT block popups?  You can check how to block/unblock popups on safari from [Block pop-ups in Safari on Mac](https://support.apple.com/en-in/guide/safari/sfri40696/mac)

**Comment by Dizzzlectic** [comment]
Excuse my late reply.
I double checked on my Mac mini (Late 2014) that the block pop-up setting in Safari was disabled, and nothing happened still, while on my newly purchased (today) Macbook Pro that's replacing the Mini, it works just fine.

It's running the same version of macOS Catalina and Safari, even though one is somewhat slower than the other, I do expect it should work the same?

**Comment by exextoc** [comment]
Could you please provide me the version of the safari browser you are using? 

Also, could you try the following steps to narrow down the issue?
1. Run the below code snippet and see if the issue is reproducible. Note: Do not add any params in the API call.
```
Office.context.mailbox.displayNewAppointmentForm({
 
});
```

2. If the issue is not reproducible, try adding the params one by one to figure out which param is causing the issue.

**Comment by exextoc** [comment]
@SpellCraft 
Could you please provide me the version of the safari browser you are using? 

Also, could you try the following steps to narrow down the issue?
1. Run the below code snippet and see if the issue is reproducible. Note: Do not add any params in the API call.

```
Office.context.mailbox.displayNewAppointmentForm({
 
});
```

2. If the issue is not reproducible, try adding the params one by one to figure out which param is causing the issue.
