### ISSUE TITLE
<Runtime> tag in the manifest + IE11 End of Life

### ISSUE THREAD

**Issue by swiecaJS** [OfficeDev/office-js#1470]
In our addin we need to use `Runtime` tag in the manifest to allow custom functions to the same runtime as taskpane. Based on this document: https://docs.microsoft.com/en-gb/office/dev/add-ins/reference/manifest/runtimes
There is no way to use the Edge Web View + Runtime tag in the manifest on the desktop version of Office + Windows 10.
Knowing that IE11 end of life is August 17th, 2021 -there is no option to use that feature on the Desktop Office afterwards.

## Expected Behavior
I would like to share runtime between taskpane & custom functions with Edge Web View

## Current Behavior
When I place that tag, in Win10, Excel uses IE11 as a web view renderer.

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. Include <Runtime> tag in your manifest.xml file

## Context

We are developing an excel add-in that requires this feature, and there is no known solution (based on the docs) how we should prepare for this after Q2 2021. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 13328.20292
* Operating System: Win 10
* Browser (if using Office on the web): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by davidchesnut** [comment]
Hi @swiecaJS, the note in that document is an error. I'll take an action to go remove it. Shared runtime will work regardless of IE or Edge WebView usage by the Office apps. 

Thanks!

**Comment by swiecaJS** [comment]
Hi @davidchesnut

However, where I have shared runtime in the manifest, the app runs in the IE11, not edge. Is there a way to force using an edge web view?

**Comment by davidchesnut** [comment]
Hi @swiecaJS , 

Sorry, I gave you bad info here. I checked with the rest of the team, and the article is correct. Shared runtime will indeed force the IE runtime to be used. So you are absolutely correct. We're working to remedy this, but there is no exact timeline yet.

Cheers,
David

**Comment by swiecaJS** [comment]
@davidchesnut so to summarize, currently, it works only on IE11, you are working on enabling runtime on Edge, but without a specified timeline. So can we assume that our app will work after August 17th, 2021 (Mainstream support ends for IE11)? We would like to be prepared for this date :)

Thanks for your help!

**Comment by smaremanda** [comment]
@swiecaJS - great question. yes, we force add-ins with "Runtime" manifest element to run in IE/Trident today. I believe you have 3 main questions here in this post:
1. is there a ways to test this functionality with EdgeHTML [the legacy Edge WebView]
-- No, there isnt a way at this point. In fact we dont recommend it because we believe there will likely be some errors you will encounter.
2. Is there a way to test this functionality using the new Chromium based Edge WebView 2?
-- Yes, absolutely. We highly recommend you test this as soon as possible and give us feedback. You can see this blog post here https://developer.microsoft.com/en-us/office/blogs/announcing-webview2-for-office-add-ins-platform/ for instructions.
3. When will you release WebView 2 for Office add-ins?
-- We are currently targeting to make this functionality available as part of the November fork of Office. Our customers should start seeing this starting in Jan 2021.

Does that help?
