### ISSUE TITLE
email opened in new browser window on itemsend

### ISSUE THREAD

**Issue by TomKnibbs** [OfficeDev/office-js#1484]
Hi,

This issue is related to when using the following code to open a dialog box on itemsend within outlook web (Do not run into the issue on the desktop version).

`<ExtensionPoint xsi:type="Events">
                  <Event Type="ItemSend" FunctionExecution="synchronous" FunctionName="validateSubject" />
 </ExtensionPoint>`

Instead of opening the dialog box the email to be sent is reopened in a new browser window and then the dialog box is opened (please see screen shots)
Any idea on what would be causing this?
![image](https://user-images.githubusercontent.com/73838303/97881692-a173ad00-1d1a-11eb-89f8-2a1b3401a552.png)
![image](https://user-images.githubusercontent.com/73838303/97881802-c2d49900-1d1a-11eb-8f3f-a67c25aed518.png)

**Comment by jak-hammond** [comment]
We have seen this happen a few times ourselves in an application we have been developing. Only myself and one of our QA engineers see this issue, for the other 4 people on my team, the message remains inline and does not pop out, so if there is anything we can do to fix or document on how to turn on or off, would be appreciated!

**Comment by TomKnibbs** [comment]
We also have the same issue in which it affects some users but not all...

**Comment by exextoc** [comment]
What you are seeing is the expected behavior if the OnSendAddinsEnabled policy is enabled for a mailbox. You can read the documentation about enabling the policy here: https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=classic#install-outlook-add-ins-that-use-on-send. The users that are not seeing this behavior might not have the OnSendAddinsEnabled policy enabled for them. Please do have check if that's the case.

**Comment by exextoc** [comment]
What you are seeing is the expected behavior if the OnSendAddinsEnabled policy is enabled for a mailbox. You can read the documentation about enabling the policy here: https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=classic#install-outlook-add-ins-that-use-on-send. The users that are not seeing this behaviour might not have the OnSendAddinsEnabled policy enabled for them. Please do have check if that's the case.

**Comment by dcegress** [comment]
Regarding the above, we have some users that do not have an OWAMailboxPolicy appliend with OnSendAddinsEnabled set to true, however when they use OWA and click Send, the Add In code runs.

Based on the documentation this should not happen?

**Comment by exextoc** [comment]
> Regarding the above, we have some users that do not have an OWAMailboxPolicy appliend with OnSendAddinsEnabled set to true, however when they use OWA and click Send, the Add In code runs.
> 
> Based on the documentation this should not happen?

The addin code will run. But even in that case are you seeing the popout coming up with its controls disabled?

**Comment by dcegress** [comment]
So what is the point of OnSendAddinsEnabled true / false then if the code always runs ?

**Comment by exextoc** [comment]
#1381

**Comment by exextoc** [comment]
@dcegress "OnSendAddinEnabled" flag set to true allows add-ins to block the editing of the email. To achieve this, OWA creates a separate dialog. If "OnSendAddinEnabled" is set to false, the add-in will still work but the pop up dialog will not come up.
 
Our documentation has inconsistencies and doesn't convey the above feature appropriately. We are in the process of fixing the document.

We hope this answers your question and solves the problem.
