### ISSUE TITLE
When will addFromBase64 API be released for Production use

### ISSUE THREAD

**Issue by jnSWPC** [OfficeDev/office-js#1496]
Currently it appears the api is provided as a preview for developers . When will it get formally released for production use?

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by lumine2008** [comment]
Thanks @jnSWPC for your questions, this API is in preview mode for 2 years because of the lack of support of Excel online, so this quarter we are actively working on supporting this API on Excel online, and this API has a small change. so it will need to release to beta soon. please stay tuned. thanks for your patient.

**Comment by lumine2008** [comment]
We just enable this API to run on Excel online, and now it is under preview. would you please verify, we will release if the quality is good.
**https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-preview-apis?view=excel-js-preview**
