### ISSUE TITLE
Button control displaying wrong icon on Outlook for the web

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js#151]
On top of the manifest, I have defined default icon X for the add-in itself. Further down, for a button control, I have defined an icon Y.

In Outlook (native, MacOS), the button correctly shows icon Y. 

But on Office365 (online), the button control mistakenly shows default icon X, but expect Y.

``` xml
<OfficeApp
    xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
    xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0"
    xsi:type="MailApp">
    
    <IconUrl DefaultValue="https://localhost:3443/bitmaps/x.png" />    
    <!--...-->
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
        <Requirements>
            <bt:Sets>
                <bt:Set Name="Mailbox" MinVersion="1.5" />
            </bt:Sets>
        </Requirements>
        <Hosts>
            <Host xsi:type="MailHost">
                <DesktopFormFactor>
                    <FunctionFile resid="functionFileUrl" />
                    <ExtensionPoint xsi:type="MessageReadCommandSurface">
                        <OfficeTab id="TabDefault">
                            <Group id="msgReadGroup">
                                <Label resid="groupLabel" />
                                <Control xsi:type="Button" id="...">
                                    <!--...-->
                                    <Icon>
                                        <bt:Image size="16" resid="y16" />
                                        <bt:Image size="32" resid="y32" />
                                        <bt:Image size="80" resid="y80" />
                                    </Icon>
                                    <!--...-->
                                </Control>
                            </Group>
                        </OfficeTab>
                    </ExtensionPoint>
                </DesktopFormFactor>
            </Host>
        </Hosts>
        <Resources>
            <bt:Images>
                <bt:Image id="y16" DefaultValue="https://localhost:3443/bitmaps/y16.png"/>
                <bt:Image id="y32" DefaultValue="https://localhost:3443/bitmaps/y32.png"/>
                <bt:Image id="y80" DefaultValue="https://localhost:3443/bitmaps/y80.png"/>
            </bt:Images>
            <!--...-->
        </bt:LongStrings>
    </Resources>
</VersionOverrides>
</OfficeApp>

```

Again, the Y icon is never shown on the button for Office365

**Comment by exextoc** [comment]
This behavior is currently behaving as designed. Outlook on the web currently uses the default icon as a representative for the add-in since the commands aren't shown individually until the dropdown is selected. However, we do recognize this is confusing behavior and will internally discuss how we could mitigate this issue. Thanks for reporting it.

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you provide a current status on this? Thanks.

**Comment by JuaneloJuanelo** [comment]
Upon further investigation. Yes, this is specially confusing when there is only one control (ribbon button) defined in the manifest, and the icon of such control is different from the default icon. What happens is that the default icon is shown (instead of the one associated with the task pane). We can only  show one icon per add-in in Outlook for the Web. 

Probably the right design is to have the task pane action icon to show up on the single control case , although it might also be confusing if more controls are added, suddenly there will be the default icon on the bar, grouping the other actions (shown in dropdown). 

We have bug 1325915 tracking this investigation.

**Comment by lindalu-MSFT** [comment]
@JuaneloJuanelo Can you verify if this has been fixed? If so, please change status from "Status: in backlog" to "Status: fixed" and close. I'm chasing down older issues that are still open. Thanks, linda

**Comment by mgrybauskas** [comment]
@JuaneloJuanelo Are there any updates on this issue? Is it possible for the group icon to change depending on the mode the user is in? (e.g.: AppointmentAttendeeCommandSurface or AppointmentOrganizerCommandSurface)?

**Comment by exextoc** [comment]
@mgrybauskas 
Currently, the feature group icon to change depending on the user mode, you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered when we go through our planning process.
