### ISSUE TITLE
Bindings are lost during concurrent editing of Word documents in SharePoint

### ISSUE THREAD

**Issue by jcupps** [OfficeDev/office-js#1527]
When two users edit a Word document from SharePoint concurrently and one user adds a binding, the binding is lost when the changes are synced with the other user.

## Expected Behavior
Bindings should not be lost.

## Current Behavior
After changes are synced, no bindings are returned from `Office.context.document.bindings.getAllAsync`, and they can be confirmed to be missing from the document by inspecting the OOXML.

## Steps to Reproduce, or Live Example
The following code demonstrates the problem. When loaded in a Word add-in, it displays a button that adds a binding to the current selection as well as the number of existing bindings.
```javascript
Office.onReady(function (info) {
  // Create a button that adds a new binding to the current selection when clicked.
  window.addBinding = function() {
    Office.context.document.bindings.getAllAsync(function (asyncResult) {
      Office.context.document.bindings.addFromSelectionAsync(
        Office.BindingType.Text,
        { id: 'binding' + (asyncResult.value.length + 1) },
        function (asyncResult) {
          var msg = asyncResult.status == Office.AsyncResultStatus.Failed
            ? 'Action failed. Error: ' + asyncResult.error.message
            : 'Added new binding with type: ' + asyncResult.value.type + ' and id: ' + asyncResult.value.id;
          document.body.innerHTML += '<div>' + msg + '</div>';
        }
      );
    });
  }
  document.body.innerHTML = '<div><button onclick="addBinding()" />Add Binding</div>';

  // Periodically check for and display the number of bindings that exist.
  document.body.innerHTML += '<div id="bindings-status"></div>';
  setInterval(function () {
    Office.context.document.bindings.getAllAsync(function (asyncResult) {
      var bindingString = '';
      for (var i in asyncResult.value) {
        bindingString += asyncResult.value[i].id + '<br />';
      }
      document.getElementById('bindings-status').innerHTML = '<div>Existing bindings: ' + asyncResult.value.length + '</div>';
    });
  }, 1000);
});
```

Repro steps:

1. Open a SharePoint document in two separate instances of Word
2. Add a binding in instance A and save changes
3. Instance B will be notified that there are updates available; click to apply updates
4. Note that instance B does not see the binding created by instance A
5. Instance A will be notified that there are updates available (even though instance B did not knowingly make or save any changes); click to apply updates
6. Instance A now does not see any bindings

Note that after step 5, the add-in is re-loaded and Word appears to auto-recover the document.

## Context
Supporting concurrent editing is high priority for our add-in.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Word for Office 365 MSO (16.0.12527.21230) 64-bit, Word 2016 (16.0.4954.1000) MSO (16.0.4939.1000) 64-bit
* Operating System: Windows 10
* Browser (if using Office on the web): N/A

## Useful logs
No errors logged

**Comment by MandytMSFT** [comment]
@jcupps I simplified your code as https://gist.github.com/MandytMSFT/a1f6a4b93788fff17571021680a35fba and tried on word desktop with scriptlab, i can't repro the issue your reported. Every time client A added a new binding, it can be synced to client B successfully without any notification. 

Given you mentioned add-in reloaded happen, I suspect there is some issue happened on your addin instead of the API issue.

My word version is as below, could you help double confirm with the scriptlab gist  ? 

![image](https://user-images.githubusercontent.com/52641972/101302611-05881480-3877-11eb-9dfb-510d257c5772.png)

**Comment by jcupps** [comment]
Hi @MandytMSFT thanks for the reply and the gist. We ran it using Script Lab and were able to reproduce repeatedly, though not 100% consistently (which could have been due to the bug being intermittent, but also possibly failure to perform the repro steps exactly). The following environmental details could explain the difference in behavior that we are seeing:
- We are on the "semi-annual enterprise" release channel as opposed to "dogfood main". We don't currently have access to the latter.
- We performed all testing with auto-save disabled, as our target environment is Word 2016 which does not support this feature. We tested in both SharePoint 2016 as well as SharePoint 365, and while auto-save is not an option in the former, it is enabled by default in the latter and had to be manually disabled by each tester prior to beginning each test.

**Comment by MandytMSFT** [comment]
@jcupps sorry for overlooking your reply and thanks for your details. Are you still facing this issue and can I know your word version to help repro?

**Comment by MandytMSFT** [comment]
@jcupps  Sorry for the delay response. I tried your scenario on Semi-Annual word ( 16.0.12527.21416, this version should similar as yours since they have same baseline), but I can not repro the issue as well. 

First I can't get notification saying update available. So I used another way: **do some changes on Client B, then Ctrl+S to save document** to trigger changes in client A got updated in client B. Even this, i can only see the addin reload issue (pls see the video attached). Binding can be updated successfully between clients, word also not crash. 

https://user-images.githubusercontent.com/52641972/103887459-06ce8a80-511e-11eb-868b-3a41a8f0e22b.mp4

Add Hoe and Jiayuan to continuing follow up on this thread as it's issue on word desktop

**Comment by jcupps** [comment]
@MandytMSFT Thank you for following up. It is puzzling that you're not seeing the same behavior. At this point, my team has settled on a work-around that completely avoids bindings. While it would be nice to get to the bottom of the problem, we have a path forward so you're welcome to close this issue if you're unable to reproduce. Thanks again for your response.

**Comment by JiayuanL** [comment]
@jcupps Thanks for reaching, I tried to follow the steps and I cannot repro the issue either. Happy to hear that you have some workaround to get unblocked. Will close this issue for this moment and please let us know if any further help we could provide. Thanks.
