### ISSUE TITLE
Impact of SameSite cookie attribute for session cookies on Outlook Add-in in Outlook Desktop client.

### ISSUE THREAD

**Issue by ShubhamJain-Outlook** [OfficeDev/office-js#1582]
Browsers are changing their default behavior for the cookies as following:-
•	Cookies without a SameSite attribute will be treated as SameSite=Lax, meaning the default behavior will be to restrict cookies to first party contexts only.
•	Cookies for cross-site usage must specify SameSite=None; Secure to enable inclusion in third party context.

For Addin in Outlook Desktop Client, we will be launching our Web Application and using its cookies but it should be behaved as first party so it should not impact us. So need to know about the impact of “samesite” cookie attribute on the Outlook Add-in.

@office-js @outlook-web-addins

**Comment by exextoc** [comment]
You probably already know this, but for reference this is the document that talks about that upcoming change: 
https://docs.microsoft.com/en-us/microsoft-edge/web-platform/site-impacting-changes

This is coming to new versions of Edge based on Chrome. 

this change is **not** going back to "Old Edge" (Spartan) or to IE, and shouldn't affect add-ins until the transition to "New" Edge for add-ins happens. (I do not have information on when that is going to production)

**Comment by ShubhamJain-Outlook** [comment]
Hi @exextoc 
Outlook Add-in application which is launched in the TaskPane of the Outlook Desktop Client, is it considered as third party application or first party applications. If it is considered as First Party Application then also can it impact add-in application.

Our assumption is that when add-in is launched in TaskPane it is opened directly in Outlook embedded browser so application is considered as first party application.

Please share your input on the same.

**Comment by exextoc** [comment]
The terms first-party cookie and third-party cookie are different from first-party add-in and third-party add-in here.

All add-ins built by internal Microsoft teams are considered first-party add-ins, whereas those built by developers external to Microsoft are considered third-party add-ins.

Cookies that match the domain of the current site in the browser's address bar are considered first-party cookies, whereas those that don't match are referred to as third-party cookies. More information here: https://web.dev/samesite-cookies-explained/

So SameSite cookies will work as expected, and they are un-related to the concept of first-party/third-party add-ins.

**Comment by ShubhamJain-Outlook** [comment]
Whether the cookies used by outlook add-in in the Outlook Desktop client will be considered as first party cookies or third party cookies. As addin is directly opening in the embedded browser of Outlook Desktop Client.

**Comment by exextoc** [comment]
The cookie will be a first party cookie if it matches the domain of the SourceLocation in your manifest. If it doesn't match, it will be a third party cookie.

**Comment by exextoc** [comment]
Let us know if this thread has answered your questions. Thanks.

**Comment by ShubhamJain-Outlook** [comment]
Thanks for the answer

**Comment by ig-jb** [comment]
@exextoc I'm seeing cookies getting treated as third party and believe it may be related to this. However, the cookies are indeed set on the domain specified in the various extension point action SourceLocation entries. I've verified this by seeing that the cookies are sent as expected when `SameSite=none`; but are blocked by the browser when `SameSite=Lax`

Example config (Testing in Outlook O365 using Chrome):
```
<FormSettings>
	<Form xsi:type="ItemRead">
		<DesktopSettings>
			<SourceLocation DefaultValue="https://mydomain/taskpane1.html"/>
			<RequestedHeight>250</RequestedHeight>
		</DesktopSettings>
	</Form>
</FormSettings>
...
<ExtensionPoint xsi:type="MessageReadCommandSurface">
	<CustomTab id="MsgReadTab">
		<Group id="MsgReadGroupTaskpane">
			<Label resid="CommandsGroupTaskPane.Label"/>
			<Control xsi:type="Button" id="MsgReadTaskpaneButton">
				<Label resid="Taskpane.Label"/>
				<Supertip>
					<Title resid="Taskpane.Label"/>
					<Description resid="Taskpane.Tooltip"/>
				</Supertip>
				<Icon>
					<bt:Image size="16" resid="TaskpaneIcon.16x16"/>
					<bt:Image size="32" resid="TaskpaneIcon.32x32"/>
					<bt:Image size="80" resid="TaskpaneIcon.80x80"/>
				</Icon>
				<Action xsi:type="ShowTaskpane">
					<SourceLocation resid="Taskpane.Url"/>
				</Action>
			</Control>
		</Group>
		...
	</CustomTab>
</ExtensionPoint>
...
<bt:Urls>
  <bt:Url id="Taskpane.Url" DefaultValue="https://mydomain/taskpane2.html"/>
</bt:Urls>
```
The cookies are set via `fetch` with `credentials: include` on https://mydomain/api/auth (OAuth2 code exchange after the taskpane receives the code, state from the auth dialog), with HttpOnly, Secure, Path=/ , Domain=mydomain SameSite=lax. 

I've verified that the cookies get set as expected, however are blocked on subsequent requests to https://mydomain/api/ as they are seen as third party when within the taskpane iframe. 

I tried changing the SourceLocation to `DefaultValue="https://mydomain/taskpane2.html"` rather than using resources to see if this might enable first party context, but this failed manifest validation. 

Just wondering if you might have any suggestions?
