### ISSUE TITLE
Add-in fails to load on Outlook iOS

### ISSUE THREAD

**Issue by bx-anil** [OfficeDev/office-js#1619]
We have an add-in works fine on desktop Outlook and OWA. When we enabled it for mobile it fails to load on iOS Outlook app. 
Is there way to inspect logs for the add-in that is loading on iOS Outlook app? 

Additional information:
1) Since the add-ins are web apps essentially, we tried loading it in Safari iOS and it works fine.
2) Cookies are not the cause. 
3) We are unable to route the traffic thru fiddler as Outlook app does not trust fiddler certs. 

Environment:
iOS v14.3
iPhone 8

**Comment by exextoc** [comment]
To test your addin, refer to [https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-mobile-addins#testing-your-add-ins-on-mobile](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-mobile-addins#testing-your-add-ins-on-mobile).

A few important points there:
_Make sure your manifest is properly formatted to contain MobileFormFactor or it won't load._
Troubleshooting on mobile can be hard since you may not have the tools you're used to. However, one option for troubleshooting on iOS is to use Fiddler (check out [this tutorial on using it with an iOS device](https://www.telerik.com/blogs/using-fiddler-with-apple-ios-devices)).

**Comment by bx-anil** [comment]
We are unable to route the traffic thru fiddler as Outlook app does not trust fiddler certs.

**Comment by exextoc** [comment]
Outlook trusts only preinstalled system CA certificates. One way to see the traffic is by making sure your certificate is part of system certificates (not user), it is tough for anyone who is not an OEM.
Another way to debug is using remote JavaScript debugging tools like	
http://vorlonjs.com/documentation/#introduction 
https://remotejs.com/  (A free version of TrackJS)
https://jsconsole.com/remote-debugging 
If your application is based on Node.js, use Node.js debugging in VS Code
