### ISSUE TITLE
Mac new Outlook client not support: Office.context.mailbox.item.enhancedLocation.addAsync

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#1623]
Mac **new** Outlook client, which is use the new UI for Mac.
version: 16.45(21011103)
code segment:
```
var locations = [
  {
    id: "Contoso",
    type: Office.MailboxEnums.LocationType.Custom
  },
  {
    id: "room500@test.com",
    type: Office.MailboxEnums.LocationType.Room
  }
];
Office.context.mailbox.item.enhancedLocation.addAsync(locations, (result) => {
  console.log(result);
});
```
error message:
Object

error: Object

code: 7000

message: "You don't have sufficient permissions for this action."

name: "Permission Denied"

![image](https://user-images.githubusercontent.com/1878089/106227435-212eec00-6224-11eb-918e-6be6e477e73d.png)

**Comment by exextoc** [comment]
This is expected behaviour. enhancedLocation.addAsync in New Outlook Mac UI is not supported. 

Please find the documentation for this
[https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/compare-outlook-add-in-support-in-outlook-for-mac#new-outlook-on-mac-preview](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/compare-outlook-add-in-support-in-outlook-for-mac#new-outlook-on-mac-preview)

API set 1.8 is targeted for Mar '21 for GA, but you can sign up for Insiders to get an earlier build which we are expecting to release by end of Feb.
