### ISSUE TITLE
Cursor moves to the bottom after inserting content to appointment body on Mac.

### ISSUE THREAD

**Issue by liwei118** [OfficeDev/office-js#1625]
Cursor moves to the bottom and scrollbar scrolls to the bottom after inserting content to appointment body on Mac. While on Windows it stays on top.

**Comment by AbidRahman-MSFT** [comment]
Hey @liwei118, can you please provide more information regarding the issue you are facing? Please use the default template when creating an issue:



## Expected Behavior


## Current Behavior



## Steps to Reproduce, or Live Example



* Link to live example: ______


* Additional details:
  1. ______
  2. ______
  3. ______

## Context



## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by liwei118** [comment]
No recurrence, the problem has been solved. Thanks.
