### ISSUE TITLE
range.numberFormatLocal does not work properly in German Regional Setting for Office Online

### ISSUE THREAD

**Issue by GeorgeHung** [OfficeDev/office-js#1632]
range.numberFormatLocal does not work properly in German Regional Setting for Excel Online

## Expected Behavior
range.numberFormatLocal should work properly in German Regional Setting for Excel Online as it works in Excel for Mac

## Current Behavior
After setting Mac's regional setting to German, range.numberFormatLocal does not apply the number format correctly in Excel online

## Steps to Reproduce, or Live Example

1. In Mac, go to System Preferences->Language & Region, and change Region to Germany.
2. Restart Mac.
3. Start Excel Online, and then load ScriptLab.
4. Import sample at https://gist.github.com/GeorgeHung/9d2fbc0458d3657d161f42ba0d155548 to ScriptLab
5. Open the Run Panel in Script Lab
6. Click on "Add Sample Data"
7. Click on "Set Number Format"
8. Check the number format on cell D3, it is "###,##000". However, in the sample code, the number format passed to range.numberFormat is "###.##0,00"

## Context
The bug is effecting our users who is running Excel online on non-us regional setting.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: Mac Big Sur
* Browser (if using Office on the web): Chrome

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by lushanbo** [comment]
Could you please try below steps on Excel Online:

1.  Changed the regional format settings in Excel for the web, follow this guideline [here](https://support.microsoft.com/en-gb/office/change-regional-format-settings-in-excel-for-the-web-c206344b-0d45-4a82-8eee-34ff6b008e9c?ui=en-US&rs=en-GB&ad=GB)
2.  Please make sure your third-party cookies in the browser are enabled, otherwise you will not be able to change the regional format settings with above way. For safari, click  "safari" -> "preferences" , click "private",  then uncheck "prevent cross-site tracking" and "block all cookies" like below picture.

![image](https://user-images.githubusercontent.com/13619304/107178776-dffebf00-6a0f-11eb-86ad-11689ed28944.png)

3. Try your sample in ScriptLab
I have tried your case in my machine with above steps, it works well for me. Feel free to let us know if the issue still exists.

**Comment by GeorgeHung** [comment]
It seems to address the issue.  You can close the bug,  Thanks.

Regards,
George
