### ISSUE TITLE
Read current mail body in FunctionFile? 

### ISSUE THREAD

**Issue by ionuttamas** [OfficeDev/office-js#1641]
I have followed the small tutorial [here](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator) and I have the following question:

How can I read the current mail body in the FunctionFile function?

I have the following simple config: 

**Manifest**:
![image](https://user-images.githubusercontent.com/5080185/107900891-2b750980-6ef7-11eb-8bce-5af276820bc9.png)

**Failing action function (reading result.value throws a silent error, but works fine in the taskpane.js)**:
![image](https://user-images.githubusercontent.com/5080185/107900993-6ecf7800-6ef7-11eb-9c39-915226f408f3.png)

**Comment by nkkinariwala** [comment]
Thank you for logging this issue. It would be nice if you can provide following details?

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: ______
Host [Excel, Word, PowerPoint, etc.]: ______
Office version number: ______
Operating System: ______
Browser (if using Office on the web): ______

**Comment by ionuttamas** [comment]
@nkkinariwala I have the following:

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
Host [Excel, Word, PowerPoint, etc.]: Outlook
Office version number: 2103 (Build 13812.20002 Click-to-Run)
Operating System: Windows 10
Browser (if using Office on the web): ______

**Comment by exextoc** [comment]
Thanks for sending your environment/config info. We are unable to reproduce this in-house.
Thanks for adding the code snippet to the original post. There are 2 issues with the code that may explain the behavior you are seeing.

1. Calling `event.completed()` immediately after calling `notificationMessages.replaceAsync`: This can result in a race condition because the add-in is asking the platform to perform an async operation, and then immediately sending a signal to the platform that the add-in's work is completed. The appropriate way to do this is to call `event.completed()` in the callback for `replaceAsync`.
2. Setting the body text as the notification message: As documented [here](https://docs.microsoft.com/en-us/javascript/api/outlook/office.notificationmessagedetails?view=outlook-js-preview), the maximum length of a message is 150 characters. So if the body text is longer than 150 characters, `replaceAsync` will fail.

Please address these 2 issues to see if they fix your issue.

**Comment by ionuttamas** [comment]
Thank you very much: this helped me in my use-case! :)
By the way, setting a message with more than 150 silently hangs the Outlook Add In (no errors either in Outlook or in node).

**Comment by exextoc** [comment]
Glad your issue is resolved.
When the 150 character threshold is exceeded, we throw an exception, which is why it appears that the add-in is hanging if the caller is not using a try...catch block.
