### ISSUE TITLE
Office Store Publishing issue: Outlook Add-in for creating appointment fails when submitting to Store

### ISSUE THREAD

**Issue by neso613** [OfficeDev/office-js#1642]
Hi
I have developed an Outlook Add-in using OfficeJS API for creating appointments with some setting and text. 
Outlook Add-in has following features-
1. Add-in should be visible at command tab as ribbon command having 2 options- settings and schedule meeting. If settings are there,only then user can create dynamic event for new appointment else save settings first.
2. A ribbon(add/remove) is at command tab of calender's new appointment page which is used to add/remove customize content for meeting.

Now, for this, I have added two ExtensionPoint in my xml .i.e. AppointmentOrganizerCommandSurface and MessageReadCommandSurface.

When I submit this to Store, It failed. Because my add-in do not read/write any info for mail.
Please tell and help to make this add-in correct for publishing.

**Comment by nkkinariwala** [comment]
@neso613 - Thank you for posting a question. It would be nice if you can provide following information.

Your Environment
Platform: ________
Host: Outlook
Office version number:________
Operating System: ________
Browser (if using Office on the web): ________

**Comment by neso613** [comment]
> @neso613 - Thank you for posting a question. It would be nice if you can provide following information.
> 
> Your Environment
> Platform: OWA
> Host: Outlook
> Operating System: Windows 10
> Browser (if using Office on the web): Chrome

**Comment by neso613** [comment]
Update?

**Comment by saurabh-msft** [comment]
@neso613 Can you please help us with the following ?

1. On submission you get a failure. Can you give us error message and snapshots?
2. We will need the exact manifest being submitted as well.
3. Please give as much details as possible.

**Comment by neso613** [comment]
> @neso613 Can you please help us with the following ?
> 
> 1. On submission you get a failure. Can you give us error message and snapshots?
> 2. We will need the exact manifest being submitted as well.
> 3. Please give as much details as possible.

[link](https://mop.infocus.net:3000/infocus-conx-outlook-addin.xml)

**Comment by saurabh-msft** [comment]
> > @neso613 Can you please help us with the following ?
> > 
> > 1. On submission you get a failure. Can you give us error message and snapshots?
> > 2. We will need the exact manifest being submitted as well.
> > 3. Please give as much details as possible.
> 
> [link](https://mop.infocus.net:3000/infocus-conx-outlook-addin.xml)

Thanks @neso613. I tried uploading the xml file you gave in our test partner center portal and it doesn't throw any error while xml gets validated in PartnerCenter-->Packages section.

Earlier you mentioned this:
"When I submit this to Store, It failed. Because my add-in do not read/write any info for mail.
Please tell and help to make this add-in correct for publishing."

Can you please paste the error message or UI snapshots when you see the failure?

**Comment by neso613** [comment]
> > > @neso613 Can you please help us with the following ?
> > > 
> > > 1. On submission you get a failure. Can you give us error message and snapshots?
> > > 2. We will need the exact manifest being submitted as well.
> > > 3. Please give as much details as possible.
> > 
> > 
> > [link](https://mop.infocus.net:3000/infocus-conx-outlook-addin.xml)
> 
> Thanks @neso613. I tried uploading the xml file you gave in our test partner center portal and it doesn't throw any error while xml gets validated in PartnerCenter-->Packages section.
> 
> Earlier you mentioned this:
> "When I submit this to Store, It failed. Because my add-in do not read/write any info for mail.
> Please tell and help to make this add-in correct for publishing."
> 
> Can you please paste the error message or UI snapshots when you see the failure?

As per the report from store validation team ----

Your offer demonstrate insufficient interaction with our service in Message Read mode. Please consider adding functionality which either reads information from or writes information to the Office Client.


*****it is likely that the validation team didn't found that you weren't interacting with the loaded mail item******,

**Comment by neso613** [comment]
@saurabh-msft 
![Screenshot_20210306-120020_Skype](https://user-images.githubusercontent.com/31642462/110197793-f6affe80-7e73-11eb-9fbd-fa29625d8801.jpg)

**Comment by neso613** [comment]
+ @kanaksony

**Comment by saurabh-msft** [comment]
@neso613 The above error is from 24 Nov, 2020. According to our validation team the validation errors you received were resolved on the submission made on Feb 11, 2021. Is there still some issue you are facing while submitting to the Partner Center?
If so please raise a ticket here https://partner.microsoft.com/en-US/support/v2/?stage=1 where you can ask for individual cert/validation failure results explanation.

For cert results(i.e. explanations of policy/ demos – rather than technical issues) clarification, partners/ISVs  should raise a ticket here https://partner.microsoft.com/en-US/support/v2/?stage=1 ; 

Please comment.

**Comment by mscharlock** [comment]
Hi @neso613 - going to close this thread but can reopen should you need more assistance. Just comment on this thread and I will go ahead and reopen. Thank you!
