### ISSUE TITLE
In certain cases Dynamic Array function returns #Spill! error although it should just work

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js#1684]
I've prepared small GIST where it is reproducible with automatic calculation, you need to click multiple times.

## Expected Behavior
Dynamic Array function (RANDARRAY) should return correct data.

## Current Behavior
It returns #Spill! error randomly but the max array size is 5x5 and the cells are empty.

## Steps to Reproduce, or Live Example
Use this gist and just click randomly in the spreadsheet. Once upon a time you will see the error.
https://gist.github.com/4tti/0d44c9d290b3365373e51ffc83c55544

## Context
We were encountering crash of Excel in some scenario but while trying to reproduce in ScriptLab I found this issue - not sure if it is specific to native functions or it can have influence on Custom Functions as well.

## Your Environment

* Platform PC
* Host Excel
* Office version number: 
![image](https://user-images.githubusercontent.com/19533927/109793327-cb7ba400-7c14-11eb-92ea-2453fafd774c.png)
* Operating System: Windows 10

**Comment by AlexJerabek** [comment]
Hi @4tti, 

Thanks for reporting this. I was able to reproduce your issue. I'll tag @lumine2008 to investigate.

One question, are you able to reproduce this behavior without the Script?

**Comment by macky360** [comment]
Which #SPILL are you getting? There are [7 types](https://support.microsoft.com/en-us/office/how-to-correct-a-spill-error-ffe0f555-b479-4a17-a6e2-ef9cc9ad4023). You can tell by clicking on the error floatie. 

My guess is that you are dealing with the indeterminate size error and the behavior is expected.  You can see details on the help page. Pasted below for convenience:

_Indeterminate size

Excel was unable to determine the size of the spilled array because it's volatile, and resizes between calculation passes. For instance, the following formula will trigger this #SPILL! error:

=SEQUENCE(RANDBETWEEN(1,1000))

Dynamic array resizes may trigger additional calculation passes to ensure the spreadsheet is fully calculated. If the size of the array continues to change during these additional passes and does not stabilize, Excel will resolve the dynamic array as #SPILL!.

This error value is generally associated with the use of RAND, RANDARRAY, and RANDBETWEEN functions. Other volatile functions such as OFFSET, INDIRECT, and TODAY do not return different values on every calculation pass._

**Comment by 4tti** [comment]
Hey @macky360,

I think you are right:
![image](https://user-images.githubusercontent.com/19533927/109881605-dff18800-7c78-11eb-8953-052971f3e975.png)

Thanks!
