### ISSUE TITLE
Disabling your Web Add-in if you have an Equivalent COM/VSTO Add-in doesn't work?

### ISSUE THREAD

**Issue by rickgoud** [OfficeDev/office-js#1686]
Like described in the feb 2021 community call I want to disable by web-addin by setting an equivalent com add-in. I update to the latest beta version (build 2103) and set all the registry key values, but does not seem to work.... What is the best way to check what is wrong? Can we debug? Any tips/examples of people that got this working?

PATH: HKCU\SOFTWARE\Policies\Microsoft\Office\16.0\Outlook\addins\equivalentcomaddin KEY (string/REG_SZ): {OfficeJS GUID} VALUE: Prog.ID

Any help would be greatly appreciated!

**Comment by AlexJerabek** [comment]
Thanks for the question @rickgoud. I'll tag @JuaneloJuanelo, who presented that part of the community call, to help you out.

**Comment by exextoc** [comment]
Can you confirm the build number of your office build is 16.0.13801.XXXXX? (or later)

The GPO Policy tool should be used to help write those reg keys: 

https://www.microsoft.com/en-us/download/details.aspx?id=49030

![image](https://user-images.githubusercontent.com/28549921/109872144-e05e3480-7c20-11eb-9bb1-b2176d24ba15.png)

Though setting those reg keys should have worked. 

The Web Add-in Id should be the same as the one in your manifest (without brackets, but with dashes). 
The Progid should be something like Addin.ProgId 

(if you can provide some sample values here, maybe that will shed some light on why it's not working)

The addin must be connected on boot.

**Comment by rickgoud** [comment]
Hi!
See screenshot. Version is 13819.
![image](https://user-images.githubusercontent.com/13066218/109928195-7d72a900-7cc5-11eb-99b3-bd72b0bf61a3.png)

This is the value I set. I tried with or without {}
![image](https://user-images.githubusercontent.com/13066218/109928093-60d67100-7cc5-11eb-8808-4904e848f18e.png)

This is the link to the manifest: https://owa.zivver.com/v3/manifest.xml

This is the name of the equivalent Com-Add-in below
![image](https://user-images.githubusercontent.com/13066218/109928455-c0cd1780-7cc5-11eb-8cfe-7a564ecb090a.png)

But when starting Outlook Desktop. I still see the Outlook Add-in associated with the manifest.
Thanks for help!

Regards,
Rick

**Comment by exextoc** [comment]
So using the group policy editor I was able to do this: 

![image](https://user-images.githubusercontent.com/28549921/110029289-21218080-7ce9-11eb-8875-1099a2ac3a39.png)

I used the UmOutlookAddin.FormRegionAddin (since that is a COM add-in that is launched by Outlook by default)... and doing it this way correctly disabled the Zivver Web-Addin. 

To use the Group Policy Editor I download the templates from here: 

https://www.microsoft.com/en-us/download/confirmation.aspx?id=49030

Then in the extracted files I copied **outlk.admx** and **outlk.adml** 

To the appropriate directories inside 
**C:\Windows\PolicyDefinitions\**
C:\Windows\PolicyDefinitions\en-us

I opened the Group Policy Editor via 
**Windows Key -> Edit Group Policy**

After using Group Policy you should be able to see the regkeys that are set in the path you screenshotted above. 

![image](https://user-images.githubusercontent.com/28549921/110030241-51b5ea00-7cea-11eb-8365-492bb7c1c72a.png)

The GPO editor may set some other reg keys that are necessary. (though I'm not sure about that). Can you try using the Group Policy Editor? 

Could you also try using UmOutlookAddinForm.RegionAddin to see if that works instead of the Zivver add-in? (To help narrow down where the problem may be)

Does Zivver Load at Startup? (this may be the issue as Outlook checks for add-ins that are connected during startup)

**Comment by rickgoud** [comment]
Hi @exextoc ,

Thanks for you help! Tried it with Group Policy Editor and also with UmOulookAddin as you suggested, but without result.

See here the settings I set in Group Policy Editor
![image](https://user-images.githubusercontent.com/13066218/110236017-dba4c380-7f33-11eb-804f-9cd2425fd2fc.png)

See here the result that were set in the registry (as expected)
![image](https://user-images.githubusercontent.com/13066218/110236040-01ca6380-7f34-11eb-9f55-ee932ccf7bf9.png)

However, in Outlook I still see the Web-Addin. See below.
![image](https://user-images.githubusercontent.com/13066218/110236013-d21b5b80-7f33-11eb-80e2-9bc0a37388e2.png)

Please let me know what to do to help debug here.

Thanks!

regards,
Rick

**Comment by exextoc** [comment]
In the File->Options->Add-ins are the COM Add-ins being loaded? (Not Disabled)

![image](https://user-images.githubusercontent.com/28549921/110367344-67822280-7ffc-11eb-8657-aebe1d83514e.png)

And if you go Manage Add-ins (Go) 

![image](https://user-images.githubusercontent.com/28549921/110367363-6f41c700-7ffc-11eb-973d-1b2ed2156f75.png)

Are the Add-ins set to Load At Startup?

Also as a random sanity test. Does the Web Manifest you have installed have the same ID that you are using in the GPO/Reg Key? Previously you sent me https://owa.zivver.com/v3/manifest.xml to test. I just want to make sure that you are using the same one. (I apologize for asking the obvious question, but we've had developers in the past install test versions of their manifest, etc. And forget)

**Comment by rickgoud** [comment]
Hi @exextoc  ; see attached. Yes, all loaded on startup (apologies for the delay).
Any other suggestions?
Do other people got this working?

Really looking forward to getting this fixed.
Thanks!

Regards,
Rick

![image](https://user-images.githubusercontent.com/13066218/111289734-bb68b900-8645-11eb-812e-204984f5089f.png)

**Comment by exextoc** [comment]
Other people have gotten it working. Personally I was able to get it working with the Manifest you provided (https://owa.zivver.com/v3/manifest.xml) me, and the "UmOutlookAddin.FormRegionAddin" Prog Id. 

So it's curious that you weren't able to get it working with the UmOutlookAddin. At this point, I would verify that the Web Add-in GUID is in fact the same one you have in the registry. (You can check the downloaded manifests in: 

C:\Users\[USER NAME]\appdata\local\microsoft\office\16.0\Wef\{[RANDOM GUID]}\[RANDOM VALUES]\Manifests

To double check the id that is being used by Outlook against the registry. 

If you have multiple Random Guids/Random Values, you can delete the Wef folder and restart outlook to force a redownload of all the files. 

You could also try on another machine or wait for the next build? (but the build you are on, is supposed to have that fix). 

I apologize that this isn't working, but we're trying to help debug and hopefully pinpoint the root cause of what may be happening.

**Comment by robino2020** [comment]
@exextoc we have multiple customers who cannot apply a GPO because they use InTune. We've tried to apply the register key in HKCU\SOFTWARE\Microsoft\office\16.0\addins\equivalentcomaddin\ however this does not seem to work reliable. 

In some cases the Addin does get removed. However, the next time we launch Outlook the Addin shows up again. In some cases the register key does work and we cannot reproduce that it doesn't go in effect. In other cases customers are totally unable to make the register key work. We checked if the user has permissions to read the regkey, and they do have this.

**Questions:**
1. Could the issue be that the reg key is in the Policies key, and therefor permissions might cause issues?

2. Is there an alternative, so that we can enable this setting through InTune?

**Things we checked:**
- Customer is using required Outlook build
- Customer is using correct AppID and COM Add-in name.
- We tried disabling UmOutlookAddin.FormRegionAddin, this also didn't work
- Addin is succesfully loaded

**Comment by exextoc** [comment]
@robino2020 If a user cannot use a GPO, then you should use the manifest method, and add the equivalentAddins section to your manifest as described here: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/make-office-add-in-compatible-with-existing-com-add-in. 

Note if your customers are on Exchange On Prem, they will have to update to the latest CU versions of Exchange. (Exchange Online is already up to date).

**Comment by lachvit** [comment]
Hi guys, maybe you will be able to help me. I'm experiencing similar issues, but with Office 2016, do we have any solutions for Office 2016?

**Comment by AlexJerabek** [comment]
Hi @lachvit,

The build requirements for the equivalent COM add-in feature are listed here: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/make-office-add-in-compatible-with-existing-com-add-in 

Basically, you'll need a supported version of both Outlook and Exchange.

- Outlook on Windows (version 2102 or later) against a supported Exchange server version
  - Exchange Online
  - Exchange 2019 Cumulative Update 10 or later ([KB5003612](https://support.microsoft.com/topic/b1434cad-3fbc-4dc3-844d-82568e8d4344))
  - Exchange 2016 Cumulative Update 21 or later ([KB5003611](https://support.microsoft.com/topic/b7ba1656-abba-4a0b-9be9-dac45095d969))

**Comment by lachvit** [comment]
Hi @AlexJerabek,

Thank you for you answer. I'm using exchange online and everything works fine with Outlook 365 but doesn't work with Outlook 2016, so if I understand correctly this solution is not designed for Office 2016. Maybe we have another solution for older office versions?

**Comment by AlexJerabek** [comment]
Hi @lachvit,

I don't believe there's a solution for Outlook 2016, but let me tag @exextoc to confirm.

**Comment by exextoc** [comment]
Yes, this is correct this solution does not work for Outlook 2016. There is no equivalent in Outlook 2016, other than to disable /remove the web addin manually

**Comment by lachvit** [comment]
@exextoc Thank You for you reply, could you elaborate more about: "than to disable /remove the web addin manually"? How I can remove we add-in, because I can't see it in "Add remove programs" or Outlook add-in list.

**Comment by exextoc** [comment]
@lachvit Do you see the web addin in "Get Add-ins" on the ribbon or File > Manage Add-ins (note that this is a different button from the COM add-ins) similar to what's described in https://support.microsoft.com/en-us/office/get-an-office-add-in-for-outlook-1ee261f9-49bf-4ba6-b3e2-2ba7bcab64c8 ?

Alternatively, you can also use powershell to get https://docs.microsoft.com/en-us/powershell/module/exchange/get-app?view=exchange-ps, disable https://docs.microsoft.com/en-us/powershell/module/exchange/disable-app?view=exchange-ps, or remove https://docs.microsoft.com/en-us/powershell/module/exchange/remove-app?view=exchange-ps

**Comment by lachvit** [comment]
@exextoc  once again thank You for your help. If I choose File > Manage Add-ins , I'm able to see that add-in, but I can't remove it (remove button is greyed out). Looks like everything what is related with web add-in settings doesn't work in Outlook 2016. I've blocked web add-ins using GPO, but his add-in is still active... :) 
![image](https://user-images.githubusercontent.com/58638102/155723831-6d1373ab-455e-4240-beeb-d56e88e1f8bf.png)

In my case I can't remove this add-in from user account. We need this add-in for all operating systems except Windows + Outlook 2016. So I need to figure out, how to remove this add-in from Outlook 2016.

**Comment by exextoc** [comment]
Thanks for trying and clarifying. The previous suggestions were all for remove the add-in from the user's account. I did not realize you only need to remove the addin for only specifically Windows Outlook 2016.  Unfortunately, I do not have other alternatives

**Comment by lachvit** [comment]
@exextoc anyway, thanks for your collaboration, I really appreciate it.
