### ISSUE TITLE
Get the range of field inserted in a document office -js word web-addin

### ISSUE THREAD

**Issue by arshadshibli** [OfficeDev/office-js#1698]
I have to insert a field around a selected range to implement a functionality. As fileds are not supported in office-js I am using office open xml . I have implemented the code to insert a field before and after a selected text in a word document. OOXML corresponding to the field inserted looks like.
```
<w:r>
     <w:fldChar w:fldCharType='begin' />
</w:r>
<w:r>
    <w:instrText xml:space='preserve'>confidential</w:instrText>
</w:r>
<w:r>
      <w:fldChar w:fldCharType='end' />
</w:r>
```
**After inserting is there anyway I can select the range where the fields are inserted.**

For example in Word.ContentControl class we have select() method which will scroll to the selection, Also it has getRange() method.

Is there any way the same functionalities ( select() and getRange() ) can be done for a field inserted in a document

office-js
word web-addin

**Comment by keyur32** [comment]
@AbidRahman-MSFT  - can you take a look please?

**Comment by AbidRahman-MSFT** [comment]
Hey @arshadshibli ,

In the future, I highly suggest you post your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/office-js) and tag `office-js` as it will help you quickly get an answer from the wider office js community. 

For issues and/or unexpected behavior regarding APIs, feel free to continue posting an issue on this GitHub repo.

For this specific scenario, there is no way to select() or getRange() for a field using OfficeJS. Is there any specific reason for using Fields instead of ContentControls? You can use the select() method on items like a Body, Paragraph, Range, Table, TableRow, and the base ContentControl class as well.

A possible workaround here would be to search for the raw text that you inserted in the Field using code in this article: [Search Guidance](https://docs.microsoft.com/en-us/office/dev/add-ins/word/search-option-guidance), after finding each range of text, you can call .select() on the range and it will select and scroll to the selection.
