### ISSUE TITLE
Unable to Load addin in MS - Word 365 - saying content is blocked as it is not signed by a valid security certificate  

### ISSUE THREAD

**Issue by harit-m-kumar** [OfficeDev/office-js#1712]
i am trying to side - 
![error](https://user-images.githubusercontent.com/58638877/110950070-6557f500-8369-11eb-97e8-ae5cafcda20e.PNG)
![Version](https://user-images.githubusercontent.com/58638877/110950073-66892200-8369-11eb-9189-87c6bf5c47b4.PNG)

load an addin, which works well in other systems with the same office versions. The addin loads with an error saying - The content is blocked because it is not signed by a valid security certificate.
My version and the error are attached. Please help

**Comment by nikhilism15** [comment]
Wherever you deployed your JS code, it needs to be HTTPS enabled. You need to install a self-signed certificate to setup HTTPS in the server.

**Comment by AbidRahman-MSFT** [comment]
Hey @harit-m-kumar, as nikhilism15 mentioned you need to install a self-signed certificate to setup HTTPS in the server that is hosting your JS code. 

As this issue is not related to Office Js or the APIs involved, I'm closing this issue. If you continue to have related problems with sideloading the add-in, I suggest posting a question on StackOverflow with the tag 'office-js', that will allow for the broader community to help you out regarding any developement issues. If you see any unexpected behavior for an API, please do open a different issue on GitHub.

Thanks!
