### ISSUE TITLE
Document get changed on replacing OOXML with it's own OOXML without making any modification

### ISSUE THREAD

**Issue by arshadshibli** [OfficeDev/office-js#1718]
I have a requirement where I am getting the OOXML of a word document , Inserting it back after making some modification . I have to upload the modified document to server from my addIn . But the server does not recognize the document as a modified version of previous document.
So I just tried to get the OOXML of a document and insert it back without making any changes.

`await Word.run(async (context) => {
          const body = context.document.body
          const ooxml = body.getOoxml()
          await context.sync()
          body.clear()
          body.insertOoxml(ooxml.value, 'Replace')
          await context.sync()`

But when I compared the OOXML of the document before and after the above function I can see a lot of changes like paragraph IDs 
## Expected Behavior
OOXMLs corresponding to document before and after the operation (Get the OOXML ,and insert it back) should be same

## Current Behavior
OOXML of the same document have many differences before and after the above operation

## Context
I have to find the all the fields in a document and replace it with content controls as fields are not supported in office-Js. But after this operation server does not recognize the document. That's why I tested whether the document will change once we get the OOXML and replace it back

## Your Environment
Windows
Office on web

## Useful logs
Attached the screenshots of OOXML corresponding to the same part of document before and after the operation as a sample
![compare](https://user-images.githubusercontent.com/36449762/111186966-8d4d8f80-85d9-11eb-879d-68dab16a8cc7.PNG)

**Comment by keyur32** [comment]
@AbidRahman-MSFT  to help investigate. 

On surface, this could be Word's code running in the app and modifying the content that is inserted (i.e. for example re-laying out things).

**Comment by AbidRahman-MSFT** [comment]
Hey @arshadshibli,

Thanks for reporting this behavior. This is expected behavior for Word. Here is some more context on the behavior from @yihuax:

When ooxml is inserted, Word doesn’t compare the new paragraphs with the paragraphs that will be replaced. So, we basically say, we now have paragraphs a, b, c, d, and we are inserting a few paragraphs that will replace a/b/c/d. We cannot name the new paragraphs as a,b,c,d, because a/b/c/d are not actually removed permanently. The old paragraphs are put into the undo document (a hidden document), and thus we have to name the new paragraphs as u, v, w, x. In fact, after the insertOoxml API is executed, the user can click the undo button and restore the old paragraphs. This can be done by

```
Word.run(async function (ctx) {
    var body = ctx.document.body;
    var ooxml = body.getOoxml();
    await ctx.sync();

    body.font.color = "red";
    await ctx.sync();

    body.clear();
    body.insertOoxml(ooxml.value, "Replace");
    await ctx.sync();
});
```

Then if user clicks undo, the document becomes red. Click undo again, the document restores to the status of very beginning.

Thus, Word only guarantees what user can see will be the same. As for the paragraph ID and the other supporting properties, they may change. This is by design.

**Comment by arshadshibli** [comment]
@AbidRahman-MSFT Thanks for the info. Change in the paragraph IDs are ok. But In my case I can see even a **bookmark got deleted** after the above operation . Is that also expected
![bookmarkmissing](https://user-images.githubusercontent.com/36449762/111969729-8d411880-8b20-11eb-958e-a12cc9074305.PNG)

**Comment by AbidRahman-MSFT** [comment]
That's certainly not expected, few clarifying questions:

1. Is this on Word for Web only?
2. Everytime you create a new bookmark, and then call the Ooxml api, does it remove the bookmark?

Can you provide some repro steps that can help us debug the issue?

Thanks,
Abid

**Comment by arshadshibli** [comment]
Hi @AbidRahman-MSFT 

1. This is in word web only .
2. I have many bookmarks in the document . It does not delete all the bookmarks , Only one bookmark shown in the image is getting deleted.

**Comment by AbidRahman-MSFT** [comment]
Hey @arshadshibli - if you are able to **consistently** reproduce this missing bookmark issue, can you please open a new issue with the sample document and the sample code and we can help investigate why its occuring.

Thanks,
Abid
