### ISSUE TITLE
loadCustomPropertiesAsync() never fires callback

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js#172]
In my code it seems the callback for loading custom properties never gets called.

```js
Office.context.mailbox.item.loadCustomPropertiesAsync(function () { console.log("hello") })
```

"hello" never gets printed.

Following this example here
https://docs.microsoft.com/en-us/outlook/add-ins/metadata-for-an-outlook-add-in#custom-data-per-item-in-a-mailbox-custom-properties

But no, with the version fetched from `//unpkg.com/@microsoft/office-js@1.1.8/dist/office.js` that callback really never seems to be triggered. The request is made, I can see in the dev console but the callback isn't run at all.

Smells like a bug to me.

**Comment by exextoc** [comment]
Hi binarykitchen,

we just tried to reproduce this on our side, but couldn't. What version of Outlook or OWA are you trying to do this in? is code execution getting to the loadCustomProperties call?

**Comment by binarykitchen** [comment]
I found the problem in my case. It was something else.

I put the above async code inside `Office.initialise()` which was plain wrong. Any code going in there must be synchronous. Anything async will have weird, unforeseen consequences and code is becomes instable.

If you want to add async code, you must drop them inside the `ExecuteFunction` function.

This is not documented. To save other developers from this pain, I would emphasize this in bold not to put anything async during initialisation.

**Comment by exextoc** [comment]
You can call async code in Office.Initialize(), but at anypoint Outlook will call your ExecuteFunction function. If ExecuteFunction finishes before whatever async calls you made in Office.Initialize(), and you complete the event, then it will close your add-in and you won't get any results. You could also wait for your callback to finish, before completing the event, in execute function. 

For UILess Commands it is probably simpler to make your calls in ExecuteFunction(). But for other add-ins like taskpanes, it makes sense to make your calls in Office.Initialize() since that is the only thing that is called.

**Comment by binarykitchen** [comment]
Right, I found that out myself. But wish this was documented. Can you add this for better DX?

**Comment by Rick-Kirkham** [comment]
@exextoc 
Is this an issue only for Outlook or for all Office Add-ins? What exactly do we want to add to the documentation for Office.initialize? Is it OK to have async calls there, if they are `await`ed?

**Comment by JuaneloJuanelo** [comment]
issue resolved probably we need to are more recommendations on initializaiton for UIless commands vs taskpanes.
