### ISSUE TITLE
Get email addresses of distribution list in Outlook

### ISSUE THREAD

**Issue by rickgoud** [OfficeDev/office-js#1723]
Hi,

We want to validate recipients in an Outlook Add-in, but what is the best way to do that? The documentation is not clear on how to do that with OfficeJS or am I missing something?

Any help would be greatly appreciated!

Regards,
Rick

**Comment by smaremanda** [comment]
@rickgoud Hi Rick - can you please explain the scenario a bit more? Will help us point you in the right direction.

**Comment by rickgoud** [comment]
Hi,

To check whether users are allowed to receive documents/messages and whether information is allowed to be shared, we need to know/check the individual recipients underlying a distribution list (so the individual email addresses). With COM-addins this is possible, so want to understand how this possible with OfficeJS too.

Does this help?

Thanks!

Regards,
Rick

**Comment by exextoc** [comment]
Hey @rickgoud,

We do not have an API to expand DLs through OfficeJS as of today. But you can use the Groups Graph API to help with your case.
The documentation for Graph API: https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&tabs=http

And these are the links on how to use Graph API in your application [with SSO](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph#:~:text=The%20best%20way%20for%20an,Excel%2C%20Outlook%2C%20and%20PowerPoint.) and [without SSO](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph-without-sso)

**Comment by lindalu-MSFT** [comment]
Closing because question has been answered. Please reactivate if you need further assistance! Thanks, linda

**Comment by frezo00** [comment]
Hi @exextoc,

I've been checking the Graph API documentation based on the answer you gave to @rickgoud, but it seems like it is not the answer we were looking for. So, if the user creates a group, that group will have its own email and members which is totally fine.
But the problem is that the users often create the distribution list using the "New contact list" under the _People_ section like on the image below:

![outlook-contact-list](https://user-images.githubusercontent.com/13180753/112621882-9127b000-8e2a-11eb-81fc-b171bed81bf9.png)

We cannot find a way to get those contact lists from the API nor their members. Are we missing something or there is no way to get that data using the Graph API or the OfficeJS?

Best regards,
Frano

**Comment by exextoc** [comment]
@frezo00 - As the original issue has been closed, may we recommend to please open a separate issue with what you're tryin to achieve/issues you are facing. This way we can have an active involvement on the new post and make sure that appropriate help is provided. It may also help others who are facing a similar issue.

**Comment by frezo00** [comment]
Thanks @exextoc, 
the question has been posted on [the Stack Overflow](https://stackoverflow.com/questions/66852944/how-to-get-distribution-list-not-group-with-its-members-inside-the-outlook-usi) with the `office-js` tag as described in the description for "_How to ..._" issues.
I hope to be checked/answered soon 😊
