### ISSUE TITLE
Excel Add-In: Table OnChange event sometimes does not trigger after cell value change

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#1760]
And if user changes values with a high speed, some cell value change event just ignored. 

## Expected Behavior
Excel.TableChangedEventArgs triggers for every cell change

## Current Behavior
Excel.TableChangedEventArgs triggers not for every cell change, some cell value change event just ignored during cells change

## Steps to Reproduce, or Live Example
Here is simple snippet for cell color change after cell's value change

```
public cellChange = async  (event: Excel.TableChangedEventArgs): Promise<any> =>
{
    try
    {
        await Excel.run({delayForCellEdit: true}, async context =>
        {
            try
            {
                context.runtime.enableEvents = false;

                if (event.changeType === Excel.DataChangeType.rangeEdited)
                {
                    let worksheet = context.workbook.worksheets.getActiveWorksheet();
                    let address = event.address;
                    let str = "Cell address: " + address + " START";
                    var start = new Date().getTime();
                    
                    let rng = worksheet.getRange(address);
                    rng.format.fill.color = "#D0DC94";
                    await context.sync();

                    var end = new Date().getTime();
                    var time = end - start;
                    str = str + `-END:${time}ms`;

                    console.log(str);
                }
            }
            catch (error)
            {
                let e: Error = error;
                let mssg = e.message;
            }
            finally
            {
                context.runtime.enableEvents = true;
            }
            return context.sync();
        });
    }
    catch (error)
    {
        let e: Error = error;
        let mssg = e.message;

        if (error instanceof OfficeExtension.Error)
        {
            console.log("Debug info: " + JSON.stringify(error.debugInfo));
        }
    }
}
```

## Context
I am developing an Excel add-in that allows to synchronize changed table cell values with external environment during Excel data changes - sort of Live Update.

## Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
Host [Excel, Word, PowerPoint, etc.]: Excel for Microsoft 365
Office version number: 16.0.13127.21336 64bit
Operating System: Windows

## Useful logs
![capture-1](https://user-images.githubusercontent.com/7677514/112793569-57071a00-9087-11eb-8b06-15a670ba9e7b.gif)

Event doesn't trigger for cells G15 and G18 at all.

**Comment by gingerjia** [comment]
@shss1985, if you comment out "context.runtime.enableEvents = false;" and "context.runtime.enableEvents = true;", then the issue won't happen.

Can I know your purpose here to add 'context.runtime.enableEvents = false;'? Thanks.

**Comment by ghost** [comment]
@gingerjia Thanks, it is really solving the problem! 
Actually it was skeleton from other method that populates excel from the db, and I have to switch off events to update excel cell values, because it will triggers cell change even and start db update and just go in cycle. But for now I have to be careful with using `enableEvents` method.
Is there an explanation why enabling/disabling events causing this type of issue?

**Comment by gingerjia** [comment]
It's great that the suggestion works for you!

Why enabling/disabling events causing this type of issue?
It's because the event handler calls from two separate trigger cannot make sure the execution sequence 1-by-1. 
For example, when modify the cell G15 value, it will execute the callback. 
Then modify the cell G16 quickly, it will try to trigger event and execute the callback. 
And since it's very quickly to modify G16, the callback execution of G15 hasn't been finished yet, so the context.runtime.enableEvents is still false, then the event for G16 won't be triggered.
If modify G16 happens after the G15 modification callback execution finished, then the context.runtime.enableEvents has been set to true, the event for G16 will be triggered as expected.

I will close this issue thread here if no other concerns. And welcome for any other questions or suggestions! :)
