### ISSUE TITLE
On-Send and ability to publish to AppSource

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#1780]
I have come across a few previously closed issues that no conclusion was made around the ability to publish an add-in that uses the On-Send functionality to AppSource. It was stated that post-GA, it would be allowed. Yet, the feature is now GA and documentation still states that you cannot publish an add-in utilizing the On-Send feature.

Referenced issues:
- https://github.com/OfficeDev/outlook-dev-docs/issues/724
- https://github.com/OfficeDev/outlook-dev-docs/issues/754

The question is will we ever be able to publish add-ins that utilize On-Send to AppSource? If not, this was pretty misleading and really hinders the ability to get our add-in in the hands of customers.

**Comment by exextoc** [comment]
@cody-lettau Could you provide some details about the scenario you're looking to implement using the On-Send functionality?

Since On-Send add-ins are not allowed in AppSource (plus other limitations), the Outlook add-ins team has been implementing other APIs or events to enable similar scenarios for add-ins in AppSource. So far, these include the [appendOnSend API](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/append-on-send) (in requriement set 1.9) and [event-based activation](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch) (currently in preview).

I believe the original answer was clarified by Elizabeth in a reply to OfficeDev/outlook-dev-docs#754. While it's true that APIs in preview cannot be used in production add-ins, the On-Send feature has additional limitations. Sorry for any confusion.

> While the feature is now available for use in production add-ins, it is not allowed in AppSource.

This and other limitations for On-Send add-ins are [described here](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=windows#limitations).

**Comment by cody-lettau** [comment]
@exextoc So we are working on an add-in that allows for encryption of emails using TDF. When composing an email, we have numerous different options around encryption of your email (expiration, attachment handling, etc). When the user clicks "Send", we have an On-Send function that is triggered. This takes the body content and attachments, encrypts all of it using TDF, and then sets the body to HTML that has the encrypted content (which our add-in can also read) and allows the message to be sent.

I had read through the limitations of the On-Send add-ins, but did see @kbrandl mention in https://github.com/OfficeDev/outlook-dev-docs/issues/724 that once the On-Send functionality was GA'ed we would be able to publish to AppSource.

I'm not sure there's any alternative in regards to implementation that would allow us to ensure the composed message is encrypted (including attachments -- which we encrypt as well and remove the unencrypted attachments).

I'd be glad to jump on a call to give a quick demo some day if it would be helpful (since I've opened a few issues and want to be as helpful as possible).

**Comment by JuaneloJuanelo** [comment]
@cody-lettau  thanks so much for sharing your scenario. I have good news and bad news for you. The bad news is that the OnSend add-ins are still not allowed in the store and the main reason why is because if your add-in becomes unavailable (due to page maintenance or whatever other reason) then users can't send email. Which in some cases is desired and in others totally unacceptable. 

I think what Kim was referring to in that post, and the good news,  is that we are currently working on a variation of the OnSend feature that will solve this problem and will allow Add-ins to be in the store. I think we will have a preview soon, so please stay tuned!.  

I talked a bit about how this feature will work on one of our community calls please check it here https://www.youtube.com/watch?v=zEkmNiIyHqw&t=1534s  (jump to 22:50 :) )

BTw i would love to hear the details of your solution and make sure our design will work for your, please email me (juanbl@microsft.com) so we can chat about it. thank you so much! 

I am closing this issue in the meantime.

**Comment by cody-lettau** [comment]
@JuaneloJuanelo thanks for the detailed reply. I just followed up with you via email.

**Comment by cody-lettau** [comment]
@JuaneloJuanelo I attempted to email you but I received a "Delivery incomplete" response.
