### ISSUE TITLE
in office.word, is there any api for setting 'header from top' and 'footer from bottom'?

### ISSUE THREAD

**Issue by waveheart** [OfficeDev/office-js#1790]
i need set default value of the 'header from top' , 'footer from bottom',  i did not found any api for it.
and for setting  margin of the word.body, i did not found any api either.

**Comment by lindalu-MSFT** [comment]
Can you explain what you are trying to do? Are you using VBA, VSTO, JavaScript... Please provide your platform, Word version, language, etc. so we can triage. Here is the template:

## Expected Behavior


## Current Behavior



## Steps to Reproduce, or Live Example



* Link to live example: ______


* Additional details:
  1. ______
  2. ______
  3. ______

## Context



## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by RuoyingLiang** [comment]
Thanks for reaching out. Currently there is no API to set the position of header and footer. You can set header/footer's body to target style. Add the request to backlog. Could you please submit the request with your scenario in  [https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform](url) ?
