### ISSUE TITLE
while using  Office.context.document.getFileAsync, Office.context always empty

### ISSUE THREAD

**Issue by digish777** [OfficeDev/office-js#1798]
while using  Office.context.document.getFileAsync, Office.context always empty.

I am using   Office.context.document.getFileAsync inside angular 11 application.

due to this, document always remain undefined. what is that issue?

calling the above method inside:
  const file: any = event.target.files[0];
      reader.readAsDataURL(file);
      reader.onload = () => {
                Office.context.document.getFileAsync(Office.FileType.Compressed, { sliceSize: chunkSize }, (asyncResult) => {
               }
      };
    }

initializing office js in main js :

declare const Office: any;
if (environment.production) {
  enableProdMode();
}

function launch() {
  platformBrowserDynamic().bootstrapModule(AppModule)
    .then((success: any) => {
      console.log('Main: AppModule bootstrap success', success);
    })
    .catch((error: any) => {
      console.log('Main: AppModule bootstrap error', error);
    });
}

Office.onReady(() => {
  console.log('Main - Initializing office.js');
  launch();
  console.log('Main - Office.js is initialized');
});

main js link is there in index.html

**Comment by lindalu-MSFT** [comment]
Hi, thanks for reaching out to us! However, in order for me to triage this, can you please fill out the following information? Also, since this appears to be a programming question, you can also try reaching out to the developer community on [Microsoft Q+A](https://docs.microsoft.com/en-us/answers/topics/office-js-dev.html) or on Stack Overflow.



## Expected Behavior


## Current Behavior



## Steps to Reproduce, or Live Example



* Link to live example: ______


* Additional details:
  1. ______
  2. ______
  3. ______

## Context



## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by digish777** [comment]
that was helpful
