### ISSUE TITLE
getAttachmentContentAsync throws error that is not catchable

### ISSUE THREAD

**Issue by eneoli** [OfficeDev/office-js#1801]
As stated in  #644, getAttachmentContentAsync fails to fetch the attachments when waiting 5 - 10 minutes. In that case the following error is thrown:

`Uncaught (in promise) o {message: "Invalid token specified", filename: "", lineno: 0, colno: 0}
`

![image](https://user-images.githubusercontent.com/23139864/115015723-63c3a480-9eb4-11eb-916c-79c8922547c2.png)

The problem is, that the error is thrown within setInterval, so it is not possible to catch it...

## Steps to Reproduce, or Live Example
wait 5 - 10 minutes
Office.context.mailbox.item.getAttachmentContentAsync(id)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: latest OWA
* Operating System: Linux
* Browser (if using Office on the web): Chrome

**Comment by bconners1005** [comment]
I'm also receiving this error and have tried a bunch of different ways to capture it so that the system will continue to function to no avail yet as the Promise structure breaks the chain of events.

My use case is less the above issue and more that if I try to continually go out and in to the plug-in, but never refreshing the actual email on OWA.

So, my use case is someone opens and closes the plug-in, that calls the getContentAsynch, an undefined amount of times.  The amount doesn't seem set but eventually this error will happen when calling for an attachment.  It is never all of them either it will seemingly pick the second one of a list?

Eventually though the system needs you to load another email or meeting, doesn't matter the type or if it has attachments, and then navigating back.  The system then responds again as intended.

**Comment by bconners1005** [comment]
@exextoc I hadn't been doing any tagging on this, but was there any momentum on this?

It causes the responses and the feature extension to be erratic.  Sometimes making it unusable without having to do full reloads of the items.

As the original poster had mentioned it seems to happen when there is a setInterval or timer on checking the asynch status of the returns.  I have tried doing an unhandled exception call on the window but it doesn't seem to correctly process as the lack of catch causes the process to freeze.

**Comment by eneoli** [comment]
@exextoc, @lindalu-MSFT  Does someone mind taking a look at it?

**Comment by exextoc** [comment]
@EneOli @bconners1005 Apologies for delay in responding. We will take a look at this shortly and get back to you.

**Comment by exextoc** [comment]
@EneOli @bconners1005 We tried reproducing this in-house but we are not able to. Here are our steps:
1. Open email with attachment
2. Open addin and keep it open for 10mins.
3. Then try running getAttachmentContentAsync API from same addin.
4. Result: API works and it returns attachment content.

We tried this multiple times and still not able to repro this.

Question:  Are you able to repro this all the time or it happens only few times?

Once again, I apologize for the delay in response on this issue.

**Comment by eneoli** [comment]
The issue still exists and happens even, if the addin is not open.

So opening a mail, waiting 10 minutes and than executing a addin command results in the error

**Comment by exextoc** [comment]
We are unable to reproduce this issue .Can you please share the repro video and console logs to investigate further?

**Comment by Krismix1** [comment]
Hi, we are also hitting this problem.

I will try later to prepare some better reproduction steps and maybe put together a sample repository.
The issue is happening somewhat consistently for me, e.g. today I had it happen at least 5-7 times.

But just to give some context where/when it happens:

1. I open an email
2. Click the button for the plugin.
3. The plugin opens a dialog and fetches the content of attachments from the email via `getAttachmentContentAsync`.
Everything works fine, the plugin does its thing. The dialog window stays open because it shows some information to the user.
4. After ~5 minutes, I close the dialog and try to open it again (from step 2). The dialog opens but the part that relies on the attachments no longer works, and the error appears in the console.

So far I saw this error in Firefox on Linux, during development. The addin files are served from localhost. I haven't tried other browsers or platforms, and I haven't verified if a deployed version is affected.

The stack trace:
![image](https://user-images.githubusercontent.com/21205591/146205644-d59ae38f-118c-41fc-9bd2-dcea20b04148.png)


```
Uncaught (in promise) 
Object { message: "Invalid token specified", stack: "1125@https://outlook-1.cdn.office.net/owamail/20211206021.06/scripts/owa.447.js:1:5987\nu@https://outlook.office.com/mail/inbox/id/AAQkADcwYTYwODBkLWU4YmItNDJkZC04YTYxLWM4ODRlMzU5NTIwZgAQAKUdx6zCuv1MmWH2kCZ5o7U%3D:604:8742\n5558@https://outlook-1.cdn.office.net/owamail/20211206021.06/scripts/owa.447.js:12:537166\nu@https://outlook.office.com/mail/inbox/id/AAQkADcwYTYwODBkLWU4YmItNDJkZC04YTYxLWM4ODRlMzU5NTIwZgAQAKUdx6zCuv1MmWH2kCZ5o7U%3D:604:8742\n19476@https://outlook-1.cdn.office.net/owamail/20211206021.06/scripts/owa.447.js:1:40601\nu@https://outlook.office.com/mail/inbox/id/AAQkADcwYTYwODBkLWU4YmItNDJkZC04YTYxLWM4ODRlMzU5NTIwZgAQAKUdx6zCuv1MmWH2kCZ5o7U%3D:604:8742\n", … }
​
colno: 0
​
filename: ""
​
lineno: 0
​
message: "Invalid token specified"
​
stack: "1125@https://outlook-1.cdn.office.net/owamail/20211206021.06/scripts/owa.447.js:1:5987\nu@https://outlook.office.com/mail/inbox/id/AAQkADcwYTYwODBkLWU4YmItNDJkZC04YTYxLWM4ODRlMzU5NTIwZgAQAKUdx6zCuv1MmWH2kCZ5o7U%3D:604:8742\n5558@https://outlook-1.cdn.office.net/owamail/20211206021.06/scripts/owa.447.js:12:537166\nu@https://outlook.office.com/mail/inbox/id/AAQkADcwYTYwODBkLWU4YmItNDJkZC04YTYxLWM4ODRlMzU5NTIwZgAQAKUdx6zCuv1MmWH2kCZ5o7U%3D:604:8742\n19476@https://outlook-1.cdn.office.net/owamail/20211206021.06/scripts/owa.447.js:1:40601\nu@https://outlook.office.com/mail/inbox/id/AAQkADcwYTYwODBkLWU4YmItNDJkZC04YTYxLWM4ODRlMzU5NTIwZgAQAKUdx6zCuv1MmWH2kCZ5o7U%3D:604:8742\n"
​
<prototype>: InvalidTokenError: 
getAttachmentContentAsyncApiMethod.ts:93:17
    on getAttachmentContentAsyncApiMethod.ts:93
    InterpretGeneratorResume self-hosted:1485
    AsyncFunctionThrow self-hosted:699
    (Async: async)
    un executeApiMethod.ts:88
    I EndpointRegistrator.ts:41
    invoke osfruntime.js:19
    E osfruntime.js:19
    x osfruntime.js:19
    (Async: setInterval handler)
    F osfruntime.js:19
```

Edit:
The version of the library, may be important:
office-js: 0.1.0
@microsoft/office-js: 1.1.71

**Comment by Krismix1** [comment]
@exextoc I have put together a repository that can trigger this issue: [link](https://github.com/Krismix1/officejs-repro-attachments-issue). The most interesting part is probably [here](https://github.com/Krismix1/officejs-repro-attachments-issue/blob/master/src/taskpane/taskpane.ts#L52).

Reproduction steps:
I have observed this behaviour in Google Chrome 96.0.4664.110 and Firefox 96.0b5.

You will need to have an email with an inline image attachment. You can generate one by using the snipping tool to take a screenshot and paste it into an email. Send that email to yourself.
Clone the repo, run the plugin, and install the manifest for yourself.
1. Open the email with an inline image
2. Open the plugin task pane (click "Show taskpane")
3. Open the devtools console
4. Click the "Run" button.
In the console, you should see something like this
![image](https://user-images.githubusercontent.com/21205591/146761754-4cb5979c-33be-4987-87f7-02e5088d68bd.png)
If the inline image was correctly setup, then the filtered images should be > 0
5. Wait 10 minutes
6. Click the "Run" again
7. You should see the error now
![image](https://user-images.githubusercontent.com/21205591/146763466-1f3d2435-35b5-41af-bd48-05dce7dc1887.png)

From what I understand, when invoking `getAttachmentContentAsync` it sends a request to `https://attachments.office.net/owa/<email>/service.svc/s/GetFileAttachment` with a JWT token in the query params. This JWT token has an expiration time of ~9 minutes and 40 seconds and perhaps is generated when the API is called the first time or the email is opened.

Switching to a different email item and back to the initial one appears to cause a new token to be generated.

You might notice that I have tried to execute the function automatically after 10 minutes. But for some unknown reason, after the timeout, the function runs fine...but not when I click "Run" again.

Hope this makes sense and will provide some help.
Let me know if I should provide any more details.
