### ISSUE TITLE
Forwarded attachment Id is invalid in Outlook Desktop

### ISSUE THREAD

**Issue by wertyphil** [OfficeDev/office-js#182]
My application is getting an access token and a list of attachment Ids (provided by `Office.context.mailbox.item.attachments`), then I send it server side (ASP.NET) to download their contents.
I try to download their contents using the ExchangeService Manage API, but GetAttachments returns an error.

## Expected Behavior
Attachments ids should be valid on a forwarded email.

## Current Behavior
A "Invalid attachment id" error occurs when attempting to fetch the attachment with the Exchange API.

## Steps to Reproduce

With a manifest override for MessageRead of outlook (With functionfile or taskpane to access the `Office.context`):

Follow this [tutorial](https://docs.microsoft.com/en-us/outlook/add-ins/get-attachments-of-an-outlook-item) from Microsoft.

Note that the [`Microsoft.Exchange.WebServices`](https://www.nuget.org/packages/Microsoft.Exchange.WebServices/) v.2.2.0 nuget package published by Microsoft was last updated 01/15/2015 and doesn't work with the tutorial.
I used [`Exchange.WebServices.Managed.Api`](https://www.nuget.org/packages/Exchange.WebServices.Managed.Api/) v2.2.1.1 nuget package which is maintained.

* Additional details:
1. I found a related issue on [stackoverflow](https://stackoverflow.com/questions/35453604/cant-get-attachments-from-ews-for-fowarded-emails-in-an-outlook-addin-in-the-de).
2. Using the exact same setup, with the same email and attachments, but with Outlook online, successfully downloads their contents. So Outlook Online Ids provided by the `Office.context` are valid.

## Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office Click-to-Run Version 1705 (8201.2209)
* Operating System: Windows 10

**Comment by exextoc** [comment]
This issue should have been fixed in Office C2R Version 16.0.8303.1000 and later. 

However, e-mails that were downloaded to the offline cache (OST) in versions OLDER than that, will still be incorrect even after the upgrade. (newly received e-mails after applying the fix, should be fixed)

You can trigger a re-download of these e-mails by deleting your OST. I don't have a direct link to these instructions, but it is searchable: https://www.google.com/search?q=deleting%20your%20ost&oq=deleting%20your%20ost

I recommended that instead of deleting your OST, you make a backup copy of it, and move it somewhere else, in case something goes wrong. (or maybe just rename it). That should trigger a re-download of your e-mails, and fix the problem if you are on a fixed version. 

If you are writing an add-in and can't guarantee the version of Outlook that you are running on. You can fallback on the workaround that you mention, and make an EWS call to GetItem and get the Attachment IDs that way. 

(i.e try using the provided attachment IDs, if they don't work fallback on the GetItem call)

**Comment by JuaneloJuanelo** [comment]
@wertyphil did you tried the recommendation? is this still an issue?

**Comment by wertyphil** [comment]
@JuaneloJuanelo Sorry for the lack of response.
Since we can't guarantee the version of Outlook we are running on, using the fallback to EWS was our only option.
### Additional questions
- Is there an issues board for ExchangeService Manage API, or is it being deprecated?
- Since the Outlook client can download attachment content, could the Officejs Api provide some kind of `getContent` method on attachment objects? This would remove the back and forth / the need of for a custom server endpoint to handle attachment downloads.
