### ISSUE TITLE
Column Width incomprehensible and not documented in API docs

### ISSUE THREAD

**Issue by troywweber7** [OfficeDev/office-js#187]
## Expected Behavior

I expect that setting a range format `columnWidth` to 64 or 8.43 should set it to either 64 pixels or 8.43 zero-character widths. This does not appear to be the case as setting it to 8.43 * 5.75 produces 8.43 character widths but setting it to 1 * 5.75 produces 0.43 column widths. Therefore, the `columnWidth` property is incomprehensible.

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: Linux
* Browser (if using Office Online): Chrome

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by JuaneloJuanelo** [comment]
@Rick-Kirkham  probably we need to be more clear on this. Is this points? picels?

**Comment by Rick-Kirkham** [comment]
@troywweber7 @JuaneloJuanelo The source file for the reference topic for Range.format.columnWidth has been corrected. The unit-of-measure for columnWidth is points. Due to an upcoming change in the way that we generate reference topics, it may be a couple of weeks or so before the fixed version is public.
