### ISSUE TITLE
Salesforce Outlook Integration - Microsoft Edge Webview2 - Multiple Instances running and Memory Leak 

### ISSUE THREAD

**Issue by atvoegerl** [OfficeDev/office-js#1913]
When using Salesforce Outlook Integration to log emails the add-in will crash.  We have observed that multiple instances of Microsoft Edge Webview2 are running as Outlook processes in Task Manager.  We have determined that these processes are spawned by the Outlook Integration add-in.  We would only expect 1 Webview2 process to run.  In addition to the multiple processes, memory usage increases with every logged email until the add-in eventually crashes. Salesforce Tech Support believes this is caused by memory leak.  

## Expected Behavior
To be able to log emails in Salesforce using Outlook Integration without the add-in crashing.

## Current Behavior
See problem description

## Steps to Reproduce, or Live Example
Log emails using Salesforce Outlook Integration

## Your Environment
* Laptop, O365 Outlook Client 
* Office version number: Version 2105 (Build 14026.20246 Click-to-Run), 32Bit
* Operating System: Windows 10 Pro, Version 21H1 OS Build 19043.985, Windows Feature Experience Pack 120.2212.2020.0

**Comment by Dengshan2018** [comment]
@atvoegerl , thanks for reporting the issues. Could you add more details for the repro steps?

What does it mean "memory usage increases with every logged email"? How much memory increasing each time in outlook.exe?

**Comment by informaruth** [comment]
This is an issue that has not bee completely fixed with the new releases.

Please refer back to this issue: https://github.com/OfficeDev/office-js/issues/1069

Our users are having the same issue:
- Open Outlook desktop app and login
- Open an email, and open a pinnable add-in
- Open Task Manager
- Double click an email in the inbox, wait for it to open in a new window and wait for the pinnable add-in to load
- Close the new window
- Repeat Step 4 and 5 multiple times
- The memory usage of "Desktop App Web Viewer" keep growing at a significant rate until **it gets over 3 gigs and then it stops responding.**

Version 21H1.

**Comment by Dengshan2018** [comment]
@informaruth @atvoegerl there are a few fix related with memory leaks. they are available in beta channel.
