### ISSUE TITLE
set border error in Desktop Excel (Mac and Windows)

### ISSUE THREAD

**Issue by Alex0cean** [OfficeDev/office-js#1920]
In our Excel add-in we validate user input for business planning. 
Invalid input is highlighted in red border. As soon as the end user corrects the wrong input, the border is changed. 
Attached video shows that part of the border (the intersection) stays red although the color should change. 

The error only occurs in Excel desktop, not in Excel Online. 

The attached txt can be renamed to yaml and contains the script lab snippet to reproduce and analyze the issue. It is used in the video. 

https://user-images.githubusercontent.com/80747078/121704351-fc9d2780-cad3-11eb-8e01-d39ac0732333.mp4

[setBorderError.txt](https://github.com/OfficeDev/office-js/files/6639245/setBorderError.txt)

**Comment by jipinshi** [comment]
@Alex0cean, the issue can be reproable, have filed bug 5190397 internally to track the issue, will update here when there is progress.

**Comment by jipinshi** [comment]
@Alex0cean , one workaround to unblock you is to reset the color in D4 and D5 in different context.sync

**Comment by dingjin-ms** [comment]
@Alex0cean We have found the root cause, there is a bug in Windows and Mac when having neighbor borders. In this case, when setting the bottom of D4 and then the top of D5, it should keep only D5's top border, and when resetting D4, it should erase D5's top border and add D4's bottom border.

We are now fixing this problem.

You could take this [gist](https://gist.github.com/dingjin-ms/965a86ba25a1135beba264744eb3dce5) as a temporary workaround. By calling **eraseBorder**(which I added) before addBorder, it would clean the neighbor borders and no longer cause the problem.

Feel free to contact if you have any other problems, thank you!

**Comment by Alex0cean** [comment]
Thanks @dingjin-ms ,
glad you found the root cause.
The code proposal from you guys works as expected. In the sample snippet as well as in our add-in. We will use this additional logic on Mac and Windows Desktop Excel until the fix from you is available and (re)tested by us in all platforms.
 
Please keep us updated once the fix is rolling out.

**Comment by dingjin-ms** [comment]
Thanks for validate @Alex0cean , and we would keep you updated! :)

**Comment by dingjin-ms** [comment]
@Alex0cean We have checked in our fix, would sync with you when it is released! Thank you!

**Comment by dingjin-ms** [comment]
@Alex0cean Hi Alex, the fix has been rolled out to the latest build, thank you for your support!

**Comment by Alex0cean** [comment]
Thanks @dingjin-ms , we have validated the fix with the current channel Excel 2108. When can we expect the roll/out to the other channels, in particularly semi-annual enterprise? Just to know when we can build back the workaround ... 

Thanks a lot for your support

**Comment by dingjin-ms** [comment]
Thank you for your validation @Alex0cean , the fix has been rolled to semi-annual enterprise channel, and I believe it's available on all other channels. If it's not, please feel free to contact me to confirm it.

**Comment by Alex0cean** [comment]
Hi @dingjin-ms ,
thanks for letting us know. We have now (sorry for delay due to vacation season) tested the fix and it seems to work fine in the current channels. 
However, the error is still reproducible in:
Monthly Enterprise Channel (64 bit) 2107 (14228.20324)
Semi-Annual Enterprise Channel 2102 (13801.20960)

Is that expected or should the fix also be rolled out to those versions? 

Best,
Alex

**Comment by dingjin-ms** [comment]
Hi @Alex0cean ,
Sorry for the misleading information and thank you for your verification.

The fix is work after build '14309.10000'. It's currently work on Semi-Annual Enterprise Channel (Preview), and would be in Semi-Annual Enterprise channel on around Mar 8th 2022. As for Monthly Enterprise Channel, it would work on next update, around Oct 12th.

**Comment by Alex0cean** [comment]
successfully tested. Thanks.
