### ISSUE TITLE
OfficeJS - Email Exchange - Outlook

### ISSUE THREAD

**Issue by KekeBenites** [OfficeDev/office-js#1929]
I'm developing a plugin using officejs , focused on outlook.
But outlook only accepts email exchange, and I need to use gmail and other platforms but does not enable the supplements. Is there another way to create addins for the office?
VSTO and COM are not options because it needs to be supported on IOS and Linux.

**Comment by alison-mk** [comment]
Hi @KekeBenites, thank you for submitting! We use GitHub issues to report bugs with the product, and it looks like you are asking a more general programming question. For programming questions, we suggest you go to [Stack Overflow](https://stackoverflow.com/questions/tagged/office-js) and see if your question has already been asked or ask a new question. Stack Overflow has an active community of developers that regularly provide feedback and guidance. 

Since this isn't a bug, I will close this issue. Let me know if you have any questions!

Alison

**Comment by exextoc** [comment]
Currently officeJS add-ins are only supported by accounts that are backed by Exchange. 
We track Outlook add-in feature requests on our [Tech Community Page.](http://aka.ms/M365dev-suggestions) Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
