### ISSUE TITLE
Expose an API for Excel Range.Characters

### ISSUE THREAD

**Issue by teroman** [OfficeDev/office-js#1934]
We are looking to rewrite an existing addin using the javascript addin api and need to be able to format the characters in a range in the way that is currently possible through the COM api.

Specifiacally our use case requires setting the Font properties on a range of characters to use them as info graphics.

This is the COM api I am refering to: https://docs.microsoft.com/en-us/office/vba/api/excel.range.characters

This doesnt seem to be possible currently, so I'd like to request adding this to the javascript api offered.

**Comment by alison-mk** [comment]
Hi @teroman, thanks for submitting! We use GitHub issues to report bugs with the product, and it looks like you are requesting a feature. For feature requests, we recommend submitting via [Microsoft 365 Developer Platform Ideas](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). We use Microsoft 365 Developer Platform Ideas to prioritize community requests for additions to the product. If the community upvotes your request, it's more likely to be added to the add-ins platform.

Since this isn't a bug, I will close this issue. Let me know if you have any questions!

Thanks again, 
Alison
