### ISSUE TITLE
NamedItems.getItemOrNullObject doesn't return null

### ISSUE THREAD

**Issue by evantrimboli** [OfficeDev/office-js#195]
## Expected Behavior
When calling `getItemOrNullObject`, I would expect that it returns null if the name doesn't exist.

## Current Behavior
It returns a `NamedItem`. To check the `isNull` property, it needs to have `load` called.

## Steps to Reproduce, or Live Example
```
const namedItems = ctx.workbook.names;
namedItems.load('items');
await ctx.sync();

const item = names.getItemOrNullObject('this_name_doesnt_exist'); // doesn't return null
item.load('name');
console.log(item.isNull); // true
```

## Context
I want to validate some user data and need to match the some provided defined names against global names in the workbook. From the function description, it seems as though it should return `null` here.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1806
* Operating System: Windows 10
* Browser (if using Office Online): N/A

## Useful logs
N/A

**Comment by Rick-Kirkham** [comment]
This behavior is by design. The `names.getItem('this_name_doesnt_exist')` method would throw an error. The `names.getItemOrNullObject('this_name_doesnt_exist')` method is designed to give you an alternative that does not throw an error when the object doesn't exist.

**Comment by Zlatkovsky** [comment]
@evantrimboli , for a bit more context:  the pattern is known as the "Null Object pattern" (https://en.wikipedia.org/wiki/Null_object_pattern).  In terms of how it applies to Office in particular, see https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-advanced-concepts#42ornullobject-methods

For your code, I believe you're missing an "await context.sync()" before the `console.log(item.isNull)`.
I just double-checked it on my computer.  Without it, you should be getting
`PropertyNotLoaded: The property 'isNull' is not available. Before reading the property's value, call the load method on the containing object and call "context.sync()" on the associated request context.`

**Comment by evantrimboli** [comment]
Thanks for your replies.

Is there any "better" way to do this? By virtue of being able to iterate the collection it seems as though there is already the ability to know if a name exists or not. Both of the current options (as far as I can see) require a load, either:

```
const item = names.getItem('bad');
try {
  item.load('name');
  await ctx.sync();
} catch (ex) {
  // handle here
}
```

or:

```
const item = names.getItemOrNullObject('bad');
item.load('name');
await ctx.sync();
if (item.isNull) {
  // handle here
}
```

As it goes, I end up building a `Set` and using that to check:

```
const allNames = namedItems.items.reduce((set, item) => {
  set.add(item.name);
  return set;
}, new Set());
```

**Comment by Zlatkovsky** [comment]
@evantrimboli , I'm not 100% sure what you're asking -- but in any case, with it being a question, I'd recommend you post it in full on https://stackoverflow.com/questions/tagged/office-js, that way other community members can answer and/or learn from it, instead of being in a closed github issues...

In just a one-sentence description:  You will _always_ need a sync at some point, either when you do `getItem`/`getItemOrNullObject`, or when you're loading a collection.  However, if you do one, you don't need to do the other.  Also, there is a big difference between `namedItems.items[i]` (already-loaded and synced objects) vs `namedItems.getItem("id")` which fetches anew.  Hope this helps.  If it doesn't, Stackoverflow is the right forum to continue this question on :-)

**Comment by evantrimboli** [comment]
Maybe I didn't articulate myself very well. Consider:

```
const namedItems = ctx.workbook.names;
namedItems.load('items');
await ctx.sync();

const good = namedItems.getItemOrNullObject('exists');
const bad = namedItems.getItemOrNullObject('doesnt');

console.log(foo.isNullObject, bar.isNullObject);
```

This throws an exception because `isNullObject` isn't available. My contention is that it seems like the object should already "know" at that point whether it's a null object or not.

**Comment by Zlatkovsky** [comment]
I understand that.  But a `get`-prefixed method will always create a new object, whether or not the collection is already loaded (if it didn't create a new object, what would be the behavior if you just recently added a new sheet, after you'd already loaded? -- it would fail, rather than trying to retrieve anew).

So if you already did a `load("items")` (which BTW is equivalent to just `load("")` which in turn is equivalent to `load()` -- none of which are great, you'd be better off loading just the properties you need, such as `load("id, name")` -- you should just use plain JavaScript for checking whether an item by that name exists.  E.g., using the [Lodash find method](https://lodash.com/docs/4.17.5#find), `find(namedItems.items, { 'name': 'exists' })`

**Comment by AltitudeApps** [comment]
Just to comment on this, the name of the method is pretty confusing. 

**getItemOrNullObject** - led me to believe that I would just get back a plain old javascript null - fine, I can call the method, and if the item I request doesn't exist, it simply returns null, instead of blowing up or throwing an exception.  _Right...?_  I've seen this pattern many times.  

But, nope, that's not how it works.


**getItemOrObjectMarkedAsNull** - a name like this would make it obvious that something more involved that vanilla javascript nulls was involved.  I now understand the architecture a little better, and I see why you'd have to do a  
`.load("isNullObject"); await ctx.sync();`  
but it is utterly counterintuitive that you'd have to perform these actions on something that **isn't there...**.  

The mental model was operating under was as follows: 

> "ok, there's this proxy object, but there's no need to haul absolutely everything from the user's document over into this process, so let's have them `.load('whatever');` items they are actually going to use, and they can call `.sync()` when they are ready..."

So the mental conditioning is that you have to do the `load/sync` dance for data that is actually part of the user's document.  But, it turns out we _also_ have to do the `load/sync` dance for metadata regarding the status of a previous call to the API...

So maybe I should monkey patch this method so that it's called **getItemOrProxyObjectWhichMightBeMarkedAsNullButBeSureToLoadTheIsNullObjectPropertyOrYouWillNeverKnow**

I can appreciate the design; it's basically an implementation of the "nullable type" idea, and ensures that the function call always returns the expected type, even when there is no actual item coming back.  Which makes programming with types, well, just _better_.

But, since:
1. I did not know about this aspect of the API, as I'm just starting out,
2. I am currently coding in vanilla javascript,
3. the name of the method suggested something I was familiar with, but was actually far off the mark,
4. and the documentation for `getItemOrNullObject` did not provide any heads up at all,
I was left spinning in circles for about an hour. 

A web search for `getItemOrNullObject does not return null` brought me here.

I mentioned this comment in this issue in the documentation repo:
https://github.com/OfficeDev/office-js-docs-reference/issues/771#issue-685736615

**Comment by AltitudeApps** [comment]
Ok, I have a much clearer picture now.


@evantrimboli wrote:

> Maybe I didn't articulate myself very well. Consider:
> 
> ```
> const namedItems = ctx.workbook.names;
> namedItems.load('items');
> await ctx.sync();
> 
> const good = namedItems.getItemOrNullObject('exists');
> const bad = namedItems.getItemOrNullObject('doesnt');
> 
> console.log(foo.isNullObject, bar.isNullObject);
> ```
> 
> This throws an exception because `isNullObject` isn't available. My contention is that it seems like the object should already "know" at that point whether it's a null object or not.

The only thing that needed clarified was that another invocation of `await ctx.sync()` also needs to happen after the calls to `.getItemOrNullObject`:

```
const namedItems = ctx.workbook.names;
namedItems.load('items');

await ctx.sync();

const good = namedItems.getItemOrNullObject('exists');
const bad = namedItems.getItemOrNullObject('doesnt');

await ctx.sync();    // .getItemOrNullObject() is a fetch operation,
                     // much like .load().
                     // but, just like .load(), you have to .sync()
                     // before accessing any field, otherwise
                     // the backing data will not yet be present

console.log(foo.isNullObject, bar.isNullObject);
```

I suggested improvements to the reference documentation here: https://github.com/OfficeDev/office-js-docs-reference/issues/771#issuecomment-680297856
