### ISSUE TITLE
getDirectPrecedent() should return separate range areas when it's not the same direct precedent position in formulas.

### ISSUE THREAD

**Issue by thanakrid-kunghair-rft** [OfficeDev/office-js#1961]
I've found that using getDirectPrecedent() return different range areas for the same cell referencing format, for example `=CONTOSO.STREAMING2(A1,A2)` and `=CONTOSO.STREAMING2(F1,F3)`, the former returns an array that looks like I reference to A1:A2 instead of separate range.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: MacOs
* Browser (if using Office on the web): Chrome
 
## Expected behavior
`=CONTOSO.STREAMING2(A1,A2)` should return the same numbers of range areas as  `=CONTOSO.STREAMING2(F1,F3)`

## Current behavior
`=CONTOSO.STREAMING2(A1,A2)` returns
![image](https://user-images.githubusercontent.com/73512008/123594685-3717fb80-d81a-11eb-8eeb-6fd93d63a1c6.png)
`=CONTOSO.STREAMING2(F1,F3)` returns
![image](https://user-images.githubusercontent.com/73512008/123594764-4f881600-d81a-11eb-81dd-a7c92408693a.png)

## Steps to reproduce
1. Clone the repo and go to main branch.
2. build and run the test-project.
3. open the provided workbook.
4. upload manifest from the the test-project.
4. open dev tool.
5. open the task pane.
6. click formula's parent cell in the workbook.
7. see log message in console.

## Link to live example(s)
https://github.com/thanakrid-kunghair-rft/test-add-in
# Provide additional details
I haven't test on other platforms yet, but I think this issue might happen on other platforms as well.
I think the results for both formulas were the same back in May.

## Context
I need to use getDirectPrecedent to get direct precedents' values to process data in my project workflow.

## Useful logs

![cell-ref-issue](https://user-images.githubusercontent.com/73512008/123595646-595e4900-d81b-11eb-96a9-0907ec317b0d.gif)

[Book 78.xlsx](https://github.com/OfficeDev/office-js/files/6724165/Book.78.xlsx)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by jipinshi** [comment]
@thanakrid-kunghair-rft , thanks for reaching us. Can you help repro it with scriptlab and share your gist to make it easy to repro? In ScriptLab also can define the function.

**Comment by thanakrid-kunghair-rft** [comment]
Hi @jipinshi.
 Github repo is attached to the issue.

**Comment by lumine2008** [comment]
@thanakrid-kunghair-rft  Could you please share the scenario? We would like to learn more about the reason you would like to unmerged cell. And see if there are some workaround for you. 

Merge the result ranges is our designed behavior. The reason is that there might be a lot of precedents cells in the workbook. When this API is called, we will need to create ranges for each individual precedent cell. But if we create too many range objects, the excel perf would be impacted. So due to perf consideration, we decide to avoid creating too many ranges by merging the result ranges (which also align with VBA behavior.)

So would you please share your scenario and see how we can unblock the scenario. Thanks.

**Comment by thanakrid-kunghair-rft** [comment]
@lumine2008  I've sent you the detail.
