### ISSUE TITLE
[Web Outlook] Task Pane addin does not support Clipboard API

### ISSUE THREAD

**Issue by Aidam1** [OfficeDev/office-js#1991]
# Provide required information needed to triage your issue
I would like to use Clipboard API to copy text on button click in web Outlook taskpane addin. However, it is currently blocked because the containing iframe doesn't have necessary permissions.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows 10
* Browser (if using Office on the web): Google Chrome Version 91.0.4472.124
 
## Expected behavior
The Clipboard API is allowed and I'm able to use it.

## Current behavior
 The addin is in an iframe without necessary permissions, it is currently impossible to copy text through Clipboard API. After I try to use it, the console writes:
 `Uncaught (in promise) DOMException: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.`

The solution would be to add more permissions to the iframe by passing `clipboard-write` permission to iframe. More info for example here: https://web.dev/async-clipboard/#permissions-policy-integration

## Steps to reproduce
1. In any react component, write onClick prop: `onClick={() => {navigator.clipboard.writeText(this.state.textToCopy)}}`
2. Go to pane and try to click on the component

**Comment by exextoc** [comment]
Thanks for reaching out and mentioning about this problem. We are looking into this for "Outlook Web" (OWA).

Does your code for clipboard in add-in code work in "Outlook Desktop" (Windows) and "Outlook Mac" (MacOS)?

**Comment by Aidam1** [comment]
I currently don't have an option to test it on MacOS, but it is working in "Outlook Desktop" (Windows).

**Comment by exextoc** [comment]
Apologies for late follow-up on this. 

Thanks @Aidam1 for reporting this issue. Currently the feature: Clipboard API access from iframe,  you requested, is not a part of the product. We track Outlook add-in feature requests on our Tech Community Page (https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

Meanwhile, please check if you want to use deprecated API document.execCommand("copy") or npm package 'clipboard' for your use-case.

**Comment by Aidam1** [comment]
Thank you for the suggestion. I have created the idea on Tech Community Page: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/outlook-addin-enable-clipboard-api/idi-p/2626853

**Comment by pietrofxq** [comment]
I also need to use this feature and stumbled upon this. The fix is simply adding a new value to the `allow` iframe attribute but has to be done on Microsoft side. Can we reopen this?

**Comment by DxDen1004** [comment]
Same here, we were trying to develop a simple internal add-in to archive email messages links but hey, no way to use the clipboard APIs, nor many other APIs to be precise. At this very moment web Add-in development is very very limited.

**Comment by pietrofxq** [comment]
@DxDen1004 we ended using the old school solution.

```
const copyLink = (link: string) => {
    const input = document.createElement('input')
    input.type = 'text'
    input.value = link
    document.body.appendChild(input)
    input.select()
    document.execCommand('copy')
    input.remove()
  }
```

**Comment by DxDen1004** [comment]
@pietrofxq unfortunately, for our outlook Web add-in the document.execCommand('copy') is not available. We tried that without being able to get it to work. I also tried using jQuery to reference the iframe from within itself and change the allow prop, but that also does not seem to work.

**Comment by BuWH** [comment]
Same with Excel here. Seems like all office addin environments don't support Clipboard API.

**Comment by ntinkler-calendly** [comment]
Can we get some clarity around the decision to close this?  This seems like a pretty sane ask.

Currently I can already write into the clipboard across all instances of the product using a combination of document.execCommand('copy') in chrome/firefox/edge, and navigator.clipboard.write() in safari.

It would be nice to be able to consolidate document.execCommand calls to the much nicer navigator.clipboard.write() interface, but I can't do it because MS does not set `allow="clipboard-write"` on the frame the addin is hosted in.

I don't mind if clipboard read is blocked (or ideally allowed behind a permission item in the manifest for the addin) I understand there is some privacy and security concerns allowing reading from the clipboard - but having to bootleg different approaches to writing into the clipboard across different clients because you guys won't set a flag is... silly.

**Comment by DxDen1004** [comment]
After reporting some more bugs related to the Navigator interface, it appears clear to me that this functionality it's a complete mess right now, it works in places where it should not and it doesn't work at all in other places where it would make truly sense to have it.

I reported a different issue but very similar to this one, and that one was actually acknowledged as a bug by Office developers, but I never received a response after that. 

At the present time, we are forced to use a horrible workaround/hack to copy content to the user clipboard while using a sandboxed add-in, which breaks Outlook Web's security, but since there are no other ways we have to stick with it.

I suggest you do find another way to achieve what you are trying to do and don't expect Microsoft to help you out anytime soon.

**Comment by ptosco** [comment]
As of 18th September 2023, Office Add-Ins still do not have read/write clipboard access due to this missing flag on the `iframe`:
```
The Clipboard API has been blocked because of a permissions policy applied to the current document.
```
This is true for web versions of PowerPoint, Excel, Outlook. Given that clipboard access works perfectly when the Add-In is loaded in the Desktop applications, could you please unblock clipboard access also in the web versions (eventually based on a setting in `manifest.xml`)?
This is a curently a major blocker.

**Comment by JavascriptMick** [comment]
> @DxDen1004 we ended using the old school solution.
> 
> ```
> const copyLink = (link: string) => {
>     const input = document.createElement('input')
>     input.type = 'text'
>     input.value = link
>     document.body.appendChild(input)
>     input.select()
>     document.execCommand('copy')
>     input.remove()
>   }
> ```

this method works but it drops out whitespace like carriage returns.  I used a textarea instead and wrapped in a promise so it mimics the behaviour of the blocked api...
```
export function navigator_clipboard_writeText(text: string): Promise<void> {
  return new Promise(function (resolve, reject) {
    try {
      const textArea = document.createElement('textarea');
      textArea.value = text;
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      textArea.remove();
      resolve();
    } catch (e) {
      reject(e);
    }
  });
}
```

**Comment by MasterZydra** [comment]
Has anyone found a solution?

**Comment by kenizhou** [comment]
any solution please
