### ISSUE TITLE
Can not run 'Enable and Disable Add-in Commands' when using setStartupBehavior(Office.StartupBehavior.load)

### ISSUE THREAD

**Issue by sitthinan** [OfficeDev/office-js#1997]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows 10
* Browser (if using Office on the web): Google Chrome
 
## Expected behavior

The button on my ribbon should be enabled or disabled following the logic after I reopen or refresh my workbook such as the sign-in button should disable when the user login.

## Current behavior

After I refresh my workbook, The button on my ribbon always shows as the default status

## Steps to reproduce

1. Open a new workbook.
2. Loading the add-in.
3. Click the button on the ribbon.
4. The 'Office.addin.setStartupBehavior(Office.StartupBehavior.load);' was run
5. the 'Office.ribbon.requestUpdate(ribbonUpdater)' was run for changing status from enable to disable and it working well.
6. Reopen or refresh the workbook.
7. After my add-in was run, it shows the error when running the Office.ribbon.requestUpdate(ribbonUpdater).

## Context

We want to run code in my add-in when the workbook was reopened or refresh to change the status of the ribbon between enabled and disabled,

## Useful logs

- [/] Screenshots
![image](https://user-images.githubusercontent.com/56704884/126473173-d63200d0-6998-4097-b97e-a23f85d605d7.png)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by sitthinan** [comment]
Hi, has any updates for this ticket?

**Comment by jerousseau** [comment]
I've nearly the same problem creating a contextual tab, and using Office.StartupBehavior.load.
When the add-in is loading at workbook open the contextual tab never appear (but without error in my case).

**Comment by ElizabethSamuel-MSFT** [comment]
@sitthinan @jerousseau Apologies for the late response. Are you still facing this issue?

@preethikakiru Can you take a look?

Thanks.

**Comment by wh1t3cAt1k** [comment]
> I've nearly the same problem creating a contextual tab, and using Office.StartupBehavior.load. When the add-in is loading at workbook open the contextual tab never appear (but without error in my case).

This is exactly what I am experiencing in Excel Online only. I can't believe such issues go for months and years without an update or a response from the team. :(

![image](https://user-images.githubusercontent.com/5159662/208694284-35490313-7eee-4216-bb89-65c444ce5966.png)

I am now working to prepare a minimal repro.

cc @gmichaud

**Comment by wh1t3cAt1k** [comment]
@Wenjun-Gong @ElizabethSamuel-MSFT could I ask you to please reopen this and take a look if possible?..

It's a blocker for our planned interface revamp because 

- our add-in needs to run some code on start-up 
- **and** at the same time it will heavily rely on the contextual ribbon for some of the user interactions.

**Comment by wh1t3cAt1k** [comment]
@Wenjun-Gong @ElizabethSamuel-MSFT 

I decided to file a new ticket with clean steps and reproduction code: https://github.com/OfficeDev/office-js/issues/3052

@sitthinan @jerousseau If this is still relevant to you I invite you to comment.

It's a blocker for our planned interface revamp because 

- our add-in needs to run some code on start-up 
- **and** at the same time it will heavily rely on the contextual ribbon for some of the user interactions.
