### ISSUE TITLE
Possible values for custom function parameter

### ISSUE THREAD

**Issue by savanetllc** [OfficeDev/office-js#1998]
Hi All,
We have Excel Add-in using Office-js API which contains couple of Custom Functions. Each CF has filter parameter which accept couple of pre-defined options. So when user start typing CF in cell then how can I show those possible options (for selection) to user like we have it for VLOOKUP (which shows possible value for range_lookup parameter).
![image](https://user-images.githubusercontent.com/82084016/126521329-fc2da2b4-15ec-4c08-80fa-ecbf98d709ee.png)

So we need to show dozen of different options for our filter parameter of each CF. 
Please guide. Thanks in advance

**Comment by grangeryy** [comment]
Hello @savanetllc, this is currently not supported in custom funtions yet. I've created an item in our backlog to track:5292503. THX!

**Comment by wh1t3cAt1k** [comment]
@grangeryy one important consideration that I'd like to point out and request support for: 

Sometimes the list of possible values will depend on the values already supplied for other arguments.

An adapted example from our add-in (real business case): our users set up connections to different hosts, which expose multiple endpoints (each their own).

Imagine there is a function like `=GETCUSTOMDATASET(ConnectionName, EndpointName)`, which returns the dataset as a dynamic array from the given host and endpoint.

The problem here is that the list of suggested values for `EndpointName` depends on the `ConnectionName`.

So, our user story is as follows: 

- We would like to get a possibility to provide a simple IntelliSense values list (basic cases) - but not just through custom functions metadata, **at runtime as well!** 
- For more complex, dynamic and context-dependent cases, at runtime, we would like to be able to provide a **value-list-getting-function**:
- It will receive the currently specified values for all arguments (`undefined` for arguments that were not specified yet) and the name of the current argument, so that it can determine and return the suggested value list.

On a side note, it would be **very nice to have** it functioning like IntelliSense in visual studio, where, as the user types in the tentative value, the dropdown list of suggested values is filtered and sorted by the best match.

I will be happy to work more closely and privately with you to demonstrate how this now works in our existing COM-based add-in and argue our business case further.

Thanks!!!

**Comment by wh1t3cAt1k** [comment]
To further illustrate our use case. In our existing COM add-in, we use System.Windows.Forms to draw an  "intellisense-like" tooltip with argument description, best match, and suggested values.

Example from our add-in, Velixo:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/5159662/126970029-b71dc9e8-b27f-404f-a76f-d7c695c7abdd.png">

The possible values for `Connection` are determined at runtime, because inside each file, the user can edit the list of his connections to various hosts. 

Hence the user story that specifying possible values in metadata is **not enough** - we don't know them at build time yet, it is dynamic.

Then, as soon as the connection is specified, the list of possible values for possible account codes is dependent on that connection name (each connection can have its own list of accounts):

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/5159662/126970387-81ff635f-44d2-424c-b40b-52cad0bba220.png">

_Behind the scenes, when we detect that `Account` argument is being edited, we actually go to the host defined by `Connection` and retrieve the list of accounts._

Hence the requirement for a JS function that can **asynchronously** (it can take a couple of seconds, during which we display a message "retrieving possible argument values...") get the list of possible values given the context of all specified arguments.

As you can see, it's a text only approximation, but if it was proper IntelliSense provided to us by the framework it would be 100x better.

**Comment by grangeryy** [comment]
We are tracking new feature request this using [feature request and ideas](https://aka.ms/m365dev-suggestions) and this one is quite similar as the [item](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/excel-custom-functions-possibility-to-provide-list-of-predefined/idi-p/3066769).
