### ISSUE TITLE
In OWA Office.context.mailbox.item.body.getAsync with Text Coercion type not returning line breaks (CR LF)

### ISSUE THREAD

**Issue by kumaro** [OfficeDev/office-js#1999]
Our add-in stopped working in OWA as body.getAsync is not returning line breaks  but it is working fine in Outlook Desktop

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:OWA
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Browser (if using Office on the web): Chrome, Edge
 
## Expected behavior

Return line breaks as expected

**Comment by kumaro** [comment]
Any update on this issue?

**Comment by exextoc** [comment]
> Any update on this issue?

Apologies for the late response. This is already in our backlog, but unfortunately we do not have any timelines to share for the same. As a workaround, we suggest to use the CoercionType.Html to get the line breaks.

**Comment by teejay001** [comment]
Hi @exextoc,

This issue is still affecting a vast number of users. Quite often a "work around" is suggested and the main issue is never revisited. The Office JS offering is meant to be a major tech which is to be the future of Add-In development so it beat me that little issues like this cannot be resolved ASAP.

The suggested approach bring in it's own set of challenges as stated here .. https://learn.microsoft.com/en-us/javascript/api/outlook/office.body?view=outlook-js-preview#outlook-office-body-getasync-member(2)

Please, could you help see if and when this issue could be resolved. The "work around" in the code base is getting very uncomfortable and quite frankly loosing confidence in this offering.

**Comment by exextoc** [comment]
This issue mentioned in the post has already been fixed. @teejay001  Are you still facing this issue? If so, Could you please provide more details on the same?

**Comment by nightelf973** [comment]
Hi @exextoc I am still having the issue mentioned above when calling the getAsync method in Outlook on the web. No line breaks are returned. You mentioned that the issue has been fixed, do I need to add any additional arguments to my function call for this to work?

**Comment by nightelf973** [comment]
Hi @exextoc @AbidRahman-MSFT could I please get some assistance with the above question
