### ISSUE TITLE
makeEWSRequestAsync fails on Outlook Desktop with Shared Calender Items when not organizer

### ISSUE THREAD

**Issue by jlevenssfdc** [OfficeDev/office-js#2009]
When using this function with a GetItem request in a Shared Calender item where you are not the organizer on a Desktop client it's returns the following

{code: 9020, message: 'API not supported for shared folders', name: 'GenericResponseError' }

When using this same function in OWA for the same event, it succeeds as expected.

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows
* Browser (if using Office on the web): Chrome

You can install this add-in and run the test on a Shared/Delegate Calendar where you are not the Organizer

https://limitless-ridge-81689.herokuapp.com/manifest.xml

@exextoc I think you have old credentials of mine from a previous issue in an email, they should still work, if you want to save some time in the setup

**Comment by Byron-Mo** [comment]
Impacted users have reported the issue after an Office update in early June. Here are some versions that are impacted:
- Outlook Desktop: (16.0.14315.20002) 64-bit
- Outlook Desktop: (16.0.13929.20406) 64-bit
- [Version 2106 (Build 14131.20320)](https://docs.microsoft.com/en-us/officeupdates/current-channel#version-2106-july-13)

**Comment by exextoc** [comment]
Since the add-in is running in a Shared Calendar scenario, I believe this error is correctly returned by the Outlook API. Per the [shared folders and shared mailbox](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?tabs=windows#rest-and-ews) documentation, add-ins can make REST requests but EWS request are not supported in delegate scenarios.

OWA may not return the same error when calling `makeEwsRequestAsync`, but the request may fail in some cases.

Are you able to use REST for your scenario instead?

**Comment by jlevenssfdc** [comment]
We'll move to use rest but it's deprecated and decommissioned in 2022 so we're talking with Juan to find a longer term solution.
