### ISSUE TITLE
Dollar sign changed to Yen symbol when inserting to Excel

### ISSUE THREAD

**Issue by timbeese** [OfficeDev/office-js#2027]
# Provide required information needed to triage your issue
I am inserting a table of data into the Excel worksheet using office-js.  When my data contains a leading $, the value that gets shown in the worksheet is changed to a ￥.  This happens when my OS regional settings are set to Chinese (Simplified, China) and I'm running desktop Excel.  It also occurs when I am using the Excel web client, and I change my File -> Options -> Regional Format Settings to be Chinese (China).

I don't believe that Excel should ever change the $ to a ￥ symbol, since that changes the meaning of the data.  If I simply paste $54.54 into Excel, the symbol is not changed.

I have recreated the issue with ScriptLab, the code will be pasted below.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: This only happens on desktop Excel.
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Excel  (16.0.14228.20200) 32-bit 
* Operating System: English Windows 10 (21H1 (OS Build 19043.1151)

 
## Expected behavior
I expect my data (in dollars) to be interpreted correctly by Excel, not changed to a different currency.

## Current behavior
My data $146.98 is changed from using the dollar sign to using the Yen symbol.

## Steps to reproduce
I have recreated the issue on ScriptLab, though make sure that your environment is an English environment with regional settings set to Chinese.  Here is the code:

```
function run() {
  return Excel.run(function (context) {
    var range = context.workbook.getSelectedRange();

    // Make sure to have 1 cell selected
    range.values = [['$146.98']];
    return context.sync();
  });
}

```

## Context
We are inserting a table from a report that we generated on the web.  The data could be from any nationality and the currency symbol that we set is specific to the data.  We have options for the user on how to insert the data so that they can control whether we insert raw values and set the cell formats ourselves, or whether we insert the web-formatted data as a string.  If that's the case, they can choose whether to let Excel interpret the value type (where this problem occurs), or where we insert everything as Text to make sure that it appears exactly as the web report (this problem does not occur).  Changing the currency value is changing the meaning of the data, and should not happen in any of these scenarios.

**Comment by gingerjia** [comment]
@timbeese thanks very for reporting the issue. After investigation, we found it's by design since the current Region settings is Chinese. 
For why simply paste $54.54 into Excel, the symbol is not changed? It's due to "$54.54" was considered as a string. 
For the above two cases, the data stored in the file are different:
![image](https://user-images.githubusercontent.com/62282034/128801459-4f99730f-b78a-41aa-a67f-f93a76b9911e.png)
And the paste string is stored in another file xl\sharedStrings.xml:
![image](https://user-images.githubusercontent.com/62282034/128801551-ae255190-b4d8-4589-b72a-bf889dc54160.png)

If you didn't want the value being impacted by region settings, maybe you can call Range.formulasLocal, which will keep as the value as "$54.54".

If you have any other questions, please feel free to let us know! Thanks again.

**Comment by timbeese** [comment]
I see what you're saying with the values.  I could always just set the numberFormat to text on the cell if I want to force the values to be placed as a string.  But, when possible, we like for Excel to interpret the type so that our user can use the value in formulas, which they can't do if the value is a string.

I still think that it is wrong for the officejs interface to take a value with one currency symbol and change it to a different symbol.  It is essentially invalidating the value of the data.  1000 yen is not the same as 1000 dollars.  If we set a cell value using the API, shouldn't it behave the same as if the user entered the value themselves?

I do see this same behavior when using a VSTO add-in as well as VBA to insert a dollar-sign value into a worksheet when my regional settings are Chinese.  They are always getting changed to the yen-symbol.

**Comment by gingerjia** [comment]
Thanks @timbeese. If I understand correct you aren't block by the issue now.
I will sync your suggestion with our PM as this impact the behavior design of VBA and Excel API. Thanks again!

**Comment by lumine2008** [comment]
Thanks Timbeese, we have discussed with this issue internal.  This is by design behavior. $ here means number format of this range is currency. so it will follow with the system locale. 
The recommendation is to use numberFormatLocal to set the right current symbol. ensure the $ symbol, you could use the following code in order to make it work.

```

async function run() {
  return Excel.run(function (context) {
    var range = context.workbook.getSelectedRange();

    // Make sure to have 1 cell selected
    range.numberFormatLocal = '$0,0.00';
    range.values = [['146.98']];

    return context.sync();
  });
}
```
