### ISSUE TITLE
setSignatureAsync is broken in OWA when email is plain text

### ISSUE THREAD

**Issue by barclayadam** [OfficeDev/office-js#2038]
When using `Office.context.mailbox.item.body.setSignatureAsync` to set a signature for a 'plain' email, the signature is not set but instead prepended to the email body when in plain text mode.

## Your Environment

* Platform: Office on the web (I have not tested with desktop Outlook at this time)
* Host: Outlook
* Browser: Chrome
 
## Expected behavior

Like with HTML signatures and the built-in functionality the existing signature should be *replaced*

## Current behavior

The body of the `setSignatureAsync` is prepended to the email body, resulting in multiple signatures.

## Steps to reproduce
1. Change to plain text editing mode
2. From an add-in call `Office.context.mailbox.item.body.setSignatureAsync('The signature', { coercionType: 'plain')`

**Comment by exextoc** [comment]
Thanks for reporting this issue. However this is a known limitation from our side and the current behavior mimics what the Outlook natively allows us to do. We will keep the enhancement request in our backlog.

**Comment by barclayadam** [comment]
@exextoc This is disappointing to be treated as an enhancement request only and not a bug with higher priority, given that (at least) Outlook on Windows handles this correctly. 

If we cannot have the same functionality with an add-in across platforms, it goes against the whole point of having cross-platform add-ins. We have to test and caveat our products with "feature x does not work in platforms x,y,z at versions 1,2,3" when, in my mind, the whole point of these add-ins is to provide the same functionality everywhere Outlook runs

**Comment by exextoc** [comment]
Hey @barclayadam ,

We understand your frustration, however, since plain text editing is not a very commonly used scenario and to support signature API in this scenario would be difficult for us, we can only keep this as an enhancement request. Can we understand your scenario and usage better as to why specifically you need setSignatureAPI to work in plaintext editing mode?

**Comment by exextoc** [comment]
Hey @barclayadam ,

We are closing this issue. For further help you can reach out on the Help and Feedback on the Outlook app: https://support.microsoft.com/en-us/office/how-do-i-give-feedback-on-microsoft-office-2b102d44-b43f-4dd2-9ff4-23cf144cfb11#platform=Office_for_the_web

**Comment by kinkoazc** [comment]
> Hey @barclayadam ,
> 
> We understand your frustration, however, since plain text editing is not a very commonly used scenario and to support signature API in this scenario would be difficult for us, we can only keep this as an enhancement request. Can we understand your scenario and usage better as to why specifically you need setSignatureAPI to work in plaintext editing mode?

The scenario is, in my case, also changing the plain text signature for plain text message.
@exextoc You could probably make it somewhat usable by keeping track of the latest applied set signature.

**Comment by bogdanst24** [comment]
Hi @exextoc, still no desire to change this? When using event-based add-ins to insert signatures, based on a new message composed and changing it based on the recipient change, this leads to multiple signatures inserted all the time. 

I get that this was a limitation of Outlook, but once extra features enabling the setSignature on multiple events were introduced, I would say this became a bug... Otherwise, is there any documentation stating this as an official limitation?
