### ISSUE TITLE
ContentControls inside a table can not be loaded [Word Online]

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#2040]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.14404.41000
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Word Online:
 - content controls inside a table should be loaded.

## Current behavior
Word Online:
 - content controls inside a table are not listed out
 
Word App:
 - works fine .

## Steps to reproduce

1. prepare a template has content controls inside and outside a table (see attachment)
[ccWithTable.docx](https://github.com/OfficeDev/office-js/files/6967056/ccWithTable.docx)

2. open that file in Word App and Word Online
3. load content control items (context.document.contentControls.load("items"))
4. observe on the web content controls inside a table are not listed.

## Link to live example(s)

https://gist.github.com/jasonhieu1905/fd58a1b0e2357cd03efbee4ee970fc9b

![eJ0OFKXSXZ](https://user-images.githubusercontent.com/13063615/128999684-7dd6d20d-91cc-42c2-acd8-44f07831819c.gif)

**Comment by qinliuMSFT** [comment]
Hi, this issue is reproducible from my side, it has been put on our backlog VSO#5338259, will let you know once we have any updates.

**Comment by AbidRahman-MSFT** [comment]
Hey @jasonhieu1905 - can you confirm that this is not a regression from a recent change? 

Unfortunately, supporting content controls inside of a table was never supported on Web and we would need to tackle this as a new feature. The current workaround is to insert some text into the same table cell - so the table cell will have the content control as well as additional text. This allows the API to detect the content control. 

Can you clarify the use case for having the content controls inside of the table? It would be great to understand what user flow you are trying to achieve so we can prioritize adding this capability to the Web version of Word.

Thanks a lot for the feedback!

**Comment by MartinSSeifert** [comment]
@AbidRahman-MSFT, I think we can not say if this has ever worked or not - I guess not!

Due to the many parity issues with the Web version for Word, not many customers have taken the time to check if their templates/documents actually work with Word for the Web.

The use case with one Content Control in a cell is a super common one for almost **every existing customer and future customer**. The workaround will not work for our use cases as the cell MUST only contain one content control and no other text.

Yes, please add this gap to your roadmap for Word for the Web. That would be another step for our customers to be able to start using Word for the Web. As usual, the sooner this gets fixed, the better :-)

**Comment by mayagit** [comment]
Happy to let everyone know that support for content controls within tables in Word Online has been rolled out to production. Please take a look if your scenario(s) are working as expected and report back if any additional issues...

**Comment by MartinSSeifert** [comment]
@mayagit love it 👍
