### ISSUE TITLE
Get Selection from mail in Outlook ReadMode

### ISSUE THREAD

**Issue by attilarickert** [OfficeDev/office-js#206]
I would like to get the selected text from the opened email in the Outlook ReadMode add in, but i can't do it with document.getSelection(), because the add in runs inside an iframe. I also can't get the main document because of cross origin problems.
I found the Office.context.mailbox.item.getSelectedDataAsync() function, what would be ideal for me, but it's only available in Compose mode. 
Is there any way to achieve this functionality in ReadMode ?

**Comment by exextoc** [comment]
Unfortunately we do not currently support getSelectedDataAsync function in read mode. The only supported mode is compose. Could you describe your scenario for requiring the method on read?

**Comment by exextoc** [comment]
Also, we track Outlook add-in feature requests on our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). Please add your request there. Feature requests on user-voice are considered when we go through our planning process.

**Comment by vtiti** [comment]
In our add-in, we would like to extract the email sender's information from her signature. It is not optimal to process the whole email text, because of many replies can contain signatures.
So the desired workflow would be, the add-in user selects the signature, and click on the addin button, which extracts the useful information from the selected text, then send it into the database.
Do you have any workaround for this?

**Comment by exextoc** [comment]
A potential work around is to implement an add-in command with the `ExecuteFunction` action and look for the Contact entities in the message. Another alternative is to implement a contextual add-in that leverages the `DetectedEntity` extension point where you can highlight Contact entities in the message.
