### ISSUE TITLE
EquivalentAddIns tag support for Outlook Web Add-ins

### ISSUE THREAD

**Issue by PlayPratz** [OfficeDev/office-js#2061]
## Article URL

https://docs.microsoft.com/en-us/office/dev/add-ins/develop/make-office-add-in-compatible-with-existing-com-add-in#specify-an-equivalent-com-add-in

## Issue

 The document mentions:
> Specify an equivalent COM add-in
> Applies to Excel, Outlook, PowerPoint, and Word.
<img width="910" alt="image" src="https://user-images.githubusercontent.com/37703928/129904824-0570558b-4252-4ee0-8e49-ce99a8b18f55.png">

However, uploading a manifest with the <EquivalentAddins> tag fails its validation. I have tried this on multiple tenants but yielded the same result. However, the manifest is accepted if a user uploads it for themselves, and the tag works as expected (i.e. the COM add-in is blocked)

**Comment by exextoc** [comment]
To clarify where/how are you uploading the Manifest and it's failing? (Are you trying to deploy via Centralized Deployment for all users in an org?)

If this is an on-prem server, make sure that you have the latest updates: 

Exchange 2019 Cumulative Update 10 or later (KB5003612)
Exchange 2016 Cumulative Update 21 or later (KB5003611)

**Update**: This is not applicable to your situation since you can sideload the manifest directly for the user. (leaving the comment here since this would be applicable to people on older exchange versions)

**Comment by exextoc** [comment]
Update there is a likely issue regarding this with Unified Deployment. I believe you are already in contact with MS support on this?

In any case, I will update this thread as soon as we find out more/can deploy a fix.

**Comment by exextoc** [comment]
This should be fixed now. Please let us know if you are still experiencing issues.
