### ISSUE TITLE
Outlook can't access Mail Signature

### ISSUE THREAD

**Issue by questionhead** [OfficeDev/office-js#2138]
When I create new message in Outlook, my Email signature should automatically appear in Email.
All I get is this error message:
![grafik](https://user-images.githubusercontent.com/80743016/134381419-06ef84bc-b22e-418c-925c-a731fe0a0c21.png)

Kind regards

**Comment by AlexJerabek** [comment]
Hi @questionhead,
I'm sorry to hear you're encountering issues with the platform. I'll tag @exextoc to investigate.

In the meantime, could you please provide some more context for your issue?
- What platform are you on (Desktop, Mac, Online)?
- What build are you on (go to **File** > **Office Account** to see this)?
- How is your add-in currently [deployed](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish)?
- Was the add-in working and now doesn't?

Thank you!

**Comment by questionhead** [comment]
What platform are you on (Desktop, Mac, Online)? --> W10 21H1
    What build are you on (go to File > Office Account to see this)? --> Microsoft® Outlook® for Microsoft 365 MSO (16.0.14326.20384) 32-bit 
    How is your add-in currently deployed? WebView2
    Was the add-in working and now doesn't? It never worked on my computer. It works on a different computer.

**Comment by exextoc** [comment]
Bug 2366604<https://o365exchange.visualstudio.com/959adb23-f323-4d52-8203-ff34e5cbeefa/_workitems/edit/2366604>: [OfficeDev/office-js] Outlook can't access Mail Signature (#2138)


Created using VSTS Outlook add-in<https://www.owiki.ms/wiki/VSTS_Add-In_for_Outlook>


From: questionhead ***@***.***>
Date: Thursday, 23 September 2021 at 2:07 PM
To: OfficeDev/office-js ***@***.***>
Cc: Outlook Extensibility Oncall ***@***.***>, Assign ***@***.***>
Subject: Re: [OfficeDev/office-js] Outlook can't access Mail Signature (#2138)

What platform are you on (Desktop, Mac, Online)? --> W10 21H1



What build are you on (go to File > Office Account to see this)? --> Microsoft® Outlook® for Microsoft 365 MSO (16.0.14326.20384) 32-bit



How is your add-in currently deployed? WebView2



Was the add-in working and now doesn't? It never worked on my computer. It works on a different computer.



—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Foffice-js%2Fissues%2F2138%23issuecomment-925609895&data=04%7C01%7CSachin.Mishra%40microsoft.com%7C84b7af6a6a2749a6446508d97e6d64c0%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637679830623839452%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WOg0zsrN9O8QgF40In8%2B6H6e3P13fpO56ISE6jCjgSI%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGZ2GIJDOVOGPNREMOUKJQDUDLRM7ANCNFSM5ERWEF4A&data=04%7C01%7CSachin.Mishra%40microsoft.com%7C84b7af6a6a2749a6446508d97e6d64c0%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637679830623839452%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=al4ogxVsL%2FQZekCekN%2F6bUWxoY5uW4f7k2c2drD1DHY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CSachin.Mishra%40microsoft.com%7C84b7af6a6a2749a6446508d97e6d64c0%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637679830623849444%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Swhzh6rGSudCtAL8jTQ9A3O8xePTTfGRQLJMc3TCbF4%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CSachin.Mishra%40microsoft.com%7C84b7af6a6a2749a6446508d97e6d64c0%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637679830623849444%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4dFAwUxIkh7FEV6Tw5ZRVNuyw%2BBrlfhcUBsr7o9LRqo%3D&reserved=0>.

**Comment by exextoc** [comment]
Is this an add-in that you are developing or are you trying to use a specific add-in?
The error you are seeing usually means that the add-in server can't be reached.

**Comment by MartinSSeifert** [comment]
@exextoc it is this add-in: https://appsource.microsoft.com/en-us/product/office/WA200003062

**Comment by MartinSSeifert** [comment]
@exextoc can you evaluate under what circumstances the Outlook host is triggered to show the message reported in this issue?

**Comment by exextoc** [comment]
If we cannot reach the add-in's server, we will fail to download the JavaScript file associated with the add-in.
The file is downloaded to a path with the following format:
`%LOCALAPPDATA%\Microsoft\Office\16.0\Wef\{[Outlook profile GUID]}\[encoding]\Javascript\[Add-in ID]_[Add-in Version]_[locale]\bundle.js`
Can you check to see if such path/file exists locally on the computer where you are running Outlook?

**Comment by MartinSSeifert** [comment]
@questionhead would you mind checking the input coming from @exextoc - thank you.

**Comment by questionhead** [comment]
@exextoc The path file exists, path and everything is correct.

**Comment by exextoc** [comment]
We've heard reports of an error similar to this. If the server returns HTTP code 304 Not modified, the file can be downloaded successfully, but our client incorrectly returns this as an error. A fix will be coming for this soon. 

You could use fiddler to see if this is what is happening in your case when Outlook makes the http request for your JS file.

**Comment by questionhead** [comment]
The fix is coming with Office-Updates?

**Comment by exextoc** [comment]
I don't have the details yet. Depending on risk/severity it would come via the monthly updates. I am not sure if it will be backported.

**Comment by exextoc** [comment]
@questionhead are you using our `sessionData` APIs in your add-in?
We have checked-in a potential fix that will rollout with Office updates.
Depending on your channel, you may get it in a few days to about 6 weeks.

**Comment by questionhead** [comment]
Meanwhile I already have a new notebook, so I can't test it.
Thanks for your help anyway.

**Comment by exextoc** [comment]
Great! Just curious, are you using our `sessionData` APIs in your add-in?
The potential fix I mentioned is un-related to the `sessionData` API. It is specific to your issue, however, I'm curious whether your add-in is using this API or not since that could be a separate issue?

**Comment by questionhead** [comment]
Hi
how should i check this?

**Comment by exextoc** [comment]
You can check if you are using any of the session data APIs detailed [here](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview#session-data) in your add-in's implementation.

These APIs are in preview, so they could be causing an exception which can prevent the add-in from loading.

**Comment by thomasdarde** [comment]
Hello , we are also seeing this message with different clients, but it's impossible to reproduce on our side.
Could you send mor information on the reason it happens , or how to debug it ?
