### ISSUE TITLE
Reading/Writing per-cell format in a performant way

### ISSUE THREAD

**Issue by jrop** [OfficeDev/office-js#215]
_First of all, thank you so much for your work on this API!_

Currently, it is possible to read and write Range values in batch, and this can be extremely performant.  However, it would seem that other properties, such as "format", "format.font", or any other per-cell data, is prohibitively expensive to retrieve on a large worksheet.

```js
Excel.run(async ctx => {
  const sheet = ctx.workbook.worksheets.getItem('sheet1')
  const range = sheet.getRange('A1:J10')
  console.time('timer')
  for (let r = 0; r < 10; ++r) {
    for (let c = 0; c < 10; ++c) {
      const cell = range.getCell(r, c)
      cell.load(['format', 'format/font'])
      await ctx.sync()
      console.log(r, c, cell.format.toJSON())
    }
  }
  console.timeEnd('timer')
})
```

The following is the worst-case performance time I have seen this achieve:

![Performance](https://i.imgur.com/ocjLwRF.png)

Is there a more performant way to access per-cell data?  I am beginning to wish that there existed some sort of query language in OfficeJS where I could describe what data I _want_, and then have the backend look at that and hand it back in one operation, instead of accessing it like this.

**Comment by jrop** [comment]
NVM, found out that `load(...)` can load recursively.  Sorry for the noise:

```js
await Excel.run(async (ctx) => {
    const sheet = ctx.workbook.worksheets.getItem('sheet1')
    const range = sheet.getRange('A1:J10')
    console.time('timer')
    const cells = []
    for (let r = 0; r < 10; ++r) {
        for (let c = 0; c < 10; ++c) {
            const cell = range.getCell(r, c)
            cell.load(['*', 'format/*', 'format/fill/*', 'format/font/*', 'format/protection/*'])
            cells.push(cell)
        }
    }
    await ctx.sync()
    for (const cell of cells) {
        console.log(cell.toJSON())
    }
    console.timeEnd('timer')
});
```
This runs in less than a second.

**Comment by Zlatkovsky** [comment]
@jrop , while you're here, a couple thoughts:

1. The biggest difference between your initial code and the one below it is the use of ` ctx.sync()` -- and the fact that in the latter code block, you moved it out of the for loop.  That's by far and away your biggest gain.  As a developer using Office.js, your goal is to minimize invocations to `context.sync()`, as each one is a perf hit -- which means batching things up, just like you did in your second code block.
2. We are investigating an API (which for now we're thinking of calling `getCellProperties` and `setCellProperties`) which would drastically improve the perf.  No ETA or firm commitment yet, but we *are* looking into it.
3. If your range ends up being 100x100 rather than just a 10x10, you might hit another perf issue -- of having too many Range objects created.  If so, see this workaround that I answered in a stackoverflow question yesterday:  https://stackoverflow.com/a/51737030/678505
4. Finally, just FYI:  loading of "*" can be quite expensive -- I recommend that in production code, you figure out exactly what properties you need, rather than loading all.

Best!

~ Michael

**Comment by jrop** [comment]
@Zlatkovsky Thanks for the info!  Yep, batching is always preferred.  I'll read through the SO answer for more info, thanks for posting!
