### ISSUE TITLE
Calling chartCollectionObject.load('items') causes an internal error

### ISSUE THREAD

**Issue by troywweber7** [OfficeDev/office-js#217]
## Expected Behavior

I should be able to load the items in a charts collection (with the intent to delete them or modify them).

## Current Behavior

Attempting a `charts.load('items')` causes "... an internal error ...".

## Steps to Reproduce, or Live Example

* Additional details:
  1. Run the following code:

```
await this.excel.run(async ctx => {
	const charts = ctx.workbook.worksheets.getActiveWorksheet().charts;
	charts.load('items');
	await ctx.sync();
	console.log(charts.items);
});
```

## Context

I need to be able to access the charts in order to update them or delete them. You guys make no guarantees on BETA, but I didn't see an issue for it yet so I thought I would submit one.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: **PC desktop**
* Host [Excel, Word, PowerPoint, etc.]: **Excel**
* Office version number: **BETA**
* Operating System: **Windows 10**

## Useful logs

- [X] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

```
Office Error: {
  "code": "GeneralException",
  "message": "There was an internal error while processing the request.",
  "errorLocation": "Chart.plotBy",
  "statement": "charts.load([\"*\"]);",
  "surroundingStatements": [
    "var workbook=context.workbook;",
    "var worksheets=workbook.worksheets;",
    "var activeWorksheet=worksheets.getActiveWorksheet();",
    "var charts=activeWorksheet.charts;",
    "// >>>>>",
    "charts.load([\"*\"]);",
    "// <<<<<"
  ],
  "fullStatements": [
    "Please enable config.extendedErrorLogging to see full statements."
  ]
}
```

**Comment by Rick-Kirkham** [comment]
You shouldn't need to specify "items" when you load a collection class. If you load anything, you get the items too. What happens if you use the command `charts.load("no-properties-needed");` ?

**Comment by MiaofeiWang** [comment]
If Rick's suggestion not work, @troywweber7 can you share with us what kinds of charts (like column, line, scatter, etc.) you are using in this worksheet?

**Comment by troywweber7** [comment]
That appeared to do it for me. I think there are some complexities of the `load()` function of which I'm not aware. I think this should allow me to do what I need to (delete and update series of all the charts). Thanks.

**Comment by troywweber7** [comment]
Could someone explain what "no-properties-needed" actually does?

**Comment by Rick-Kirkham** [comment]
@troywweber7 See [Excel Add-ins Advanced Concepts](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-advanced-concepts.md) for some information about load(). It does not, however, answer your question, so I will make a work item to add that. 

When your code is not going to read any particular properties, then you don't need to specify any in a parameter to load(). But if you don't pass anything at all to load(), it loads, counterintuitively, **all** scalar properties. This can be a significant performance hit, so to get load() to not load any properties (which is what you would intuitively think it does if you don't pass any parameter), you have to pass it _something_. But if you pass it the name of a property, then its going to load that property, which you don't need. So to trick it into loading nothing (except things like items that are always loaded) you pass it _any random string_.  Which brings me to the second counterintuitive fact about load(). It will not throw an error if you pass it a string that is not the name of a property. So, load("eseojfljlej") would work just as well as load("no-properties-needed"). But, passing "no-properties-needed" is more self-documenting. It tells a person reading the code _why_ you are not passing the name of one or more properties. I've noticed that some people use load("$none"), which I think is less self-documenting, but it works the same way because _any_ string (that isn't the name of a property) works. 

Also, I recommend this book to all Office add-in developers: [Building Office Add-ins](https://leanpub.com/buildingofficeaddins)
