### ISSUE TITLE
Search doesn't work properly when using matchWholeWord  in Word Online. 

### ISSUE THREAD

**Issue by va1729** [OfficeDev/office-js#218]
The `context.document.body.search` API doesn't work if `matchWholeWord` is set to true in [SearchOptions](https://dev.office.com/reference/add-ins/word/searchoptions) and the search term is in brackets. It works in Windows Word application though.

## Expected Behavior
It should search and return results even if the search term is in brackets.

## Current Behavior
Searching for `[text]` in a document filled with something like `[text] [text] [text]` with `matchWholeWord` option set returns 0 items instead of 3.

## Context
We are working on an Word add in and we are providing a search feature from within the add-in.

## Your Environment
* Platform: Office Online
* Host: Word
* Operating System: Windows
* Browser (if using Office Online): Chrome, IE11

## Steps to Reproduce
You can reproduce the same by just searching in any Office Online Word document using the inbuilt search feature of Word. 
- Add the text - `[text] [text] [text]` to your document
- `Ctrl+F` and search for `[text]` with `Find Whole words only` option selected.

**Comment by JuaneloJuanelo** [comment]
I was able to repro this issue. btw here is a Script Lab gist. https://gist.github.com/JuaneloJuanelo/30a4c79ef4540451e5972e45552dff53

tracking with bug 2491489

**Comment by meisammofidi** [comment]
@JuaneloJuanelo Seems this issue is still in force.
In my experience on Word online, When `matchWholeWord ` is set to True result is empty array [ ] while when we set to False some result come back. Anyways matchWholeWord  doesn't work in online Word. We are working on a project and this search option is crucial for us otherwise get wrong result by setting this option to False. I am wondering if any plan to resolve this issue ?
