### ISSUE TITLE
Office Add-ins not showing in Microsoft Edge Devtools Preview

### ISSUE THREAD

**Issue by PauRosello97** [OfficeDev/office-js#2185]
When opening an office add-in (Outllok, Word, Excel or PowerPoint) locally or once deployed, I should be able to see it in the Microsoft Edge Devtools, but it's appearing blank. What are the steps we should follow to discover the problem?

## Expected Behavior
When opening an office add-in it should appear Microsoft Edge Devtools

## Current Behavior
The Microsoft Edge Devtools list is blank (even after refreshing).

## Context
I'm trying to develop a series of add-ins for Outlook, PowerPoint, Excel and Word. This is working in other computers, but not in mine. I've followed the steps in the documentation, and I don't know what more can I try.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Desktop
* Host [Excel, Word, PowerPoint, etc.]: Word, PowerPoint, Excel and Outlook.
* Office version number: v2109 (comp 14430.20298)
* Operating System: Windows

## Useful logs
![image](https://user-images.githubusercontent.com/49373982/137752313-13512c0c-5d5a-4da2-8139-3c888ab0dcdc.png)

**Comment by Rick-Kirkham** [comment]
The Edge DevTools can only see and attach to processes running in the Edge Legacy webview (EdgeHTML). Based on your version of Office, your add-in is probably running in the new Chromium-based Edge webview (WebView2). See [Browsers used by Office add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins). To debug an add-in that is using WebView2, see the article [Debug add-ins on Windows using Edge Chromium WebView2](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-desktop-using-edge-chromium). 

Let us know if that doesn't work. Otherwise, I'll close this issue in a couple days.
