### ISSUE TITLE
Windows Outlook, Office.context.ui.displayDialogAsync prompt dialog have security issue while using google oauth login

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#2187]
error message is:
```
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can try again to sign in.
```

![image](https://user-images.githubusercontent.com/1878089/137886314-9e05a943-c663-4ecc-bd31-c64b299a9bfb.png)

there is no problem on chrome owa.

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @hello-chenchen. Would you please be able to provide repro steps? By using the following template you help us better analyze your issue. 


# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior


## Current behavior



## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)



1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context



## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by JamiesWhiteShirt** [comment]
This is still an issue. [Embedded webviews cannot be used for authenticating with Google](https://developers.googleblog.com/2021/06/upcoming-security-changes-to-googles-oauth-2.0-authorization-endpoint.html) (and perhaps other identity providers as well). Thus, dialogs cannot be used to authenticate with Google in all non-browser versions of Office. Browser version of Office are not affected as Google does not prevent authentication in the browser popup windows used for dialogs.

Resolving this issue would require additional capabilities from the add-in API to support authentication in native web browsers. To support OAuth2.0 flows it would require API to open a page in a native web browser (this might already be possible, I haven't checked), and an API to handle the callback from the native web browser. It'll be tricky to support for sure.

Unfortunately it seems the only option for reliable authentication is the built-in Microsoft one.
