### ISSUE TITLE
Getting API error: GeneralException with WorksheetFreezePanes.freezeRows

### ISSUE THREAD

**Issue by Lilyliu123** [OfficeDev/office-js#2196]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___PC desktop___
* Host [Excel, Word, PowerPoint, etc.]: __Excel__
* Office version number: __2019 Build (16.0.1440.20292) 64-bit__
* Operating System: __Windows 10 64 bit__
* Browser (if using Office on the web): __N/A__
 
## Expected behavior
No exception when using addin

## Current behavior
Get the error "API Error: GeneralException, There was an internal error while processing the request, WorksheetFreezePanes.freezeRows
## Steps to reproduce
The current function is to import a json file to the Excel and freeze the window on certain row.
The current code throws this exception in the middle the entire importing process.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. _No issue on version 2019 Build (16.0.11430.20154) 32-bit_
2. _No issue with office 365_____
3. _No issue with office web_____

## Context

The current feature is just simply import a json file to Excel and freeze the pan on a certain row after importing

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @Lilyliu123! Connecting you with @dingjin-ms who may be able to help.

**Comment by zhenhuangMSFT** [comment]
Hi @Lilyliu123! Thanks for reporting the issue! The API call of `WorksheetFreezePanes.freezeRows` will throw a general exception if the row you try to freeze is outside the visible range. Could you please verify that if this is the case? If not, could you please provide more details about your add-in's script so that we can reproduce it for further investigation.

**Comment by Lilyliu123** [comment]
Hi Zhenhuang,

Sorry for the delay. Yes, it could be the reason. 
When the issue happened the worksheet we tried to freeze was not activated. 
I have added the code to activate the sheet before calling WorksheetFreezePanes.freezeRows . We are now doing the testing and I'll update to you once we finish the testing.

Cheers
Lily

**Comment by Lilyliu123** [comment]
Hi Zhenhuang,

Yes. I think it is the case that WorksheetFreezePanes.freezeRows throw an exception when the row is outside of visible range.

I added activating sheet and removed some rows above the target row to make target row visible, then it worked.

Are you going to fix this issue or we need to put the workaround to make it work for now? It is a bit hard to us to use the workaround as I have to remove ( or maybe hide would work) some rows above target row to remove the exception.

Kind regards
Lily

**Comment by zhenhuangMSFT** [comment]
Hi @Lilyliu123,

Thanks for your precious feedback!

The general exception is indeed confusing and we have been trying to make it more informative. As to whether we will fix the issue, we will need more discussion with our PM since this will be a change on API design. After all, it does not make sense to freeze rows outside the visible range because that would freeze the whole view. 

We will keep you updated.

**Comment by Lilyliu123** [comment]
Hi Zhenhuang,

Thanks for the clarification. That does make sense.
We have made some changes to make the frozen row visible to solve the issue.

Kind regards
Lily
