### ISSUE TITLE
getDirectPrecedents API call is not robust

### ISSUE THREAD

**Issue by Alex0cean** [OfficeDev/office-js#2206]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

If you call getDirectPrecedents API on a range that does not contain a formula or only formulas with no precedents, it fails and returns an API error. 

see screenshot:

![image](https://user-images.githubusercontent.com/80747078/138683510-07abef7f-74e5-4be0-bc6b-546f4bdec84e.png)

## Your Environment

Excel desktop 2102 (with WebView runtime), Excel Online (Chrome)
Operating System: Win10

 
## Expected behavior
We would expect to support the isNullObject logic.
Or: return an WorkbookRangeAreas object with empty range array.

## Steps to reproduce
See attached scriptlab gist.
[getDirectPrecedents.scriplab.txt](https://github.com/OfficeDev/office-js/files/7409485/getDirectPrecedents.scriplab.txt)

**Comment by chiz-ms** [comment]
Hi @Alex0cean, thanks for the report. Based on our investigation, this behavior is considered by design. If you're requesting a new method `Range.getDirectPrecedentsOrNullObject`, please go to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) and see if your feature has already been requested or request a new feature. Feature requests on are considered when we go through our planning process.

Thanks,
Microsoft 365 Developer Platform team

**Comment by Alex0cean** [comment]
Hi,
thanks for your prompt answer.
Can you help us (we're developing an add-in available in the MS store) how we should use this function?
We currently need the direct precedents information whenever a formula changes. But not all formula changes raise a sheet_change (e.g., if you don't touch the formula, but only move one of the precedents). Due to this, we have to get the direct precedents in sheet_calculate for all formulas. 
Using try/catch is not a real option as we would have to do this for each single formula individually - which would lead to poor performance.
Any help/tips is appreciated. 

Best,
Alex

**Comment by chiz-ms** [comment]
Could you share more details about the purpose of keeping track of the direct precedents of all formulas in your add-in?

**Comment by Alex0cean** [comment]
For each formula which is located in a certain Excel NamedRange (one which we populate with data), we move the formula around, if we change the data in this Excel NamedRange.

Formulas, which have precedents in the same NamedRange, we ignore and we inform the user, that we will ignore this formula.

**Comment by chiz-ms** [comment]
I'm not sure I understand the scenario, but let me try to rephrase:
- There are a significant number of cells with data in the worksheet, possibly referenced by formulas;
- A large number (otherwise it'll be feasible to call `getDirectDependents` on each cell) of data cells will be moved by your add-in at the same time, but you're afraid of breaking the formulas dependent on them;
- So you would like to track the formula dependencies.

If that's the case, one workaround would be to replace absolute address references with named ranges, structured references (e.g. table column), INDIRECT function, or custom functions, which could work after data being moved.

Otherwise, besides posting a feature request for `getDirectPrecedentsOrNullObject` on to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions), I would suggest you go to [StackOverflow](https://stackoverflow.com/questions/tagged/office-js) and see if your question has already been asked or ask a new question. This will allow both the community to help, and allow us to ensure the community can see our answer.
