### ISSUE TITLE
Office.context.mailbox.getCallbackTokenAsync to return a token valid for Graph API mail scopes/endpoints?

### ISSUE THREAD

**Issue by courington** [OfficeDev/office-js#2223]
Currently the Office.context.mailbox.getCallbackTokenAsync method returns a token that I can use as an Authorization Bearer token for Outlook REST API calls in my Outlook add-in. Will this method be able to return a token with graph scopes for mail endpoints when the REST API is turned off?

If not, is there another preferred method to achieve Graph API authentication without presenting the end user with another dialog or needing to set up SSO auth flow on a server?

**Comment by exextoc** [comment]
Hey @courington ,

The authentication to Graph API is only possible through [SSO API ](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph)or through [Dialog API](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph-without-sso). I have linked the documentations here.

**Comment by jonmoshier** [comment]
Hey @exextoc, 

We're looking at using the SSO API but are concerned that the [getAccessToken endpoint](https://docs.microsoft.com/en-us/javascript/api/office-runtime/officeruntime.auth?view=excel-js-preview#getAccessToken_options_) doesn't currently support outlook.com.

Is there a workaround for this or will outlook.com eventually be supported?
![image](https://user-images.githubusercontent.com/763527/140802681-b79819dd-f829-4fcd-a514-67bc6a67165c.png)

**Comment by exextoc** [comment]
Currently graph API doesn't allow auth in personal accounts. We track Outlook add-in feature requests on our [Tech Community Page](https://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). 
Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by courington** [comment]
@exextoc Thanks, I'll post in the Tech Community Page. Currently I'm using the Dialog API and that's working for us, but I am hoping for something a bit more seem less, ie: when the customer installs the add-in and accepts scopes there, since they're already authenticated into Outlook when the add-in is being used and scopes have been accepted on add-in installation being able to forgo a dialog or sso auth flow and simply request a token. I'll post this feature request in the proper channel you shared. Thanks!

**Comment by ryanulit** [comment]
@exextoc is there any plan in the authentication roadmap to add support for generating a Graph API token from the Common API as @courington was asking in the original question (e.g. `OfficeRuntime.auth.getAccessToken()` actually returning a Graph API token or introducing some other new method)?  While I appreciate that there is a SSO approach to enhance the user experience and not require an additional login, that approach also requires setting up a server component to interact with the Graph API using the On-Behalf-Of flow.  Other than that, you are stuck with using the Dialog flow to get a Graph API token, which then degrades the user experience by requiring another login.

At my company, we've built an Outlook add-in that is strictly client-side code using React and would really like to keep it that way.  We use the Outlook REST API in that add-in and due to the planned Nov 2022 deprecation, we've started investigating migration to the Graph API.  Is there really no way to get a Graph API token client-side since the user is already logged in to Outlook when our add-in is loaded?  It's a little frustrating to have the REST API be deprecated, yet not provide similar functionality in the Common API for generating a token usable with Graph API.

I really hope I'm missing something here, so please correct me if I've misunderstood anything mentioned above.

**Comment by cbishop-fv** [comment]
> @exextoc is there any plan in the authentication roadmap to add support for generating a Graph API token from the Common API as @courington was asking in the original question (e.g. `OfficeRuntime.auth.getAccessToken()` actually returning a Graph API token or introducing some other new method)? While I appreciate that there is a SSO approach to enhance the user experience and not require an additional login, that approach also requires setting up a server component to interact with the Graph API using the On-Behalf-Of flow. Other than that, you are stuck with using the Dialog flow to get a Graph API token, which then degrades the user experience by requiring another login.
> 
> At my company, we've built an Outlook add-in that is strictly client-side code using React and would really like to keep it that way. We use the Outlook REST API in that add-in and due to the planned Nov 2022 deprecation, we've started investigating migration to the Graph API. Is there really no way to get a Graph API token client-side since the user is already logged in to Outlook when our add-in is loaded? It's a little frustrating to have the REST API be deprecated, yet not provide similar functionality in the Common API for generating a token usable with Graph API.
> 
> I really hope I'm missing something here, so please correct me if I've misunderstood anything mentioned above.

We have the same client-side react app. And agree with what you are saying. It's so easy to connect to the rest API with the provided token. Much better UX.

**Comment by ryanulit** [comment]
bump 

@exextoc any hope of getting a response here?

**Comment by cody-lettau** [comment]
It'd be great to get an update on this @exextoc.

Have the REST APIs been fully decommissioned for add-ins that were not given a grace period? If so, this absolutely needs to be better defined with an easier flow.

**Comment by cbishop-fv** [comment]
The graph flow thru azure is atrocious. Our users are very annoyed that they have to reauth with MS every day.

**Comment by exextoc** [comment]
This is not possible today. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions).

It looks like the feature you want has been requested by others already. Please upvote the existing request [Add support for MS Graph](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/add-support-for-ms-graph-to-getcallbacktokenasync-in-office-js/idi-p/2277811). Feature requests on Tech Community are considered when we go through our planning process.

**Comment by cody-lettau** [comment]
@exextoc based on the EOL of the Exchange Web Services scheduled for 2026, this is something that we strongly feel needs to be implemented in order to replace existing functionality and provide a similar user experience. If it is not, then the user experience of add-ins will be impacted for the worse, or require that all add-ins now have a backend component to support the add-in.
