### ISSUE TITLE
getAsync recipient from mailbox item (cc, to, bcc ...) return different results between outlook web and outlook for Mac and for Windows.

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#2238]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook web, Outlook Mac 
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2110 (Build 14527.20234)
* Operating System: Windows
* Browser (if using Office on the web) Chrome Version 95.0.4638.69 (Official Build) (64-bit)
 
## Expected behavior
The result should be synchronized between web and app

## Steps to reproduce

1. loggined my personal same account jason.hieu@hieudoandev.onmicrosoft.com on outlook
2. enter 2 addresses in web and app to get the recipientType (one in the same company, one from other):
3. on Web : it shows "other" for Diego@hieudoandev.onmicrosoft.com and "externalUser" for hieu@gmail.com
 on App : it shows "user" for Diego@hieudoandev.onmicrosoft.com and "other" for hieu@gmail.com

## Link to live example(s)
Can try any example here : https://docs.microsoft.com/en-us/javascript/api/outlook/office.recipients?view=outlook-js-preview#getAsync_callback_

# Provide additional details

![1](https://user-images.githubusercontent.com/13063615/141045462-6f9909b3-0920-42b2-b058-3fa71631d0a2.PNG)

![2](https://user-images.githubusercontent.com/13063615/141045489-558661b4-c403-4962-bcb6-2fcf507c2110.PNG)

**Comment by exextoc** [comment]
@jasonhieu1905 Thanks for reporting this issue regarding the getAsync recipient results. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.

Internal tracking id:: Outlook Web: 134393, MAC: 5563127

**Comment by barisbikmaz** [comment]
@exextoc Maybe to explain the problem with this issue and get more attention for it. We have an Outlook addin which inserts a Mail Signature. Outlook has now the feature to have Event-Based actions. When the user adds new recipients to his mail, we decide based on the recipient types if we insert a signature for internal or extenal users. Currently our addin cannot insert the correct signature in Outlook Online because the recipient types are wrong. I am sure that other ISVs creating signature products will face the same problem.

**Comment by JuaneloJuanelo** [comment]
Hello all. thanks I wanted to add a quick clarification to this email.   its not clear on this issue what are the impacted platforms.

1. Outlook for windows is working as expected, just validated this on our latest update.
2. OWA and Mac are returning incorrect information we are working on a fix soon. thanks and sorry for the delay.

**Comment by hxltinh** [comment]
> Hello all. thanks I wanted to add a quick clarification to this email. its not clear on this issue what are the impacted platforms.
> 
> 1. Outlook for windows is working as expected, just validated this on our latest update.
> 2. OWA and Mac are returning incorrect information we are working on a fix soon. thanks and sorry for the delay.

Hi @JuaneloJuanelo, this issue also happens on runtime process for reply message:
email: andrew@tinhhadev.onmicrosoft.com
reply to: sushi@tinhhadev.onmicrosoft.com
Environment: Outlook for Mac

<img width="990" alt="Screen Shot 2022-07-11 at 12 10 54" src="https://user-images.githubusercontent.com/8114730/178224710-e5605c9a-98cc-4b4b-bf55-180eabbee150.png">
it shows that the user has `recipientType` is "externalUser" instead of `user`. I expect that it would always show that the user has recipientType is `user`
