### ISSUE TITLE
Sometimes Execute function not work in Excel installed version (Semi-Annual)

### ISSUE THREAD

**Issue by lordbenz** [OfficeDev/office-js#2253]
## Environment
* Platform: Excel Installed Version(Semi-Annual) on window 10
![image](https://user-images.githubusercontent.com/28835449/142177618-df6722f6-5438-4d39-b4b6-3e8d65dae10a.png)

 
## Expected behavior
Execute function must be callable every time that the Ribbon button was clicked.

## Current behavior
We found that sometimes the Execute function at the Ribbon button did not work. 

Step to reproduce ([Example Code](https://github.com/benzdechapon/test-ribbon
))
1. Run the addin in my example code
2. Test in Excel installed version (Semi-annual)
3. Repeatedly try it again sometimes you may found that the dialog not show and the excel show message working on your xxx.

If you not found the issues that I stated I want to confirm that what is the possible causes for this kind of issues.

**Comment by alison-mk** [comment]
Hi @benzdechapon, thank you for submitting this issue! We've assigned it to @dingjin-ms, who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by pkkj** [comment]
Hi @benzdechapon, one more question: does this problem only happen in semi-annual, or it also happens in the newest build?

A few questions:
1. Does this problem only happen in semi-annual, or it also happens in the newest build?
2. How often does this problem happens?
3. You may verify a similar scenario in the ScriptLab add-in. It's an add-in command and you could install it from the store easily. Once installed, you could click the "Help" button, which will show a dialog, and try the multiple times. Try to figure out whether this add-in is working correctly in your environment.
4. One more small tip is in your source code, it's better to call event.completed() in the callback of displayDialogAsync(), since it's an async function and takes time to finish.


Thanks.
Kejing
