### ISSUE TITLE
PowerPoint.createPresentation is not working

### ISSUE THREAD

**Issue by emmanuelpineda** [OfficeDev/office-js#2255]
The PowerPoint.createPresentation method is no longer working. I received reports from my users that this stopped working as of yesterday.

## Environment

* Platform: Office on the web
* Host: PowerPoint
* Office version number: PowerPoint on the web
* Operating System: mac, windows or chromebook
* Browser: firefox, chrome and edge
 
## Expected behavior
After calling the createPresentation method it should display two confirmation prompts for the user to agree to create a file in OneDrive and after confirming, a new PowerPoint tab should open with a new presentation or the one specified in base64 

## Current behavior
Only a confirmation window is displayed and the following message is shown in the browser console:

GeneralException: An internal error has occurred.

## Steps to reproduce
To reproduce the error use the Script Lab add-in for PowerPoint and run the example: "Create presentation".

## Context
I use this method so that my users can create content from a presentation.

## Useful logs
Console log error: An internal error has occurred.

**Comment by ononder** [comment]
We have identified the issue that is causing this and currently waiting for the fix to be deployed. Thanks for your feedback.

**Comment by emmanuelpineda** [comment]
Thank you!

**Comment by emmanuelpineda** [comment]
Do you know the estimated time for the solution to be deployed live?

**Comment by ononder** [comment]
Sorry for my delayed reply, as I was trying to get more information about the timelines, the deployment speed depends on the success of changes so the timing can vary a lot, I was going to mention it might take up to a week, but today I can see several production level rings have the fix and I can verify the fix is working in my end. Not all rings have the change yet, but it might become available fully today or tomorrow.

**Comment by emmanuelpineda** [comment]
Thank you, I checked that it works fine now

**Comment by emmanuelpineda** [comment]
I have received reports that the error has returned, although it is not generalized, I received the report from a user in Canada, could you please check it out?

**Comment by emmanuelpineda** [comment]
Any update on this error?

**Comment by ononder** [comment]
Hello Emmanuel, sorry for my late response, I was out of office and I'm taking a look at this issue today.

I tried to execute this function from a few locations and couldn't reproduce the bug mentioned here. CreatePresentation call worked as expected.

I don't have data to see if there is a datacenter specific issue with an older build, but I would like to double check with you if the issue is still happening in for this specific user you mentioned?

And any other information regarding the repro steps you may have would be very helpful to pinpoint this issue.

Thanks,
