### ISSUE TITLE
Office.context.ui.openBrowserWindow is not working

### ISSUE THREAD

**Issue by thoriyadaxesh** [OfficeDev/office-js#2261]
Office.context.ui.openBrowserWindow is not working with restricted permission of outlook web add-ins after installing to outlook desktop application
If I set "ReadWriteItem" permission Office.context.ui.openBrowserWindow is working fine.

## Expected Behavior
Office.context.ui.openBrowserWindow should open the window in default browser

## Current Behavior
Office.context.ui.openBrowserWindow is coming as undefined

## Steps to Reproduce, or Live Example
Office.context.ui.openBrowserWindow(<url>);

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 11.0.0
* Operating System: Windows 10
* Browser (if using Office Online): NA

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by preethikakiru** [comment]
Hi @thoriyadaxesh, thank you for submitting this issue! I've assigned it to the Outlook Engineering Team @exextoc who will be able to further help you resolve this issue and provide you with more information. 
Best, 
Preethika

**Comment by exextoc** [comment]
Thanks for reporting. I can reproduce the behavior and will be taking a closer look.

**Comment by thoriyadaxesh** [comment]
Do we have any ETA on fix?

**Comment by exextoc** [comment]
We are still investigating this issue. What is your scenario when you want to use Office.context.ui.openBrowserWindow with Restricted permission?

**Comment by thoriyadaxesh** [comment]
Yes that's correct

**Comment by exextoc** [comment]
Could you please describe your scenario in more detail for when you use Office.context.ui.openBrowserWindow with a Restricted permission level?

**Comment by thoriyadaxesh** [comment]
Here is my scenario.
We are not reading any outlook mail data so we have keep permission level as "Restricted". We have button on ribbon when user clicks on, it should open default browser and open website.

**Comment by exextoc** [comment]
This is going through an internal security review on whether or not this API should be allowed at the Restricted level. We will update when there is a decision made.

**Comment by thoriyadaxesh** [comment]
Is there any update or ETA for this issue?

**Comment by JuaneloJuanelo** [comment]
> Is there any update or ETA for this issue?

@thoriyadaxesh   we know that this API is used to pop a window, can  go in a bit more detail on why you want to pop a page in restricted permission? i wonder why you need that having zero interaction with Outlook does not seem to be add value to Outlook users and as a result you might fail validation in our store.

**Comment by thoriyadaxesh** [comment]
@JuaneloJuanelo I want to redirect user to our portal if they need to do more transaction which can not be done using outlook add-ins. So we provided option and when user clicks on it, it should open our portal in default browser. I don't want to pass any outlook/mail information to portal.

**Comment by exextoc** [comment]
@thoriyadaxesh is there a reason why you cannot use the ReadItem permission level?

**Comment by lukesolar** [comment]
Hi - I'm facing the same problem. Maybe related to this one. However I did set `<Permissions>ReadWriteItem</Permissions>` 
The problem only appears on Office 2016 (exact version: 16.0.5197.1000) (maybe with IE running in the background, which is still supported)
Can you reproduce this? Any suggestions?

**Comment by thoriyadaxesh** [comment]
> 

"ReadItem" permission gives me more control over user's mail, which is privacy risk. Mail could be anything, it can contain personal information.
We don't need those details to run our add-ins then why should we give more permission to our add-ins.

**Comment by JuaneloJuanelo** [comment]
Hello. After careful consideration we have decided to not fix this issue, rationale:

1. It can be easily fixed by providing a read permission. (Please note that even if you fix this, it will be a violation of our store policies and most probably the add-in will be rejected to be on the store) 
2. We don't want to encourage an extensibility model in Outlook that does provide any interactions other than opening a secondary page to fix an issue. That is actually against the productivity gains that are promoted as part of our Add-in model. 
3.  If we fix it, we will have background compatibility issues as we are not planning to backport any fixes to one-time purchase Skus. 
4.  Last but not least, its mentioned that this issue happens in Outlook 2016 on this thread, that release is already out of main line support so we can only release critical security fixes, which is not the case, so even if we fix it will not be backported to such sku. 

Based on the above we are closing this issue.
