### ISSUE TITLE
Highlight text

### ISSUE THREAD

**Issue by AlexeyVanyukevich** [OfficeDev/office-js#2262]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I'm attempting to implement functionality to highlight some text within a Word document. I don't want to modify the document, much like when you perform a search with Find and Replace feature (and text matching your search is highlighted in yellow).

Is this possible using the Office JavaScript APIs?

**Comment by chiz-ms** [comment]
Hi @AlekseyVanyukevich, currently the feature you described is not supported. In some cases you may consider using selection instead of highlighting as a workaround, or you may go to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) and see if your feature has already been requested or request a new feature.
