### ISSUE TITLE
Pin doesn't work in Outlook for events invitations

### ISSUE THREAD

**Issue by sztukiecki** [OfficeDev/office-js#2290]
# Provide required information needed to triage your issue

## Your Environment

* Platform: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2102 (13801.21050)
* Operating System: Windows
 
## Expected behavior
Pin works contentiously for every type of message. 

## Current behavior
Pin doesn't work in Outlook Desktop App for event invitations. It works for all other messages, but when it comes to invitations, the add in gets closed.

## Steps to reproduce

1. Open Add In
2. Click on PIN
3. Open message, which is an invitation to an event

## Link to live example(s)
https://gs24-my.sharepoint.com/personal/jakub_sztukiecki_ext_scout24_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fjakub%5Fsztukiecki%5Fext%5Fscout24%5Fcom%2FDocuments%2Fvideo%2Emp4&parent=%2Fpersonal%2Fjakub%5Fsztukiecki%5Fext%5Fscout24%5Fcom%2FDocuments

**Comment by exextoc** [comment]
The link to the live example didn't work for me. Can you send a publicly accessible link or attach the video if there are no privacy concerns? I just tried this on a recent build of Outlook and it works fine for me.

**Comment by sztukiecki** [comment]
[video.zip](https://github.com/OfficeDev/office-js/files/7701989/video.zip)

**Comment by exextoc** [comment]
I sync'ed the version of Outlook that your reported. And this works for me: 

![image](https://user-images.githubusercontent.com/28549921/145919665-6eabcd33-c5b0-43fe-8e87-7c57922705c7.png)

(Other developers on the team tried with more recent builds of Outlook, and it also worked) 

Do you have anything else installed on your machine that may cause this? Perhaps, A COM add-in that has a custom form for meeting accepts? 

Does it repro if you try on a completely fresh machine and install of Outlook? (mainly curious if there is some add-in / form installed, and this would be a way to be sure) 

Do other add-ins works? (install Script Lab from the Store, as a test, as it supports pinning). 

What happens if you do the following: 

1) Click on the Meeting Accept Item (No add-in opened)
2) Open an add-in on that Meeting Accept Item

And

1) Open that Item in a window (by double clicking)
2) Open an Add-in on that Item.

**Comment by sztukiecki** [comment]
Thank you for your answer.
I checked out the Script Lab and it works fine.
Then I commented out my `Office.context.mailbox.addHandlerAsync` invocation and I realized that it fixed the issue (I had a bug in `Office.context.mailbox.addHandlerAsync`).
Thanks for help, I'll close this ticket.

**Comment by exextoc** [comment]
Glad to hear you resolved it. Note that handling addHandlerAsync for the itemChange event is necessary for pinned add-ins otherwise the item API will not be updated as you change between items.
