### ISSUE TITLE
Custom function doesn't work on Windows machines (#VALUE!)

### ISSUE THREAD

**Issue by jake-chambers** [OfficeDev/office-js#2326]
# Provide required information needed to triage your issue
This issue has been occurring only on Windows machines. We cannot reproduce it on Excel for Mac, or on Excel Online.

We built our Office Add-In using the React guide https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-react

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **Windows PC Desktop**
* Host [Excel, Word, PowerPoint, etc.]: **Excel**
* Office version number: **Microsoft Excel 365 Subscription Version 2110 Build 14527.20276**
* Operating System: **Windows 10 Home Edition Build 19044.1348**
 
NOTE: this bug is not limited to only this environment, it happens on different Windows Excel OS configurations as well

## Expected behavior

The function should resolve to a value like it does on every other platform

## Current behavior

- After loading in the add-in, it asks the user to "Trust this add-in", the user selects trust and proceeds
- Then the user logs in and tries to use the function, it seems the whole add-in is reloaded and the user is prompted to "Trust this add-in" a second time.
- The function does not process and returns #VALUE!
- The autocomplete for our function does not seem to work either, so it looks like its not even reading our `functions.json` file

## Steps to reproduce

Download Wisesheets add-in on Windows machine and try to use our WISE function (instructions are in sandwich menu of sidepane)

## Link to live example(s)

https://user-images.githubusercontent.com/79162379/147140967-39be3bb7-6f48-49fc-a1e8-30f64664506c.mp4

# Provide additional details

- The autocomplete for our function does not seem to work either, so it looks like its not even reading our `functions.json` file

## Context

- This has been a prevalent issue with MANY of our users on Windows machines and we cannot figure out the solution

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by JHJ-MS** [comment]
Hi, @jake-chambers, we'd like to get some details about your issue:

Has this function worked well before? When did this issue occur?

**Comment by sheldoncoates** [comment]
Hi, @JHJ-MS, I worked on this with @jake-chambers... originally we had our task pane add in working with vanilla HTML, CSS, JS. We upgraded to React using the tutorial mentioned in the issue description and the function worked on Excel for Mac and Excel online but not for Excel on PC Desktop. We're not sure why this is happening since we followed the tutorial for both the task-pane add in and the custom function one as listed in the Office docs so any advice would be helpful.


Here's the customer function tutorial: https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows

**Comment by jiju-MS** [comment]
Hi, sheldoncoates, some thoughts according to you video:
1. From the video, it has the intelligence of your function "wise" and "wisePrice", usually it means your json file has been successfully read by excel.
2. Considered you add-in is able to work with vanilla HTML and JS on win32 before, seems neither Custom Function native functionality nor add-in function logic is the root cause, may I know is a very simple function like function test(){return 1;} able to work on your test environment after you changed to React?

**Comment by jake-chambers** [comment]
@jiju-MS Here is a video trying what you suggested, we modified the WISE function to only `return 1` (shown in video)
The taskpane loads then throws an error but refreshing makes it work. Please watch the whole video to get full context. We'd be happy to send over our source code to let you reproduce it yourselves.

https://user-images.githubusercontent.com/23714923/147372010-e7eee481-7a15-4067-9e73-c0b79f00a0f2.mov

**Comment by JHJ-MS** [comment]
@jake-chambers If you don't mind, could you send over your source code to my work email haijiajin@microsoft.com? We'll try to reproduce it on our side and do a further investigation.

**Comment by jake-chambers** [comment]
@JHJ-MS Just sent an email, thank you so much for your help!

**Comment by JHJ-MS** [comment]
@jake-chambers We have reproduced it locally. We find that your custom functions can be worked well on all platforms when using a shared runtime. We suggest you to using a shared runtime to solve the problem. More details can be seen in the email. Besides, the reason for the #VALUE! on Windows will still be investigated.

**Comment by chiz-ms** [comment]
The issue has been tracked in our backlog as ADO#5696455.

**Comment by JHJ-MS** [comment]
hi @jake-chambers, does the issue resolved by using shared runtime on your side?

**Comment by jake-certn** [comment]
Ya everything seems to be okay, really appreciate the help on this @JHJ-MS!

**Comment by jake-chambers** [comment]
Ya @JHJ-MS , everything seems to be fine. Thank you so much for your help on this
