### ISSUE TITLE
Relative Path SRC/SCRIPT links in taskpane.html don't match file name generated for .js

### ISSUE THREAD

**Issue by FreeSoftwareServers** [OfficeDev/office-js#2339]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2021
* Operating System: Win10
* Browser (if using Office on the web): 
 
## Expected behavior

`npm run build` should utilize the "hash" name for file transformed from relative `src=../` relative link for scripts correctly.

IE:

```
    <!-- Template styles -->
    <link href="taskpane.css" rel="stylesheet" type="text/css" />
```
Becomes this after `npm run build`

`<link href="8d768f65702f2137206f.css" rel="stylesheet"/>`

Filename is `8d768f65702f2137206f.css`

## Current behavior
This works fine for the css file, but my js reference was consistently incorrectly each build.

This :
```
    <!-- Extra Scripts -->
    <script type="text/javascript" src="../commands/commands_funcs.js"></script>
```

Becomes this after `npm run build`

`<link href="4asd8865asd9876asd9.css" rel="stylesheet"/>`

Filename is `7d6123kjasdasdgasdas.css`

## Steps to reproduce
add a relative path reference to a js file in taskpane.html
run `npm run build`
compare generated taskpane.html src hash filename w/ real file name

## Link to live example(s)
Let me know if you can't reproduce, I can share git repo

# Provide additional details
I resolved by adjusting src to be http URL and that fixed, but may cause lots of frustration for others.

## Context
I host my add-in main command function inside commands.js, but repeatedly used functions I plan to store in separate .js files and reference in the taskpane.html. This part is working, its just the `npm run build` file hashing for relative filepaths that didn't seem to work for my .js file.

## Useful logs

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by FreeSoftwareServers** [comment]
I realized this is actually to do w/ webpack.config.js which is shipped w/ yo office script templates. I don't like how it changes my files anyway, so I've switched to VS Templates and am good now. Not sure if this is the right place to report webpack issues/yo office issues. Can likely be closed, but will annoy many others likely.

**Comment by millerds** [comment]
Webpack does this by default (I believe for chunking and caching reasons) and you have to explicitly configure it not to change file names if you don't like that.  If you leave it, it should hash the names and still load them at runtime correctly as long as they are linked to in files.  

Adding new files to the project and further configuration of webpack is something we leave up to the add-in developers.  If you want to use VS Code you can adjust webpack config file to keep the names as they are.  The example they use in their documentation adds a js files referenced in another js file and still uses the hash, but you can see how they are controlling the name https://webpack.js.org/guides/output-management/.  You can also control names by updating the rules section as we are doing the images since our manifest file needs these to be consistent.
