### ISSUE TITLE
[ Outlook ] 'Use Smart Alerts and the OnMessageSend event... ' not work

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#2342]
According to issue: https://github.com/OfficeDev/office-js/issues/2308
I have tried this again. But still have problem on it. I will attach my all code here and hope this will helpful. 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2110 (14527.20276)
* Operating System: win 10 20H2 19042.1415
* Browser (if using Office on the web): NA
 
## Expected behavior
Add-in can call function when event send.

## Current behavior
Nothing happen when sending an event.  

## Steps to reproduce

1. open a new appointment
2. add a topic and attendee
3. click send

By the way, below should be 'OnMessageSend' or 'onMessageSendHandler' ?
Office.actions.associate("onMessageSendHandler", onMessageSendHandler);
In 'https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch' it looks like 'OnMessageSend'. 
But in sample doc it's 'onMessageSendHandler'. 
And I tried both it's all not work.

**Comment by SWei1234** [comment]
[test-send3.zip](https://github.com/OfficeDev/office-js/files/7805168/test-send3.zip)
This is my sample for this feature. All code copied from 'https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough'.
Hope this will be helpful.

**Comment by exextoc** [comment]
As mentioned in the [issue](https://github.com/OfficeDev/office-js/issues/2308) linked above, this feature is currently in Preview, and only available if you are in the Beta Channel. Can you confirm that you completed the steps in [these ](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#how-to-preview)instructions to use the events in Preview?

Your repro steps says that you are testing on appointments, so in your add-in's manifest ensure that you are using `OnAppointmentSend` event instead of `OnMessageSend`. 

What you have looks correct, as in: `Office.actions.associate("onMessageSendHandler", onMessageSendHandler);`

**Comment by SWei1234** [comment]
@exextoc Okay, I will try and update result here. Thanks
