### ISSUE TITLE
Can you create function to detect close events on Task Pane?

### ISSUE THREAD

**Issue by teerayutRefinitiv** [OfficeDev/office-js#2367]
I have a problem with detecting and opening the popup before closing the task pane or when the user changes the application on the task pane to show the popup before changing it. Now I can't do it. I need your help to add a function when clicking Change app on the Ribbon, any app that is currently open on the task pane can be recognized before it is closed.

**Comment by AkhileshShah-MS** [comment]
Please provide more details about the issue in the format below 



# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior


## Current behavior



## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)



1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context



## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by teerayutRefinitiv** [comment]
**Your Environment**
Platform [PC desktop, Mac, iOS, Office on the web]: **All Platform**
Host [Excel, Word, PowerPoint, etc.]: **Excel**

**Expected behavior**
App in Task pane can detect when user switching app on Ribbon or close event

**Current behavior**
the app currently running on the task pane cannot detect event close or when the user changes the app from the ribbon. I try to add it in OnDestroy but not work

**Comment by AkhileshShah-MS** [comment]
Thank you for providing details. @dingjin-ms could you please help with the issue?

**Comment by yuc014** [comment]
Hi @teerayutRefinitiv, 

Thank you for reaching us. 

Based on my knowledge, so far we don't have this method.

I recommend going to [Microsoft 365 Developer Platform Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) and see if this feature has already been requested or request a new feature.

Thank you.

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
