### ISSUE TITLE
Prevent On-Send add-in error when user clicks different message

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#2377]
Currently, when an on-send add-in is running after clicking "Send" on a reply, an error will be displayed and the message will be saved as a draft if the user clicks away to another message if the add-in has not completed.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows 10
 
## Expected behavior
Complete the processing of the on-send add-in in the background even if the user clicks away from the message.

## Current behavior
An error is shown:
"An add-in prevented this message from being sent. It will be saved as a draft"

and (if the reply is popped out):
"Add-ins are still running on this message. The message won't be sent until the add-in completes. Do you want to wait for them to finish?"

## Steps to reproduce
1. Create an outlook add-in with the "On-Send feature" as described [here](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=windows)
2. Install the on-send add-in
3. Reply to a message (don't pop out)
4. Click send. Then immediately click away to another message.
(Note: Same thing for a popped-out reply -- just a different error message is shown)

# Provide additional details
A Stack Overflow question was asked here: https://stackoverflow.com/questions/61345763/how-to-prevent-on-send-add-in-errors-when-user-clicks-elsewhere

## Context
When we have on-send processing that may take a few seconds to complete, we want the user to be able to continue using Outlook as they would (which may include navigating to another message). There should not be any reason (that I can think of) that the on-send add-in cannot obtain a reference to the message it is running on and run in the background.

**Comment by exextoc** [comment]
This is how the feature is currently designed. There are issues that certain Office.JS APIs need the UI to function. Also if the add-in rejects the Send or if there are issues/bugs with the Add-in, then the user wouldn't know that their email wasn't sent. (they could be notified about this in some other way, but that just isn't in the product right now). 

One workaround is to use displayDialogAsync, that will pop a dialog that prevents the user from switching. (but this is quite intrusive) 

Going forward, this scenario is being addressed/replaced with SmartAlerts (though it is only available on Beta channels of Outlook right now). Also your scenario, still repros with this new feature. But Future suggestions and improvements for this scenario would likely be made on top of SmartAlerts, instead of ItemSend. 

https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough

You can make your feature request/change at our Tech Community Page, which is monitored for new features/changes to work on. 

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

With the "product feature request" label.

**Comment by cody-lettau** [comment]
@exextoc thank you for the quick feedback here -- much appreciated!

**Comment by cody-lettau** [comment]
For reference, here is the feature request: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/prevent-on-send-add-in-error-when-user-clicks-different-message/idi-p/3067187#M656

This is having a huge impact on our users :(

**Comment by JuaneloJuanelo** [comment]
As shared previously, this is by design Cody. There are a couple of recommendations here, of of them to show a dialog while you are processing the message.

I would love to understand how is this impacting your customers, because the email will be eventually sent again and processed?

if there is critical for them not to move then use the show dialog for help on this.

Again, by design and as such the issue is closed. lets follow up offline if you need further assistance email me. Juanbl@microsoft.com. thank you!

**Comment by cody-lettau** [comment]
Hi @JuaneloJuanelo - I sent an email regarding our use case back in mid-June. Just wanted to follow up as we have tried the popup to indicate the add-in is running during the send process, but it's really not a good user experience.

Many times, we are seeing issues with opening/closing of the dialogs causing issues (sometimes we show another dialog for the user to decide if an email needs to be encrypted or not based on the content of the email, so we have to close the sending dialog, open that new dialog, wait for an action, close it, and re-open the sending dialog). Many times (specifically on Windows desktop for the most part), we see a delay in closing of the dialog and have to continually retry opening the next dialog (since you can only have 1 open at a time).

As I mentioned in my email, I'd be glad to jump on a call to demo our add-in and discuss the limitations of the add-in platform further.

**Comment by carlosb1504** [comment]
> I would love to understand how is this impacting your customers, because the email will be eventually sent again and processed?

We are also seeing issues with this. I'm confused about the above statement because in our experience, messages are not in fact sent at all and will just sit forever in Drafts unless the user realises what has happened. This is made worse in OWA where there's no message to alert the user.

I feel like this should be at least made consistent, preferably made configurable to enable the user to have the processing finished before the moving away operation is then done.

**Comment by JuaneloJuanelo** [comment]
@carlosb1504  The issue in OWA is a bug been fixed and expecting to release a fix by end of May.

@cody-lettau  we are considering a work item to keep processing the email on item switch. there is not ETA at this moment. and there is a big challenge of what would be the right experience if we need to block the send.   One other important item here is that your add-in should process emails fast on send. This issue will be minimized if the performance of your add-in is fast.  If you need to process attachments or other heavy operations, you need to use event-based add-ins to preprocess as much as you can so the send logic is optimized.

**Comment by cody-lettau** [comment]
@JuaneloJuanelo that sounds great! Thanks for the update. I know right now our typically processing time is ~4 seconds if there are minimal attachments. But we are looking to handle attachments in a different way to support this as well and move toward event-based triggers.
