### ISSUE TITLE
ItemSend event function is called twice

### ISSUE THREAD

**Issue by svlc1** [OfficeDev/office-js#2379]
The ItemSend event function defined in the manifest.xml is called twice when sending. This only happens in the browser, where "the item is popped out to its own browser window or tab in order to complete validation and other processing", see https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=classic.

The function defined for the ItemSend event is called from the original browser window and the popup simultaneously.

## Your Environment

* Platform: Office on the web
* Host: Outlook
* Office version number: Office 365 online
* Browser (if using Office on the web): Tested with Firefox, Chrome
 
## Steps to reproduce
Can be reproduces using the Contoso example project:
https://github.com/OfficeDev/Outlook-Add-in-On-Send

**Comment by exextoc** [comment]
@svlc1 We are unfortunately not able to repro this issue at our end. It is by design that we trigger the on-Send function twice for validation and other processing. 

Can you please elaborate on your use case of onSend to understand the problem better? Are you validating every time an event is created? And, it will be good if you can share a hosted manifest of your use-case so that we can debug the issue.

**Comment by svlc1** [comment]
We use the event to send a non-idempotent request to our server. As a result, one of the two requests now goes wrong. Depending on which event finishes first the result is now event.completed({ allowEvent: false }) or event.completed({ allowEvent: true }).

**Comment by exextoc** [comment]
We are not able to repro the issue at our end. We debugged using contoso add-in and the function validateSubjectAndCC gets called only once. Also the add-in works perfectly fine in main and popout window both. Can you please share a repro video or a test account where the issue is reproable to help us understand more on this issue.
