### ISSUE TITLE
file.getSliceAsync download a pdf with this.print(true) javascript in it

### ISSUE THREAD

**Issue by laurensmartz** [OfficeDev/office-js#2390]
[Enter feedback here]
I use file.getSliceAsync api to convert a office file to pdf.

I can convert the file succss, but when I download it, the pdf with a js this.print(true) in it, and my pdf editor auto open the print dialog when I open the converted pdf. This is not happen in Word but in Excel and PPT, the js in pdf is below:

//-------------------------------------------------------------
//-----------------Do not edit the XML tags--------------------
//-------------------------------------------------------------

//<Document-Level>
//<ACRO_source>0</ACRO_source>
//<ACRO_script>
//
this.print(true)
//</ACRO_script>
//</Document-Level>

How can I remove the print js?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19725696-ef74-1668-5a3e-8bc2bfef81d8
* Version Independent ID: 53436d1d-c281-edfe-d128-6609e62600a1
* Content: [Office.File interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.file?view=common-js-preview#office-office-file-getsliceasync-member(1))
* Content Source: [docs/docs-ref-autogen/office/office/office.file.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.file.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by guliums** [comment]
Hi @laurensmartz , Thank you for taking the time to report an issue. I tried this API on Excel win32 build 14827 and open the pdf using Adobe Acrobat Pro, I didn't see the javascript script. Could you share more details about the script you are using to download the pdf file and also the excel version you are using when met this issue? Thanks very much.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior


## Current behavior



## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)



1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context



## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
