### ISSUE TITLE
[New Outlook for Mac] `displayNewAppointmentForm()` creates meeting by default for November 2032

### ISSUE THREAD

**Issue by balazserdeszlogmein** [OfficeDev/office-js#2393]
Running this single line of code will reproduce the issue:
```
Office.context.mailbox.displayNewAppointmentForm({ } as Office.AppointmentForm);
```

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: New Outlook for Mac
* Host [Excel, Word, PowerPoint, etc.]: New Outlook for Mac
* Office version number: 16.57 (22011101)
* Operating System: MacOS Big Sur 11.6
* Browser (if using Office on the web): -
 
## Expected behavior
Running this line of code:
```
Office.context.mailbox.displayNewAppointmentForm({ } as Office.AppointmentForm);
```
creates a meeting just like Outlook creates one when I click "New Appointment" in the Email Tab.

## Current behavior
A weird meeting is created for November 2032:
![Screen Shot 2022-01-27 at 16 57 14](https://user-images.githubusercontent.com/69678560/151395262-bb523b8c-c65a-4320-b3e9-f68ce368ad60.png)

**It is also important to mention that setting the `start` or `end` properties have no effect whatsoever on the displayed date.**

## Steps to reproduce

1. Just press the run button on the ScriptLab Gist I attached.

## Link to live example(s)
ScriptLab Gist: https://gist.github.com/balazserdeszlogmein/b6e64523eb5b0055adf7cc93c8263d03

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding displayNewAppointmentForm(). We are able to reproduce this issue internally. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by luketowell** [comment]
Hi, are there any updates on this issue?

I have created a plugin and I am able to create the appointment using the displayNewAppointmentFormAsync method however as is stated above I receive a date of 17/11/2032 instead of the current date which is correctly displayed in the console. 

Please find screen shots below: 
Code:
```
const createMeeting = () => {
    const now = new Date();
    const end = new Date();
    end.setHours(now.getHours() + 1);
    const start = Office.context.mailbox.convertToLocalClientTime(now);
    const endUtc = Office.context.mailbox.convertToLocalClientTime(end);

    console.log(`start: ${JSON.stringify(start)}`);
    console.log(`end:`, endUtc);
    console.log(`start UTC client time : `, Office.context.mailbox.convertToUtcClientTime(start));
    console.log(`end UTC client time : `, Office.context.mailbox.convertToUtcClientTime(endUtc));
    Office.context.mailbox.displayNewAppointmentForm({
      subject: 'new appointment',
      body: generateBody({ meetingUrl: 'https://www.google.com' }),
      start: Office.context.mailbox.convertToUtcClientTime(start),
      end: Office.context.mailbox.convertToUtcClientTime(endUtc),
      requiredAttendees: [],
      optionalAttendees: [],
      location: 'online appointment',
      resources: [],
    });
  };
```
Created Outlook Appointment: 
<img width="920" alt="Screenshot 2022-09-07 at 16 28 03" src="https://user-images.githubusercontent.com/29888913/188918288-8c374636-9936-478c-93c2-6f3d8eff0a8e.png">

Correct Console logs of time: 

<img width="740" alt="Screenshot 2022-09-07 at 16 28 22" src="https://user-images.githubusercontent.com/29888913/188918436-e6c26a2a-aaa1-4bd4-a2e5-91f39680c68a.png">

Any update that you can provide would be appreciated.

**Comment by exextoc** [comment]
This issue has been fixed.
