### ISSUE TITLE
Outlook Online: setSignatureAsync - sometimes signature is placed at cursor position 

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#2432]
* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook for web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows
* Browser: Chrome Version 98.0.4758.82 (Official Build) (64-bit)
 
## Expected behavior
signature should be inserted at the end.

## Current behavior
signature is inserted at the cursor position.

## Steps to reproduce

This is just one of the way I can reproduce the issue
1. Create a message compose
2. Start adding some content in the mail body (better to have a line break).
3. Place the cursor at somewhere in the middle.
4. Run the scriptlab taskpane having signature automatically 's been inserted when office is ready.
5. Observe the signature is inserted at the marked cursor

![EMp0nsvHBo](https://user-images.githubusercontent.com/13063615/154240180-5a9699b5-4cc1-49aa-b933-c0fe9b3618cf.gif)

## Link to live example(s)
https://gist.github.com/jasonhieu1905/1682b4abfae8fc6c740acf5b414f9508

## Context
This issue does not meet in outlook app for windows

**Comment by exextoc** [comment]
@jasonhieu1905 I tried on my local set-up and am not able to repro the issue. So, we will like to understand a few things:
1. Was this issue always there or you started to see it with some recent build?
2. Can you try a different browser and see if the problem is still there?

**Comment by jasonhieu1905** [comment]
@exextoc : I could reproduce on MS Edge too (Version 98.0.1108.55 (Official build) (64-bit). 
Basically with our addin's context:
 - new message compose
 - type something in the body - with having multiple line breaks.
 - click somewhere in middle of the body
 - click more apps -> Script Lab -> run (make sure the editor with code is ready before)
 - observe the result (do not click somewhere else)
 - signature is inserted in the middle
 
![sHB7I3Nj6a](https://user-images.githubusercontent.com/13063615/154728837-b65a0542-da54-400d-bfff-d160a4550642.gif)

**Comment by kinkoazc** [comment]
Hello. I've also encountered this issue. I've created a repro setup around the `outlook-set-signature` sample, at https://github.com/kinkoazc/Office-Add-in-samples/tree/main/Samples/outlook-set-signature (you can work with either the remote or local install manifest). Here is how this issue looks in my case:
![2432-repro](https://user-images.githubusercontent.com/2164590/154747078-490a3900-b117-41c5-a008-73227dbe19b9.gif)
This appears when auto-reinserting the signature on recipient change.
I've investigated this issue up to some point. It could be caused by the signature insertion option sent to `roosterjs-editor-core`(currently option 3 is used, equating to insertion on `SelectionStart`, see https://microsoft.github.io/roosterjs/index.html#api/insertContent demo) and some specific runtime sequence/conditions in `office-js`(or `owa.Addins.js`).
Not sure how changing the insertion option(e.g. to `End`) would play out in case of reply/forward messages though.

**Comment by exextoc** [comment]
Thanks for reporting this issue . It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by fedeisas** [comment]
@exextoc is there a timeline for this issue to share at this point? Thanks.

**Comment by exextoc** [comment]
@fedeisas @jasonhieu1905 This issue has been fixed. Please let us know if it still happens.
