### ISSUE TITLE
(ContentControl):  insertFileFromBase64 to table of contents has ItemNotFound ContentControl._OnAccess error.

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#2448]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Version 2201 Build 16.0.14827.20198
* Operating System: Windows
 
## Expected behavior
content control insert file from base 64 should have no error.

## Current behavior
exception: ItemNotFound ContentControl._OnAccess

## Steps to reproduce
1. create content control
2. insert Table of Contents inside the content control created in step 1.
3. insertFileFromBase64 into the content control

## Link to live example(s)
https://gist.github.com/jasonhieu1905/f1144aff931a90e5cd3c91e9cd57ce84
![96v8ZheN92](https://user-images.githubusercontent.com/13063615/155256686-5b7bd78b-b2bd-4e30-aa84-45664660d9a6.gif)

## Context
- It might happens for others api like insertText, insertHtml.
- It does not throw the issue if table or text are inside the content control.

## Useful logs
![image](https://user-images.githubusercontent.com/13063615/155256615-09e661bd-6022-4215-a425-5d10401566e6.png)

**Comment by RuizhiSunMS** [comment]
@yihuax , seems another issue in word client api. Please have a look.

**Comment by yihuax-msft** [comment]
This is by design.

After you inserted TOC, there are two content controls: the original content control, and the TOC's content control.

You code inserts something into both content controls. But, after the stuff is inserted into the first content control, the nested second content control has been replaced and it no longer exists.

If you change the second parameter "**Replace**" in the line:
        **cc.insertFileFromBase64(base64, "Replace");**
with "**End**":
        **cc.insertFileFromBase64(base64, "End");**
you will be able to see it clearly.
Thanks.

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
