### ISSUE TITLE
Forwarded message loads custom properties from previous message

### ISSUE THREAD

**Issue by milankonir** [OfficeDev/office-js#2456]
# Provide required information needed to triage your issue

According to documentation, the `loadCustomPropertiesAsync` should return custom properties on per app / per item basis. This is not true when you forward a message in Outlook for Windows - the `loadCustomPropertiesAsync` will return custom properties from the forwarded message.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2201 Build 16.0.14827.20180
* Operating System: Windows 10
* Browser (if using Office on the web): N/A
 
## Expected behavior

Custom properties of new message should be empty.

## Current behavior

Custom properties of the new message has data from the forwarded message.

## Steps to reproduce
1. Compose item
2. Set custom properties
3. Send item
4. View item in the sent folder
5. Forward the message
6. The new message has custom properties from the previous message

## Link to live example(s)

Public gist for Script lab: https://gist.github.com/milankonir/27882ecf6613dfc69c1b8002908c391e

# Provide additional details

This can only be reproduced in Outlook for Windows, it works as expected in Outlook for Mac and OWA.

## Context

We need to have custom properties isolated per message item

## Useful logs

Repro video: https://share.getcloudapp.com/Z4u1Qggx

**Comment by exextoc** [comment]
Could you elaborate on your scenario for requiring custom properties to not be included on forwarded messages?

**Comment by milankonir** [comment]
We use the custom properties to store various metadata that are processed by our backend services once the email is sent. Copying such metadata on top of the forwarded message can cause all sorts of problems (duplicate processing, incosistencies...).

To give you an example, we store a follow steps in the custom properties that instruct backend services to perform certain chain of actions once the email is sent. It does not mean the same set of steps should also be performed when you forward the email.

**Comment by exextoc** [comment]
Thanks for your providing your scenario here. Will `internet headers` work for your scenario, as an alternative to `Custom Properties`?

**Comment by milankonir** [comment]
The `custom properties` data are private to our add-in / exchange user, while the `internet headers` can be publicly accessed by anyone including email recipients. That's something we would rather avoid.

**Comment by exextoc** [comment]
Thanks for the extra information. I'm not sure what data you are storing in `Custom Properties`, however, we don't recommend storing private/sensitive information there. Moreover, `Custom Properties` are also publicly accessible but not as easily as `Internet Headers`. `Custom Properties` can be accessed via EWS/REST by other add-ins or any client that leverages either protocol.

**Comment by milankonir** [comment]
We don't store any PII or otherwise sensitive data as we are aware that as long as you have an access to the exchange account and know the add-in id, you can access them. Unlike internet headers, they are not visible to the recipient, correct?

Of course, another concern with migrating to internet headers is the require rewrite of the add-in and back end processing.

Circling back to the original report, do you consider it a bug? The Mac and OWA clients behave according to the documentation and do not copy custom properties from forwarded message. Is it a problem to fix in the Windows client?

**Comment by exextoc** [comment]
Yes, `Custom Properties` are not visible to the recipient. If no sensitive data is stored in `Custom Properties`, it seems reasonable that `Internet Headers` will be an alternative here. However, there will be a cost in rewriting a bunch of code. I was unaware of this since it wasn't clear whether you were implementing a new feature or had already implemented it.

The individual clients (Windows Outlook, OWA, Mac Outlook) have nuances in their handling of various scenarios. And this falls into that category. Also, forwarding an email from the Sent Items folder is far less common that doing so from your Inbox.

Let me discuss further with the team and get back to you.

**Comment by milankonir** [comment]
Hi, could we please get an update on this? We need to understand the urgency to look into a workaround on our side.

**Comment by JuaneloJuanelo** [comment]
Hello @milankonir, most probably we will not fix this issue because:

1.  this is platform consistent behavior. Meaning the products behave differently and the programmability is a reflection of that.
2. We shipped this behavior since Office 2013 and usually we do not backport fixes. Giving that this would drastically change the semantic of the method it could potentially break folks who are in 2013, 2016, 2019 and 2021, since this is a change in behavior.

so you have a couple of alternatives.

1. you can use internet headers to save your state. they behave as you expect.
2. you can also do a bit more sophisticated handling of the properties. You can identify use our [getComposeType APIs](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-1.10&preserve-view=true#outlook-office-messagecompose-getcomposetypeasync-member(1)) to check if the composition is a new message or is a fwd message. This was released in 1.10. basically you can identify this is a fwd message and remove the custom properties if so needed. as well as potentially saving other properties to identify if the settings were created during new or fwd messages.
3.  you can also use smart alerts (in conjunction with above) to do this processing when the user sends the email.
