### ISSUE TITLE
Office Version reported as 0.0.0.0

### ISSUE THREAD

**Issue by vitalykuvaev** [OfficeDev/office-js#2470]
## Issue Description

When running an Excel Addin in Office Online, `Office.context.diagnostics.version` is always set to '0.0.0.0'.

We are logging issues our customers experience and including platform and version information in the log data. We would definitely like to log the actual build version/number as reported in the About section.

## Environment

* Platform: Office Online
* Host: Excel
* Office version number: _16.0.15103.35054_
* Operating System: any
* Browser: Chrome and Safari
 
## Expected behavior

`Office.context.diagnostics.version` is set to actual build number.

## Current behavior

`Office.context.diagnostics.version` is set to '0.0.0.0'.

## Steps to reproduce

`Office.onReady(() => { console.log(Office.context.diagnostics.version) });`

## Additional details

This issue has been dismissed as "By Design" [here](https://github.com/OfficeDev/office-js/issues/1602) previously, but we would certainly expect that the version is set to the same build numer as reported in About section.

## Context

We are logging Office platform and version on logged exceptions. The version is needed to trace back the issue and possibly contact Microsoft tech support which requires Office build number.

**Comment by RuizhiSunMS** [comment]
Hello @vitalykuvaev 
As mentioned, this return value is by-designed and your issue is nearly a feature request. To better in helping you, we suggest you to Microsoft Tech Community New Ideas forum for the Microsoft 365 Developer Platform with the link of https://docs.microsoft.com/answers/products/m365 to submit new feature request (or might find that request has been submitted yet). 
By this way could let other customers and us know it.
Thanks.

**Comment by ChienHo** [comment]
This issue still occurs, please update this issue.
![image](https://github.com/OfficeDev/office-js/assets/30323038/a4117169-532d-477b-8211-b3f33b30ef6c)
