### ISSUE TITLE
Word add-in does not trigger DocumentSelectionChanged event when creating a new table

### ISSUE THREAD

**Issue by egloff** [OfficeDev/office-js#2473]
## Your Environment
* Platform: PC desktop
* Host: Word
* Office version number: Microsoft Word for Microsoft 365 MSO (Version 2201 Build 16.0.14827.20180) 32-bit 
* Operating System: Microsoft Windows 10 Enterprise (Version 10.0.19043 Build 19043)
 
## Expected behavior
Inserting a table should trigger a selection changed event.

## Current behavior
There is no event when creating a new table. Before creating the table the selection was for example in the body and after that the selection is in the first cell of the new table.

## Steps to reproduce
1. Attach the event listener to the document: `Office.context.document.addHandlerAsync(Office.EventType.DocumentSelectionChanged, eventArgs => this._onDocumentSelectionChanged(eventArgs));`
2. Insert a table via Insert -> Table

## Link to live example(s)
https://gist.github.com/egloff/2029b40f6a675192dd1dcd1f799d6b0a

## Context
Our add-in changes behaviour depending on the selection but it currently seems not to be possible to get a notification/event when a new table is inserted.

**Comment by RuizhiSunMS** [comment]
@yihuax take a look please :)

**Comment by grangeryy** [comment]
Hey @yihuax, could you help to take a look on this issue? THX!

**Comment by yihuax-msft** [comment]
When inserting a table, I believe your cursor is at the beginning of a paragraph, right? 

Let's say You have two paragraphs as:
AAA[EOP]
BBB[EOP]
where [EOP] is the end-of-paragraph mark.

Suppose your cursor is at the beginning of the second paragraph, that is, the cursor is right before BBB. So, your cursor is now at location 4 (after 'A', 'A', 'A', '[EOP]'). After your table is inserted, the cursor is at the beginning of the first cell, thus it is still at location 4: No move! Therefore, the selection changed event is not fired. This is by design.

If your cursor is NOT at beginning of a paragraph, then, the event should be fired, because the cursor moved forward 1 character due to the insertion of an extra [EOP] right before the table. In this scenario, if the event is NOT fired, please let us know.

Thanks!

**Comment by egloff** [comment]
Hi @yihuax 
Thanks for your reply.
Indeed it is exactly as you have described it, if I am NOT at the beginning of a paragraph everything works as expected. This is not necessarily lucid, but from a technical point of view I can understand you.
But for our add-in (we are currently migrating from an existing VSTO add-in) we need to know, if the cursor location is in a table or not. Is there another way (another listener) we can use (except for polling every few (milli)seconds and check the selection)?

**Comment by yihuax-msft** [comment]
Thanks for the information. You are right, for pulling, it is easy with getSelection().parentBody.type or getSelection().parentTableCellOrNullObject or getSelection().parentTableOrNullObject. But for event, right now we don't have one if the cursor is at the beginning of a paragraph before inserting a table.

I guess that inserting an empty table is meaningless, so maybe you can postpone your handling of the table until user types something into the table? At that time you will get selectionChanged event.

**Comment by egloff** [comment]
Thanks for your response, its not completely "meaningless" in our case 😉 
Because our add-in can insert different content if the cursor is in a table or not.
But if this is not possible we have to work around this issue somehow.
