### ISSUE TITLE
Cell is not auto adjusting in new workbook created using createWorkbook() in office online.

### ISSUE THREAD

**Issue by libjosep** [OfficeDev/office-js#2488]
I am creating a new workbook using `Excel.createWorkbook()`. The issue that I am facing here is that in the newly created workbook, the cells are not properly auto-adjusting. This happens only in the online version. It works fine on Mac and Excel desktop.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:  Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 365 online
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

The cells in the newly created workbook should auto adjust its height and width like how it is happening in Excel desktop and Mac.

## Current behavior

The cell height/width in the newly created workbook are not auto adjusted.

## Steps to reproduce

1. Run the attached scriptlab snippet in Excel online.
2. Click on Create Workbook button.
3. Go to newly created workbook.
4. You can see that the cell with text "Table of Contents" is not auto adjusted.

## Link to live example(s)

1. https://gist.github.com/libjosep/7ec579a20a417e061e92108df5719335

## Useful logs

- [x] Screenshots
- Issue in online version]
![AdjustCell_online](https://user-images.githubusercontent.com/28481997/159473088-6549002f-671c-426e-99cf-45f99150b213.png)
- Excel desktop version
-![AdjustCell_desktop](https://user-images.githubusercontent.com/28481997/159473113-9894c5ad-4d7c-47f9-85be-e29234db2f46.png)

**Comment by davidchesnut** [comment]
Hi @libjosep, thanks for letting us know about this issue.

@grangeryy could you please look into this issue?

Thanks!
David

**Comment by grangeryy** [comment]
Adding @RuizhiSunMS, @lushanbo

**Comment by RuizhiSunMS** [comment]
Hello @davidchesnut , thanks for your report.
Here are some questions about details we want to know:
1. Can you share your original excel file if convenient?
2. How did you get the base64 content string?
3. Have you ever tried to upload your original file and see if there is the render issue instead of using one created by basec64 string?
Thanks.

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.

**Comment by libjosep** [comment]
@RuizhiSunMS I get the base64 from an API. I don't have the actual workbook.

**Comment by libjosep** [comment]
Any updates on this

**Comment by RuizhiSunMS** [comment]
@libjosep is this issue still blocking u? Our colleague tried with your gist and found everything ok recently.

**Comment by libjosep** [comment]
I can still see the issue with the gist attached.

**Comment by ruijiaMS** [comment]
Hi @libjosep,
This api does not autofit for Excel Online is because of performance reasons and excel online only support baseline in this scenario. What's more, the desktop Excel support autofit after creating a new workbook but the Excel online does not support, 
I would like to provide a workaround if you expect autofit after the new workbook comes up, you can do a row autofit for the content from UI (Home -> Format(drop-down box) ->Auto Fit Row Height). Hopefully this helped!
