### ISSUE TITLE
Open 2 different taskpane using office.js

### ISSUE THREAD

**Issue by gopinathshiva** [OfficeDev/office-js#2504]
Multiple taskpane with different id's can be opened using manifest.xml.

Would like to know if same is achievable with Office.js, right now Office.js only offers below method
Office.addin.showAsTaskpane()

will it be possible to open a new taskpane with existing taskpane side by side using Office.js ?

**Comment by nkkinariwala** [comment]
@AbidRahman-MSFT  - Is it something you can help with?

**Comment by AbidRahman-MSFT** [comment]
Hey @gopinathshiva -

Thanks for the question. Currently this is not possible. In order to use the `Office.addin.showAsTaskpane()` and `Office.addin.hide()` methods, your add-in must use Shared Runtime. As noted in our [documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime#multiple-task-panes), Shared Runtime only supports the use of a single task pane.

Thanks,
Abid
