### ISSUE TITLE
RGBA stopped working when inserting html on outlook desktop?

### ISSUE THREAD

**Issue by pietrofxq** [OfficeDev/office-js#2511]
# Provide required information needed to triage your issue

We are developing an add-in that inserts custom HTML in the email body with custom formatted links. This seemed to work fine this week until yesterday, where the HTML got completely broken. Upon further debugging, I found out some CSS properties are not working anymore in outlook desktop (windows and mac)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Mac desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2202
 
## Expected behavior
```
Office.context.mailbox.item.body.setSelectedDataAsync(
    `<p style='color: rgba(255,85,0, 1)'>Test</p>`,
    {
      coercionType: Office.CoercionType.Html,
    },
    asyncResult => {
      event.completed()
    }
  )
```

Should insert colored text

## Current behavior
color style is not applied. Fixed when changing `rgba(255,85,0, 1)` to `rgb(255,85,0)`

## Steps to reproduce
Run this function in a command

```
Office.context.mailbox.item.body.setSelectedDataAsync(
    `<p style='color: rgba(255,85,0, 1)'>Test</p>`,
    {
      coercionType: Office.CoercionType.Html,
    },
    asyncResult => {
      event.completed()
    }
  )
```

# Provide additional details
Everything works fine on outlook web

## Context

Our add-in inserts a custom like in the email body. Our design system library uses rgba colors and it works on Web
![image](https://user-images.githubusercontent.com/6238029/161276411-641edf7b-8440-4e14-8ff0-f323930baf30.png)

**Comment by exextoc** [comment]
We can reproduce this issue and we are looking into this.

**Comment by exextoc** [comment]
Looking a bit further into this, this problem seems to repro on older versions of Desktop Clients (At least back to Outlook 2016, and older versions of Mac Desktop Client). It may be something that Word does not support, though we will have to verify. (To clarify Word is used as the HTML renderer in Desktop Versions of Outlook)

You mentioned that it was working in older versions of Outlook, do you know the specific desktop client version that supported it?

UPDATE: Checking with other internal teams, this looks the alpha channel is not supported in the desktop clients. If you have a specific outlook build that you can repro this WORKING, we could investigate more.
