### ISSUE TITLE
Can't install the beta version using npm

### ISSUE THREAD

**Issue by sroy9** [OfficeDev/office-js#2560]
`npm install @microsoft/office-js@beta --save` gives me an error 
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @microsoft/office-js@beta.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by AlexJerabek** [comment]
Hi @sroy9,

To access the preview APIs for Office.js through NPM, target [@microsoft/office-js-preview](https://www.npmjs.com/package/@types/office-js-preview). That said, we do recommend referencing the Office CDN, instead of NPM. This ensures you always have the latest version that is the most secure and reliable experience. More information on referencing the CDN can be found here: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/understanding-the-javascript-api-for-office

Since the behavior described in the original issue is expected, I'm going to close this. If you have any more questions or have issues with the preview APIs in the CDN, please create a new issue or comment on this thread. Thanks!
