### ISSUE TITLE
Text highlighting resets to default yellow color even if you change it in word

### ISSUE THREAD

**Issue by Keertan22** [OfficeDev/office-js#2562]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: M365
* Operating System: ______
* Browser (if using Office on the web): Chrome
 
## Expected behavior
 When you select any color for highlighting it should remain consistent for next highlighting operation and should not reset to default. 

## Current behavior
When we change default color from yellow to any other it works fine but for second highlighting operation, even though "highlight" icon shows selected color, applied action is of yellow only. 

## Steps to reproduce

1.Select "Highlight" icon in Home Section and change color to Cyan.
2.Now highlight any text, it will be highlighted with Cyan color.
3.Now select different text and highlight again by clicking on "Highlight" icon but highlighted color will be yellow.
![Word Bug](https://user-images.githubusercontent.com/104830614/166436761-265475f8-7be1-4d99-a124-9f2b1a1287f9.png)

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by AlexJerabek** [comment]
Hi @Keertan22,

This GitHub repo is for reporting issues with the Office JavaScript APIs and [Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/?view=word-js-preview). Please correct me if I'm wrong, but this sounds like an issue with the user-interface of Word on the web. To report issues with the web application, please select **Help** > **Feedback** from the ribbon.
![image](https://user-images.githubusercontent.com/38896772/166488505-55752187-209c-4d94-bd16-fbd16516ec2f.png)

Doing so lets the application capture logs and helps the product better understand why the highlighting color is changing, so they can make a fix.

Since this issue is not about Office.js, I'm going to close the issue. Please reply to the thread if I have misunderstood something, and I'll reopen it.
