### ISSUE TITLE
Debugger not working for On-send Event

### ISSUE THREAD

**Issue by RaviKumar1096** [OfficeDev/office-js#2573]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: _PC desktop____
* Host [Excel, Word, PowerPoint, etc.]: ____Outlook__
* Office version number: _____16.0.15128.20158_
* Operating System: ____Windows__
* Browser (if using Office on the web): ______
 
## Expected behavior

When I attached a Debugger with On-send event i should be able to debug my code

## Current behavior

When I attached a Debugger for Outlook Events like OnNewMessageCompose and ItemSend the Debugger works for OnNewMessageCompose but not working for ItemSend. 

## Steps to reproduce

1. ______Create a event in manifest for itemsend
2. ______attached a Debugger with following steps provide in the Microsoft documentation
3. ______run your Application (npm start),open outlook and try to send something

## Link to live example(s)

1. [______](url)
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

i attached a function with itemsend event and tries to debug that but won't be able to do that with this bug.

## Useful logs

https://user-images.githubusercontent.com/66593878/167557540-c994dd0f-77ba-4d7a-af8c-a599fb978d60.mp4

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by timwan10** [comment]
Thanks for supplying the video, it greatly helps to figure out what is happening. 

In your manifest file you are using the old ItemSend event, that uses WebView and not the bundle.js. Those requests will go to the HTML function file. In the manifest. 

Instead you should be using the launch event lines that you have commented out. (OnMessageSend and OnAppointmentSend)

https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough

```
          <!-- Enable launching the add-in on the included event. -->
          <ExtensionPoint xsi:type="LaunchEvent">
            <LaunchEvents>
              <LaunchEvent Type="OnMessageSend" FunctionName="onMessageSendHandler" SendMode="PromptUser" />
            </LaunchEvents>
            <!-- Identifies the runtime to be used (also referenced by the Runtime element). -->
            <SourceLocation resid="WebViewRuntime.Url"/>
          </ExtensionPoint>
```

**Comment by RaviKumar1096** [comment]
@timwan10  Thank you for replying ,
Well I tried using this Event as well I am attaching a video also, even with this the debugger won't hit my function inside the bundle.js

https://user-images.githubusercontent.com/66593878/168422872-13c7788a-1ebf-441c-a028-08c38e0e29d6.mp4

s

**Comment by timwan10** [comment]
From your video it looks like the On Send launch event is *working* but you can't debug it? (please confirm) 

Item Send is actually somewhat special cased from the other Launch Events (like OnNewMessageCompose). The issue is that ItemSend actually launches a new instance of the process, and needs to be debugged separately. (evidenced by the fact that a SECOND dialog pops up, when you hit send). 

If you could try either attaching AGAIN after the second dialog pops up. (after you hit send). 
OR try removing the OnNewMessageCompose from your manifest. Then attach when the dialog pops up (after you hit send)

**Comment by RaviKumar1096** [comment]
Well I tried the way you said, First I tried it with only the ItemSend event and this time debugger hits my function also I tried the launching another debugger instance (after the OnNewMessageCompose event) and also this time debugger hits the function
But the Catch here is when I tried to change my function definition with my actual code the same problem occurs [debugger hits for OnNewMessageCompose but not on ItemSend]. I am sharing two videos please take a look. If you feel anything wrong with my function definition I can share the code with you as well. but the only point is debugger should hit my function regardless of the function definition only then I can find out what is wrong with my function definition.


https://user-images.githubusercontent.com/66593878/168964124-6a47596e-e86c-4370-aee8-f50205e6f9d6.mp4

https://user-images.githubusercontent.com/66593878/168964272-a20d2cec-5cf9-40d5-9832-06b309fe1bf1.mp4

**Comment by timwan10** [comment]
What could be happening here is that the bundle downloaded isn't updated? Some things you could try.

1) make sure you've uploaded your manifest with the change to the function name, and make sure outlook is using it. (You can test by changing a string in the ribbon, and making sure that it actually changed) 

2) Make sure that Outlook has the latest bundle. (usually by rebooting Outlook).

You can verify Outlook has your latest file, as Outlook caches them on the disk. 
The bundle.js will be at: 

`C:\Users\[User Name]\AppData\Local\microsoft\office\16.0\wef\{175BAEB9-7BE5-47E3-B4EE-4C8770746D1F}\lhToxVf3k2e5ZGfUjAGIwA==\Javascript`

The Manifest that is being used is at: 

`C:\Users\[user name]\AppData\Local\microsoft\office\16.0\wef\{175BAEB9-7BE5-47E3-B4EE-4C8770746D1F}\lhToxVf3k2e5ZGfUjAGIwA==\Manifests`

Replace [User Name] with the windows user. The GUID and the encoding will be different on your machine. There should be one per Outlook profile. Hopefully you just have one. If you can't figure out which one is the one that you are interested in. You can delete (or just move if you're worried) the Wef folder, then reboot Outlook so that Outlook will recreate the files. 

Deleting the WEF folder can also force Outlook to refresh everything on boot as well.

**Comment by RaviKumar1096** [comment]
I took the step that you mention and there is no change add-in still behave the same, also deleted the WEF folder but nothing impacted.
![image](https://user-images.githubusercontent.com/66593878/169826842-7a01fe85-6b92-49fe-aa03-2959cbfdce7d.png)

**Comment by timwan10** [comment]
I'm not sure I completely understand what the issue is right now. So the Breakpoint WAS being hit, but then you changed the name of your function and it stopped being hit? Does it start working again if you change the name back?

(i.e. what is the difference between when your code hits the breakpoint and when it doesn't?) 

When you don't hit the breakpoint, does the Add-in work anyway?

**Comment by RaviKumar1096** [comment]
ok here are some scenarios
1. when there is an on-compose and on-send event 
debugger hit in the on-compose event function
but debugger won't hit for on-send also implementation of that function not working (means add-in won't behave like that function).
2. when there is an only on-send event
debugger hit the function also add-in behave like that function.

**Comment by rexweston** [comment]
Hi Ravi & Tim,

Please keep working diligently on this until you have success – it is very important to me that we get this resolved.

Thank you.

**Comment by timwan10** [comment]
Are you saying that if you have a OnNewMessageCompose and a OnMessageSend event, then the OnMessageSend portion doesn't run at all? (regardless of debugger)? (this is a bit confusing because earlier you said they were _working_ but the debugger breakpoints just weren't being hit) 

If so that would be a bug, but it could also be something is configured incorrectly in your manifest or js file. If you can repro with a small add-in and can upload the files somewhere (in a private github) that may be helpful.

**Comment by RaviKumar1096** [comment]
hey, Timwan10 sorry I think I confused you please ignore my last reply this time actually, I restarted my system and deleted the WEF folder that thing was working for me debug point hits both the event and implementation also work but after that, a pop comes up sending you a screenshot of that and after that, the same behavior again happens debugger only hit for onCompose Event not hitting for Onsend (but the implementation is working for both the function). I again tried deleting the WEF folder and restarting my system again the same scenario happens. but now I am unable to delete the WEF folder due to some permission issues
![Screenshot 2022-05-26 185510](https://user-images.githubusercontent.com/66593878/170501170-5522a090-1468-47da-ac31-5c59f666ee2c.png)
![Screenshot 2022-05-26 192937](https://user-images.githubusercontent.com/66593878/170502841-4186961b-b314-4487-85ca-0fd160a18934.png)
t

**Comment by RaviKumar1096** [comment]
@timwan10  any update?

**Comment by rexweston** [comment]
@timwan10 - Hi Tim, please help Ravi with this as promptly as you can - this project is very important to me and is considerably overdue at this time.  Anything that can be done to speed up the resolution would be greatly appreciated.  Thank you.

**Comment by timwan10** [comment]
I'm not sure I have more to suggest here. 

The msosdfsb.exe crash is bad, but outside my area of expertise. Is that reproducible when you don't attach the debugger? It may be that webview2 should be uninstalled/reinstalled to see if it helps fix it. 

As mentioned the WEF folder is only relevant in that it contains the bundle.js that is downloaded from your webserver. You can check it at: 

C:\Users\[User Name]\AppData\Local\microsoft\office\16.0\wef\{175BAEB9-7BE5-47E3-B4EE-4C8770746D1F}\lhToxVf3k2e5ZGfUjAGIwA==\Javascript

(the GUIDs and Encoding there can be unique). I only mention it because you said that when you changed the name of your function, that you stopped hitting your breakpoints? It was only meant as a way to make sure that outlook was loading the latest files from your webserver. 

Both the OnNewMessageCompose and OnMessageSend instances are loaded in SEPARATE sandboxes that need to be debugged separately. It sounds like you can hit your breakpoints. If you can't hit them, maybe you are attaching it to the wrong process. 

If there are errors in the actual bundle.js file that could also prevent debuggers from hitting breakpoints. (but I think this is unlikely, if the feature is working normally)

**Comment by rexweston** [comment]
Thanks Tim.  Ravi, I hope this helps - I really need to get this project finished soon.  Thank you.

**Comment by RaviKumar1096** [comment]
@timwan10 yes, when I don't attach the debugger the msosdfsb.exe error won't come, and can you please tell me how can I uninstall/reinstall the webview2. I didn't get webview2 and I am sure that there is no error in my bundle.js because the code in both launchevent.js(which is for handling the event for the desktop version )and bundle.js are the same and while running code the server won't throw any error. And one more thing can we call any outside function(any utility function or any API call that returns a promise) inside the launchvent.js file? because when I do I get some errors and declare them in the same file that was working

**Comment by rexweston** [comment]
@timwan10 Hi Tim - please help Ravi with this as soon as possible.  He's very close to the completion of an important project for me that many people are waiting on, and this is the only thing that is holding him up.  Thank you.

**Comment by timwan10** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

I believe any function you want to call must be in the launchEvent.js file.

Keep in mind that if there may be runtime JS errors that you are hitting that could cause issues. I'm still confused as to your problem. the OnMessageSend event is working when the debugger is not attached? So do you just need to attach the debugger to test/verify things? Or is there a specific part of your OnMessageSend handler that is not working?

Do you have any code snippets as to the parts that aren't working?

**Comment by RaviKumar1096** [comment]
hey @timwan10  yes my onMessageSend event is working (means the triggered function that is working but I need to verify a few things in that function because the output that I am expecting is not coming as expected.

setubject is the function that is triggered when event fires and in this function getAllRecipients is the function that I think isn't working as expected


```
async function setSubject(event) {
     var isInDOmain =  await getAllRecipients();
    getSignature().then(async (data) => {
      composeSignature(data.data, isInDOmain,event)
    });
  }

function getAllRecipients() {

    var CheckDOmain=[];
    let isInDOmain;
  
    var toRecipients, ccRecipients, bccRecipients;
    if (Office.context.mailbox.item.itemType == Office.MailboxEnums.ItemType.Appointment) {
      toRecipients = Office.context.mailbox.item.requiredAttendees;
      ccRecipients = Office.context.mailbox.item.optionalAttendees;
    }
    else {
      toRecipients = Office.context.mailbox.item.to;
      ccRecipients = Office.context.mailbox.item.cc;
      bccRecipients = Office.context.mailbox.item.bcc;
    }
  
        CheckDOmain.push(getAllCC(toRecipients));//null//true//false
        if(CheckDOmain[0] || CheckDOmain[0]===null)
        {
          CheckDOmain.push(getToCC(ccRecipients));//null//true//false
          if(CheckDOmain[1] || CheckDOmain[1]===null)
          { 
            CheckDOmain.push(getBCC(bccRecipients));//null//true//false
            if(CheckDOmain[2] || CheckDOmain[2]===null)
            {
  
            }
          }
        }
        isInDOmain = CheckDOmain.find((ele)=>{
          return ele===false || ele ===true;
        });
        return isInDOmain===undefined?null:isInDOmain;
  }

  function getAllCC(toRecipients) {
   return new Promise((resolve,reject)=>{
      toRecipients.getAsync(async function (asyncResult) {
       if (asyncResult.status == Office.AsyncResultStatus.Failed) {
         reject(asyncResult.error.message);
       }
       else {
         
         // Async call to get to-recipients of the item completed.
         // Display the email addresses of the to-recipients. 
          const CheckDOmain = await displayAddresses(asyncResult);
         resolve(CheckDOmain)   
       }
     });
   })

  }

 function getToCC(ccRecipients){
    return new Promise((resolve,reject)=>{
      ccRecipients.getAsync(async (asyncResult) => {
        if (asyncResult.status == Office.AsyncResultStatus.Failed) {
          reject(asyncResult.error.message);
        }
        else {
          // Async call to get cc-recipients of the item completed.
          // Display the email addresses of the cc-recipients.
         const CheckDOmain = await displayAddresses(asyncResult);
          resolve(CheckDOmain);
        }
      });
    });
  }
  
   function getBCC(bccRecipients){
    return new Promise((resolve,reject)=>{
      bccRecipients.getAsync(async (asyncResult) => {
        if (asyncResult.status == Office.AsyncResultStatus.Failed) {
          reject(asyncResult.error.message);
        }
        else {
          // Async call to get cc-recipients of the item completed.
          // Display the email addresses of the cc-recipients.
         const CheckDOmain = await displayAddresses(asyncResult);
          resolve(CheckDOmain);
        }
      });
    });
  }
function displayAddresses(asyncResult) {
    var IsSameDomain = null;
    var CurrentUserAddress = Office.context.mailbox.userProfile.emailAddress;
    var CurrentUserDomain="metadesignsolutions.co.uk"
    for (var i = 0; i < asyncResult.value.length; i++) {
      var RecpDomain = asyncResult.value[i].emailAddress.split('@')[1];
      if (CurrentUserDomain == RecpDomain) {
        IsSameDomain = true;
      }
      else {
        IsSameDomain = false;
        break;
      }
    }
    return IsSameDomain;
  }
```

**Comment by timwan10** [comment]
this line seems off: CheckDOmain.push(getAllCC(toRecipients));//null//true//false

getAllCC returns a promise. You need to get the result from the promise after it has finished. 

Something like 

```
		getAllCC(toRecipients).then((value) => {
                        // Do actual code you want to do here
			console.log("Promise Result:" + value);
		});
```

Something that may be helpful is installing ScriptLab from the Office Store. And use that to test your JS and making sure it all works from a taskpane before putting it into your ItemSend JS. 

Also this line is never used: var CurrentUserAddress = Office.context.mailbox.userProfile.emailAddress;

But I assume this was a debugging workaround to hardcode metadesignsolutions.co.uk.

**Comment by RaviKumar1096** [comment]
hey @timwan10 ,  do you tag some helpful links around ScriptLab (how to test js using that)? and also can I call an API from launchevent.js

**Comment by timwan10** [comment]
Script lab has some built in samples you can access and work off of: 

![image](https://user-images.githubusercontent.com/17890744/173154659-079ab931-6761-4449-9311-718ea6344747.png)

You cannot call functions from LaunchEvent.js. The idea is that you can use script lab to quickly test code, and get the syntax right. (i.e. I copy pasted your code that you provided, and put it in script lab to quickly diagnose the error). At least with your current example, it's straight forward enough that you should be able to get it working in Script Lab then copy/paste into your launchEvent. 

ScriptLab is just a test playground that lets you experiment against the office.js platform.

**Comment by RaviKumar1096** [comment]
@timwan10  just needs confirmation from your side that we can't call any get/post/update/delete API call from the launch event.js file?

**Comment by timwan10** [comment]
Get and Post are supported. (via Fetch or XHR) See this page: https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch 
Under "Requesting External Data" 

The documentation isn't updated, but if you are hitting CORs errors make sure you add the "well-known" urls so that it can access this. The format of this JSON/file is here. https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/use-sso-in-event-based-activation (under List Allowed Add-ins with a well-known URI)

Note that this document is talking about the SSO, but this also applies to CORS and Fetch/XHR.
