### ISSUE TITLE
What is the account type for Hybrid Exchange Servers?

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#2634]
In your document, there is a list of account values and a description for each.
Just to confirm, Hybrid Exchange Servers are classified as 'office365'?  
Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4058c33c-f16c-fcad-1c4c-38efe69a06a5
* Version Independent ID: 39937c7a-37f8-32a3-6db5-bf7c6d5c0c00
* Content: [Office.UserProfile interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.userprofile?view=outlook-js-1.6#outlook-office-userprofile-accounttype-member)
* Content Source: [docs/docs-ref-autogen/outlook_1_6/outlook/office.userprofile.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook_1_6/outlook/office.userprofile.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by samantharamon** [comment]
Hi @glr0221,

Thank you for your post. The accountType property value returned for user mailboxes in a hybrid Exchange environment will depend on where the mailbox is. If the mailbox is on the on-prem server, the accountType value returned is 'enterprise'. On the other hand, if the mailbox is on Exchange Online, the accountType value returned is 'office365'.

I've created an internal backlog item for our team to clarify this in the documentation (internal item number: 6105421).

**Comment by glr0221** [comment]
Thank you @samantharamon 

As a follow up, do hybrid exchange servers having their mailbox on-prem support the REST-ful APIs? Or just Exchange Web Services   (EWS) API?

I was intending to use the 'accountType'  as criterion to determine whether an environment supports REST/GRAPH. If accountType is 'enterprise' then I would just force my app to use Exchange.  Or is this a flawed logic?

Thanks.

**Comment by samantharamon** [comment]
Because the ability to use REST APIs in hybrid deployments will no longer be supported in March 2023 (see [Use REST APIs to access mailboxes in Exchange hybrid deployments (deprecated)](https://docs.microsoft.com/en-us/graph/hybrid-rest-support)), it is recommended to use Microsoft Graph to work with mailboxes that live on Exchange Online and use EWS for those that are on an on-prem server. With that in mind, I believe your logic should work. This might also provide guidance as you continue to develop your add-in: [The End of the REST API for On-Premises Mailboxes Preview](https://techcommunity.microsoft.com/t5/exchange-team-blog/the-end-of-the-rest-api-for-on-premises-mailboxes-preview/ba-p/3221219).

We also encourage you to visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/office-js-dev.html) or [StackOverflow](https://stackoverflow.com/) to see whether a question you have has already been answered or to post a new question. We have a great community of developers in these forums who are happy to help out.

**Comment by glr0221** [comment]
Thank you for the answers @samantharamon.
They are very much appreciated. 

First, I understand the part that the logic will work once REST is deprecated on March 2023. 
However, as of this time, where REST works with hybrid, what is the best way to determine if the environment FULLY supports REST?  Is checking for Mailbox 1.6 support good enough? 

Moreover, I am in the opinion that the REST APIs will be deprecated by November 2022. But for Hybrid Exchange servers, REST APIs will be deprecated March 2023?  

Thanks.

**Comment by samantharamon** [comment]
No worries at all, @glr0221. I'm clarifying your follow-up questions with our feature crew and will let you know once I hear back.

**Comment by samantharamon** [comment]
Hi @glr0221,

I've updated our documentation on account type values for hybrid Exchange environments in [PR #60764](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60764). I'm still working with the team on getting answers to your queries.

**Comment by samantharamon** [comment]
Hi @glr0221,

Thank you for your patience.

I was able to verify that checking for Mailbox 1.6 support isn't a good indicator for determining whether an environment fully supports REST because the check only returns the set supported by the client, but not the one supported by the server. Instead, you can use the restUrl property to determine whether a server supports REST (see [Office.context.mailbox.restUrl](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox#outlook-office-mailbox-resturl-member) for additional information). If the restUrl returns a value, e.g. https://outlook.office.com, REST is supported. Otherwise, REST isn't supported. Mailboxes hosted on servers running Exchange 2016 and above supports REST.

Regarding REST deprecation dates, you're right that the APIs will be deprecated by November 2022. I'm still waiting to get clarification on what the March 2023 date implies for hybrid Exchange environments. Stay tuned.

**Comment by samantharamon** [comment]
Hi @glr0221,

I've received clarification from the team that the Outlook REST v2.0 APIS will be decommissioned in November 2022 for Exchange Online. All other REST APIs for on-prem servers will then be decommissioned in March 2023.

Should you require further assistance, please do not hesitate to let us know.

**Comment by glr0221** [comment]
Thank you for the informaion @samantharamon . This is very much appreciated.

Moreover, may we also ask how this 'decommissioning' will happen? Assuming an addin is currently running with REST APIs. And then REST gets decommissioned by November 2022. Will the addin start failing in getting the resturl? or the token for rest? 

Thanks again.

**Comment by samantharamon** [comment]
That's a great question, @glr0221. Please be advised that any active add-in using the REST service prior to the November 2022 decommission date will be granted an exception to keep using the service until Office 2019 goes out of support (October 14, 2025). This exception is based on the add-in's ID and applies to both privately released and in-store add-ins. If you're still developing your add-in after the November decommission date, any call to the REST API will fail. If you have an active add-in prior to November and would like to verify its exception, please complete the verification form at https://aka.ms/RESTCheck.

For additional information, please refer to the [Office Add-ins community call](https://www.youtube.com/watch?v=O47gN9P8KAI) and [blog post](https://pnp.github.io/blog/office-add-ins-community-call/office-add-ins-community-call-february-9-2022/).

**Comment by glr0221** [comment]
Hello @samantharamon 

You are a heaven-sent. Thank you so much for being so responsive and accurate on your answers.

I did not know of this exception for existing addins that use the REST APIs. I thank you sincerely for this answer and the additional links that you posted. May I know when was this exception offered? Aside from the blog and the youtube video, which documentation was this exception mentioned as well? I am pretty sure it is not in the REST-Deprecation page.

I was looking into the form to verify ann addin's exception. Is the addin ID in that form referring to the manifest ID element? If so, won't this method of exception be a bit problematic because this ID is a randomly generated sequence.  (https://docs.microsoft.com/en-us/javascript/api/manifest/id?view=common-js-preview)  What if the existing addin has over 500 instances with different IDs? Do we have to list all these 500 IDs down and verify each? 

Thank you again. 

PS : How do I give you feedback for a job well done? I really really am grateful. Thank you again.

**Comment by JuaneloJuanelo** [comment]
Hello @glr0221 , good discussion. We are already following with you offline for this issue. We are going to be using the ID element on the manifest to determine what are those add-ins using REST prior to the decommission date. Each add-in in the store gets its own GUID for an ID automatically. For folks not using the store as deployment model they need to make sure you use the same ID (GUID) going forward.  If you are using different IDs for each customer, then that will be an issue after November. we recommend you use the same ID if possible.   BTW we received like 6 different IDs from your organization, lets validate this offline, our recommended approach is that you stay with a single GUID. 

We announced this exception on February. 

Let me know if you have additional questions, and yes I agree, @samantharamon  is awesome!

**Comment by samantharamon** [comment]
Thanks for clarifying the information about the ID, @JuaneloJuanelo.

@glr0221, regarding the documentation, we will be updating [Use the Outlook REST APIs from an Outlook add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/use-rest-api) in the coming days to include guidance on the exemption. Regarding feedback, no worries at all; I'm happy we were able to help. :)
