### ISSUE TITLE
SupportsPinning for outlook taskpane addins not working on Outlook for Mac

### ISSUE THREAD

**Issue by ksdaniel** [OfficeDev/office-js#2635]
# Provide required information needed to triage your issue

When deploying a taskpane addin that implements the SupportPinning property, "New Outlook for Mac" will not display the pinning option. 

The same solution on Outlook for Windows or the "Old Outlook for Mac" displays the expected pinning option.  

## Your Environment

System Version:	macOS 12.4 (21F79)
Kernel Version:	Darwin 21.5.0
Outlook Version: 16.61 (22050700)

## Expected behavior

The pinning option should be visible for addins that have a taskpane with the "SupportsPinning" option.

## Current behavior

The pinning button is missing from the "New" Outlook Client.

## Steps to reproduce

1. Create a simple Outlook addin that will show a taskpane and add the SupportsPinning option. 

```
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="Taskpane.Url"/>
                    <SupportsPinning>true</SupportsPinning>
                  </Action>
```

2. Sideload the addin and open in the "New" Outlook for Mac client. 

3. The pinning button will be missing. 

## Context

This issue is only visible in the "New" Outlook Client for Mac. The old "look" and the Windows version work as expected.

Tested also with 16.63 and the behavior is the same.

**Comment by exextoc** [comment]
Hi @ksdaniel 

We tried this on our end with both new and old outlook in Outlook version 16.63 and were not able to reproduce. I have attached a screenshot of the pinning button in the new outlook. Please share your manifest file, or a video of the reproduction so that we can help you further. Thanks.
<img width="144" alt="image" src="https://user-images.githubusercontent.com/28549921/173503887-f25290b9-168f-4f4a-b2c0-a6d19c096823.png">
