### ISSUE TITLE
Outlook add-in: Attachment Change event should be emitted when a cloud attachment is changed to a copy

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#2657]
Currently, the ```Office.AttachmentsChangedEvent``` does not get emitted when an attachment is changed from a "Cloud" attachment to a "Copy" (see screenshot), and vice-versa.

Since there a pretty major differences in how cloud and copies need to be handled, I believe that the change in type of attachment should be emitted as a change to the attachment.

## Your Environment
All platforms
 
## Expected behavior
A change to the type of attachment (cloud vs copy) should emit an ```Office.AttachmentsChangedEvent``` event.

## Current behavior
No event is emitted when the attachment type is changed via the UI.

## Steps to reproduce
1. Add an attachment from the Cloud (do not attach as a copy).
2. Click the dropdown arrow on the attachment and select "Attach as a copy"

## Context
We encrypt attachments on emails and are not able to support encryption of cloud attachments. Due to this, we show a warning that they have a cloud attachment attached to their email. This all works as expected if they add/remove attachments.

But in the case where they click to "Attach as a copy", we are not made aware of this change, so we can't remove the warning message that they cannot have cloud attachments.

It would be great to be notified of this change to attachments.

## Useful logs
![image](https://user-images.githubusercontent.com/7740624/175058868-6eb13f37-a38e-4745-9863-5bc2fb69c506.png)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by alison-mk** [comment]
Hi @cody-lettau, thanks for submitting! We use GitHub issues to report bugs with the product, and it looks like you are requesting a feature. For feature requests, we recommend submitting via [Microsoft 365 Developer Platform Ideas](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). We use Microsoft 365 Developer Platform Ideas to prioritize community requests for additions to the product. If the community upvotes your request, it's more likely to be added to the add-ins platform.

Since this isn't a bug, I will close this issue. Let me know if you have any questions! If I've misunderstood and you regard this issue as a product bug, please reply to let me know. 

Thanks, 
Alison
