### ISSUE TITLE
Outlook Appt Compose RequiredAttendees.getAsync returns the Outlook User in addition to current list

### ISSUE THREAD

**Issue by ANHPearce** [OfficeDev/office-js#2679]
When using Office.js RequiredAttendees.getAsync the current outlook user is appended to the listed recipients even if they are already present in the list. This makes the returning value not suitable for subsequent re-use with RequiredAttendees.setAsync without modification as it will duplicate the current Outlook user in the recipients list. 

## Your Environment

* Platform : Desktop, 
* Host : Outlook
* Office version number:   Version 2204 Build 16.0.15128.20278
* Operating System: Windows 10 Pro 64 bit
* Browser: Edge
 
## Expected behavior
I would have expected the list to only include those currently listed in the UI, possible with the addition of the current user if that is the intended behavior, but not with continuous additions of the current user on subsequent calls. 

Call RequriedAttendees.getAsync and then using the result in RequiredAttendess.setAsync without modification should produce no change in the recipient list. 

## Current behavior
The current Outlook user is append and re-appended to the list on calling getAsync even if already present in the list

## Steps to reproduce
See Attached script which can run in ScriptLab
![2022-06-30_10-28-09](https://user-images.githubusercontent.com/25624851/176706129-8082a0ed-ed69-4b04-8d1e-62ea5abd9118.png)

```  
const item = Office.context.mailbox.item;
   item.optionalAttendees.getAsync((result) => {
    console.log(JSON.stringify(
      result.value.map((i) => {
        return { emailAddress: i.emailAddress, displayName: i.displayName };
      }))
    );

    Office.context.mailbox.item.requiredAttendees.setAsync(result.value);
  });
}
```

## Context

This issue prevent easy use of the Recipient.get/setAsync API

**Comment by samantharamon** [comment]
Thank you for reporting this, @ANHPearce. I was able to replicate the issue in Outlook on Windows. I also noted that running optionalAttendees.getAsync then passing its value to requiredAttendees.setAsync worked as expected, i.e. the current required attendees were overwritten and the organizer's name wasn't duplicated or added. I tested both of your snippets in Outlook on the web and it worked as expected. When you get a chance, could you also test your snippets in Outlook on the web to see if they run as expected?

In the meantime, we will investigate the reported issue further.

**Comment by JuaneloJuanelo** [comment]
@ANHPearce  Hello, thanks for reporting. I have a question about your scenario, are you doing operations on your scenarios for each recipient and you are not checking if there are any dupes there? (ie. what if a user actually types a recipient 2 times). I want to understand more the impact of this issue, and hence adjust the priority of the bug. thank you!

**Comment by ANHPearce** [comment]
@JuaneloJuanelo 

The scenario in question is just adding users to the required attendees list without having to check for duplicates. The operation would be getRecipients --> Add an email address --> setRecipients. 

There should be no need to check that something not being asked to be added to the list is being added. 

Please read ticket above again and test for yourself. The entity being added in the getRecipients call is the active user of the add in. So I would not expect the user to be typing out there own address once, let alone twice.

However in the case that they do add themselves 1 or 2 times, calling getReicpients will include an extra entity every time it is called.  See the screenshot of calling getRecipients and doing no other operation 5 times in a row.

![2022-08-20_21-22-49](https://user-images.githubusercontent.com/25624851/185771448-fcfe8ee5-0e33-4de7-930f-4f1f8585ded7.png)

**Comment by JuaneloJuanelo** [comment]
@ANHPearce ;

I understand your problem description, but I was confused because on the "steps to reproduce" section above the code in the post is inconsistent with the code in the screenshot: In one you are using the required recipients list and in other from the optional list.

Anyways, the root cause of this problem is that in the Win32 implementation of the API we return the Organizer as a required recipient. This is consistent with the UI, for instance, in the "Scheduling Assistant " dialog the Organizer shows up as a required recipient. 

I think you don't describe a specific scenario where this might be problematic (other than appending using setAsync, which we have an alternative), other than just mention that you don't want to check for dupes and just directly get and set recipients, but you are ok with other dupes typed by the user.   I am yet to find a scenario where it makes sense to get and set exactly the same set of required recipients. 

For your  

> The operation would be getRecipients --> Add an email address --> setRecipients. 

looks like what you really want to do is to add new recipients to the list, my recommendation is to use the requiredAttendees.addAsync method instead of SetAsync, that's the right operation to use in this case. Here is an example of how to use it:

```
function addRequiredAttendees() {
  const newRecipients = [
    {
      "displayName": "Allie Bellew",
      "emailAddress": "allieb@contoso.com"
    },
    {
      "displayName": "Alex Darrow",
      "emailAddress": "alexd@contoso.com"
    }
  ];
  Office.context.mailbox.item.requiredAttendees.addAsync(newRecipients);
}
```

FYI, we have an API to get the organizer of the meeting, so if this scenario is causing trouble, the recommendation is to look for the organizer and include it only the set operation. 

Finally, we are concerned about making any changes because we shipped this API many years ago and a change on its behavior given a semantic chance has a potential of break existing Add-ins, so we are not planning to change this API at this point. 

We recommend you handle this case as described above.
