### ISSUE TITLE
Office.onReady instantiation is failing on Outlook for Mac

### ISSUE THREAD

**Issue by nrakochy** [OfficeDev/office-js#270]
Office instantiation is failing on Outlook for Mac (Version 16.17). Not sure what I missing here? Any help would be greatly appreciated.

## Expected Behavior
`Office.onReady` will fire and initialize app script

## Current Behavior
I can initialize in Chrome and Firefox, but Mac for Outlook (not sure what browser is rendering -- some sort of IE 11 hybrid?) silently does not init the app. 

Here is the init script (which gets loaded via `<script src="path/to/script/>` on the DOM. Sidenote: loading via `<script src=with/path />` versus `<script> inline</script>` is necessary to keep Outlook for Mac taskPane happy about `XSS` concerns)- 
```
(function() {
	"use strict";

	function initApp(OfficeAPI){
		  console.log("Office Successfully resolved promise. API: ", OfficeAPI);
		  // JS App specific initialization below...
	}
		
	function init(){
		console.log("In the init function post-content load", Office);
		//Office.onReady(function(){ initApp(Office); });
		//Office.initialize = function(){ initApp(Office) }
		Office.onReady().then(function(){ initApp(Office); });
	}

	window.addEventListener('DOMContentLoaded', init);
})();
```
In the commented lines above, none are functional - `initialize`, `onReady(func)`, or `onReady().then(func)`

This is the same behavior on the three script sources for `Office.js` that I could find - 
`https://appsforoffice.microsoft.com/lib/1/hosted/Office.js`
`https://appsforoffice.microsoft.com/lib/1.1/hosted/Office.js`
`https://unpkg.com/@microsoft/office-js@1.1.7-release-next.0/dist/office.js`

Tried including and then excluding [polyfill](https://github.com/taylorhakes/promise-polyfill).

If I simply pass `Office` to the `init` function without `Office.onReady`, the app will load correctly, and only fail upon attempting to use the API (e.g. `item.location.setAsync`, etc.)

## Context
In development at this point, so nothing unusual here. Loaded HTML from whitelisted manifest AppDomain

## Your Environment
* Platform - Mac
* Host - Outlook
* Office version number: 16.17
* Operating System: macOS High Sierra

## Useful logs
- [ x] Screenshots
[console.log](https://pasteboard.co/HIJHEvY.png) (note: the first init message but not the second)

**Comment by nrakochy** [comment]
I am using an enterprise platform which has its own set of DOM rules. My guess is that there is a conflict between `Office.onReady` which modifies `window` scope and the platform DOM restrictions. Loading `onReady` in Mac Outlook client outside of platform constraints seems to be working.

**Comment by Zlatkovsky** [comment]
@nrakochy , could you clarify what you mean by the DOM rules?  Office.onReady shouldn't modify anything on the `window`, so the fact that it's not working for you might be indicative of a bug.  Reopening for tracking...

**Comment by nrakochy** [comment]
Thanks for the note. Looking at the DOM within the platform, the HTML is rendered in an iFrame and the `Office.js` initialize does not work. Without the iFrame cruft, the HTML + Office.js appears to be working. 

What I mean by DOM rules - I know that the platform disables / re-defines some common apis on the `window` object, but it sounds like that shouldn't matter.

**Comment by nrakochy** [comment]
@Zlatkovsky Is there any further info that would be helpful to add?

**Comment by Zlatkovsky** [comment]
To clarify:  Are you saying that your add-in has an iframe inside of it?  (I ask because on Office Online, the add-in itself runs inside of an iframe, but that's the case with all add-ins; so I want to make sure that the iframe you're referring to is one level deeper, in your *own* add-in).

If so, the behavior you saw is probably expected (today, anyway).  Office.js makes the assumption that it's script reference is at the top level of your add-in, not inside of any iframe.

You can still use an iframe inside the add-in if you want, but office.js needs to be top-level. Which means that:

1. If you iframe is on the same domain as the main page, you can just pass down the Office object to the child.  `iframe.contentWindow.Office = Office`
2. Otherwise, you will need to create your own postMessage-based approach to get the iframe to ask the parent to do something on its behalf.

Does that make sense?

**Comment by nrakochy** [comment]
Okay thanks. Yes, it was an `iFrame` rendered by the platform, not the Outlook iFrame api.
