### ISSUE TITLE
Office.addin.beforeDocumentCloseNotification.*() does not appear after `close anyway` dialog button is closed

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#2726]
Hi,

I have an issue in Excel with `Office.addin.beforeDocumentCloseNotification.*()`.
It works perfectly when I click `Don't close` meaning that the dialog will appear again next time when the Excel document is going to be closed.

The problem comes when I click `Close anyway`, the dialog disappears and then I click cancel on the dialog that asks me to save or not save the changes, but if I try to close the Excel, the close dialog does not appear anymore.

Workaround: 
I've seen that If I will continuously call `Office.addin.beforeDocumentCloseNotification.onCloseActionCancelled()` and add the handler it will work. This means that somehow the handler gets discarded, even though I haven't called disable on it `Office.addin.beforeDocumentCloseNotification.disable();`

Is there another way of making the dialog appear every time, even though I click `Close anyway` on it?
It would be nice to know when the user has clicked `Close anyway`, at least this way we can reinitialise the handler, otherwise it is quite hard to make a fix for it.

Btw, is there a way to change the text that appears on the dialog linked with `beforeDocumentCloseNotification` ?

**Comment by JinghuiMS** [comment]
@danielpdev Thanks for reporting this issue! 
To better answer your question, add @guliums who is the developer of these Apis. He will reply you later today in Beijing time.

**Comment by guliums** [comment]
Hi @danielpdev , thanks for reporting the issue. When design this API, we are trying to avoid showing the dialog for many times which may annoy users. If user click "Close Anyway", we think that the users already noticed the notification but they still want to close. In this case we will clear the add-in lists which have enabled the notification. So after user click "Cancel" in Excel save dialog and close again, the dialog will not show again. That is by design behavior.  If you want the dialog to show again, you will have to call beforeDocumentCloseNotification.enable() again at some time when your add-in need user attention before close. 
For the text in the dialog, it does not support customize. You may go to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) to request a new feature for that. New feature request will be considered when we go through our planning process. Thanks for your support!

**Comment by danielpdev** [comment]
Hi @guliums 
Thanks for responding so quickly. 
The thing with calling `beforeDocumentCloseNotification.enable()` is that we don't know when the add-in list has been cleared out in order to reenable the notification.

Is there a way to check if the `beforeDocumentCloseNotification` is enabled or not?

**Comment by guliums** [comment]
Hi @danielpdev , we don't have API to check enable/disable status. The add-in should enable/disable it according to the add-in's logic. If you need to enable the notification, I think you can always call enable() without checking its current status. It should work even when beforeDocumentCloseNotification has already be enabled.

**Comment by danielpdev** [comment]
This can be closed for now.
