### ISSUE TITLE
Email Address returns empty string for sender and from

### ISSUE THREAD

**Issue by feannyn** [OfficeDev/office-js#2736]
When making a call to `Office.context.mailbox.item.from.emailAddress` and `Office.context.mailbox.item.send.emailAddress` the return value is not the user's email address, instead it is an empty string.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows 365 Cloud PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2205 (build 15225.20356)
* Operating System: Windows 11
* Browser (if using Office on the web): Chrome
 
## Expected behavior
When making this call to Office.context.mailbox.item.from.emailAddress or Office.context.mailbox.item.send.emailAddress, I should be able to get the user's emailAddress, not an empty string value.

## Current behavior
Office.context.mailbox.item.from.emailAddress and Office.context.mailbox.item.send.emailAddress are returning an email string value instead of the actual emailAddress.

## Steps to reproduce

Just make a call to either Office.context.mailbox.item.from.emailAddress or Office.context.mailbox.item.send.emailAddress

## Context
We have an Outlook Add-in which utilizes this property to render specific components, without this value, we cannot render these components.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 

<img width="865" alt="Screen Shot 2022-07-27 at 4 36 19 PM" src="https://user-images.githubusercontent.com/17707848/181555528-d67c322a-b88e-440d-8563-6766ebb54f99.png">
<img width="404" alt="Screen Shot 2022-07-27 at 4 28 51 PM" src="https://user-images.githubusercontent.com/17707848/181555555-aef165e0-a035-4c67-b74f-d8a99fbd6760.png">

**Comment by ztcddsb** [comment]
Thanks for reaching out. Can you be more clear about the version of outlook? Are you using win32 version or web version?

**Comment by feannyn** [comment]
Hey! This is the Outlook for Windows Desktop (win32)

**Comment by exextoc** [comment]
@feannyn Thanks for your reply. But we are not able to reproduce this issue locally. 
Does this happens to all your emails or just a specific one? Can you attach that email in the thread so that we can look into it?

**Comment by feannyn** [comment]
[eml_files.zip](https://github.com/OfficeDev/office-js/files/9236528/eml_files.zi

This is a zip containing the .eml files of the messages along with a recording. I also created a new outlook account and this is reproducible.

**Comment by exextoc** [comment]
@feannyn Can you resend the recording, I don't see it in the zip file above.
Also I am not able to reproduce the issue with the email in attachment sadly. We would need the recording to better understand your scenario.

**Comment by cody-lettau** [comment]
@exextoc - @feannyn will be putting together a better video with an example of what we're seeing (hopefully will have that to you here today or tomorrow).

**Comment by feannyn** [comment]
https://user-images.githubusercontent.com/17707848/182397002-ddd36925-f803-4748-b889-fc203a1d349b.mov

<img width="687" alt="Outlook_version" src="https://user-images.githubusercontent.com/17707848/182397161-b8ef61ac-9f2f-4a5b-b1d2-10203ba60ed4.png">

This is the video recording and also linked is the version of Outlook we are using to test this.

**Comment by exextoc** [comment]
@feannyn Sorry about the delay, but I am still not ale to re produce this. What is your options setting in Virtru and what is the size of impact of this issue?

**Comment by cody-lettau** [comment]
@exextoc this is only occurring for us with free Outlook.com accounts. We do not see any issues with other types of accounts.

I'm not sure what you mean by "Options settings" in Virtru. The impact of this is that users of our add-in who are using a free Outlook.com account will have some major usability issues due to the add-in not being able to tell if the email being viewed was sent by the current user or not (which then shows them options for managing the encrypted email if they are the sender). That said, typically this would be users of our add-in that are not paying customers, but we still would really like to provide them a good experience.

As you can see in the video, we are simply viewing a mailbox item and expecting that we would find the appropriate information for that email on ```Office.context.mailbox.item```, but it is missing some important data points.

Is there a chance it could have something to do with the Outlook.com account settings? If I have my team setup an account they can reproduce it on and provide those credentials to you to try, would that be worthwile?

**Comment by exextoc** [comment]
@cody-lettau 
![image](https://user-images.githubusercontent.com/28549921/183510458-c05eb505-4e68-4689-997a-2d1871137057.png)
It will be super helpful if your team can share the account with us. Because I am still not able to reproduce the issue.

Below are my reproducing steps, please correct me if I am wrong:
1. Start a new compose with outlook.com account
2. Encrypt message with Virtru and send it out
3. Open email in sent item and lookup Outlook.context.mailbox.

Also, is this issue only happens for sent item or it could happens for item in inbox too?

**Comment by exextoc** [comment]
@cody-lettau @feannyn If you have your test account ready, please follow the steps to share the credential:
1. Create a private git repo
2. Put your credential in a file and give @exextoc access to your repo.
3. You can delete the repo once we close the ticket.

**Comment by feannyn** [comment]
https://github.com/feannyn/ticket_for_microsoft

**Comment by feannyn** [comment]
> @cody-lettau @feannyn If you have your test account ready, please follow the steps to share the credential:
> 
> 1. Create a private git repo
> 2. Put your credential in a file and give @exextoc access to your repo.
> 3. You can delete the repo once we close the ticket.

I added you as a collaborator on the repository

To reproduce:

1. Use the provided Outlook account
2. Open Compose for a new message
3. Install the Virtru add-in and activate
4. Once activated, enable the Add-in
5. From here, you want to send the new message, keep the add-in open and wait for the "Sending With Virtru" pop-up to close. If you leave before this occurs, the message will not complete the encryption process.
6. Go to your "Sent Messages" directory
7. Open the message you just sent and open the Virtru Add-in
8. When you open the Virtru Add-in, on the top right, the user should have the ability to modify existing settings (There would be a Cog which they can click on to do this); It does not render.
9. The user's email for sender and from are `""`

**Comment by cody-lettau** [comment]
@exextoc let us know if you have questions.

On another note, you can see how we are handling the issue where a user cannot click away during the send by showing the "Sending in progress" modal. It's definitely not an ideal user experience (another bug that we've reported in the past, but is considered a feature request).

**Comment by exextoc** [comment]
@feannyn What is the name of your repo? I don't see it in my list.

**Comment by feannyn** [comment]
> @feannyn What is the name of your repo? I don't see it in my list.

ticket_for_microsoft

**Comment by exextoc** [comment]
@feannyn @cody-lettau  I logged in the account in the repo and followed all steps above, but I am still not able to repro it in my local. 
![image](https://user-images.githubusercontent.com/28549921/184683601-a9fe77ef-b170-4f66-994f-7056214308a9.png)

We don't have a solid repro at this point so we will investigate/add more detailed error logs to find the problem and fix it. If you can identify a user condition or have a solid repro please feel free to comment here again that will help our investigation and get sooner to the issue.
