### ISSUE TITLE
User is getting logged out from the outlook addin in iOS

### ISSUE THREAD

**Issue by somenathmaji** [OfficeDev/office-js#2785]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: iOS
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 4.2230
* Operating System: iOS 15.6
* Browser (if using Office on the web): N/A
 
## Expected behavior
The user shouldn't get logged out after closing the outlook app.

## Current behavior
Intermittently the user is getting logged out from the outlook addin in iOS. They are not facing this issue in the desktop or in the web.

## Steps to reproduce
1. Open Outlook
2. Open the Outlook addin and log in
3. Close the Outlook and reopen the addin after sometime

## Context
The user gets logged out and he needs to log back in again which is cumbersome. We save the session information in local storage. Initially, we thought it could be because of Mobile Device Management but they don't use it.

Have you guys faced any issues like this? Could you please give some input on what else we can check?

**Comment by exextoc** [comment]
Hey, we are unable to reproduce this issue. Anything written to localStorage should persist across sessions on Outlook. Can you share a manifest for your add-in if your add-in is publicly hosted so that we can investigate further? Otherwise you can try setting a simple value to localStorage from your add-in and see if it persists across Outlook sessions and report if you can still see the issue.
