### ISSUE TITLE
InsertWorksheetOptions method inserting relative path to existing workbook formulas

### ISSUE THREAD

**Issue by omarenri29** [OfficeDev/office-js#2809]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

[Enter feedback here]
Hello, 

I´m using insertWorksheetsFromBase64 method in an Excel Add-in to import an existing workbook to a new workbook, but when I do this, formulas from existing workbook are breaking. Is there a way to keep same functionality from existing workbook 

Evidence: 
![image](https://user-images.githubusercontent.com/90602445/186544717-1e33eae9-8cb7-4892-bbac-8057dbc6fa63.png)

Noticed that when importing workbook its adding relative path to formulas
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d658620-8d5f-5857-37dd-d7d4d4c2c091
* Version Independent ID: 73937eef-3a3d-8b23-1100-9128d9c3dc0e
* Content: [Excel.InsertWorksheetOptions interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.insertworksheetoptions?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.insertworksheetoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.insertworksheetoptions.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @omarenri29,

Thanks for reporting this. @alison-mk, could you please investigate?

**Comment by omarenri29** [comment]
In addition to the above, the method works correctly in Excel desktop and the problem is in the formulas that have references to other tabs in the document.

**Comment by alison-mk** [comment]
Hi @omarenri29, thank you for reporting this issue and for providing additional information. To help clarify, I have a few questions: 
1. I see that you say that the insertWorksheetsFromBase64 method works correctly in Excel on desktop. Are you only seeing this problem in Excel on the web? 
2. Can you provide a code snippet to illustrate the how you're using the method? 

Thank you, 
Alison

**Comment by omarenri29** [comment]
Hi @alison-mk thanks for replying, 
1. yes the problem only occurs on Excel web version.
2.
` Excel.run(async function async(context) {
      let sheets = context.workbook.worksheets;
      sheets.load("items/name");
      await context.sync();
      let sheetNames = sheets.items.map((sheet) => sheet.name);
      if (!compareArray(sheetNames)) {
        // Remove the metadata before the base64-encoded string.
        let startIndex = dataUrl.indexOf("base64,");
        let externalWorkbook = dataUrl.substr(startIndex + 7);
        // // Retrieve the current workbook.
        let workbook = context.workbook;
        // Insert the new worksheets into the current workbook.
        workbook.insertWorksheetsFromBase64(externalWorkbook, {});
        await context.sync();
      } else {
        console.log("already loaded!");
      }
    });`

![image](https://user-images.githubusercontent.com/90602445/187268994-2e1bfbce-eacc-4d2a-8a4c-8fdacdde10db.png)

**Comment by omarenri29** [comment]
These are examples of how the formulas are displayed when they run on the web and on the desktop
Desktop:
![image](https://user-images.githubusercontent.com/90602445/187339864-6dc06edd-e7f3-4e0a-8060-c14d9e6c78c6.png)

Web: 
![image](https://user-images.githubusercontent.com/90602445/187339906-22f7faa6-981a-464f-ab67-84d7f9857b3f.png)

As I mention before when running on web I get a path attached to the formula, this only occurs when the formula has reference to another tab of the imported  workbook

**Comment by omarenri29** [comment]
Hi @alison-mk were you able to reproduce this bug?

**Comment by alison-mk** [comment]
Hi @omarenri29, thank you for the information and for reporting this issue! 

I see a similar issue. It's not exactly the same issue, but I think we are seeing the same bug. Here are the steps that I take, and the bug that I see: 

1. Open this snippet in Script Lab, in **Excel on the web**: https://github.com/OfficeDev/office-js-snippets/blob/main/samples/excel/50-workbook/workbook-insert-external-worksheets.yaml
2. Use the snippet to import a workbook that has multiple worksheets and links between those worksheets
3. Excel on the web shows me a Security Warning saying "External data connections have been disabled". The formulas referencing other worksheets have a #BLOCKED! error.
![image](https://user-images.githubusercontent.com/7977793/188054299-ae07a944-7f75-4f66-a61d-1a8daec742bd.png)
5. I select the "Enable Content" button. 
6. The #BLOCKED! error changes to a #CONNECT! error in the cells that have formulas referencing other worksheets. My workbook shows an Unable to Refresh warning.
![image](https://user-images.githubusercontent.com/7977793/188054684-4b666a28-7704-4279-96c8-8838d8e45d1a.png)

**The bug**: When I use the same Script Lab snippet to import the same workbook in Excel on desktop, the formulas with references to other worksheets work as expected. They don't show a #CONNECT! or #BLOCKED! error. 

Since I'm able to replicate this issue and I agree that it's a bug, I will transfer your issue to the office-js repository so that our engineering team can address it. This repository (office-js-docs-reference) is a documentation repository, not an engineering repository. 

Thanks again for reporting the issue!

**Comment by alison-mk** [comment]
@JinghuiMS Can you take a look at this Excel issue? It's a bug with the insertWorksheetsFromBase64 method that was initially reported in a docs repository. I was able to replicate the bug. My steps are recorded in my previous comment. 

The bug: In Excel on the web, when using the insertWorksheetsFromBase64 method to import a workbook that has links between worksheets, the links between worksheets break. This behavior does not occur in Excel on desktop.

Thanks!

**Comment by yuc014** [comment]
@alison-mk  @omarenri29
I can repro this bug on my machine, this bug now added in our backlog(tracked as 6570397 internally). Thanks for reaching us.

**Comment by omarenri29** [comment]
Thanks a lot
