### ISSUE TITLE
contextual menu for office add in

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#2816]
As of now add in's allow the user to interact with ms partners technology through the task pane (in the particular case of excel, you have the possibility to create custom functions)
To have a more integrated approach, is there anything that allows to ms partners to add their functions in side the contextual menu (right click menu) ?
i.e. take a look at this image where you can see ms partner function 1 and ms partner function 2
<img width="573" alt="image" src="https://user-images.githubusercontent.com/102920976/188807764-1407a03a-3e32-4b3c-a7ce-cb61f5bea2b1.png">

**Comment by ghost** [comment]
@jqueguiner

**Comment by ghost** [comment]
@jqueguiner

**Comment by JinghuiMS** [comment]
@jsoto-gladia 
Provide required information needed to triage your issue. Include as many relevant details about the environment so we can triage your issue. Better to provide current behavior and expected behavior together.
* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
* Expected behavior
* Current behavior

**Comment by ghost** [comment]
This is a generic question that applies for : 
Platform [PC desktop, Mac, iOS, Office on the web]: all platforms
Host [Excel, Word, PowerPoint, etc.]: all hosts
Office version number: latest i.e. 1.1
Operating System: all OS
Browser (if using Office on the web): all browsers
Expected behavior : have ms partner functions appeareing in contextual menu
Current behavior : it is impossible

**Comment by SiruiSun-MSFT** [comment]
Hi jsoto-gladia,

Thanks for sharing your feedback. However, currently, the feature: Add-in entry in contextual menu is not supported yet. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests are considered when we go through our planning process. 

Thanks, Microsoft 365 Developer Platform team
