### ISSUE TITLE
getUserIdentityTokenAsync method keeps returning obsolete identity token until 30 minutes when EdgeHtml used as browser in Outlook add-in

### ISSUE THREAD

**Issue by sc41322** [OfficeDev/office-js#2830]
We are using getUserIdentityTokenAsync method provided by Microsoft to fetch the identity token for our custom Outlook add-in.

Whenever we are updating the manifest file in Outlook to install the add-in, getUserIdentityTokenAsync keeps returning obsolete identity token with old aud value instead of updated one. getUserIdentityTokenAsync method returns the correct updated token only after 30 minutes of installing new manifest. This issue is only occurring where EdgeHTML is used as browser for add-in . For Outlook where Chromium is used as browser, it is working fine(https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins). Can you please look into the issue & let us know if there is any recent change done by Microsoft in its behavior & what is the reason if done or is it an issue?

**Comment by exextoc** [comment]
Hi @sc41322 , thanks for reaching out. Are you trying it on Outlook desktop or OWA?

**Comment by sc41322** [comment]
Hi @exextoc , Its Outlook desktop

**Comment by CG49071** [comment]
@exextoc @michelleranmsft We are facing same issue with Chromium browser as well and it is impacting our customer base. Can you please provide any work around or update me on this issue?

**Comment by exextoc** [comment]
@sc41322, This is strange. Browser version shouldn't affect this at all. Are you perhaps testing on different build versions of Outlook or Windows? Against different versions of Exchange? (On Prem? Office 365?) 

We need more information here to figure out what is going on: 

* What specific build version of Outlook are you reproing this on. If it doesn't repro on a specific build, what is that too? (Build versions looks like 16.0.XXXXX.YYYYY) 

* What Builds of Exchange are you connecting against?

* Does this repro at all in OWA? (have you tried in OWA?) Or Only Win32? 

* It's unclear what "Correct updated token only after 30 minutes of installing new manifest." Is this you install the App, then for 30 minutes it returns to you outdated tokens? Then after 30 minutes it's fine forever? Is it every time you make the call for the user it returns to you an expired token? Then if you make the call in 30 minutes again, it returns to you an unxpired token? 

* It feels like something is wrong here, but some repro steps may have been left out. (i.e. Exchange, Outlook, Windows versions...are you testing on multiple machines, are you getting other tokens etc.) They may not seem consequential but any additional information you can provide here may provide insight as to what is happening. 

The way this code works in Win32, is that when you ask for the token, if it is the first time. We ask the Server for the Token. The token is returned to use with a TTL in the EWS Response. (we don't check the actual token). We will cache that token on the client side, for the duration of the TTL that the server told us. (minus a few minutes). We won't ask the server for a new token unless that token is expired. 

If you can capture a fiddler response of when Outlook.exe asks the Exchange Server for the Token Response, that should tell us if the server is giving back a valid token. (i.e. if the TTL doesn't match with the expiration of the token) 

As you can see there are multiple things that could be going wrong here. (Server Call, Client side Cache). There is currently no known issues with this code. (but that doesn't mean there isn't some unknown bug somewhere) We have tried to repro, but couldn't.  Additional information is necessary. Capturing an iDNA trace could help if we believe the problem is client side.

**Comment by CG49071** [comment]
Please my response inline in blue:

From: Outlook Add-ins Team - MSFT ***@***.***>
Sent: 01 November 2022 01:57
To: OfficeDev/office-js ***@***.***>
Cc: Chhavi Gupta ***@***.***>; Comment ***@***.***>
Subject: [External Origin] Re: [OfficeDev/office-js] getUserIdentityTokenAsync method keeps returning obsolete identity token until 30 minutes when EdgeHtml used as browser in Outlook add-in (Issue #2830)


@sc41322<https://github.com/sc41322>, This is strange. Browser version shouldn't affect this at all. Are you perhaps testing on different build versions of Outlook or Windows? Against different versions of Exchange? (On Prem? Office 365?)

Chhavi: It is not build specific issue and it is occurring on different version and builds as we have tested on multiple outlook versions of Office 365

We need more information here to figure out what is going on:

  *   What specific build version of Outlook are you reproing this on. If it doesn't repro on a specific build, what is that too? (Build versions looks like 16.0.XXXXX.YYYYY)

Chhavi: It is not build specific however you can refer these version for troubleshooting purpose , version 2202 build 16.0.014931.20764 on Chromium WebView2, version 2209 build 16.0.15629.20152

  *   What Builds of Exchange are you connecting against?

Chhavi: builds are mentioned in above line

  *   Does this repro at all in OWA? (have you tried in OWA?) Or Only Win32?

Chhavi: Outlook Desktop as our Add-in is not supported in Outlook Web

  *   It's unclear what "Correct updated token only after 30 minutes of installing new manifest." Is this you install the App, then for 30 minutes it returns to you outdated tokens? Then after 30 minutes it's fine forever? Is it every time you make the call for the user it returns to you an expired token? Then if you make the call in 30 minutes again, it returns to you an unxpired token?

Chhavi: When we install new manifest, it is giving the outdated token(identitytoken has old aud value)  of old manifest for 30 mins. After 30 mins, token get refreshed for new manifest(updated SourceLocation) and it works fine forever.

  *   It feels like something is wrong here, but some repro steps may have been left out. (i.e. Exchange, Outlook, Windows versions...are you testing on multiple machines, are you getting other tokens etc.) They may not seem consequential but any additional information you can provide here may provide insight as to what is happening.

Chhavi: Machine 1-Window Edition : Window 10 enterprise, version 21H2(outlook - version 2202 build 16.0.014931.20764 on Chromium WebView2) ,Exchange – Exchange Online Office 365

Machine 2-Window Edition : Window 10 enterprise 2016LTS, version 1607(version 2209 build 16.0.15629.20152) ,Exchange – Exchange Online Office Professional plus 2021

The way this code works in Win32, is that when you ask for the token, if it is the first time. We ask the Server for the Token. The token is returned to use with a TTL in the EWS Response. (we don't check the actual token). We will cache that token on the client side, for the duration of the TTL that the server told us. (minus a few minutes). We won't ask the server for a new token unless that token is expired.

If you can capture a fiddler response of when Outlook.exe asks the Exchange Server for the Token Response, that should tell us if the server is giving back a valid token. (i.e. if the TTL doesn't match with the expiration of the token)

Chhavi : Attached the screenshot of token in which aud value is not updated

As you can see there are multiple things that could be going wrong here. (Server Call, Client side Cache). There is currently no known issues with this code. (but that doesn't mean there isn't some unknown bug somewhere) We have tried to repro, but couldn't. Additional information is necessary. Capturing an iDNA trace could help if we believe the problem is client side.

**Comment by timwan10** [comment]
I apologize, I had misread your post that the Token was expired. But it is in fact the AUD that is not updating. I think however, the cache is still the cause of what you are seeing. I tried to repro what you describe and see this: 

1) Install Manifest
2) Get User Identity Token
3) Change Manifest Source Location to a different URL
4) Install Manifest
5) Get User Identity Token 

The Token obtained in Step 5 is the same as in Step 2. This is by design, and will actually stay this way for up to an hour. (it can depend on what TTL the server sends down, but from my tests it was approx 50-60 minutes) 

However, if after step 4) you **Reboot **Outlook**, this will clear the in memory cache and then the tokens will update to the new AUD value. 

This is by design, as the client token cache exists to prevent excessive calls to the server. 

What is your scenario that the AUD url needs to change so often? This would only be a problem if you were changing the SourceLocation value every 60 minutes. The design of the Token and Source Location is to be set once, when you update your manifest and not change it afterwards. Even if you do update your manifest infrequently, it will fix itself as soon as the Token times out, or you can request that your users restart Outlook. 

If I have gotten the repro steps different from yours please let me know. (note that I could not see the screenshot of your token), I think you have to be on github to post attachments.

**Comment by CG49071** [comment]
We are facing the issue with step exactly you mentioned.
1. Can you please tell me where the token has been cached. How to remove that cache from outlook application. We have cleared the manifest cache but it did not work for us. We have deleted the manifest from the following location:
%userprofile%\AppData\Local\Microsoft\Office\16.0\Wef
2. We have UAT customers which move to the Prod enviornment, in that case AUD value get change and this issue would not create good experience to our customers.
3. We have started facing this issue since few months, before that, it was working fine. So is there any design change happened at your place.

**Comment by timwan10** [comment]
The cache is an in-memory cache. It is only cleared on reboot of Outlook. Customers that face this issue can reboot Outlook to fix it.

The tokens will automatically time out after the TTL for the token has expired. (which is usually one hour), but can depend on the server implementation. 

This is considered by design. 

It is possible that the timeout of the token has changed some months ago, but we are NOT aware of such a change. (but for example if you moved from On Prem to Office 365 then this timeout value could have been adjusted). 

Even so the client side cache will remain for the TTL value of the token. 

Are your users switching AUD really often? If you are hitting this a lot, you could put a message to your users to reboot Outlook if they hit an invalid token.

**Comment by CG49071** [comment]
Rebooting outlook is not fixing the problem. We tried that as well.

It took 20-30 minutes to update the AUD value for the new manifest. We are using only Office 365. But did not get this issue earlier.

User does not switch AUD value very often but it would create bad experience when they move from UAT to PROD environment.

**Comment by exextoc** [comment]
If rebooting outlook doesn't fix the issue, then this could be a different problem. 

How are the manifests being updated for users? Is it installed by the Admin? Or is it sideloaded manually by the user? 

When this bug happens, is the manifest out of date *locally*? (or does it have the correct AUD value). The local manifest can be found at: 

`C:\Users\[username]\AppData\Local\microsoft\office\16.0\wef\{A98BE375-791E-4897-A0DB-B890ACCD00C6}\jsdiOrZEwLFvkmFYeSA0fQ==\Manifests`

Note that the GUID/Encoding will be unique on your machine. If there are multiple folders that is due to multiple Outlook Profiles/Multiple Exchange accounts, so you will have to find the right one. (or delete the folder then reboot outlook). Note tokens are NOT stored here.  

One possible solution is to change the ID of the Add-in when you change the AUD value. (i.e. have one manifest for UAT and another for PROD, each one using a different ID value).

**Comment by CG49071** [comment]
Manifest is upto date but we are still getting the incorrect AUD value in the token. We have provided all the information but seems like unable to conclude it. So, can we have call on it if you need more details on it.

**Comment by timwan10** [comment]
Currently this isn't something that we are able to repro. I've tried the following: 

1) Install an Add-in By Clicking **Get Add-ins -> My Add-ins -> Add a custom Add-in -> Add From File**
2) GetUserIdentityToken (has correct AUD value) 
3) ONLY change the first sourceLocation Url in the Manifest under Desktop Settings
4) Re-install the Add-in (without changing the Id) 
5) GetUserIdentityToken (this has INCORRECT AUD value, as by design of the client cache) 
6) Reboot Outlook. 
7) Call GetUserIdentityToken (this now has the correct AUD value of the what was set in Step 3) 

Can you provide the diff of the two different manifests you are using before and after? 
Do you have a video recording of the issue?

I will also follow up with the Server Team to see if this is something they know about. 

Can you answer the following questions: 

- Also does the solution of switching your **add-in id** work? This should cause both the Server and Client to treat this as an entirely new add-in, and prevent any of these problems. 

- Also How are the manifests being updated for users? Is it installed by the Admin? Or is it sideloaded manually by the user? (This information is important to the Server team) Are you installing the same way I describe above?

- When you get the second token, is it EXACTLY the same as the first token? Or is it different but has the same AUD value?

If you have a support account, and can engage a support engineer then they should be able to set up a call.

**Comment by CG49071** [comment]
- Yes , reproducible steps are same. In the step 7, we are again getting the old token.
- Difference in manifest is the sourceLocation
- No switching add-in id would not work for us.
- The manifest is uploaded by the Admin
- The second token is exactly the same as first one though we checked the manifest in cache, it is showing new one.
Please let me know in case of any queries

**Comment by timwan10** [comment]
I followed up on this issue with the Server team, and they noted there is NO cache of Tokens on the Server Side. Getting the *exact* same Token from the Server should be impossible. If you have the UPN (email) of the user and time of the server requests it may help. 

Here are some additional queries/comments

- The only cache for tokens is In Memory of the Win32 client. This should be reset when Outlook Win32 is **Rebooted**. If it is NOT rebooted, then this behavior is by design. (It is worth checking to make sure outlook.exe is completely gone from the taskmanager, and some other app is not keeping it open somehow)

- Is the Add-in *centrally deployed* by the Admin for all users? If so it takes time for the Manifest to propagate to all users. But this actually can take 24 hours which is longer than the time frame that you mention. If the Local WEF cache is immediately updated, this doesn't align with the fact that the Manifest was Admin deployed. 

We will need some logging to figure out what is happening. 

Get a Fiddler Trace that shows Outlook Getting a Token from the Server. Every time you call getUserIdentityTokenAsync() it should result in an EWS call from the Outlook.exe client to the Server, if the Client is rebooted between requests. Can you get those fiddler traces and look at the results? Ideally these should be completely different tokens obtained. If these are the EXACT same tokens, we'll need the fiddler traces to forward to the Server team to examine at what could cause this. 

If the Second EWS call is not happening, there could be a bug in the client. If so we will need an iDNA trace to track what is happening. 
https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-record

Please do the following: 
1) Start iDNA Trace
2) Get your Add-in to make the getUserIdentityTokenAsync() call
3) Stop Trace
4) Reboot Outlook. (make sure outlook.exe is gone from the taskmanager)
5) Install the new Manifest 
6) Start a new iDNA Trace
7) Get your Add-in to make the getUserIdentityTokenAsync() call again
8) Stop the Trace. 

This should result in two traces that we can take a look at. 

Can you also record a video of all the steps you are taking to repro the issue, as there may be something small/different that was not accounted for that is causing the issue. This will also take any ambiguity out of any of the terms/steps that I may have misunderstood.

If possible you could also try this with a very simple add-in that does nothing but make a GetUserIdentityTokenAsync() call and dump out the results, to make sure there isn't something with your Add-in caching the results. (though I would expect a reboot of outlook to clear out anything that your add-in cached in memory too)

**Comment by CG49071** [comment]
EWS call before Manifest
<img width="552" alt="EWS_call_before-manifest" src="https://user-images.githubusercontent.com/101329285/208398765-f5fbdeca-ca29-4c38-b0ac-9ef3530619b8.PNG">

OWA call before Manifest
<img width="545" alt="owa_beforemanifest" src="https://user-images.githubusercontent.com/101329285/208397719-1c446604-7744-4e68-aa2d-2007762d5c30.PNG">

OWA call after Manifest
<img width="546" alt="owa_afterManifest" src="https://user-images.githubusercontent.com/101329285/208397761-b29c02f8-5ad8-4f60-bdb4-44276efb2d12.PNG">

Attaching the Fiddler Response, I cannot see second EWS call after Outlook Restart but there is owa call in which Bearer token is same. Is this info would be helpful for you to recreating issue at you end.

Please let me know if you need additional info. Kindly share you microsoft email id so that I can add you for meeting invite and add you in the existing mail thread  with Microsoft folks

**Comment by timwan10** [comment]
As per our further investigation, we were able to determine that the Outlook process is not being fully shutdown on the repro machines. (which is outside the scope of the add-ins platform). Usually if Outlook is not shutting down, it is because a 3rd party process is hanging on to Outlook (i.e. antivirus, or another app accessing outlook's COM Object Model). This will prevent the in-memory cache from clearing out during a reboot. 

Normally the tokens will expire as soon as the TTL from the exchange server is up. (currently Exchange is returning values of 60 minutes, but as this is server determined it could change in the future). 

Additionally, if the add-in in Admin Deployed via Centralized Deployment, it could take up to 24 hours for users the receive the updated manifest. 

We consider this situation to be by design, as the cache improves normal operation greatly, and the workaround is to wait for the tokens to expire or fully reboot Outlook, as manifests changes should not be frequent.
