### ISSUE TITLE
[Excel 2016 for Mac] Nothing happens when calling Office.context.ui.displayDialogAsync

### ISSUE THREAD

**Issue by vhenneuse** [OfficeDev/office-js#284]
I'm working on Mac environment with up-to-date Office for Mac 2016 (16.16.3) and i'm trying to open a popup from my office-js ribbon using displayDialogAsync function.
The popup is correctly opened with my Excel Add-in under Office for Windows and Excel Online, but not under MacOs (no error message, nothing happens).

Is there any known issue with this Office version and MacOs ?

## Steps to Reproduce

From my manifest, on ribbon button click I execute an "openLoginPage" JS function
```
<Action xsi:type="ExecuteFunction">
    <FunctionName>openLoginPage</FunctionName>
</Action>
```

My openLoginPage function :
```
var dialogUrl = 'https://' + location.host + '/xxx/Login.html';
Office.context.ui.displayDialogAsync(dialogUrl, { height: 50, width: 50 }, dialogCallback);
```
My URL use HTTPS and my page Login.html is hosted in my Add-In website.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: **Mac**
* Host [Excel, Word, PowerPoint, etc.]: **Excel**
* Office version number: **16.16.3 (181015)**
* Operating System: **MacOs 10.11.6 (El Capitan)**

**Comment by YiJinMSFT** [comment]
Hi Vhenneuse,
We currently do not have a known issue for dialog API in MAC. Would you mind providing more info, so that we can help to investigate?
First, it is very hard to get debugging info in Ribbon Add-in. Could you create a taskpane add-in or open a taskpane when ribbon is clicked. Then open the dialog from the taskpane. 
If the error doesn't show in taskpane, please let me know. If it also shows in taskpane scenario, could you try the follow steps to get more info?
1. set a breakpoint and get the actual url when calling displayDialogAsync. (you can hide the domain and path name if it is sensitive. I want to double check if it is in good format. )
2. Does your dialogCallback function get called, and is there any error returned in call back function?
3. Is there any javascript error shown in your Safari Inspector console?
Thank you very much. 
Best Regards
Yi Jin

**Comment by vhenneuse** [comment]
Hi Goldensky321,

Thanks for your answer.
When I try to open the dialog from the taskpane the page is correctly opened ! But unfortunately I really need to open it from the ribbon.

To check the issue doesn't came from my Macos version, I migrate to mojave (10.14) and I installed the latest Excel version too (16.19) without change.

**Comment by danielgwilson** [comment]
Hi @vhenneuse, would you mind describing your use case further? Why you need it to open from the ribbon as opposed to the taskpane?
