### ISSUE TITLE
Word Desktop:Non-editable content controls can't be deleted when revision tracking is enabled

### ISSUE THREAD

**Issue by StephenRieger** [OfficeDev/office-js#2886]
# Provide required information needed to triage your issue

For the desktop version of Word, when I insert a content control and mark it as non-editable (cannotEdit = true), the content control cannot then be deleted from the document when revision tracking is enabled. When I try to delete the content control, the error message reported is: "Some changes could not be accepted/rejected because they are contained in controls which are locked for editing."

The content control is marked as deletable (cannotDelete = false).

## Your Environment

* Platform: PC desktop, Mac
* Host: Word
* Office version number: 16.0
* Operating System: MacOS 12.6, Windows 11
 
## Expected behavior
I'd expect to be able to delete content controls that are marked as deletable.

## Current behavior
Attempting to delete a deletable content control fails with the noted error message.

## Steps to reproduce
Insert a content control into a document, mark is as non-editable. Turn on revision tracking. Select the content control and attempt to delete it.

## Sample document
[Non-editable content controls + Revision Tracking.docx](https://github.com/OfficeDev/office-js/files/9718389/Non-editable.content.controls.%2B.Revision.Tracking.docx)

**Comment by jipyua** [comment]
@StephenRieger thanks for reporting this. We synced with the word feature team and confirmed this is a by-design behavior back to Office 2010. When "tracked changes" is on, a deletion is performed using an edit to apply a property indicates that this part of content should be tracked as a deletion instead of real deletion. Applying this property is, a form of edit and if the content control is locked for edits, we cannot apply this property. Unless there is a strong customer asks, we'd like to keep this behavior. Thanks.

**Comment by StephenRieger** [comment]
@jipyua It's definitely an ask. And for us, a strong ask. As it is, this renders non-editable content controls useless for add-ins that need to support revision tracking. Supporting revision tracking is an absolute requirement for us.

Note that Word's native bibliographic citations already support this. They appear to be content controls that are non-editable, but can be deleted when revision tracking is enabled.
