### ISSUE TITLE
OfficeRuntime.Storage length

### ISSUE THREAD

**Issue by adim1973** [OfficeDev/office-js#2901]
Not sure where this issue should be posted....
Is there a way to check if OfficeRuntime.Storage is full? If OfficeRuntime.Storage becomes full, setItem will throw a QUOTA_EXCEEDED_ERR?

**Comment by RuizhiSunMS** [comment]
This is not owned by Custom Function. 
@ElizabethSamuel-MSFT I see you in the list of this API's doc page, can you share some information or direct the user to the right channel?

**Comment by ElizabethSamuel-MSFT** [comment]
@adim1973 Thanks for letting us know about this issue.

@RuizhiSunMS I'll transfer the issue to the office-js repo.

**Comment by AkhileshShah-MS** [comment]
Thanks for reaching out to us! To help us triage the issue to correct team, could you please provide more details regarding the issue in following format? 



# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior


## Current behavior



## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)



1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context



## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by adim1973** [comment]
Not much to say here: according to the [official documentation of OfficeRuntime.Storage interface](https://learn.microsoft.com/en-us/javascript/api/office-runtime/officeruntime.storage?view=common-js-preview#office-runtime-officeruntime-storage-setitem-member(1)), the storage limit is 10 MB per domain. What happens when the storage limit is reached and I use the OfficeRuntime.Storage.setItem? Is an error thrown? If yes, what error?
Also, is there a way to get the available size of the OfficeRuntime.Storage?

![image](https://user-images.githubusercontent.com/5249431/196523604-53c6e866-88ea-41a2-81f7-ad01015a1fb5.png)

**Comment by adim1973** [comment]
Any updates?

**Comment by ElizabethSamuel-MSFT** [comment]
@madhavagrawal17 Can you address this issue?

Thanks.

**Comment by adim1973** [comment]
Any updates?

**Comment by madhavagrawal17** [comment]
Sorry for the delay. Per my investigation, there is no API for OfficeRuntime.storage that can be used to get the current memory status of the Storage. The Storage limit is 10 MB. And we do throw an exception if someone tries to set it into storage once the limit is reached. The exception will contain the HRESULT with value 0x8007000E(E_OUTOFMEMORY).

**Comment by adim1973** [comment]
OK, thank you.
