### ISSUE TITLE
mailbox.item.body.getAsync with Text Coercion type html adds line breaks to content

### ISSUE THREAD

**Issue by stijndeschuymer** [OfficeDev/office-js#2910]
with an Outlook add-in, add a long enough text between html tags to an email body using office-js:
```
Office.context.mailbox.item?.body.setAsync(
    `<div>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</div>`,
    { coercionType: Office.CoercionType.Html },
    (asyncResult) => {
        if (asyncResult.status === Office.AsyncResultStatus.Failed) {
            console.error(asyncResult.error.message);
        }
    }
);
```
Then retrieve the body using the following code:
```
Office.context.mailbox.item?.body.getAsync(Office.CoercionType.Html, (asyncResult) => {
       console.log(asyncResult.value);
});
```

The returned value now contains line breaks `\n` in random places in the text. Which is not expected.

##  Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host : Outlook 
* Office version number: ______
* Operating System: Mac
* Browser: Chrome Version 106.0.5249.119 (Official Build) (arm64)
 
Thanks for looking into this issue

**Comment by timwan10** [comment]
I noticed that this was for OWA, so I'll let someone chime in for OWA, but you should not expect this to have 100% fidelity on Win32.  Since Windows uses Word as a rendering engine, when you Set HTML it gets translated to Word. When the HTML comes back from Word, it often has additional stuff added in it. 

Since add-ins should run on all platforms, you should consider that in any code that you write.

**Comment by exextoc** [comment]
In OWA as well we dont expect 100% fidelity , we have highlighted this in our doc for get API "When working with HTML-formatted bodies, it is important to note that the Body.getAsync and Body.setAsync methods are not idempotent. The value returned from the getAsync method will not necessarily be exactly the same as the value that was passed in the setAsync method previously. The client may modify the value passed to setAsync in order to make it render efficiently with its rendering engine." Please follow [this](https://learn.microsoft.com/en-us/javascript/api/outlook/office.body?view=outlook-js-preview#outlook-office-body-getasync-member(1)) doc for more details
