### ISSUE TITLE
Using chart.series.add() results in incorrect y-axis data on a chart. The new series on a chart do not match the values on the sheet.

### ISSUE THREAD

**Issue by leybal** [OfficeDev/office-js#2927]
# Provide required information needed to triage your issue
Hi. Our team and I working on charts. And we noticed that when we add a new series to the chart, incorrect data is displayed on the Y-axis of the chart.
Let's say we wanna create a chart and add a series on it referring to the same range.
The first series is displayed correctly.
The second series is displayed as if the Y-axis data has been multiplied by 2.
The second series is displayed as if the Y-axis data has been multiplied by 3.
And so on.
The second series and subsequent series are always displayed incorrectly, regardless of the original range.
It is currently not possible to use the Excel JS API for building Chart for the case when more than one series needs to be displayed. That is in most cases. This is a critical error. We will be grateful for any comments. We hope for your prompt reply.

## Your Environment

* Platform: Office on the web (screenshot below), Mac, PC desktop
* Host: Excel
* Office version number: 16.0.15825.42300
* Operating System: Windows 10 Pro
* Browser: Chrome 107.0.5304.88
* Session id: 80d02f22-818a-44ee-8ded-fafc35250daf
 
## Expected behavior

Using `chart.series.add()` we will see the same result with the same range. The series should overlap each other if we use the same data set.

## Current behavior

The first series is displayed correctly.
The second series is displayed as if the Y-axis data has been multiplied by 2.
The second series is displayed as if the Y-axis data has been multiplied by 3.
And so on.

## Steps to reproduce

1. Add to column B some dates (27-Oct-21, 28-Oct-21, and so on). Please see [the screenshot](https://drive.google.com/file/d/1Tu28YIA4E4xXtQ8gy7fCpt3SuiubLbws/view?usp=sharing)
2. Add to column C some numbers (from 1 to 10).
3. Open Script Lab
4. Run the code

> async function createLineChart() {
>  await Excel.run(async (context) => {
>     let sheet = context.workbook.worksheets.getItem("Sheet1");
>     const range = sheet.getRange('B2:C11');
>     const chart = sheet.charts.add(Excel.ChartType.lineStacked, range, Excel.ChartSeriesBy.columns);
>     chart.setPosition("E1", "M20");
>     chart.axes.categoryAxis.tickLabelPosition = Excel.ChartAxisTickLabelPosition.low;
>     chart.legend.position = Excel.ChartLegendPosition.bottom;
> 
>     let rangeSelection = sheet.getRange("C2:C11");
>     let xRangeSelection = sheet.getRange("B2:B11");
>     let newSeries = chart.series.add("Qtr2");
>     newSeries.setValues(rangeSelection);
>     newSeries.setXAxisValues(xRangeSelection);
>     await context.sync();
>   })
> }
5. Take a look at the new chart. It should be 2 series on it. And they will not match. That's the problem.

## Link to live example(s)
1. [The excel file](https://spdua-my.sharepoint.com/:x:/r/personal/o_kravchuk_spdua_onmicrosoft_com/Documents/Book%20231.xlsx?d=wb1125c9fd992484499e7faaee452b6d8&csf=1&web=1&e=fN208j)
2. [The screenshot](https://drive.google.com/file/d/1Tu28YIA4E4xXtQ8gy7fCpt3SuiubLbws/view?usp=sharing)

**Comment by yuc014** [comment]
Hi @leybal, thanks for reaching us.
According to https://learn.microsoft.com/en-us/javascript/api/excel/excel.chartseries?view=excel-js-preview,
setXAxisValues(sourceData) : Sets the values of the x-axis for a chart series. **Only works for scatter charts.**
Thus this method is not for your chart(lineStacked type).

And secondly, you mentioned
> The second series is displayed as if the Y-axis data has been multiplied by 2.
The second series is displayed as if the Y-axis data has been multiplied by 3.
And so on.

This is the feature of lineStacked type chart. The second line will use first line as its baseline to accumulate the value. That's why you see it double and triple. I think you should use: `const chart = sheet.charts.add(Excel.ChartType.line, range, Excel.ChartSeriesBy.columns);`

And this is my gist, you can try it: https://gist.github.com/yuc014/d83b329b6bfb63716cb20677a07164a4

Thanks.

**Comment by leybal** [comment]
Hi @yuc014 
Thanks for the quick response. It was very helpful.
We have tested `setXAxisValues(sourceData)` method with `Excel.ChartType.line` chart and it seems to work correctly. Can you confirm that we can use `setXAxisValues()` for `ChartType.line` in [production](https://learn.microsoft.com/en-us/javascript/api/excel/excel.chartseries?view=excel-js-1.16)? If not, what are the difficulties we can face?

**Comment by yuc014** [comment]
Hi @leybal , sorry for the late reply.
I think use `setXAxisValues(sourceData)` for `Excel.ChartType.line` may cause some unknown issues, I recommend you not use it.
And the reason is `setXAxisValues(sourceData)` is kind of method only for scatter charts since only in scatter charts we will have the definition for "X values" and "Y values".
If you create two charts (line and scatter) with UI, you can see this when you double click the chart:
![image](https://user-images.githubusercontent.com/87364252/203013925-c2d59a81-bc0a-4467-95f3-749c9e483968.png)
![image](https://user-images.githubusercontent.com/87364252/203013982-0388dabf-2594-4db3-8e26-daa00f356910.png)
You can see, in UI, there is no "X or Y values" for line chart.
So I think `setValues` is enough for a line chart.

**Comment by leybal** [comment]
@yuc014 thanks for the help. We can close the issue.
