### ISSUE TITLE
Sheet name inconsistency different API calls

### ISSUE THREAD

**Issue by georgechr** [OfficeDev/office-js#299]
## Expected Behavior
Sheet names from different API calls (context.workbook.getSelectedRange() and context.workbook.worksheets.getActiveWorksheet().name) should be consistent

## Current Behavior
If a sheet name has a space then context.workbook.getSelectedRange() returns the name wrapped in quotes and context.workbook.worksheets.getActiveWorksheet().name returns it as it is

## Steps to Reproduce, or Live Example
Make sure you run this on a sheet that has a space in its name.
```
await Excel.run(async (context) => {
        const selectedRange = context.workbook.getSelectedRange();
        selectedRange.load('address');
        const worksheet = context.workbook.worksheets.getActiveWorksheet();
        worksheet.load('name');
        await context.sync();
        OfficeHelpers.UI.notify(`Selected range:${selectedRange.address} and worksheet name: ${worksheet.name}`);
    });
```

## Context
this makes it difficult to keep track of data based on sheet names

## Your Environment
* All environments

**Comment by JuaneloJuanelo** [comment]
@georgechr thank you for reporting this. In order to make an investigation actionable, can you please describe in what clients and versions you are observing this? (in other words can you please fill more details as per asked in the issue-template? thanks that will really help to promptly investigate!

**Comment by JuaneloJuanelo** [comment]
verified the behavior this is by design. if a developer just wants the sheet name (ie. for displaying it in the add-in task pane) there is no need to get unnecessary quotes, onthe other hand in the context of using it in a range they are required (if there are spaces in the sheet name, otherwise the name cannot be resolved).  We cannot guarantee that getting the name of a sheet will be used only for the purpose of referencing a range.
