### ISSUE TITLE
Outlook add-in error: We're sorry, we couldn't access [add-in name]. Make sure that you have a network connection. If the problem continues, please try again later

### ISSUE THREAD

**Issue by Alexander-He** [OfficeDev/office-js#3000]
# Provide required information needed to triage your issue
- This Error appears immediately when launch to compose a new message in Outlook 
- The side panel part of the add-in works fine. (We guess this error caused by event-based activation code part)
- All Users within customer organization are complaining about this Error Message
- Outside of Customer’s Environment will not have this error message
- Can not reproduce this issue in test environment.

## Your Environment
* Platform:  Windows Desktop
* Host: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2202 Build 16.0.14931.20648) 32-bit
* Operating System: Windows 11
 
## Expected behavior
- Expect add-in do not show this error message.
- The event-based activation code works correctly. 
- Know the diagnostic method and error reason.

## Current behavior
1. Install [add-in](https://smc-prod-cdn.seismic.com/static/outlook/public/1.0.0/manifest.xml).
2. Click "New Email" button to open new message window.
3. The error message will show on the top.

## Steps to reproduce
1. Install [add-in](https://smc-prod-cdn.seismic.com/static/outlook/public/1.0.0/manifest.xml).
2. Click "New Email" button to open new message window.
3. The error message will show on the top.

## Context
Add-in has the LaunchEvent "OnNewMessageCompose", "OnMessageRecipientsChanged" and "OnInfoBarDismissClicked" to complete a kind of insight notification for user. Seems this part does not work on user's Outlook, 

## Useful logs
There no error in network tab.

**Comment by davidchesnut** [comment]
Hi @Alexander-He, thanks for letting us know about this issue. @exextoc can you help resolve this? Thanks!

**Comment by exextoc** [comment]
@Alexander-He, after installing the add-in, please restart Outlook since it needs to download your launchevent.js file. I believe what is happening is that the file isn't downloaded when you open a new email shortly after installing. If this doesn't resolve your issue, then it is possible that the JavaScript code in launchevent.js isn't "compatible" with the environment.

The first thing to do here is to turn on runtime logging:

1. Close Outlook (check the Windows TaskManager to ensure that it is closed.)
2. Close any Office applications (Teams is exempt here)
3. Enable runtime logging using the instructions here: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging#runtime-logging-on-windows. Create the ClientLogs folder manually afterwards. It is not necessary to create the log.txt manually.
4. Open Outlook and trigger your add-in.
5. Check the log.txt file for any relevant logs.

If this doesn't help, mark your add-in for debugging:

1. Close Outlook and all Office applications. Ok to leave Teams running.
2. Mark your add-in for debugging using the instructions here: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/debug-autolaunch#mark-your-add-in-for-debugging
3. Start Outlook
4. Trigger your add-in and look out for the debugging dialog from the instructions page. Click Cancel to skip debugging so that your add-in is executed. Look at the runtime log.txt file to see if there's any relevant log. If you want to debug your add-in, follow the instructions at the top of the page.

If all of this doesn't work, we will have to take a look at your un-obfuscated/un-minified launchevent.js file. We can have an offline session for that and then update this post with our findings.

**Comment by Alexander-He** [comment]
@exextoc Thanks for your detailed explanation, we will try that steps and gather info for further investigation.
