### ISSUE TITLE
In Chart Object, all dataLabel property is coming as null.

### ISSUE THREAD

**Issue by SanjitKumarr** [OfficeDev/office-js#3010]
## Expected Behavior

Excel api should return value of datalabel property of charts.
## Current Behavior

All property in datalabel is coming as null.
## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by SiruiSun-MSFT** [comment]
Hi @SanjitKumarr,

Thanks for reporting this issue. However, unfortunately, this current result is by design. Since series.datalabels is a collection, there may be different settings and attributes for the datalabel of each datapoint in the series. So when getting the properties of series.datalabels, in order to avoid conflicts and inconsistencies, we temporarily return null. If you need to get exact results, you can use series.points.getItemAt(0).datalabel. Maybe you can refer to this link: https://learn.microsoft.com/en-us/javascript/api/excel/excel.chartdatalabel?view=excel-js-preview. 

In response to your feedback, we have opened a task([Task 7252540](https://office.visualstudio.com/OC/_workitems/edit/7252540): [Chart API] Review the design of chartSeries.dataLabels.), and will review the current design later. And since we track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). You can also add your request there. Feature requests are considered when we go through our planning process. 

Thanks, Sirui

**Comment by SanjitKumarr** [comment]
Thank you for clarification @SiruiSun-MSFT

**Comment by SanjitKumarr** [comment]
How dataLabels can be added(set) to the point collection as there is no add method in point collection. @SiruiSun-MSFT

**Comment by SiruiSun-MSFT** [comment]
DataLabel is the basic object of DataPoint, not Data Point Collection. It doesn't need to be added by ourselves. You can get it using these steps: @SanjitKumarr 
    _const sheet = context.workbook.worksheets.getItem("Sample");
    let chart = sheet.charts.getItemAt(0);
    let series = chart.series.getItemAt(0);
    var pointsCollection = series.points;
    var point = pointsCollection.getItemAt(0);
    point.load("dataLabel");
    await context.sync();
    console.log(point.dataLabel);_

**Comment by SanjitKumarr** [comment]
Thanks @SiruiSun-MSFT , but actually I was trying to set dataLabel values and I was able to set it through series[0].dataLabels.

**Comment by SiruiSun-MSFT** [comment]
Hi @SanjitKumarr, that's correct behavior. Our current JS API for series.dataLabels support successfully setting value, but not support get value. That's because "Since series.datalabels is a collection, there may be different settings and attributes for the datalabel of each datapoint in the series. So when getting the properties of series.datalabels, in order to avoid conflicts and inconsistencies, we temporarily return null. " as I said before. But obviously, setting properties are not affected by this inconsistency, so set operations can be supported. Thanks~
