### ISSUE TITLE
Parity between applications - rotation of shapes in PowerPoint

### ISSUE THREAD

**Issue by MCGods** [OfficeDev/office-js#3022]
PowerPoint API does not allow for rotating shapes. This is both a parity issue between office applications and a key missing API of PowerPoint functionality. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: Office 365, Version 2210
* Office-js: 1.0.300
* Operating System: Windows 10
* Browser (if using Office on the web): ______
 
## Expected behavior

I would expect PowerPoint API to be close to Excel, and have properties such as rotation on Shape.

## Current behavior

Currently, this functionality is missing from PowerPoint. 
## Context
I have been looking at migrating an existing VBA add-in, however not being able to manipulate shape rotation is a significant issue. 

This is required from the following user story: As a graphics designer, I want X text displayed vertically to make efficient use of space with branding. As textboxes (textframes) are shapes, rotating text requires rotation of the shape.

There may be other requirements where shapes need specific orientations to convey meaning.

**Comment by Rick-Kirkham** [comment]
You are correct that this functionality is not in PowerPoint. Please suggest this in the [M365 Dev Platform Ideas page](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). 

Since the Issues of this repo aren't used to track platform enhancement ideas, I'll close this, but you can still make comments on it and we will see them.
