### ISSUE TITLE
Geolocation API in Excel Mac and Excel Online

### ISSUE THREAD

**Issue by SharonCKC** [OfficeDev/office-js#3032]
Geolocation API `navigator.geolocation.getCurrentPosition()` doesn't work in Excel for Mac and in browsers. It works in Excel for Windows.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Browser (if using Office on the web): Chrome, Safari
 
## Expected behavior
A dialog should appear asking for permission to the user's location. If the user allows it, the add-in would be able to retrieve the user's location. This is how it currently works in Excel for Windows.
<img width="323" alt="image" src="https://user-images.githubusercontent.com/113057307/206792486-beb7572b-fbf5-47ee-a668-ce79d28f524d.png">

## Current behavior
It just returns an error, code 1, message "User denied Geolocation"

**Comment by dingjin-ms** [comment]
@SharonCKC Thank you for reporting the issue and sorry for the late response.

The API you are using is not an Excel API, and we could not guarantee it works in Excel environment. As for the geolocation similar scenarios, we do not yet support these kind of scenarios, so we would like to suggest you go to propose a new feature request on the [forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform).  Feature requests on the forum will be considered when we go through our planning process.

**Comment by SharonCKC** [comment]
@dingjin-ms Thank you for the reply. The Geolocation API is not an external API, it is a web standard (just like Fetch API), and all current browsers support it. https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

Would it be possible to reconsider this as a bug?

**Comment by dingjin-ms** [comment]
Hi @SharonCKC, I will discuss more about this issue with internal team and come back to you with a conclusion, thank you!

**Comment by dingjin-ms** [comment]
Hi @SharonCKC , after some investigations and discussions internally, we have opened an internal ticket #7898291 to track the problem. Still, this is not treated as a bug but a feature request.  

We will come back to you when the feature is implemented. Thank you!

**Comment by adrianwu8516** [comment]
Hi @SharonCKC, 

Thank you for bringing this up. We currently do not support such operations at the API level. If you are expecting such functionality, it would be very helpful if you could help us create a new post in [our technical forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) so that more people with similar request can join the discussion and upvote for this idea.

Thanks again for your suggestion.

Microsoft 365 Developer Platform:
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
