### ISSUE TITLE
Excel ribbon contextual tabs: supertip length is unnecessarily restrictive. Can you relax the schema requirement?

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#3042]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
 
## Expected behavior

[This source](https://learn.microsoft.com/en-us/dotnet/api/microsoft.office.tools.ribbon.ribbonsplitbutton.supertip?view=vsto-2017) confirms possible supertip lengths up to 1024 characters.

## Current behavior

Because of [this schema](https://developer.microsoft.com/en-us/json-schemas/office-js/dynamic-ribbon.schema.json), I am seeing a cryptic "JSON parser error" if I specify supertip description over 250 symbols long.

BTW the "error parsing JSON" is very cryptic and short, we would appreciate if there were more details about what went wrong.

## Steps to reproduce

Specify a supertip description 251 characters long.

## Context

Not enough characters to describe what the button is doing :)

**Comment by RuizhiSunMS** [comment]
Forward this issue to heidi.

**Comment by wh1t3cAt1k** [comment]
@RuizhiSunMS I wanted to follow up on this issue since a month has passed, whether there are any news?

**Comment by Heidi-mu** [comment]
The ribbon definitions in contextual tabs were designed based on the manifest definition for the ribbon and the keyboard shortcuts for consistency.  The size limitations are consistent with the manifest.    At the time this was built, we were seeing developers getting confused by differences in the two version overrides in the mail manifest and the one in the task pane manifest as well as the different level of ribbon support in different applications that use the task pane manifest.   We were trying to avoid adding additional variation in what a ribbon definition is in this feature.  

The validation of the json for the API occurs in native code, so to allow different json to be valid, we would need to add a new 
requirement set in a future build making this a new feature request.  Developers who want to work everywhere contextual tabs are supported would then need to code against both the current and new requirement set for multiple years due to semiannual M365 build support timeline and support for the current feature in perpetual Office 2021.  

We track feature requests, at <https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform> please add yours there.
