### ISSUE TITLE
Requesting external (API Fetch)  not working in Smart Alert

### ISSUE THREAD

**Issue by Francisco-Vios** [OfficeDev/office-js#3044]
**Manifest**: https://github.com/Francisco-Vios/add-in-Outlook/blob/main/manifest.xml

**JS action**: https://github.com/Francisco-Vios/add-in-Outlook/blob/main/onMessageSendHandler.js

**Comment by AlexJerabek** [comment]
Hi @Francisco-Vios,

Could you please share the error your fetch call is generating? Also assigning @samantharamon to continue the investigation.

**Comment by Francisco-Vios** [comment]
Hi @samantharamon,
The error generated when fetch is called: "TypeError: network request failed".
When I change from smart alerts to event, the fetch calls does not throws error.
As the desire is to publish in the store. It is necessary to use smart alerts.
What could be happening?

**Comment by samantharamon** [comment]
Hi @Francisco-Vios,

Thanks for providing additional information on the error you're getting. You may need to enable the localhost loopback exemption, as follows.

1. Close Outlook if you have it open.
2. Open **Task Manager** and ensure that the **msoadfsb.exe** process isn't running.
3. Set the loopback exemption in an elevated prompt by running the following command:
`call %SystemRoot%\System32\CheckNetIsolation.exe LoopbackExempt -a -n=1_https___localhost_300004ACA5EC-D79A-43EA-AB47-E50E47DD96FC`
4. Open Outlook.

Let me know if that helps resolve the issue.

**Comment by Francisco-Vios** [comment]
Hi @samantharamon,
I tried the command, and it doesn't worked.
This is the result on the terminal:
![resultado](https://user-images.githubusercontent.com/120414036/207884608-05c1724c-27ae-4170-853a-6ec11de3ee03.JPG)


Thanks

**Comment by samantharamon** [comment]
Thanks for giving that a go. When you get a chance, could you enable runtime logging on your machine and share your logs with us? For guidance with enabling this, see [Debug your add-in with runtime logging](https://learn.microsoft.com/office/dev/add-ins/testing/runtime-logging). In addition to this, please also verify that your well-known resource is set up for CORS requests.

**Comment by Francisco-Vios** [comment]
Yes, my well-known is set up for CORS requests.
Follow runtime logging:
https://github.com/Francisco-Vios/add-in-Outlook/blob/main/OfficeAddins.log.txt

**Comment by samantharamon** [comment]
Thanks for providing the logs. We've taken a look and everything looks alright there. If possible, could you try using XMLHttpRequest instead of Fetch to see if that works with Smart Alerts?

**Comment by Francisco-Vios** [comment]
I rewrote the request using XMLHttpRequest and presented the following error: "**The origin and request url must have the same url scheme.**".
I made the same request using XMLHttpRequest through the taskpane and it worked.

When I sent a request to the same domain as the add-in: "localhost:3000" the request returned the error stating that there is no endpoint (expected error), which implies that it is not possible to send requests to a different domain than the add-in.

**Comment by exextoc** [comment]
@Francisco-Vios, I'm trying to reproduce your environment in-house. I have your JS and manifest. What is the URL to your well-known resource file on localhost? I want to see if something changed recently because we do allow requests to other domains listed in the AppDomains section of the manifest XML file.

**Comment by Francisco-Vios** [comment]
@exextoc I'm sending a request to a proxy server that I created locally with the address localhost:8001 of type "POST" with the body of the email as data, then send a request to the endpoint (https://juridico.vios.com.br/api/extension-office/bind-message/processes/378). The error happens when I send the request to localhost:8001 (proxy server).

Requests with fetch are not executed.
XMLHttpRequest error:

```
{
  "UNSENT": 0,
  "OPENED": 1,
  "HEADERS_RECEIVED": 2,
  "LOADING": 3,
  "DONE": 4,
  "readyState": 4,
  "status": 0,
  "timeout": 0,
  "withCredentials": true,
  "upload": {},
  "_aborted": false,
  "_hasError": true,
  "_method": "POST",
  "_perfKey": "network_XMLHttpRequest_http://localhost:8001/api/extensao-office/vincular-mensagem/processo/378",
  "_response": "The origin and request URL must have the same URL scheme.\\n",
  "_url": "http://localhost:8001/api/extensao-office/vincular-mensagem/processo/378",
  "_timedOut": false,
  "_trackingName": "unknown",
  "_incrementalEvents": false,
  "_performanceLogger": {
    "_timespans": {
      "network_XMLHttpRequest_http://localhost:8001/api/extensao-office/vincular-mensagem/processo/378": {
        "startTime": 1672150999833
      }
    },
    "_extras": {},
    "_points": { "initializeCore_start": 1672150997848, "initializeCore_end": 1672150997849 },
    "_pointExtras": {},
    "_closed": false
  },
  "_requestId": null,
  "_headers": {
    "content-type": "application/json",
    "authorization-vios-office": "Bearer 35_eb318b990eee86aea5f674af6e3eb25cef8655e744178700c673243432294355"
  },
  "_responseType": "",
  "_sent": true,
  "_lowerCaseResponseHeaders": {},
  "_subscriptions": []
}

```

**Comment by exextoc** [comment]
@Francisco-Vios, thanks for the extra information. Can you also share your well-known resource? It's path and contents?
Also, is there a reason why `_url` is using HTTP instead of HTTPS? If there's a scheme mismatch, the requests will fail as is reported in the response `The origin and request URL must have the same URL scheme`.

**Comment by Francisco-Vios** [comment]
Also, is there a reason why `_url` is using HTTP instead of HTTPS? Yes, because we are talking about a local server made on my machine (localhost) to receive requests and then send them to our server, this is done to avoid CORS errors. What does not change the fact that it works when I use **"Events"** and does not work with **"Smart Alerts"**. Here is a link to the well-know resource: https://github.com/Francisco-Vios/well-know-resource. (In this repository is the simplified logic of the add-in for outlook and the proxy server where it is possible to verify it working using **"Events"**, in the manifest it is possible to change to the use of **"Smart Alerts"** and observe that the add-in crashes)

**Comment by exextoc** [comment]
@Francisco-Vios, your manifest XML uses HTTPS for localhost. If you used our [toolset](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest#set-up-your-environment) to create and run your add-in, it comes with HTTPS support. If not, then your add-in's server obviously supports HTTPS. Either way, HTTPS support is required for Smart Alerts requests because the add-in is executed in a custom sandboxed process that enforces this restriction. For the old Events feature, the add-in is executed in a browser, which may have less restrictions on network requests.

I checked the link to your well-known resource, and I could not find a file named `microsoft-officeaddins-allowed.json`, which is the [well-known resource](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/use-sso-in-event-based-activation#list-allowed-add-ins-with-a-well-known-uri) that the custom sandboxed process relies on to allow network requests.

**Comment by Francisco-Vios** [comment]
@exextoc The problem that occurred was during the execution of "Smart Alerts", where an external request for data is made that returned with an error. Error I managed to fix. The call to "Smart Alerts" is not external to the rest of the add-in.

Now another problem is happening. "Smart Alerts" is not running in Outlook Web.

**Comment by exextoc** [comment]
@Francisco-Vios, it seems you managed to resolve this issue. If not, please clarify. If yes, please open another issue for Outlook Web so that we can discuss that separately and track our list of issues better.

**Comment by Francisco-Vios** [comment]
@samantharamon e @exextoc Thank you for your help. Problem solved.
