### ISSUE TITLE
Cannot getItem for some Excel.BuiltInStyles

### ISSUE THREAD

**Issue by timnudecision** [OfficeDev/office-js#3061]
# Provide required information needed to triage your issue
Some built-in styles don't work when using getItem() to load Excel API style objects

`
    let syle1a = context.workbook.styles.getItemOrNullObject(Excel.BuiltInStyle.heading1).load("name,font,fill");
    let syle1b = context.workbook.styles.getItemOrNullObject("Heading 1").load("name,font,fill");
    let syle2a = context.workbook.styles.getItemOrNullObject(Excel.BuiltInStyle.heading2).load("name,font,fill");
    let syle2b = context.workbook.styles.getItemOrNullObject("Heading 2").load("name,font,fill");
    await context.sync();

    console.log(`syle1a: ${syle1a.isNullObject}`); // should not be null
    console.log(`syle1b: ${syle1b.isNullObject}`); // is not null
    console.log(`syle2a: ${syle2a.isNullObject}`); // should not be null
    console.log(`syle2b: ${syle2b.isNullObject}`); // is not null
`
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel desktop app version 2301 Beta channel
* Office version number: ______
* Operating System: Windows 11
* Browser (if using Office on the web): NA
 
## Expected behavior
Expect getItem calls using Excel.BuiltInStyle enums to return an object

## Current behavior
context.workbook.styles.getItemOrNullObject(Excel.BuiltInStyle.heading1) return as isNullObject true
It should return an object.

context.workbook.styles.getItemOrNullObject("Heading 1") does return an object
I guessed at this and it worked. 

## Steps to reproduce
create a simple script using script lab and paste the code snippet above into it

## Link to live example(s)

# Provide additional details

## Context
the value of the enum Excel.BuiltInStyle.heading1 is "Heading1" while the "Heading 1" with a space works (matches text in the user interface).  

Solution is to change either the enum value to "Heading 1" or the the user interface text to "Heading1".

## Useful logs

Console output:
syle1a: true
syle1b: false
syle2a: true
syle2b: false

**Comment by ruijiaMS** [comment]
Hi @timnudecision, thanks for your question.
We can learn that Excel.BuiltInStyle is an enum from https://learn.microsoft.com/en-us/javascript/api/excel/excel.builtinstyle?view=excel-js-preview. And I searched our document and find that developers never use getItemOrNullObject for Excel.BuiltInStyle. This API only help developer easily to use some basic built-in styles, so I think you can directly use it instead of justifying the object. I prefer providing an example usage about how to use or test this API here, hopefully this will help you:

`var worksheet = context.workbook.worksheets.getActiveWorksheet();`
 `context.load(worksheet);`
`worksheet.getRange("A1:A1").style = Excel.BuiltInStyle.bad;`
`worksheet.getRange("A1:A1").format.verticalAlignment = 'Justify';`
`var range = worksheet.getRange("A1:A1");`
`context.load(range);`
`context.load(range.format);`

**Comment by timnudecision** [comment]
Here I am accessing the list of styles provided by the workbook:
`context.workbook.styles.getItemOrNullObject(Excel.BuiltInStyle.heading1)`

This is a distinct use case that is different from from accessing range.format.  It requires that I access the style using its enum.

In my application, I am creating new custom styles for the workbook based on existing styles.

**Comment by guliums** [comment]
Hi @timnudecision, thanks very much for reporting the issue. Excel.BuiltInStyle is used in Range.style API so we cannot change its value (range.style returns "Heading1" for that style.) For styles.getItemOrNullObject() API, the style name is "Heading 1" which is not consistent with range.style API. I have created work item 7409142 to track that issue internally. You may use styles.load() to get all available names for styles.getItemOrNullObject() API and get your desired style by using the name string directly.
