### ISSUE TITLE
Apply the API Calculate to a list of cell

### ISSUE THREAD

**Issue by tqdo** [OfficeDev/office-js#3062]
If I have a list of cells ["A1, "B2", "C5"], is there a way to apply the API Calculate to all of these cells? I know a way to Calculate these cells if I select them in Excel, but just wonder whether there is a way to input a list of cells and have them Calculated. Thanks

**Comment by lindalu-MSFT** [comment]
Will this work?
```
function main(workbook: ExcelScript.Workbook) {
	let selectedSheet = workbook.getActiveWorksheet();
	// Set range A3 on selectedSheet
	selectedSheet.getRange("A3").setFormulaLocal("=SUM(A1+B2+C5)");
}
```
I recorded it using OfficeScripts for Excel.

**Comment by tqdo** [comment]
i am sorry my question was not clear. I wanted to use the API Calculate to refresh the list of cells, not to sum them up. If the users manually select these cells, then I know how to do it. I just don't know how to input a list of cells and have them Calculated

**Comment by RuizhiSunMS** [comment]
@tqdo Thanks for the reporting. Our ENG had some investigations and found your question should be Excel API related but not Custom Functions. Then we may suggest you report your issue in the office-js channel <https://github.com/OfficeDev/office-js/issues> and add an 'Excel' tag.
@JHJ-MS

**Comment by lindalu-MSFT** [comment]
Unless your workbook is in manual calculation mode, there should be no need for you to force a recalc. It's on by default so dependent cells should get updated automatically. 
<img width="209" alt="image" src="https://user-images.githubusercontent.com/30682803/209586365-f33a537d-180f-4725-9d0d-f1a55dd6f6cd.png">

If you turn it off, then you can force an immediate recalculation using [Application.calculate(calculationType)](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-workbooks#control-calculation-behavior).

Since this is a programming question, I suggest reaching out to the Excel Developer Community on StackOverflow. Use the office-js and excel tag.

**Comment by b-gonzalez** [comment]
> If I have a list of cells ["A1, "B2", "C5"], is there a way to apply the API Calculate to all of these cells? I know a way to Calculate these cells if I select them in Excel, but just wonder whether there is a way to input a list of cells and have them Calculated. Thanks

Will this code work?

```
async function run() {
  await Excel.run(async (context) => {

    let wb = context.workbook

    let ws = wb.worksheets.getActiveWorksheet()

    let rang = ws.getRanges("A1,B2,C5")

    rang.calculate()

    await context.sync()
    
  })
};
```

**Comment by lindalu-MSFT** [comment]
You've got a typo in "range.calculate" but otherwise give it a go and test it. From there, you should seek help from the developer community on StackOverflow. Thanks, Linda
