### ISSUE TITLE
"Side-loading" more than 6 add-ins on Mac

### ISSUE THREAD

**Issue by billshander** [OfficeDev/office-js#309]
I had to create a series of add-ins for a project that are all independent of each other. I have 8 total add-ins for the project. Everything is working perfectly, side-loading works (per instructions [here](http://dev.office.com/docs/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac)) BUT there's a problem. I can only see 6 add-ins in the dropdown. There's no way to get the extra 2 add-ins to load! Is there a workaround?

**Comment by kbrandl** [comment]
@macOutlookExtensibility can you please provide input on this issue?  Thanks!

**Comment by Reezaali** [comment]
[https://office.visualstudio.com/OC/_workitems/edit/2708106](https://office.visualstudio.com/OC/_workitems/edit/2708106)

**Comment by smaremanda** [comment]
@billshander - we arent able to repro this bug [see attached bug from @Reezaali ]. Can you update your Mac client to the latest version and try again? Or maybe there are errors in some of your manifests? If you are able to repro, then please send us the your manifests, Office version and OS version. thanks!

**Comment by billshander** [comment]
I'm not using Visual Studio - just side loading into Excel directly. Are you talking about updating Excel? I keep it constantly uploaded. I'm on Mac (last time I tried this was on Sierra, I believe) and using Excel 16.19 but last tested this about 6 months ago (when I posted this bug) - not sure what version of Excel I was on at that point.

**Comment by kbrandl** [comment]
@billshander since you encountered this behavior 6 months ago but we're currently unable to repro, I'm going to close this issue with the assumption that it's no longer a problem. (The Office JS platform has evolved quite a bit in the past several months.) If you do encounter this problem again, please feel free to comment here in this thread so that we can reopen this issue and investigate further. Thanks!
