### ISSUE TITLE
Custom shortcuts are slow and unstable in Excel Online

### ISSUE THREAD

**Issue by irynakaban** [OfficeDev/office-js#3091]
# Provide required information needed to triage your issue
We should be able to add shortcuts for our add-in, but now the custom shortcuts work perfectly on Excel Desktop, but Excel in web has problems with it. Sometimes, unlike the desktop version, they work slowly and worse, they don't always work after a shortcut to open the taskpane.
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac, Office on web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Mac Desktop: 16.69 (23010700), Office on web: 16.0.16111.42306
* Operating System: Mac OS
* Browser (if using Office on the web): Google Chrome
 
## Expected behavior

Shortcuts work correctly after opening the taskpane. The behavior is the same as in Excel Desktop.
## Current behavior

In some cases, after opening a taskspace using a shortcut, any other custom shortcuts do not work. 
In some cases, after opening a taskspace, it is impossible to close it with a shortcut immediately.
## Steps to reproduce

1. Add a manifest from the example.
2. Open the taskpane using the Control+Option+1 key combination.
3. Try closing the screen using the Control+Option+2 key combination.
4. Try the key combination Control+Option+3, you can see that it works quite slowly.
5. Try Control+R after opening the taskpane to get a modal window with a shortcut selection. Sometimes it does not appear and can be displayed only after closing the taskpane.

## Link to live example(s)

1. [GitHub](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/excel-keyboard-shortcuts)
2. [Video](https://drive.google.com/file/d/1DUh2ViZKN9IrzBiDzWpHSX86Wfn1Kgft/view?usp=sharing) (part 1: chrome, part 2: excel desktop)

# Provide additional details

1. I noticed that when using shortcuts when they do not work, in DevTools in Networks tab you can notice that requests are not sent to the server.

**Comment by gingerjia** [comment]
@irynakaban Thanks very much for reporting the issue! I can repro the issue on Excel WAC sometimes and logged a bug (7492255) for partner team to follow up with it. If have any update, we will let you know.

**Comment by irynakaban** [comment]
@gingerjia Thanks a lot! I will wait for updates.

**Comment by gingerjia** [comment]
Hi @irynakaban, sorry for the late response. When first time check the issue, I do repro the issue. But when tried to repro the issue locally and investigated the root cause, we found the issue cannot repro locally now. And these days we double check the repro steps but still not repro now. It's a little strange. Here are my detail repro steps:
1. Follow below steps to install the sample add-in: https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/excel-keyboard-shortcuts
2. Open the taskpane using the Control+Option+1 key combination.
3. Try closing the screen using the Control+Option+2 key combination.
4. Try the key combination Control+Option+3, you can see that it works quite slowly.
5. Try using the Control+Option+1/2 key combination and find no response sometimes

Could you help to double confirm from your side to see if the issue still repro? If yes, could you share the detail different steps to me to help us further investigate it? Really thanks very much for helping us improve our quality!

**Comment by irynakaban** [comment]
Hello, @gingerjia! Everything is working correctly now, thank you very much!
