### ISSUE TITLE
Outlook Event-Based Activation does not work from a published manifest, but does work from that same manifest when side-loaded

### ISSUE THREAD

**Issue by baseenhoorn** [OfficeDev/office-js#3109]
# Outlook Event-Based Activation does not work from a published manifest, but does work from that same manifest when side-loaded

## Your Environment
* Platform: PC desktop, Office Online
* Host: Outlook
* Operating System: Windows 11
* Browser: Chrome, Firefox
 
## Expected behavior
We have a published Office Add-In, which is available in Outlook. We have implemented Event-Based Activation, which will show a notification on creating a new message by using the OnNewMessageCompose event. (It does a bit more, but for new users, initially it will only show a notification, I think this is enough information for now).

## Current behavior
When the Store Addin is downloaded, the notification will not be shown.

Then I went to my cache, found the manifest, and used that exact manifest by side-loading it.

Now when creating a new mail, the notification does show.

In both cases, published and side-loaded, I can see our JSRuntime .js file being loaded (using Fiddler network monitor). But for some reason it just wont work in the Published Store Addin.

## Steps to reproduce
1. I download the store version of our addin.
2. I press new mail.
3. No notification is shown. But the JSRuntime .js file is loaded just fine.

4. Now I go to my cache, and copy and save the exact manifest Outlook has cached (to ensure there are no differences).
5. I side-load this Addin.
6. I press new mail.
7. A notification is shown. The JSRuntime .js file is loaded (obviously).

## Context
It is kind of a big issue, as we have quite a few clients using this feature. Today a client told us and asked why it didnt work. It only now came to our attention is doesnt work.

## Useful logs
- I dont really have logs. I can send a screen shot of the script being loaded, and the manifests being the same?
- However I dont know if that would provide any more info, as the manifest and the .js file do work when side-loaded, so I dont see how it will provide more info.
- But if you do need it I can send it, no problem.

## Closing arguments
I hope someone can help me. Thanks in advance.

**Comment by timwan10** [comment]
This is currently by design. As LaunchEvents / EventBased add-ins do not run from the store. (see the documenation here: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest) Under "Deploy to users" 

They only work when sideloaded. For Admins, they can deploy Event Based add-ins from AppSource (https://appsource.microsoft.com/en-US/?exp=ubp8) to allow all users in an org to use Event Based Add-ins.

**Comment by baseenhoorn** [comment]
Oh really. Thanks for the response. That makes sense then.

Do you know if this is permanent?  (as you said 'currently'). Or are there maybe plans to only support the OnMessageComposeHandler? 

Is it done because of some security reasons?

**Comment by timwan10** [comment]
EventBased Add-ins have the potential to be really powerful, both in a good way and in a bad way. (i.e. I imagine you can come up with a lot of annoying/destructive things that you could do, whether by accident or on purpose). Since the add-ins do not take a user action (aside from install), an end user may not know what is happening, as opposed to App Commands where they have to click on a ribbon button. 

I think they are just being evaluated to see their impact, and COULD eventually be allowed to be installed from the user store...but the decision could be made to not allow them as well. I unfortunately, don't have any information of when this could possibly change.

**Comment by baseenhoorn** [comment]
All right, thanks for explaining. It does make sense, Event Based Activation could indeed do a lot of destruction without the user even noticing (initially, at least).
