### ISSUE TITLE
Unable to conditionally hide a Custom Tab defined in the manifest

### ISSUE THREAD

**Issue by jgamboavx** [OfficeDev/office-js#3110]
# Provide required information needed to triage your issue

I'm unable to conditionally hide a Custom Tab defined in the manifest via `Office.ribbon.requestUpdate()`.

Doing so results in a `RichApi.Error: ControlIdNotFound`, even though the provided `id` is correct (see below).

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2212 Build 16.0.15928.20196) 32-bit 
* Operating System: Windows
* Browser (if using Office on the web): ______
 
## Expected behavior

Having a CustomTab defined in the manifest as:
```xml

<ExtensionPoint xsi:type="PrimaryCommandSurface">
  <OfficeTab id="TabHome">
              ...
  </OfficeTab>
  <CustomTab id="ConstosoCustomTab">
    <Group id="ConstosoCustomTabGroup">
      <Label resid="ContosoGroup.Label"/>
      <Icon>
                 ...
      </Icon>
      <Control xsi:type="Button" id="ConstosoCustomTabButton">
        <Label resid="TaskpaneButton.Label"/>
        <Supertip>
                   ...
        </Supertip>
        <Icon>
                   ...
        </Icon>
        <Action xsi:type="ShowTaskpane">
          <TaskpaneId>ButtonId1</TaskpaneId>
          <SourceLocation resid="Taskpane.Url"/>
        </Action>
      </Control>
    </Group>
    <Label resid="CommandsGroup.Label" />
  </CustomTab>
</ExtensionPoint>
```

It should be possible to hide it via:

```js
  Office.ribbon
    .requestUpdate({
      tabs: [
        {
          id: "ConstosoCustomTab",
          visible: false,
        },
      ],
    })
    .then(() => console.log("It's hidden"))
    .catch((err) => console.log(err));
```

However, the tab is not hidden and the following error is thrown:

![image](https://user-images.githubusercontent.com/122270839/214866032-2dbe621b-2f73-40d3-b3d5-253935b14321.png)

On the other hand, I'm able to disable a control within the custom tab, so it appears the problem is specific to toggling visibility:

```js
  Office.ribbon
    .requestUpdate({
      tabs: [
        {
          id: "ConstosoCustomTab",
          groups: [
            {
              id: "ConstosoCustomTabGroup",
              controls: [{ id: "ConstosoCustomTabButton", enabled: false }],
            },
          ],
        },
      ],
    })
    .then(() => console.log("It's disabled"))
    .catch((err) => console.log(err));
```

## Current behavior

The tab is not hidden.

## Steps to reproduce

1. Generate a new Yeoman project with a shared runtime
2. Add a custom tab to the manifest
3. Attempt to hide it via ```Office.ribbon.requestUpdate```

Alternatively, I've prepared a minimal repro repo at:
https://github.com/jgamboavx/repro-controlid-notfound

**Comment by Heidi-mu** [comment]
This is by design.   The tabs defined in the manifest cannot be hidden.  Only custom contextual tabs support changes to the [visible](https://learn.microsoft.com/en-us/javascript/api/office/office.tab?view=common-js-preview#office-office-tab-visible-member) property.   For more information on custom contextual tabs see: https://learn.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs.   

The Office ribbon framework has two types of tabs: core tabs and contextual tabs.  The Home tab is a core tab and the Table Design tab is a contextual tab.  These two types of tabs have different UI styles and placement in the ribbon.   In the Office UI design model, core tabs should always be visible and contextual tabs should be shown in the relevant context and hidden in all other contexts.   The web add-in framework enforces that UI paradigm. Tabs from the manifest use the core tab type and their visible state cannot be changed.  The Tabs created by [Office.ribbon.requestCreateControls](https://learn.microsoft.com/en-us/javascript/api/office/office.ribbon?view=common-js&preserve-view=true#office-office-ribbon-requestcreatecontrols-member(1)) use the contextual tab type.  These custom contextual tabs should be shown and hidden by the add-in.

**Comment by jgamboavx** [comment]
Understood, thank you for the detailed response.
