### ISSUE TITLE
Non-Prod File Loading Error (503) - Cengage

### ISSUE THREAD

**Issue by aaroncengage** [OfficeDev/office-js#3130]
In all of our development environments, as of Thursday afternoon of last week, Excel Online is not loading files.   Excel Online shows a file loading indicator in the bottom right hand corner that leads to a 503.   Screencast: [https://www.screencast.com/t/PgG8fpJtwa].  This issue currently is not impacting our live production environments.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: _Office for web_____
* Host [Excel, Word, PowerPoint, etc.]: ___Excel___
* Office version number: __Excel for Web 16.0.16130.42308____
* Operating System: __Win____
* Browser (if using Office on the web): __Chrome____
 
## Expected behavior

Excel Online should open the file.

## Current behavior

Excel Online returns a 503 when trying to open a file from non-prod environment

## Steps to reproduce

1. Some additional information: when trying to load [the file](https://urldefense.com/v3/__https:/nam06.safelinks.protection.outlook.com/?url=https*3A*2F*2Fc5h-excel-15.cdn.office.net*2Fx*2Fs*2Fh8E06BA5CD35CA10F__layouts*2FResources*2Fen-US*2FclientManifest.js&data=05*7C01*7Cwegon*40microsoft.com*7C9e38a4311a9b498457a508db060b1542*7C72f988bf86f141af91ab2d7cd011db47*7C1*7C0*7C638110416946598174*7CUnknown*7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0*3D*7C3000*7C*7C*7C&sdata=3rA7PJJoyTZBbnt5MUpgfOqXRuhrMCOx*2BesONCaeGj0*3D&reserved=0__;JSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSU!!MXVguWEtGgZw!LDDy-hEoFUGkjdTm3hUc4gV1nWJnojqQVx1PGXJ2BvHEnvgEzEcRu0IR26XB53pJFR4jzAafwxYPwdCoJbzS$) that is returning the 503:
 
This is the error message we receive when trying to load the file that is returning the 503:

An error occurred while processing your request.
Reference #30.462a0660.1675443098.650e3782

2. ______
3. ______

## Link to live example(s)

1. What is odd is [https://c5h-excel-15.cdn.office.net/x/s/hCB27DE4E12836C47__layouts/App_Scripts/excelOnline.min.js](https://urldefense.com/v3/__https:/nam06.safelinks.protection.outlook.com/?url=https*3A*2F*2Fc5h-excel-15.cdn.office.net*2Fx*2Fs*2FhCB27DE4E12836C47__layouts*2FApp_Scripts*2FexcelOnline.min.js&data=05*7C01*7Cwegon*40microsoft.com*7C9e38a4311a9b498457a508db060b1542*7C72f988bf86f141af91ab2d7cd011db47*7C1*7C0*7C638110416946598174*7CUnknown*7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0*3D*7C3000*7C*7C*7C&sdata=oLxCZQ*2B1zjf8YfcdxhgMVvnT6QbFEv5prCP*2BdIBP1QQ*3D&reserved=0__;JSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSU!!MXVguWEtGgZw!LDDy-hEoFUGkjdTm3hUc4gV1nWJnojqQVx1PGXJ2BvHEnvgEzEcRu0IR26XB53pJFR4jzAafwxYPwRj8QU8v$) returns a file, and it is on the same server as the one erroring out, so I think the server is reachable, it is just having a problem with some files
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

![EO_NotLoading_Dev](https://user-images.githubusercontent.com/124586271/216992253-502dd119-22ac-489d-921d-047abe1a69c4.png)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by atuszyn** [comment]
https://ffc-excel.officeapps.live.com/x/_layouts/xlviewerinternal.aspx?edit=1&ui=en-us&rs=en-us&WOPISrc=https%3A%2F%2Fwopi-test.cengage.com%2Fservices%2Fv1%2Fspreadsheet%2Fwopi%2Ffiles%2F1aj7k2ptv%21gp8e%211gojhb12e%21bfgs%21t&access_token=0000ldswbsx5-00002u4-0&sftc=1&sc=https://s-c-cxp.cengage.com&host_install_addins=%5B%7B%22addinId%22%3A%22wa104379190%22%2C%22type%22%3A%22TaskPaneApp%22%7D%5D is an example URL trying to load our wopi file.  Not sure how long the access token is good for though.

**Comment by donlvMSFT** [comment]
Hi, thanks for reporting the issue, 

I could open [this link](https://ffc-excel.officeapps.live.com/x/_layouts/xlviewerinternal.aspx?edit=1&ui=en-us&rs=en-us&WOPISrc=https%3A%2F%2Fwopi-test.cengage.com%2Fservices%2Fv1%2Fspreadsheet%2Fwopi%2Ffiles%2F1aj7k2ptv%21gp8e%211gojhb12e%21bfgs%21t&access_token=0000ldswbsx5-00002u4-0&sftc=1&sc=https://s-c-cxp.cengage.com&host_install_addins=%5B%7B%22addinId%22%3A%22wa104379190%22%2C%22type%22%3A%22TaskPaneApp%22%7D%5D), and [the file](https://urldefense.com/v3/__https:/nam06.safelinks.protection.outlook.com/?url=https*3A*2F*2Fc5h-excel-15.cdn.office.net*2Fx*2Fs*2Fh8E06BA5CD35CA10F__layouts*2FResources*2Fen-US*2FclientManifest.js&data=05*7C01*7Cwegon*40microsoft.com*7C9e38a4311a9b498457a508db060b1542*7C72f988bf86f141af91ab2d7cd011db47*7C1*7C0*7C638110416946598174*7CUnknown*7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0*3D*7C3000*7C*7C*7C&sdata=3rA7PJJoyTZBbnt5MUpgfOqXRuhrMCOx*2BesONCaeGj0*3D&reserved=0__;JSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSU!!MXVguWEtGgZw!LDDy-hEoFUGkjdTm3hUc4gV1nWJnojqQVx1PGXJ2BvHEnvgEzEcRu0IR26XB53pJFR4jzAafwxYPwdCoJbzS$) is a bad url to me.

And I see you mentioned this issue currently is not impacting live production environments but only developing env, could you share the both version of Excel online?

Thanks

**Comment by atuszyn** [comment]
I just checked this morning and it is now working in our lower environments.  As far as I know, we did not make any changes to the content/template file, and I know that we did not do a code change.  I don’t know what the root cause might have been, but I am assuming that something had to have been resolved on the Microsoft side.

Thanks.

From: donlvMSFT ***@***.***>
Date: Tuesday, February 7, 2023 at 10:32 PM
To: OfficeDev/office-js ***@***.***>
Cc: Tuszynski, Alex ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [OfficeDev/office-js] Non-Prod File Loading Error (503) - Cengage (Issue #3130)

Hi, thanks for reporting the issue,

I could open this link<https://urldefense.com/v3/__https:/ffc-excel.officeapps.live.com/x/_layouts/xlviewerinternal.aspx?edit=1&ui=en-us&rs=en-us&WOPISrc=https*3A*2F*2Fwopi-test.cengage.com*2Fservices*2Fv1*2Fspreadsheet*2Fwopi*2Ffiles*2F1aj7k2ptv*21gp8e*211gojhb12e*21bfgs*21t&access_token=0000ldswbsx5-00002u4-0&sftc=1&sc=https:**As-c-cxp.cengage.com&host_install_addins=*5B*7B*22addinId*22*3A*22wa104379190*22*2C*22type*22*3A*22TaskPaneApp*22*7D*5D__;JSUlJSUlJSUlJSUlJS8vJSUlJSUlJSUlJSUlJSUl!!MXVguWEtGgZw!NWZx-ACVeAheHFi5fr8EAMYK1RzIF_oohafXt_6GHttaDfsZK-Kd0e3TbWMDEP4QmD-1lLgxSs08zj9aa2Rm9fycsfjPSw$>, and the file<https://urldefense.com/v3/__https:/nam06.safelinks.protection.outlook.com/?url=https*3A*2F*2Fc5h-excel-15.cdn.office.net*2Fx*2Fs*2Fh8E06BA5CD35CA10F__layouts*2FResources*2Fen-US*2FclientManifest.js&data=05*7C01*7Cwegon*40microsoft.com*7C9e38a4311a9b498457a508db060b1542*7C72f988bf86f141af91ab2d7cd011db47*7C1*7C0*7C638110416946598174*7CUnknown*7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0*3D*7C3000*7C*7C*7C&sdata=3rA7PJJoyTZBbnt5MUpgfOqXRuhrMCOx*2BesONCaeGj0*3D&reserved=0__;JSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSU!!MXVguWEtGgZw!LDDy-hEoFUGkjdTm3hUc4gV1nWJnojqQVx1PGXJ2BvHEnvgEzEcRu0IR26XB53pJFR4jzAafwxYPwdCoJbzS$> is a bad url to me.

And I see you mentioned this issue currently is not impacting live production environments but only developing env, could you share the both version of Excel online?

Thanks

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
