### ISSUE TITLE
Office 365 on Windows Server Operating Systems which still support IE11

### ISSUE THREAD

**Issue by jd1984** [OfficeDev/office-js#3132]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hello,

Please can you update this article with further details regarding Windows Server Operating Systems.

For example:
Office 365 on Windows Server 2016
Office 365 on Windows Server 2019
etc.

Thank You

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @jd1984,
Thank you for raising this question. Let me consult with the team and get back to you about the current Windows Server support/browser story.

**Comment by jd1984** [comment]
Thanks @AlexJerabek

**Comment by AlexJerabek** [comment]
Hi @jd1984,

Since it's the holiday season in the US, many of our team members are on vacation and responses may be slow. In the meantime, I found this Stack Overflow thread about running add-ins on Windows Server: [Loading Word add-ins on Windows Server](https://stackoverflow.com/questions/50254517/loading-word-add-ins-on-windows-server).

Judging by the thread, it looks like add-ins run on Windows Server, but you need to toggle some settings to make them work. As for the browser control, my guess is that Server 2016 and 2019 run an IE11 browser control, but I'd have to verify that. I would along want to verify the support story before committing to an answer.

Have you been testing on those platforms? Or was this issue raised out of curiosity?

**Comment by jd1984** [comment]
Hi @AlexJerabek, no problem.

Yes the problem we are seeing is with Office 365 Semi Annual 2202 running on Server 2016 OS.
Specifically the Visio Data Visualizer add-in for Excel saying IE11 is no longer supported.
We do have Edge installed, so I guess the solution will be how do we force Excel to use Edge.

Thank You

**Comment by AlexJerabek** [comment]
With [older versions of Windows](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins#microsoft-365-subscription-versions-of-office-on-windows), there isn't a way to "force" Edge to be the browser. That's because it's really a browser control in Office that's being used. 

That said, I'm surprised the Visio Data Visualizer is giving that error. I thought that had been around for long enough that had to have supported IE11. Is this new behavior for you? Was the add-in previously working?

**Comment by jd1984** [comment]
Hi @AlexJerabek 

Yes this is new behaviour for us, and did used to work.
We are currently on O365 Semi Annual 2202 release.
Is there any feedback from your wider team members yet?

Thanks

**Comment by AlexJerabek** [comment]
@slabereemsft, any insight?

**Comment by slabereemsft** [comment]
@jd1984 - Thanks for reporting.  I'm not sure whether this is an OS specific issue or an installation specific issue as the Edge WebView2 component is technically an optional component for installation.   

@yatibawri1 - Can you investigate here?

**Comment by yatibawri1** [comment]
@slabereemsft after investigating with engineers seems like it is an installation issue. Office installation will trigger webview2 runtime installation. I am following up to reach out to the right individual

**Comment by Ben-ITLogic** [comment]
I have found a similar issue on two Server 2016 instances. However it is the actual M365 logon prompt that is using IE11. If a user needs to enroll in MFA, they are unable to do so as the login prompt runs in IE11. The MFA enrollment page does not support IE11.

Office version 16.0.14931.20858

One of them was a new server provisioned in October too. So a fresh install only a few months old.

It installs WebView2 with office, however Office doesn't actually bother using it. It still uses IE11.

As per this documentation page: https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins
Windows 10 ver. < 1903 uses IE11. Windows Server reports as build 1607. So is it possible that it is detecting it as Windows 10 1607 thus using IE11?

**Comment by yatibawri1** [comment]
Can you please check if WIP is enabled/disabled? In order to enable WIP you need to create a Policy please check the link here- https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

**Comment by Ben-ITLogic** [comment]
WIP is disabled on both clients.

**Comment by slabereemsft** [comment]
@Ben-ITLogic - This question was posed on our developer forum which made a few of us think that this was related to Office Add-ins.  The MFA enrollment page sounds like its actually an office feature (vs using one of our APIs).  Is that correct?  That'll help us route this to the right folks.

**Comment by Ben-ITLogic** [comment]
@slabereemsft It is related to the normal Office login UI, so probably not an add-in directly. However this is literally the only place I have managed to find anyone mentioning office using IE11 for webpages instead of EdgeWebView2 on Server 2016. So thought it could have been related to underlying code somewhere.

**Comment by SylvaD-MS** [comment]
Office 365 only deploys WebView2 on Windows 10 and it is already pre-installed on Windows 11.  For Windows down-level, you need to deploy WebView2 manually.
https://developer.microsoft.com/en-us/microsoft-edge/webview2/
Choose the **Evergreen Bootstrapper** in order to always be on the WebView2 latest build.

**Comment by Ben-ITLogic** [comment]
@SylvaD-MS In my case WebView2 is installed and works on other apps. Office M365 Login UI just doesn't use it.

**Comment by slabereemsft** [comment]
@Ben-ITLogic - If I recall correctly, that feature isn't using any of our 3rd party extensibility capabilities.  So its likely hard-coded to use the Trident control (which is based on IE 11).  That's not technically supported through this support channel.  I'll see if I can follow-up on an internal channel to get an update from the team but if its urgent then I'd recommend going through one of our paid support channels.

**Comment by jd1984** [comment]
@slabereemsft yes this was originally raised as a Visio Data Visualizer add-in for Excel issue, although based on @Ben-ITLogic 's additional feedback it sounds like the problem is more widespread?

@SylvaD-MS I have just tested manually installing WebView2 on Server 2016 and this still does not work

![issue](https://user-images.githubusercontent.com/43063718/212055430-ebec9e2d-9e60-4d54-9c27-91cd1fa8e9e7.png)

Thank You

**Comment by AlexJerabek** [comment]
Quick note: I've added the Windows Server support notes to the previously mentioned article in OfficeDev/office-js-docs-pr#3832. However, this thread points at a different issue of decreased functionality. I'm going to transfer this from the documentation into the product repo for tracking purposes.

**Comment by jd1984** [comment]
@yatibawri1 Can we have an update please?
