### ISSUE TITLE
Inconsistent language keys via Office.context.displayLanguage

### ISSUE THREAD

**Issue by nagod** [OfficeDev/office-js#3133]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Platform: Office on the Web

As written in your documentation, the value of **Office.context.displayLanguage** should return a  string in the RFC 1766 Language tag format, such as "en-US".

This is not the case, as you can see in the provided screenshot.
 
![Screenshot 2023-02-07 at 10 13 02 AM](https://user-images.githubusercontent.com/28481277/217210536-ce370f45-5e9a-407d-830d-ac8691cd2ebe.png)

**Comment by isabela-dominguez** [comment]
Hi @nagod, thank you for reaching out to us. Can you please provide us with more details using this template? 


# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior


## Current behavior



## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)



1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context



## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by nagod** [comment]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: ______
* Operating System: MacOS
* Browser (if using Office on the web): FireFox
 
## Expected behavior
Office.context.displayLanguage => "en-US"
Office.context.displayLanguage => "de-DE"

## Current behavior

**See context for some context :)**

Office.context.displayLanguage => "EN-US"
Office.context.displayLanguage => "DE-DE"

## Context
To load e.g localized text values into a sideloaded WebView via AddIns, I need the currently used Office language, e.g. English, German etc..  
The Office API provides a displayLanguage property of the Office.context object for this purpose.
As described in your documentation, the value of Office.context.displayLanguage should return a string in the format of the RFC 1766 language tag, e.g. "en-US". Unfortunately, this is not the case as you can see at **"Current behavior*"*

# Provide additional details
The Office.context.displayLanguage property returns only a "wrong" value in Word online. 
When sideloading the same WebView into Excel, PowerPoint online, the Office.context.displayLanguage property returns a valid RFC 1766 language tag.

# Word Online Screenshot
![word-online](https://user-images.githubusercontent.com/28481277/218401418-139f03aa-ae1e-4d6a-8908-edf70d6a1a60.png)

# Excel Online Screenshot
![exel-online2](https://user-images.githubusercontent.com/28481277/218402949-24720e03-e971-44b3-9544-46702abab445.png)

**Comment by alison-mk** [comment]
Hi @nagod, thank you for submitting this bug! I've assigned it to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison
