### ISSUE TITLE
How to add custom functions to an existing addin

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js#3173]
Hi,

i've created a 'functions.ts' file, but seem to be having issues with my webpack, throwing an error

`[tsl] ERROR in C:\Repos\ojsx-addin-service\src\functions\functions.ts(17,1)
      TS2304: Cannot find name 'CustomFunctions'.

We have several forums where you can ask the developer community questions about your code. Try one of the following forums to ask technical questions about:
- [Developing Office Add-ins for Word, Excel, PowerPoint, Outlook, Project, Visio, and OneNote](https://docs.microsoft.com/answers/topics/office-addins-dev.html)
- [Access programming in Office](https://docs.microsoft.com/answers/topics/office-access-dev.html)
- [Developing COM or VSTO Add-ins for Office](https://docs.microsoft.com/answers/topics/office-vsto-com-dev.html)
- [Office JavaScript API](https://docs.microsoft.com/answers/topics/office-js-dev.html)
- [SharePoint and OneDrive development](https://docs.microsoft.com/answers/topics/sharepoint-dev.html)
- [Deploying and publishing Office or SharePoint apps to AppSource](https://docs.microsoft.com/answers/topics/microsoft-365-apps-publishing-dev.html)

For additional information about JavaScript programming, see the [JavaScript at Microsoft](https://docs.microsoft.com/javascript/) community hub.

**Comment by theboyknowsclass** [comment]
[webpack.config.dev.zip](https://github.com/OfficeDev/office-js/files/10806872/webpack.config.dev.zip)

**Comment by alison-mk** [comment]
Hi @theboyknowsclass, thank you for submitting and sorry for the delay. I've assigned it to @yaweizhu-henson who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by rundongmsft** [comment]
Hi @theboyknowsclass, looks like the ts in your side cannot recognize `CustomFunctions`. Please try to run this command under your project: `npm install --save @types/custom-functions-runtime`

If this method can't solve your issue, please send me a complete project so that I can help to debug it.

The differences between CF Add-in and non-CF Add-in include 5 parts:
1. Functions.js or Functions.ts
2. Functions.html
3. manifest.xml
(For details about these 3 parts refer to this [doc](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview#how-a-custom-function-is-defined-in-code).)
4. Webpack config
5. Dependences
(For details about these 2 parts, you can refer to a [yoman generated CF sample add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows).)

If you want to add custom functions to an existing add-in, check and update these 5 parts.

**Comment by donlvMSFT** [comment]
I'd like to close this issue due to current status, please raise a new one or reactive if there're further questions.
