### ISSUE TITLE
Outlook JSAPI - Need visibility in Series state

### ISSUE THREAD

**Issue by thoffmann-fms** [OfficeDev/office-js#3188]
Our Outlook add-in needs to know if the calendar event being edited is part of a series.  Currently the only way to get this requires saving the Event as a draft, then pass the ID to a backend API to call Graph to get the Event object by ID, and then look at the Event.Type property.  Also, if the event is an "Occurrence" then the SeriesMaster records needs to get looked up to find the Recurrence Range, etc., properties.  This information should be directly readable by the Add-In via the JavaScript API. Related to that the Add-In needs to know if the Edit is "Edit All", "Edit Single" or the OWA-specific "Edit here and forward".

**Comment by alison-mk** [comment]
Hi @thoffmann-fms, thanks for submitting! We use GitHub issues to report bugs with the product, and it looks like you are requesting a feature. For feature requests, we recommend submitting via [Microsoft 365 Developer Platform Ideas](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). We use Microsoft 365 Developer Platform Ideas to prioritize community requests for additions to the product. If the community upvotes your request, it's more likely to be added to the add-ins platform.

Since this isn't a bug, I will close this issue. Let me know if you have any questions!

Cheers, 
Alison
