### ISSUE TITLE
Missing types for Office.ribbon.requestCreateControls

### ISSUE THREAD

**Issue by celluj34** [OfficeDev/office-js#3190]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: N/A
* Operating System: Windows
 
## Expected behavior

Referencing https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64455#discussioncomment-5129083

I expect to have more specific type information than just `Object`.

## Current behavior
More specific types are not provided for `Office.ribbon.requestCreateControls`

## Steps to reproduce

1. Install `@types/office-js@1.0.315`
2. See that specific types are not available

## Context
I would like specific type information for this method instead of just `Object`. Currently there's no validation so I cannot be sure that the type I am passing in is correct. Please let me know if you require and more information.

**Comment by Rick-Kirkham** [comment]
@celluj34 Your suggestion has been accepted. I will make an internal task assigned to me. You are the only customer who has requested this, so it won't have the highest priority. I'll tentatively schedule it for April. I'll close this issue, so that we're not double-tracking the work. You can still comment on a closed issue. Just "@" mention the person you want.

**Comment by Rick-Kirkham** [comment]
On further research, we will not be strong typing the parameter of `requestCreateControls` after all, for the following reasons:

1. The shape of the parameter needs to be flexible. The [dynamic ribbon schema](https://developer.microsoft.com/json-schemas/office-js/dynamic-ribbon.schema.json) is expected to change over time. 
2. We have devised a system in which developers create JSON that matches the schema and then passes it to `JSON.parse()` to create the parameter for `requestCreateControls`. This is explained in [Create custom contextual tabs](https://learn.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs).
3. It is not necessary for validating the parameter. As explained near the top of the section [Define the groups and controls that appear on the tab](https://learn.microsoft.com/office/dev/add-ins/design/contextual-tabs#define-the-groups-and-controls-that-appear-on-the-tab), the schema can be used provide Intellisense while creating the JSON. There is a link there to how this can be done in Visual Studio Code. 
4. The type we created, if we strong-typed the parameter, would be confusing. For example, because the JSON must have a "version" property (that specifies the version of the schema), the parameter type would also have to have this "version" property which would make no sense as a property of a JavaScript type. 

I will, however, add some explanation to the reference topic for `requestCreateControls` explaining why it is not strongly typed.
