### ISSUE TITLE
how to set up EWS endpoint url for makeEwsRequestAsync

### ISSUE THREAD

**Issue by Kee3f** [OfficeDev/office-js#3192]
we have several ews url for different network area . do you know how to specify ews endpoint url？

**Comment by alison-mk** [comment]
Hi @F3eev, thank you for submitting! We use Github issues to report bugs with the product, and it looks like you are asking a more general programming question. For programming questions, we suggest you go to [Stack Overflow](https://stackoverflow.com/questions/tagged/office-js) and see if your question has already been asked or ask a new question. Stack Overflow has an active community of developers that regularly provide feedback and guidance. 

Since this isn't a bug, I will close this issue. Let me know if you have any questions!

Alison
