### ISSUE TITLE
Office.context.mailbox.item get bcc is null bug

### ISSUE THREAD

**Issue by hhqqnu** [OfficeDev/office-js#321]
Get the mailbox item recipient bcc is empty.
I have tried reading the source code of office.js and can't find the bcc attribute.

filename: outlook-web-16.01.debug.js
![image](https://user-images.githubusercontent.com/2911670/49422977-c4188680-f7d0-11e8-8543-186901d610cf.png)

**Comment by exextoc** [comment]
Currently, bcc property is only available in compose mode. Are you trying to access "bcc" in read-mode? Please read documentation on 'bcc' here: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item#bcc-recipientsjavascriptapioutlook15officerecipients

**Comment by kbrandl** [comment]
@hhqqnu does the information that @exextoc provided in this thread resolve this issue? If not, please add repro steps to this issue so that we can investigate.

**Comment by hhqqnu** [comment]
@exextoc Thank you for your answer, I am getting the "bcc" attribute in the sent message, I tried to pass "Office.context.mailbox.item.get_data()._data$p$0"
Get "bcc", which can be obtained in OWA, but not in OUTLOOK. The difference between OWA and OUTLOOK is shown in the screenshot below.

> This example is modified by "outlook-add-in-command-demo"

OWA:
![image](https://user-images.githubusercontent.com/2911670/49707659-3d97f500-fc67-11e8-87ab-93f302530977.png)

OUTLOOK:
![image](https://user-images.githubusercontent.com/2911670/49707667-47b9f380-fc67-11e8-9a8d-5cee6db8bf18.png)

**Comment by exextoc** [comment]
The way you are accessing the bcc property from the OWA API file is not publicly documented or supported in all clients. As stated earlier, there is no way to access the bcc property in Read in all clients (see [bcc](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/preview-requirement-set/office.context.mailbox.item#bcc-recipientsjavascriptapioutlookofficerecipients). If you would like to request this feature, please do so on our [UserVoice](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins) page.

**Comment by jschilmo** [comment]
Is it possible to re-open this issue or to get a working link to a location to suggest this as a feature, or some kind of a workaround?

We're developing an outlook add-in and would greatly benefit from being able to retrieve BCC emails in the Message Read context.

Edit: To clarify, if viewing a sent email in your Outlook inbox you can see the BCC emails, as you were the sender. Since that information is displayed right on the email you have selected it seems like it should be possible to expose that information through the API in the Message Read context under those circumstances
