### ISSUE TITLE
Web Add-ins not loading in Outlook Online

### ISSUE THREAD

**Issue by bogdanst24** [OfficeDev/office-js#3240]
Today I started to observe our Web Add-in doesn't load in Outlook Online. Then, figured out that suddenly **no Web Add-ins are loaded/available**. Outlook Desktop (Windows) and Outlook for Mac are still working as expected.
The issue is present regardless of the browser.

After the page is loaded, after a few seconds this error is reported to the console:
![image](https://user-images.githubusercontent.com/65173226/226935262-a0ce3860-e18b-463b-a973-ce240f108fc7.png)

**Please prioritize this issue, as it is critical!**

Other information that might help:
- name=scriptVer content=20230310007.20
- name=webServerForest content=eurprd02

Might also be related to this report: https://github.com/OfficeDev/office-js/issues/3231

____

**Update:** 
Something has changed and now the add-ins are loaded. However, there seems to be an issue currently related to access to roamingSettings from the Office.context

**Comment by bogdanst24** [comment]
After investigating it in the meantime, this is what we know:

1. We have customers still reporting that the Web Add-in does not show at all on the compose window. Something else that we observed is that the Apps pop-up is completely empty.
2. In other cases (our own subscriptions), it is only partially working. Communication through the RuntimeSettings doesn't work. The value seems to be saved, but then it is not persisted

**Comment by eugene-plutoflume** [comment]
I get the same error with event-based activation in OWA, see #3241 .

**Comment by bogdanst24** [comment]
The Add-in is using event based activation (OnNewMessageCompose and OnMessageRecipientsChanged). It might be the same issue, or at least the same root cause.
The worst part is that I'm not even able to debug. When I try using any manifest pointing to localhost, the add-in simply doesn't show and I can see another error in console.
![image](https://user-images.githubusercontent.com/65173226/227135367-10ce02cd-0cf4-4fc4-a80a-43dd1c3aa494.png)

**Please prioritize this issue or at least publicly acknowledge it somewhere. This is causing real damage.**

**Comment by exextoc** [comment]
Thank you for reporting the issue. We are able to repro it. We also want to highlight that this issue is only impacting users in Targeted Release, not Standard Release (learn more here: [Set up the Standard or Targeted release options - Microsoft 365 admin | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fmicrosoft-365%2Fadmin%2Fmanage%2Frelease-options-in-office-365%3Fview%3Do365-worldwide&data=05%7C01%7Cnikitamittal%40microsoft.com%7Cc6da7d64ef71453cc0ae08db2b6fa187%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638151530723008808%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4A5caLhbmTb80Vxvj6Z1dKY3FzhqmM%2B3NBrMP5emNMA%3D&reserved=0)). We will update the thread once we have more updates on the fix.

**Comment by bogdanst24** [comment]
Thanks for looking into it. Do you have any updates?

**Comment by exextoc** [comment]
The issue should be resolved now. Please let us know if you are still able to repro the same.

**Comment by bogdanst24** [comment]
I can confirm, I can't reproduce it anymore

**Comment by ArjunSureshKumar92** [comment]
@exextoc This issue is happening again. No addins are showing in the list
Our addin is available in the my addins sections:
![image](https://user-images.githubusercontent.com/35875176/234360619-7b23f6f0-d670-4e69-b8dc-4f1eee22992d.png)

But when trying to open it from the apps option in OWA there are no addins:
![image](https://user-images.githubusercontent.com/35875176/234360916-2327381e-d2a7-43ef-b082-4a45a1ec1ab3.png)

**Comment by exextoc** [comment]
@ArjunSureshKumar92 Thanks for reporting this issue. Can you please confirm whether you are seeing this issue in the Targeted release or in the Standard release channel? (learn more about the same here: [Set up the Standard or Targeted release options](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/release-options-in-office-365?view=o365-worldwide))

**Comment by ArjunSureshKumar92** [comment]
@exextoc  I had this issue in the Targeted release. After posting this issue, I switched to Standard for testing. Today in standard release, I can confirm it is working fine. I have switched again to Targeted release and the addin is not showing up. 
In short, the issue is with the Targeted release.
Thanks.

**Comment by ArjunSureshKumar92** [comment]
@exextoc My colleague has confirmed it is not working in the Targeted release.

**Comment by krubenok** [comment]
Hi @ArjunSureshKumar92, can you let us know which browser/os you're using to test this? Can you try it out in Edge (specifically, not in an InPrivate window)? Thanks!

**Comment by ArjunSureshKumar92** [comment]
@krubenok I tried in regular edge browser. I am using windows. 
Exact windows version:
![image](https://user-images.githubusercontent.com/35875176/235183853-1d02c336-8fdb-43af-9c5c-db02a6c33e69.png)

Exact Edge version:
Version 112.0.1722.58 (Official build) (64-bit)

**Comment by exextoc** [comment]
Hi @ArjunSureshKumar92 , can you please let us know if you are still able to repro this issue in the Targeted release  channel?

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
