### ISSUE TITLE
Outlook event-based activation doesn't work in OWA

### ISSUE THREAD

**Issue by eugene-plutoflume** [OfficeDev/office-js#3241]
If you try to follow the guide [Configure your Outlook add-in for event-based activation](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest) you will find the following error in the console:

![An error in the OWA.49099.js file](https://user-images.githubusercontent.com/32734640/226936574-4aa0de9a-5e85-483c-8c7e-aca0c2e3fa97.png)

And the `OnNewMessageCompose` event is not triggered in OWA. While Outlook for desktop works correctly.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: _
* Operating System: Windows x64
* Browser (if using Office on the web): Microsoft Edge Version 111.0.1661.44 (Official build) (64-bit)
 
## Expected behavior

The `OnNewMessageCompose` event is triggered in OWA.

## Current behavior

The `OnNewMessageCompose` event is not triggered in OWA.

## Steps to reproduce

Just follow the guide described at https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest

## Context

We can't use launch events in Outlook add-ins.

## Useful logs

![image](https://user-images.githubusercontent.com/32734640/226938967-8e7f972c-17a2-4bd2-b954-bc256e720287.png)

Thank you!

**Comment by neville-jones** [comment]
Seems similar to #3240 , at least the error being reported in the console.

**Comment by exextoc** [comment]
@eugene-plutoflume Thank you for reporting the issue. We are able to repro it. We also want to highlight that this issue is only impacting users in Targeted Release, not Standard Release (learn more here: [Set up the Standard or Targeted release options - Microsoft 365 admin | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fmicrosoft-365%2Fadmin%2Fmanage%2Frelease-options-in-office-365%3Fview%3Do365-worldwide&data=05%7C01%7Cnikitamittal%40microsoft.com%7Cc6da7d64ef71453cc0ae08db2b6fa187%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638151530723008808%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4A5caLhbmTb80Vxvj6Z1dKY3FzhqmM%2B3NBrMP5emNMA%3D&reserved=0)). We will update the thread once we have more updates on the fix.

**Comment by exextoc** [comment]
The issue should be resolved now. Please let us know if you are still able to repro the same.

**Comment by eugene-plutoflume** [comment]
The issue has been fixed, the events were returned back on Monday.
