### ISSUE TITLE
[Outlook for windows] 5100 error wait until the previous call completes.

### ISSUE THREAD

**Issue by Howard-Song** [OfficeDev/office-js#3274]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **PC desktop**
* Host [Excel, Word, PowerPoint, etc.]: **Outlook**
* Office version number:  **Version 2302(Build 16130.20332)**
* Operating System:  **Windows 11**
* Browser (if using Office on the web): N/A
 
## Expected behavior

Return correct response when calling Office API.

## Current behavior

When using Office API on Outlook windows client, will return 5100 error:
```javascript
{"name":"API Call Failed",\"message":"Wait until the previous call completes.","code":5100}
```
Can someone can explain or provide something to avoid this error? 
## Steps to reproduce

Run this following code with **script lab** on Outlook windows client
```javascript
$("#run").click(loop);
let count = 0;
let now = new Date().getTime();
function loop() {
  window.Office.context.mailbox.item.to.getAsync((result) => {
    if (!isSuccess(result)) return retry();
    window.Office.context.mailbox.item.cc.getAsync((result) => {
      if (!isSuccess(result)) return retry();
      window.Office.context.mailbox.item.bcc.getAsync((result) => {
        if (!isSuccess(result)) return retry();
        window.Office.context.mailbox.item.getAttachmentsAsync((result) => {
          if (!isSuccess(result)) return retry();
          window.Office.context.mailbox.item.sessionData.setAsync("test", new Date().getTime() + "", (result) => {
            retry();
          });
        });
      });
    });
  });
}

function retry() {
  setTimeout(() => loop(), 300);
}
function isSuccess(result) {
  if (result.status !== window.Office.AsyncResultStatus.Succeeded) {
    console.log("error count:", count, "duration:", (new Date().getTime() - now) / 1000 + "s", result);
    now = new Date().getTime();
    count = 0;
    return false;
  } else {
    count++;
    return true;
  }
}
```
## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
Loop time set to 300ms:
![Screenshot 2023-04-04 at 17 32 52](https://user-images.githubusercontent.com/28775661/229754093-e6a2177b-4bd5-442e-a3cd-0931bacfb053.png)
Loop time set to 3000ms:
![image](https://user-images.githubusercontent.com/28775661/229758204-b7a45807-1feb-4dfd-8b8d-32fd64cc5617.png)

We have some data on 5100 error, it will happened on these version:
![Screenshot 2023-04-04 at 17 31 33](https://user-images.githubusercontent.com/28775661/229754292-c7d737b7-f482-44a8-b53b-48a3dca4fb8b.png)

**Comment by timwan10** [comment]
I could not repro this with your script, running this once. However, If I pressed the "run" button in script lab a BUNCH. I would eventually repro it. I was able to follow up with the product team. 

When an Add-in makes an async function call to the client. (i.e. to.GetAsync()) If there are over 1,000 existing concurrent async calls, it will return this error. (this is kind of a sanity check to make sure Add-ins don't have a bug or maliciously make too many API calls).

**Comment by Howard-Song** [comment]
@timwan10  But the next API call will start in the previous callback, so you mean that callback doesn't finish the previous API call? How does Offic-JS to calculate the 1,000 async calls?

**Comment by timwan10** [comment]
In your test script does it repro every time you click the button **Once**? (I couldn't get this to repro). It makes sense if I clicked the button a bunch of times, it puts repeating calls of API calls in a loop, and the concurrent calls would eventually hit 1000. 

In theory, there could be a bug somewhere that is "leaking" a count of the calls. 

Are you hitting this in a real world scenario?

**Comment by Howard-Song** [comment]
@timwan10  Yes, it happened when I click button Once. And Just in Outlook for 365 windows client, version include Version 2302(Build 16130.20332). Any outlook for windows 365 client may can repro this issue.

**Comment by timwan10** [comment]
I haven't been able to repro with your script just clicking once. Is there anything special about the email that you're composing/sending this on?

Are you also doing something that could cause this in a real world add-in? (i.e. making a ton of api calls) in general that isn't recommended?

**Comment by Howard-Song** [comment]
New compose message, then open script lab run the script and wait for minutes. Then the error will log in console. I haven't open other add-in or message, just one compose message, and error happened.

**Comment by timwan10** [comment]
Does this only happen in Script-Lab? or also your production Add-in?

**Comment by Howard-Song** [comment]
Both

**Comment by timwan10** [comment]
I was able to follow up with the product team. I was incorrect in the 1000 call limit. The actual number is 50. An Add-in is only allowed 50 pending Async calls to the client, before you start getting that error. That being said after a call is finished, it no longer counts towards that number. In your script lab example, it is only putting one call in the queue at a time. To the point, where I *cannot* repro the issue in script lab? I was able to repro the issue if I clicked on the Run button approx 50 times...as that puts 50 simultaneous calls into the queue constantly. 

However even after running the script lab example for hours...I never was able to observe the error, even after several million cycles of the loop. 

In your production add-in, if you are getting this error. You may need to re-examine the code to see if there is some loop, etc. that can continually put calls into the queue to avoid this. 

What is your scenario that you need to make repeated API calls into the client? There may be a better way to achieve what you are trying to do if you can describe your scenario.

**Comment by Howard-Song** [comment]
@timwan10  Have you try on Outlook for windows client? The error screenshot is come from script lab not our production add-in.

**Comment by timwan10** [comment]
Yeah, all our tests are on Win32 Outlook on "old" outlook: (from your version number I assume you are also NOT on "new" Outlook)

![image](https://github.com/OfficeDev/office-js/assets/17890744/87040f37-e4ab-4ed9-9126-7fc32190726b)

I tried script lab with your script, and ran it for quite a long time (and also reduced the timeout) and couldn't produce a repro. The dev team took a look, and the underlying code to triggering the 50 call limit wasn't close to being reached. It WAS reached if the Run button was clicked a lot. (which would be by design). When Script Lab was stopped, they could also see that the internal code, tracking the call limit went back down to 0...which kind of means that there isn't any known "leak" of the call count. 

It's possible that you are on some other unique scenario (maybe a slow machine?) that is different that is triggering this. But if this is also happening in your production add-in with customers then this could be a problem with your add-in. The limit for this is so high, that it really shouldn't be possible to hit this without something weird going on. For example doing something like your example in script lab isn't recommended, as it will constantly make an API call to the Client in a loop. 

I would say there is either something unique to your scenario that is missing from the repro steps that causes us not to be able to repro the issue. Or there is something in your Add-in that is making a lot of api calls at the same time (again hitting this limit is quite high...we've never seen someone hit this error before). Again making a lot of api calls from an add-in kind of indicates that there may be a better solution? (are you polling instead of using events?) Describing you scenario could help. 

I don't want to discount the possibility of a bug, but right now we cannot repro with your repro steps, so we need more information on the repro.
