### ISSUE TITLE
Opening add-in task pane is modifying the document unexpectedly

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/office-js#3296]
We have a task pane add-in, whenever a user opens the task pane the document is modified, when I check the DOCX file I can see a folder has been added called webextensions which contains metadata information about our task pane etc

![image](https://user-images.githubusercontent.com/137350/231936907-567050f8-06d9-43bf-9402-3288c0ca1afe.png)

This is unexpected, as we aren't calling any sort of functions to add this information to the document...

**Comment by xuruiyao-msft** [comment]
@catmanjan  Actually this is as expected behavior.  Whatever add in opened, once you save the word, the webextensions folder would be added.

**Comment by catmanjan** [comment]
@xuruiyao-msft where is this documented?

**Comment by slabereemsft** [comment]
Hi @xuruiyao-msft 

The documentation can be found here - https://learn.microsoft.com/en-us/openspecs/office_standards/ms-owexml/a2cd741a-4cca-4b1a-ade4-b2c443972afa

**Comment by catmanjan** [comment]
@slabereemsft  sorry but where in that documentation does it say if/when the document will be modified by opening an add in?

In highly audited environments information on document modifications must be accurate and we don’t understand the business rules Microsoft is applying

**Comment by slabereemsft** [comment]
Hi Catmanjan,

Sorry for not fully understanding your question!  The documentation above contains the schema and examples of what can get persisted to the files.  In some cases, that's relatively self explanatory. E.g. when you insert a content add-in the document, you have a reasonable expectation that its going to persist some of its state just by virtue of having inserted it.  

When Office Add-ins (was Apps for Office) were introduced in Office 2013, the main gesture to use them was to Insert them regardless of whether they were a taskpane or content add-in. The behaviour you are seeing is a result of that historic implementation that hasn't been cleaned up, in part because the UI to Insert add-ins from the Insert menu is still available.  

Does that help?

**Comment by catmanjan** [comment]
@slabereemsft thanks that makes sense, as a legacy holdover are there any plans to remove the behavior for add-ins that don't write to the document?

At the moment we have highly secure environments that use the check out paradigm, so unlike cobalt/fsshttp interactions users are acutely aware every time a new version is created.

This is confusing users who are checking out a document, not making any changes other than opening an add in, and then being prompted to save changes (when they believe they have not made any, and making a change to one of these documents is an auditable action)

**Comment by slabereemsft** [comment]
At this time we do not have any plans to remove that behaviour.  We're definitely listening to feedback so if more folks run into this as a problem we may reconsider that.
