### ISSUE TITLE
OfficeRuntime.storage not available on Outlook (Desktop and OWA)

### ISSUE THREAD

**Issue by teejay001** [OfficeDev/office-js#3312]
# "OfficeRuntime.storage" was suggested as an alternative to local storage for launch events but this as proved not so because the OfficeRuntime.storage is undefined.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop and OWA
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2303
* Operating System: Windows
* Browser (if using Office on the web): Chrome
* 
## Expected behavior

I expected to be able to store data within OfficeRuntime.storage during launch event and retrieve on the taskpane, and vice versa

## Current behavior

I do not have access to the  OfficeRuntime.storage object so I can not prove it usage 

## Steps to reproduce

1. Follow instruction to create an Add-In which uses smart alert (https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest) 
2. Update the code to be able to store and retrive data from  OfficeRuntime.storage  (https://learn.microsoft.com/en-us/samples/officedev/pnp-officeaddins/using-storage-to-share-data-between-ui-less-custom-functions-and-the-task-pane/)
3. Spin up Add-In and try sending a message as instructed in step 1 above (https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest)

## Link to live example(s)

Repo: https://github.com/teejay001/-OfficeRuntime.storage

# Provide additional details

The Console error and the log showing  OfficeRuntime.storage is undefined
![image](https://user-images.githubusercontent.com/99417649/234272437-4078846b-1dfb-4a93-ad1c-63d51cdc6fb6.png)

## Context

Since the future of Add-In is the use of smart alert, we need to ensure we can meet all business requirements and technical requirements

## Useful logs

- [ ] Console errors
![image](https://user-images.githubusercontent.com/99417649/234275288-97e1a98a-8c5d-4366-856f-3295bde12fec.png)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Hey @teejay001 ,

Sorry for the delay in response. We have confirmed that OfficeRuntime.storage is indeed not available in Outlook for Web. We will update our documentation regarding the same. Thank you for reporting this.

**Comment by kaizen-lazevedo** [comment]
Hi @exextoc,
What would then be the best way then to create a local cache of data in Outlook so it works when it's offline ?

My goal would be to download a small list of atributes from our server using  "event-based activation" and then save it on OfficeRuntime.storage which would then be accessed by the taskpane, but if I try to access OfficeRuntine.storage on the taskpane is always null.

**Comment by kaizen-lazevedo** [comment]
> Hi @exextoc, What would then be the best way then to create a local cache of data in Outlook so it works when it's offline ?
> 
> My goal would be to download a small list of atributes from our server using "event-based activation" and then save it on OfficeRuntime.storage which would then be accessed by the taskpane, but if I try to access OfficeRuntine.storage on the taskpane is always null.

Found the answer, OfficeRuntime can't be used to share data between event-based functions and Taskpane in Outlook because there is no Shared runtime, from the documentation:

"For Excel, PowerPoint, and Word add-ins, use a [Shared runtime](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtimes#shared-runtime) when any two or more features, except dialogs, need to share data. In Outlook, or scenarios where sharing a runtime isn't feasible, you need alternative methods."

Instead, Office.SessionData should be used on windows and localStorage on MAC:
"To share data between an Outlook event-based task and a task pane or function command, you must branch your code by the value of the [Office.context.platform](https://learn.microsoft.com/en-us/javascript/api/office/office.context#office-office-context-platform-member) property.

When the value is PC (Windows), store and retrieve data using the [Office.sessionData](https://learn.microsoft.com/en-us/javascript/api/outlook/office.sessiondata) APIs.
When the value is Mac, use Window.localStorage as described earlier in this list."

**Comment by exextoc** [comment]
You can use [Office.sessionData](https://learn.microsoft.com/en-us/javascript/api/outlook/office.sessiondata) in Mac as well now. It's supported in New Outlook as a part of 1.11 API set. Please check following docs for more details: 
[Outlook client support](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/outlook-api-requirement-sets?view=powerpoint-js-preview&tabs=xmlmanifest#outlook-client-support)
 [Outlook add-in API requirement set 1.11](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/requirement-set-1.11/outlook-requirement-set-1.11?view=powerpoint-js-preview)
