### ISSUE TITLE
Mac Outlook - New UI - Add-ins that run appendOnSendAsync on a timer will block other Add-ins from sending messages

### ISSUE THREAD

**Issue by carlosb1504** [OfficeDev/office-js#3407]
One of our customers uses a 3rd party add-in as part of their CRM solution, that add-in uses a taskpane which polls on a timer, and as part of this calls item.body.appendOnSendAsync().

In Mac Outlook only, this means that any other add-ins running side by side, cannot send items using the OnSend hook (by calling event.completed(true) to send the message.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac Outlook 
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.73.1
* Operating System: Mac Monterey 12.6.6
* Browser (if using Office on the web): N/A
 
## Expected behavior
Given a taskpane app that uses appendOnSendAsync() on a timer, other add-ins should still be able to invoke OnSend and call event.completed(true).

## Current behavior

The add-in calling event.completed(true) loops continuously and the message cannot be sent.

## Steps to reproduce

See github link below for a ScriptLab example using this Taskpane + append on sync combination. Run this alongside any add-in using OnSend. the OnSend need not do any actual processing. Just call event.completed(true) in order to allow the message to be sent. 

Observe that the message does not send and instead loops forever or until an error occurs and the message cannot be sent.

## Link to live example(s)

https://gist.github.com/carlosb1504/46c7726b0b7aa295f1ad2408a32b781e

**Comment by carlosb1504** [comment]
Works fine in all versions of Windows Outlook and OWA that I've tried. 

Also downgrading to 'Legacy Mac Outlook' resolves the issue. It's just Mac Outlook with the new UI that is affected.

**Comment by exextoc** [comment]
Hi @carlosb1504 
Thanks for reporting this issue. We tried to reproduce this issue. Steps followed:
1. Install an On-Send add-in which calls event.completed.
2. Run the gist provided by you. 
3. Enter some text to be appended.
4. Send email. 
The email was sent with appended text and we were not able to reproduce it. 

Can you give us a video of the issue or send the manifest of the other add-in which you are running with this gist on this email id - [OutlookExtensibility@M365x27035562.onmicrosoft.com](mailto:OutlookExtensibility@M365x27035562.onmicrosoft.com) . 

Just a note - On Mac, if you send plaintext then please pass Office.CoercionType.Text  to the appendOnSendAPI. And if it is HTML, pass the coercion type as Office.CoercionType.Html . I saw in the gist that the default value is a plaintext with Html coercion type. This will not append anything because of an existing bug on Mac. 
Change the type to Office.CoercionType.Text, to make it work with your default text.

**Comment by carlosb1504** [comment]
Thanks for the reply @exextoc - appreciate the comment about the coerciontype. I was replicating exactly what I found the 3rd party add-in was doing which is hard coding to Html but I'll bear that in mind going forward.

Let me double check the steps on mac and I'll try to provide the manifest for a simple app which exhibits the problem.

**Comment by exextoc** [comment]
@carlosb1504 Please mark needs attention after checking back and sharing the manifest.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding appendOnSend. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: 8039753

**Comment by exextoc** [comment]
This issue is fixed, and fix is available in version >= 16.76.23070403
