### ISSUE TITLE
Event on closing the Excel workbook 

### ISSUE THREAD

**Issue by stenly311** [OfficeDev/office-js#3427]
## How to get an event in the Task pane about the Excel workbook closing action

Is there any way how to get a notification event to the Task pane (Office.JS) in the Excel workbook about the user closing the workbook?

Thanks.

**Comment by donlvMSFT** [comment]
Hi @stenly311 ,

Thanks for letting us know this issue. However, currently, the feature: Workbook onClose event, you requested, is not a part of the product. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests are considered when we go through our planning process. 

Thanks, Microsoft 365 Developer Platform team

**Comment by stenly311** [comment]
@donlvMSFT thanks for your reply. I have raised that as a new idea as suggested. Link: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/office-js-web-add-in-add-workbook-onclose-event/idi-p/3848764#M1825 

Please, vote up :) thanks

**Comment by adrianwu8516** [comment]
Hi @stenly311, 

Since the feature request was created in the tech community, we will continue to track the feature requests from the forum and close the issues here on GitHub. 

For people who also expect this feature, please feel free to vote up and leave comments on [this post](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/office-js-web-add-in-add-workbook-onclose-event/idi-p/3848764#M1825) so that we can gather all the feedback and prioritize properly. 

Thank you very much!
