### ISSUE TITLE
"Uncaught (in promise) RichApi.Error: An internal error has occurred." "Error Status code: 5001"

### ISSUE THREAD

**Issue by VB-007** [OfficeDev/office-js#3440]
In the excel add-in, we have used Excel Javascript API functions for Pivottables. We can drag and drop the columns in respective filed. When we do drag and drop operations 15-20 times, it shows "Uncaught (in promise) RichApi.Error: An internal error has occurred." "Error Status code: 5001". We tried to debug with the documentation available in excel Javascript API, but could not solve the issues. Any help to solve this issues will be helpful 
[Screen Shot of console error.docx](https://github.com/OfficeDev/office-js/files/11787309/Screen.Shot.of.console.error.docx)

**Comment by VB-007** [comment]
It'd be grateful if you could provide some assistance to solve the issue above

**Comment by yuc014** [comment]
Hi @VB-007 , 

Please give more details about how to repro your issue, for example repro steps and the code. It is better if you have a recording video. Then I can help you with this.

**Comment by VB-007** [comment]
The reason seems to be that remove API is not working. Remove api is currently not available in excel API

**Comment by yuc014** [comment]
Hi @VB-007 , sorry to hear that. If you refer to this issue: https://github.com/OfficeDev/office-js/issues/3462. Then yes, remove api is not in Excel.PivotHierarchyCollection class now.

Normally, we recommend following https://learn.microsoft.com/en-us/javascript/api/excel/excel.tablerowcollection?view=excel-js-preview to see what apis we can use. Sometimes, apis not in our doc will not show a red line or compile error in js code, because some apis are ok for js. But it may not perform what you expect in the document.

For new feature request, we would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.
