### ISSUE TITLE
Error in remove function in Pivot 

### ISSUE THREAD

**Issue by VB-007** [OfficeDev/office-js#3462]
I am working in Excel add-in with Pivot table (PivotFilter Function), I can add the filter with the following code from document.
but when I use remove function it removing the filter which I added, after agian I add in filter It getting error(An Internal error has occoued) 
after excel is closed.

 

This below code only I did:
async function add_pivot_filter() {
  await Excel.run(async (context) => {
    await context.sync();
    let pivotTable = context.workbook.worksheets.getActiveWorksheet().pivotTables.getItem("Farm Sales");
    // check if the PivotTable already has rows
    await context.sync();
    // addind one filter
    let classHierarchy = pivotTable.filterHierarchies.getItemOrNullObject("Classification");
    await context.sync();
    if (classHierarchy.isNullObject) {
      classHierarchy = pivotTable.filterHierarchies.add(pivotTable.hierarchies.getItem("Classification"));

      await context.sync()
    }
    // again adding another one filter
    let framHierarchy = pivotTable.filterHierarchies.getItemOrNullObject("Farm");
    await context.sync();
    if (framHierarchy.isNullObject) {
      framHierarchy = pivotTable.filterHierarchies.add(pivotTable.hierarchies.getItem("Farm"));

      await context.sync()
    }
    // removing one filter
    let filter_remove = pivotTable.filterHierarchies.getItemOrNullObject("Classification");
    await context.sync();
    if (filter_remove.isNullObject == false) {
      pivotTable.filterHierarchies.remove(filter_remove);
      await context.sync();
    }
    // again adding one filter
    let TypeHierarchy = pivotTable.filterHierarchies.getItemOrNullObject("Type");
    await context.sync();
    if (TypeHierarchy.isNullObject) {
      TypeHierarchy = pivotTable.filterHierarchies.add(pivotTable.hierarchies.getItem("Type"));

      await context.sync()
    }
  });
}

Note:
* I am adding one filter it adding without any error.
* Again adding another one filter it adding without any error.
* After I removing one filter it removing.
* After adding one filter again the excel sheet was closed.
The error was((An Internal error has occoued)). error status code 5001

 

Error Image:
<img width="462" alt="image" src="https://github.com/OfficeDev/office-js/assets/57539419/81706359-02af-4bcc-9dd6-75755072a250">

**Comment by yuc014** [comment]
Hi @VB-007 ,
After reading your code, I think the issue is in this line
```
pivotTable.filterHierarchies.remove(filter_remove);
```
In the offcial Doc: https://learn.microsoft.com/en-us/javascript/api/excel/excel.pivothierarchycollection?view=excel-js-preview
There is no "remove" method for Excel.PivotHierarchyCollection class.
So, this will not work as you expect.

Normally, we filter the pivot table like this: https://gist.github.com/yuc014/a6276fd8dd4a828967e246e2f2678c3a
And when you added a filterHierarchy, it cannot be removed based on my knowledge, you just can clear the criteria.

If, you have a strong need for remove this "filterHierarchy". The workaround is to re-initialize the whole pivot table.

And you can go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform to send a new feature request. Feature requests on it are considered when we go through our planning process.
