### ISSUE TITLE
range.getImage() captures the page number watermark.

### ISSUE THREAD

**Issue by mburbea** [OfficeDev/office-js#3471]

**Comment by yuc014** [comment]
Hi @mburbea , 
Please give more details about how to repro your issue, for example repro steps and the code. It is better if you have a recording video. Then I can help you with this.

**Comment by mburbea** [comment]
Apologies, my companies compliance  was making it difficult for me to share an example. 
I'm uisng the following code to get the named range and turn it into a base64 image:

```js
export function getImagesAsBase64(context: Excel.RequestContext) {
  const { names, properties } = context.workbook;
  const items = properties.custom.items;
  return names.items
    .filter(
      ({ name, type }) =>
        /^dg\./i.test(name) &&
        type === "Range" &&
        !items.some(({ key }) => key === name)
    )
    .map(
      (v) =>
        [v.name.substring(3) + ".png", v.getRange().getImage()] as [
          string,
          OfficeExtension.ClientResult<string>
        ]
    );
}
```

If a user leaves the page where the named range exists in the page break preview mode they will get the page number watermark. See an example image attached:
![mburbea](https://github.com/OfficeDev/office-js/assets/213233/df5b9d65-f2d8-4fb0-bb60-ce5097a03f41)

**Comment by yuc014** [comment]
@mburbea Finally I can repro your issue after a long-time investigation.
I have created an internal bug #8116488 in our backlog. Then our engineers will look at it.

**Comment by SiruiSun-MSFT** [comment]
Hi @mburbea, After opening the page break preview of Excel, it will automatically show the page number in the form of a watermark. There seems to be no way to hide this watermark on the UI (unless you switch to normal view).
![image](https://github.com/OfficeDev/office-js/assets/86719968/38d4baa2-14e2-46a7-ab03-15220994a897)


In this case, the current behavior of range.getImage() can be considered as By Design. The background watermark is also considered to be part of the current range and appears in the Image, which will not be removed.
![image](https://github.com/OfficeDev/office-js/assets/86719968/10d87c32-7daa-4e1f-99a5-9ef7e250160d)

If you want to delete the watermark, you can only switch back to the normal view. But our JS API does not seem to support the switch currently. If you need our support, please add your request there [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Feature requests are considered when we go through our planning process. Thanks!
