### ISSUE TITLE
Viva cards by default rendering in Medium View even though card size is configured as Large

### ISSUE THREAD

**Issue by harshkumardubey** [OfficeDev/office-js#3484]
# Provide required information needed to triage your issue
We created custom viva cards by default it's returning card size value large even though it's rendering in medium view but when admin is changing it's value from Sharepoint or from Teams from large to medium and then back to large it starts working fine.

<img width="1344" alt="MicrosoftTeams-image (6)" src="https://github.com/OfficeDev/office-js/assets/83409796/d5ecb687-ee06-4d50-b1d6-c61826ea320a">

 
## Expected behavior
Viva cards should render in whatever is configured.

## Current behavior
Viva cards by default rendering in Medium View even though it's configured as Large View

**Comment by yjoshi-msft** [comment]
Hi harshkumardubey,
Thank you for raising the issue. We would ideally need more information to reproduce the issue on our end properly. 

Please fill in more information following the below template format - 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior


## Current behavior



## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)



1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context



## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.

**Comment by harshkumardubey** [comment]
Platform [PC desktop, Mac, iOS, Office on the web]: MacOS
Host [Excel, Word, PowerPoint, etc.]: Microsoft Teams / Sharepoint
Office version number: Microsoft Teams Version 1.6.00.16465.
Operating System: MacOS Ventura 13.4.1 (22F82)
Browser (if using Office on the web): Reproducible on both Teams Client / Web

Expected behavior: Viva cards should render in large view.
Current behavior: Viva cards not rendering in large as in above screenshot.

Steps to reproduce

Create custom viva card by following this document https://learn.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part.
Upload new solution in sharepoint.
