### ISSUE TITLE
Outlook for Mac not returning itemID of email

### ISSUE THREAD

**Issue by tobiasviehweger** [OfficeDev/office-js#3516]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.74.2 (23062500)
* Operating System: OS X 10_15_7
 
## Expected behavior
itemID is provided

## Current behavior
itemID is empty
![image](https://github.com/OfficeDev/office-js/assets/2111803/06c01397-f51e-4f48-a73c-8ebe55d703f8)
![image](https://github.com/OfficeDev/office-js/assets/2111803/14b6654d-26e1-474d-8f93-edb1ede1ee13)

## Steps to reproduce
We can't reproduce this on our side - even with the same version of Outlook

## Link to live example(s)
n/a

# Provide additional details
Works in OWA
AccountType = office365

**Comment by exextoc** [comment]
Hey @tobiasviehweger 

Can you help us with more details here?
What scenario are you trying? 
Or if there is any sample manifest that can be used to reproduce it?

**Comment by tobiasviehweger** [comment]
Hi @exextoc - it's really just accessing the current email in the Outlook add-in (we do it from the ribbon click handler). 
```
<Action xsi:type="ExecuteFunction">
     <FunctionName>executeCommand</FunctionName>
</Action>
```

We can't reproduce this on our side, even on the same version of Outlook for Mac. For this one customer, a few Mac users seem to be facing this issue, where all mail data (Office.context.mailbox.item) is present, except the ID. As stated, it does not appear to be a mailbox issue, because it works in OWA for them. We're not really sure how this can happen at all:
```
Office.context.mailbox.item.conversationId => Has value
Office.context.mailbox.item.internetMessageId=> Has value
Office.context.mailbox.item.itemId => Empty
```

**Comment by tobiasviehweger** [comment]
Not sure if this could be related to #3508

**Comment by exextoc** [comment]
Hey @tobiasviehweger, can you also collect the Diagnostics and share the Incident Id as well.
'Help -> Collect Diagnostics and share the incident ID`

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.

**Comment by tobiasviehweger** [comment]
@exextoc  Here's the incident ID: DuSYEHRC6F

**Comment by exextoc** [comment]
Thanks for the incident id @tobiasviehweger . We were not able to discern much details out of this one incident. If this reproduces again, could you please share the incident id again? 
We also have a few follow up questions:
1. Is this a consistent repro for the particular user?
2. Is it happening on any particular email or conversation?
3. What are the exact steps being followed by the user to repro this issue?
4. Could you provide us with a test account in the tenant where this issue is happening?
5.  Is this happening when the user is replying to an existing email?

**Comment by benjaminyasoon** [comment]
@exextoc Hi there, we can provide you with a new inicident ID: A38SU2KS

- Is this a consistent repro for the particular user?
Yes
- Is it happening on any particular email or conversation?
No, it happens with any email
- What are the exact steps being followed by the user to repro this issue?
He opens up an email and clicks on the ribbon of our app "new issue". It can't be loaded because we are not getting any email ID (like described from Tobias above).
- Could you provide us with a test account in the tenant where this issue is happening?
We don't think this might be possible. If nothing can be investigated I will surely ask our customer.
- Is this happening when the user is replying to an existing email?
It is an existing email he received, but he is not replying but trying to open it up via our application (as mentioned).

Let me know if you find out something :)

**Comment by exextoc** [comment]
@benjaminyasoon Can you please confirm if the Incident ID was generated after reproducing the issue. As per the incident Id A38SU2KS, things seem to work fine.
Please follow below steps to Generate Incident ID.
Steps to generate Incident ID:
1.       Re-launch Outlook 
2.       Repro the issue mentioned
3.       Click on Help->Collect Diagnostics
4.       Share the ID generated.

**Comment by benjaminyasoon** [comment]
@exextoc After clarifying: Yes, the user proceeded exactly as you described. I don't know if this would be helpful for you but we can offer you to have a screen sharing call together to determine this. In this case maybe you could provide me with your availabilities and in which time zone you are located. We (and the customer of ours) are on CEST.

**Comment by exextoc** [comment]
@benjaminyasoon If you can provide a manifest and screen recording of the issue, it would also be helpful. Please highlight where the item Id is null in the video.

**Comment by benjaminyasoon** [comment]
@exextoc We are trying to get the customers approval for a screen recording and see if we can have a screen cast session with him. I'll let you now about any updates.

**Comment by exextoc** [comment]
@benjaminyasoon 
1) Can you please create powerlift logs and send the ID?
2) Are you seeing this issue with a single user or multiple users?

**Comment by benjaminyasoon** [comment]
@exextoc We are still waiting for the last response from our customer. Keep you updated about this.
Answering your second question: This issue occurs only for Mac-users on this tenant, I.e. at least two users with Mac for this specific customer are having this issue.
