### ISSUE TITLE
Setting cookie in OfficeJS Dialog API window is not reflected in Taskpane window in Desktop Excel

### ISSUE THREAD

**Issue by fds-sj** [OfficeDev/office-js#3519]
# Provide required information needed to triage your issue

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]:  Desktop Excel using Edge Webview2
* Host [Excel, Word, PowerPoint, etc.]:  Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2208 Build 16.0.15601.20676) 64-bit
* Operating System: Windows 10
 
## Expected behavior
- When setting a cookie inside the officejs dialog api window, it should be shared and usable by the taskpane
- Expected behavior works in Office on the web but not consistent in Desktop Excel (not working for others)
![browser-cookie-working](https://github.com/OfficeDev/office-js/assets/105348054/4b74c098-389e-4abb-9ecc-ee687a2afde9)

## Current behavior
- Set cookie in the dialog window is not being shared with the taskpane in Desktop Excel
![desktop-excel-cookie-not-working](https://github.com/OfficeDev/office-js/assets/105348054/2cb17661-4a9d-4581-a90a-1c60ab08d765)

## Steps to reproduce
1. Open addin in desktop excel
2. Open officejs dialog api, set a cookie, and message parent without passing set cookie values in the message
3. On message receive, log or display the cookie by reading `document.cookie`
4. Verify that cookie is not available

## Link to live example(s)
- In order to reproduce this, we created a small reproducer that only uses officejs dialog api and scripts to set cookie
- Reproducer link: https://github.com/fds-sj/officjs-dialog

## Context
- We've recently moved our authentication system to use OfficeJS Dialog API which we expect to work since this is the recommended way according to the documentation. 
- We open an authentication page in the dialog, user logs in, authentication cookies are set, and redirects to a successful authentication page. This messages the taskpane to redirect to another page which would only work if auth cookies are set in the taskpane as well.
- This works smoothly in the browser, but is observed to not work on some machines in Desktop Excel.
- We want to ensure that our authentication flow would not fail before releasing to Desktop and Mac.

**Comment by samantharamon** [comment]
Thanks for reaching out, @fds-sj.

@slabereemsft, could you please investigate this Dialog API behavior?

**Comment by fds-sj** [comment]
Hi @samantharamon, @slabereemsft,  are there any updates regarding this issue?

**Comment by rvendiola-fds** [comment]
@samantharamon can we get an update here please? This is a critical blocker for our add-in release on the Mac and PC/Desktop.

**Comment by pkkj** [comment]
Hi, 
Based on the [documentation ](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/auth-with-office-dialog-api)here, the dialog should communicate with the taskpane via message API only. Office is not a browser so developer could not treat dialog and taskpane as two tabs like other browser.
Thanks.

**Comment by bermylle** [comment]
Hello @pkkj,

The authentication problem we're encountering seems to be limited to specific machines. Any thoughts on why this might be happening?

**Comment by bermylle** [comment]
Hi @pkkj, 

I have another question I'd like to ask. According to the documentation you provided, the dialog and task pane are two separate browser instances. How does this account for the successful logins we're experiencing? It's worth noting that the authentication issue, where cookies aren't shared between the two components, is not as common as the instances of successful logins on our application. Can you clarify this part so that we can figure out a way to get the login authentication succeed consistently?

**Comment by pkkj** [comment]
Hi Bermylle,

I just did a quick test in my local machine and verified that cookie from dialog will be shared to the taskpane, if they are in the same domain. Since I am not able to access the source code from your project, I am not able to tell why. But I am wondering is this caused by your local test environment (since you are using localhost). Browser may have special behavior for such domain. If possible, you may test your scenario against a real domain.

Thanks.

**Comment by bermylle** [comment]
hello @pkkj,

We have a reproducer for the issue and it is accessible on https://github.com/fds-sj/officjs-dialog. 

`I just did a quick test in my local machine and verified that cookie from dialog will be shared to the taskpane, if they are in the same domain.`
The cookies are properly shared on Web, but there is an issue when sideloaded on PC. We've made sure that both dialog and taskpane share the **same domain**, yet the behavior on PC is still different. 

I created a GIF where I show the cookies being shared on Web versus PC. 

Reproducer [Web] - Cookies are properly shared
![reproducer - web](https://github.com/OfficeDev/office-js/assets/50631121/e537d047-c52d-48ee-9409-d8ed7cc4eee7)

Reproducer [PC] - Cookies are **not** shared
![reproducer - pc](https://github.com/OfficeDev/office-js/assets/50631121/115cc2c4-a48a-4fe0-852e-00dd7ba8d75b)

**Comment by bermylle** [comment]
Hey @pkkj,

We identified the cause of the issue and it occurs when we sideload manifest files with the debug mode activated. It will show a "WebView Stop on Load" dialog and will disable the sharing of cookies between the dialog and task pane. 
![image](https://github.com/OfficeDev/office-js/assets/50631121/0ffc952d-961b-4053-adb6-a250ba090c31)

We will start using the [office-addin-debugging](https://www.npmjs.com/package/office-addin-debugging) for sideloading so that we can explicitly disable debug mode to avoid issues.

**Comment by pkkj** [comment]
Hi @bermylle,

Thanks for letting me know. I feel that debug mode and "localhost" domain will cause some trouble for the cookie but I believe that in production environment, cookie should work.

Thanks.
