### ISSUE TITLE
Can't set a test license token in an Outlook addin

### ISSUE THREAD

**Issue by THPubs** [OfficeDev/office-js#352]
I'm trying to set a test license token in an Outlook add-in. According to the documentation, I have to set it in the `SourceLocation` in the manifest file:

    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:3000?et=%3Cr%3E%0A%20%20%3..."/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>

The problem is, when I try to get the URL query params, it won't work. `window.location` looks like this:

`https://localhost:3000/?et=`

Any idea why it's happening?

**Comment by kbrandl** [comment]
@THPubs sorry to hear that you've run into this problem. @exextoc can you please look into this?

**Comment by THPubs** [comment]
@kbrandl Great thanks!

**Comment by exextoc** [comment]
see comment on https://stackoverflow.com/questions/54026756/cant-set-a-test-license-token-in-an-outlook-addin

**Comment by kbrandl** [comment]
@exextoc thanks for the pointer to the related question on Stack Overflow. 

@THPubs and @exextoc I'm going to close this issue in the **OfficeDev/office-js** repo; please continue to engage as necessary on the related Stack Overflow post:  https://stackoverflow.com/questions/54026756/cant-set-a-test-license-token-in-an-outlook-addin. (Stack Overflow question/answer is more likely to be discovered by / useful to other developers than this issue here in OfficeDev/office-js.)

**Comment by THPubs** [comment]
Still waiting for a solution...
