### ISSUE TITLE
Outlook custom add-in application occasionally failed to load office JS from CDN link thereby rendering white screen

### ISSUE THREAD

**Issue by KwFung7** [OfficeDev/office-js#3522]
We have developed a React application and serve it as custom Outlook plugin.
The application occasionally failed to load office JS from CDN link since May 2023 [https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js](https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js).
The React app won't render anything if it failed to load office JS thus user only saw the white screen.

Questions:
- Is there any way to monitor the Office JS CDN health status and check the past status ?
- Is there any difference between using npm module @microsoft/office-js and CDN Office JS ?

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook Desktop
* Office version number: [https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js](https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js)
* Operating System: Window 10
* Browser (if using Office on the web): No issue reported on Outlook Webapp 
 
## Expected behavior
Application successfully load Office JS and won't display white screen

## Current behavior
Outlook custom add-in application occasionally failed to load office JS from CDN link thereby rendering white screen

## Steps to reproduce
1. Open Enterprise Outlook and the custom add-in
2. User occasionally saw the white screen in custom add-in

## Useful logs
Can't provide log or screenshot as it's confidential

**Comment by cproscia** [comment]
Can you please share the HTTP status of the office.js request and the duration/latency of the request? To fully investigate a particular request, we would need the full network log for the office.js request.

I noticed the URL you mentioned for office.js isn't the recommended one. The official URL for office.js is https://appsforoffice.microsoft.com/lib/1/hosted/office.js (see [Referencing the Office JavaScript API library](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/referencing-the-javascript-api-for-office-library-from-its-cdn)).

The URL you are using (https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js) has the same file contents. But in theory the CDN performance of that URL could sometimes be worse due to CDN caching if it's not used as often. In case the reliability issue is related to a client timeout, performance could impact the reliability of the add-in (though I would expect this to be rare).

I would suggest using the official URL even if it doesn't help with this particular issue. And if you remember where you retrieved the "1.1" URL, let us know in case it's in a sample that we can update.

> Is there any way to monitor the Office JS CDN health status and check the past status ?

There isn't a history page for the CDN, though I'm not aware of any outages. There was an issue reported here in June that turned out to be a DNS issue specific to a customer's ISP.

> Is there any difference between using npm module @microsoft/office-js and CDN Office JS ?

The NPM package is updated less frequently and is published for the scenarios outlined in its package description.

**Comment by KwFung7** [comment]
@cproscia After discussed with the team, we will replace the CDN link with the official one and observe the performance, thanks for the follow up.
