### ISSUE TITLE
Subresource Integrity hashes for Office.js

### ISSUE THREAD

**Issue by richnew10** [OfficeDev/office-js#356]
The CDN is:

```
$ curl -s https://appsforoffice.microsoft.com/lib/1/hosted/office.debug.js | head -n2
/* Office JavaScript API library */
/* Version: 16.0.10831.10000 */
```

The current version in this repo is newer:

```
$ curl -s https://raw.githubusercontent.com/OfficeDev/office-js/release/dist/office.debug.js | head -n2
/* Office JavaScript API library */
/* Version: 16.0.10910.10000 */
```

The previous commit is months earlier, and older:

```
$ curl -s https://raw.githubusercontent.com/OfficeDev/office-js/b18900e1d90a4e3bb7ab4baad5f0c493e9d9aae9/dist/office.debug.js | head -n2
/* Office JavaScript API library */
/* Version: 16.0.9316.1000 */
```

Is there a process in place for updating this repo? Why is the CDN at a different version? I would expect that:

1. Every version retrieved from the CDN appears first in this repo, so it can be used for Subresource Integrity checks.
2. Each version delivered to the CDN appears in this repo's history.

**Comment by kbrandl** [comment]
@richnew10 thanks for reaching out about this. 

@wandyezj are you able to provide feedback regarding the questions @richnew10 has asked about the process/timing for updating this repo (OfficeDev/office-js) relative to the process/timing for updating the CDN?

**Comment by richnew10** [comment]
Any news on this? The CDN files seem to be updated very frequently:

```
/* Version: 16.0.11208.10000 */
```

**Comment by JuaneloJuanelo** [comment]
@sumurthy is a good person to answer this.
@richnew10 : why is this question relevant? our updates are incremental, and yes they are updated relatively frequently. the goal is to have that repo consistent to additions to APIs we ship.

**Comment by richnew10** [comment]
@JuaneloJuanelo @sumurthy I would like to build an automated mechanism for computing [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) hashes for valid, published office.js files. On the face of it, this repository would be the right way to do this, if new releases appear here at some point before they are pushed to the CDN.

Right now add-in developers have two bad choices:

1. Don't use SRI; anyone who can MITM users or compromise the Microsoft CDN can run arbitrary code in all Office add-ins.
2. Use SRI; each add-in developer has to build a reactive automated system to repeatedly fetch from the CDN, thousands of times each day (just in case a new release is deployed!), and compute new hashes to put into their add-in HTML. Users will be exposed to a small interval after each push in which their add-ins will fail to load because of an SRI check failure.

**Comment by wandyezj** [comment]
Hello @richnew10 

The files in the GitHub office-js repository are currently updated on an adhoc basis.

At the moment, the office CDN always contains the most up to date files.

We are currently working on internal tooling to be able to update the files in the office-js repository on a more frequent basis in line with the office CDN.

**Comment by richnew10** [comment]
In the temporary absence of a notification channel, a couple of follow-up questions:

How long does it take for the Office CDN to achieve global stability when replicating a new version, such that all clients in all locations will see the same snapshot? 30 seconds? 5 minutes?

Is it acceptable for service providers to poll to detect changes? What is the highest frequency that's acceptable?

**Comment by richnew10** [comment]
And will that new internal tooling be retrospective (i.e., CDN deploy occurs prior to GitHub push) or prospective (GitHub first, then some pause, then CDN deploy)?

**Comment by wandyezj** [comment]
Regarding Subresource Integrity hashes,

I'm not sure that Subresource Integrity hashes are practical for Office Add-ins:

* The Office CDN is meant to be updated at any moment to address any immediate issues.
* Office.js itself, is an entry point that loads other files on the Office CDN.
* The Office CDN is compliant with various governments security standards.
* Office Add-Ins are recommended/required to run on HTTPS (required for any Store-bound Add-Ins and for running in Office Online). I believe HTTPS makes Man In The Middle less of a concern?
* We also provide a [office-js NPM package](https://www.npmjs.com/package/@microsoft/office-js) (a direct copy of this repository) that can be hosted in an alternative endpoint on an internal network if required. Note: The office-js NPM package is updated when we update this repository.

**Comment by wandyezj** [comment]
Regarding Office CDN and GitHub update timing,

At the moment I can't give you any absolute guarantees on what will come first. In general you can expect the Office CDN to be the source of truth.

**Comment by richnew10** [comment]
In general, I would 100% prefer to host my own copy of the entire office.js code, which would allow for better testing and solid automated SRI. However, the add-in docs require that the Office CDN version be used if the add-in ships via AppSource. If that's no longer the case, please let me know (and update the docs!).

HTTPS is necessary but not sufficient; it makes attacks more challenging. Assorted malicious actors can still deliver different code to users. (Consider e.g., an attacker that controls a CA or an internal corporate network, which makes DNS poisoning realistic.)

I 100% understand that changes should be deployed quickly. That's orthogonal to a responsibility to protect users from malicious actors, and even imperfect protective mechanisms are worth the effort. (I was a browser engineer for many years, so "imperfect but worthwhile" is pretty familiar!)

Compliance with government standards is not a great bar.

https://tools.geekflare.com/report/hsts-test/https://appsforoffice.microsoft.com/lib/1/hosted/office.debug.js

https://hstspreload.org/?domain=appsforoffice.microsoft.com

— no HSTS header, not HSTS preloaded, etc.

SRI is one appropriate technique to guarantee that two actors agree on which code will be run, reducing the problem to one of the actors figuring out when the expected code changed. The reason for this ticket is to define some rudimentary properties to allow for that, so that your customers can hold a higher bar.

That's all I want to do: figure out when an office.js deploy occurs (whether by polling or some API), so I can ensure that an add-in expects the right content, so it'll reject malicious code.

**Comment by wandyezj** [comment]
Regarding Subresource Integrity hashes,

Just checking that we are on the same page: Office.js is a loader that loads other JavaScript files off of the Office CDN. So while the Subresource Integrity hash can be checked for Office.js the Subresource integrity hash will not be checked for the JavaScript files that Office.js loads.

It's possible to view Office.js file loading behavior using F12 tools.

Additionally, I'm not sure if Subresource integrity hashes are supported on all of the platforms that Office.js runs on.

Would you mind sharing your specific use case so we can better address your concerns?

**Comment by richnew10** [comment]
Specifying SRI for office.js is the only thing an add-in is able to do, so it's a good first step. @wandyezj I think it would be a fine idea for `office.js` to itself use SRI when loading other files from the CDN, if it does so by adding script tags to the DOM. It's super easy if you're in control of the build system: build 'bottom-up' and calculate hashes. A nice safety win for users.

For those following along, here's a good overview of what these technologies are meant to address:

https://www.troyhunt.com/the-javascript-supply-chain-paradox-sri-csp-and-trust-in-third-party-libraries/

SRI is supported pretty much everywhere apart from IE11:

https://caniuse.com/#feat=subresource-integrity

I suspect that earlier browsers will just ignore the attribute, and so will fail gracefully, but we'll find out!

Our use case is nothing special: an Outlook add-in with an authenticated user, with the add-in working with local Office data and remote service actions. The issues and approaches I've shared in this issue are really just modern web fundamentals.

**Comment by wandyezj** [comment]
Thank you for the pointers @richnew10 !

Are Subresource Integrity hashes essential for your Add-In?

If you have a very strong security requirement for using Subresource Integrity hashes, you can include a note about it in your store submission. The store may grant an exception for you to reference your own version of Office.js. This would allow you to host and reference your own version of the office-js NPM package which would allow you to maintain a Subresource Integrity hash of Office.js. If you decide to host your own version, consider following these [best practices](https://github.com/officedev/office-js#target-scenarios).

**Comment by richnew10** [comment]
I wouldn't say "essential", in that it would work without them, but SRI (along with the rest of the family of web security technologies) is part of an expected baseline that we feel is necessary for our users.

I am hesitant to rely on "may grant", only to find out later that we took the wrong path — do you have a contact I can email to discuss further about how to proceed?

**Comment by wandyezj** [comment]
@sumurthy could you please follow up with @richnew10 ?

@richnew10 is there an email we can contact you at?

**Comment by richnew10** [comment]
@JuaneloJuanelo, @sumurthy, @wandyezj: I sent @sumurthy an email just now; please feel free to broaden circulation.

**Comment by sumurthy** [comment]
This is in the backlog. The earliest we think we'll be able to take it up is in Q1-2020.

**Comment by sumurthy** [comment]
No status update yet for this... still in backlog and no ETA yet.

**Comment by lindalu-MSFT** [comment]
@sumurthy Is there a bug number where we are tracking this internally?

**Comment by ineale2** [comment]
This is still a strongly desired feature/security improvement. I work at one of the larger US tech companies and our security guidelines only allow using external CDNs if SRIs are able to be used. This security feature would help drive adoption significantly.

**Comment by wandyezj** [comment]
@ineale2 How do you envision SRI working with the office.js evergreen model where the CDN can update at any time?

Does your Add-In need to work on Office on the Web? Would it be sufficient if your Add-In loaded the JavaScript from the Desktop client directly instead of a CDN?

**Comment by ineale2** [comment]
@wandyezj Could versions be used in the CDN along with published SRI hashes for each version? 

Perhaps instead of `https://appsforoffice.microsoft.com/lib/1/hosted/office.js.` we could hit `https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js.` with a SRI published for 1.1. If 1.2 is published, so too is the SRI and clients could update both at once. 

Any loads of subresources of office-js then would be controlled by microsoft, meaning Microsoft can ensure that all subresources and their hashes in office-js are updated atomically by some mechanism.

Admittedly, this somewhat defeats the purpose of using a CDN as updates need to be manually taken. However, the company that I work for could have a wrapper package that is loaded via our internal npm-like package registry that contains these updates and we can auto update with that. Because I can trust this internal package to have good SRI hashes and update the version via an appropriate  microsoft CDN URL, we can take auto updates without any change from my team just by specifying "always take the latest version of this internal package" via npm syntax. 

That seems like a much more secure mechanism. 

The above isn't mutually exclusive to the existing mechanism, so existing clients need not break. `https://appsforoffice.microsoft.com/lib/1/hosted/office.js.` can just always point to the latest 1.x version and clients just wouldnt be able to use SRI in that case.

**Comment by ineale2** [comment]
@wandyezj I'm not sure what you mean by "desktop client" in this context. Do you mean via an explicit npm dependency? It would be sufficient to do that, but unfortunately my company has issues with the license not being open source that makes the npm package deny-listed.

**Comment by rakeshgandham** [comment]
@wandyezj any update on this issue or any resolution? We are building a wordAddin to integrate with our application, and this is brought up in the security review and recommending us to use SRIs for external CDNs.

**Comment by grichards23** [comment]
@wandyezj curious if there's been any changes here. We are in the process of building an outlook addin and our static code analysis tool is flagging our use of Office.js via CDN without an SRI. I contemplated using npm as suggested earlier and self hosting.

**Comment by wandyezj** [comment]
@grichards23 There have been no changes here.

Office JS operates on the evergreen CDN model - which ensures the latest security updates are applied.

The [office-js NPM package](https://www.npmjs.com/package/@microsoft/office-js) is offered as a way to host your own CDN for specific supported scenarios. You could use this to host your own CDN to use SRI, but this is not a supported scenario.

While it is frequently cited as best practice to use SRI. The case of office.js is different since it relies on an evergreen CDN model. The evergreen CDN model is incompatible with the idea of SRI. Please understand that the evergreen CDN model is designed to mitigate security risks, and deviating from this model reopens those security risks.

I know this isn't the answer everyone is looking for, but please understand that this is a lot more complicated than it appears at first glance, and we've spent - and continue to spend - a lot of time making sure our systems are secure.

**Comment by Shujee** [comment]
I read through the entire thread and still not sure what's the way out for us here:

1. We are going to publish to Office Store, so using the CDN version is our only option.
2. SRI hash must be specified because otherwise the browser does not load `office.js`.
3. `office.js` can change at any time, so SRI hash must be recalculated and the add-in be published again.

How do we even know that the SRI hash needs to be updated? A monitor service that keeps running round the clock? Or do we ask our users to report when the add-in stops loading all of a sudden (really?)?
