### ISSUE TITLE
Outlook addin focus lost from draft window

### ISSUE THREAD

**Issue by lorenz-nlp** [OfficeDev/office-js#3638]
# Provide required information needed to triage your issue

An action within an Outlook addin uses "setSelectedDataAsync" to set some text in the message draft window at the current cursor position. Afterwards, a user would expect to be able to continue to write within the message draft window. However, the focus is still on the addon so that any keystrokes are not captured till the user clicks into the message draft window.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.16626.20170
* Operating System: Windows 10
 
## Expected behavior
After pushing text to the message draft window bei using "setSelectedDataAsync", the draft window shall gain focus again.

## Current behavior
After pushing text to the message draft window bei using "setSelectedDataAsync", the draft window shall does not gain the focus. Instead, the addon itself still has the focus.

## Steps to reproduce
1. Perform an action within an outlook addon
2. Try to write text into the draft window

**Comment by exextoc** [comment]
@lorenz-nlp - Are you using "New Outlook" on Windows, or old Outlook?

**Comment by lorenz-nlp** [comment]
I do have O365 subscription so that Outlook is always updated. Currently version 16.0.16626.20170. Does that answer your question?

**Comment by exextoc** [comment]
@lorenz-nlp Do you have "New Outlook" toggle to on? Here is how the toggle looks when you are using "New Outlook"
![image](https://github.com/OfficeDev/office-js/assets/28549921/051f5d82-c6ff-4ede-915a-d10a3602a84f)

**Comment by lorenz-nlp** [comment]
Noo, it is switched off.

**Comment by besiler** [comment]
@lorenz-nlp , I'm from the Outlook add-ins team and wanted to follow up on this. Did you find a fix or are you still experiencing the issue?

**Comment by lorenz-nlp** [comment]
Hello,

no, this is still a pending issue. Could you advise how to solve the problem?

**Comment by millerds** [comment]
Sorry for the much delayed follow up.  

The API isn't actually setting the focus one way or the other.  If I make a taskpane that has a button that calls setSelectedDataAsync then select some data and click the button, the button was the last thing that the user did and so that is what has the focus.  If I put the setSelectedDataAsync call in a Timeout function, click the button, and click in the body to start typing before the timeout finishes then the API will run after clicking the body, and the focus will be maintained in the body (not switching back to the taskpane).

Can you provide a more specific scenario in which you expect the focus to switch to the body?
