### ISSUE TITLE
Can not add custom add-ins from OWA

### ISSUE THREAD

**Issue by liamtim** [OfficeDev/office-js#3645]
# Provide required information needed to triage your issue

The "Get Add-ins" button is no longer visible on OWA. There does not appear to be a way to add add-ins via xml anymore. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: OWA
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Mac
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Need a way to add custom add-ins via Outlook Web Mail.

## Steps to reproduce
1. Open Outlook Web Access
2. Attempt to load a custom add-in via XML

## Context
Can not continue development on add-ins until we have the ability to add custom add-ins via OWA.

**Comment by exextoc** [comment]
@liamtim Thank you for reaching out. As a recent change, Get-Addins button has been removed, and we are recommending to sideload addins by going to this URL directly. https://aka.ms/olksideload
More details are available in the documentation here: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=web#sideload-manually

Please note, Due to caching, it may take up to four hours for the sideloaded add-in to appear in your Outlook client on the web.
