### ISSUE TITLE
APIs to copy the values of a range to the clipboard

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#3650]
There are APIs such as `Range.copyFrom` and `Range.moveTo` to copy paste among  ranges.

Now, I would like to copy the values of a range to the clipboard. The manual way to do that is to 1) select the range; 2) press Ctrl+C. I would like to know if there is any official API to do so.

Could anyone help?

**Comment by donlvMSFT** [comment]
Hi @chengtie , thanks for reporting the issue.

However, Excel APIs currently doesn't support copy to clipboard. Could you share more of the scenario to see whether there's any workaround?

Also, we track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum]( https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests are considered when we go through our planning process. 

Thanks

**Comment by adrianwu8516** [comment]
Hi @chengtie, 

Thank you very much for the suggestion. As @donlvMSFT mentioned, we currently do not support such operations at the API level. If you are expecting such functionality, it would be very helpful if you could help us create a new post in [our technical forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) so that more people with similar requests can join the discussion and upvote for this idea.  

Given the circumstances, I will be closing this issue to keep our tracker focused on immediate actionable items. We appreciate your engagement and look forward to your contributions on the forum! 

Thank you again for your suggestion and your active participation. 

> Microsoft 365 Developer Platform:  
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
