### ISSUE TITLE
addHandlerAsync with event RecipientsChanged not working on MAC

### ISSUE THREAD

**Issue by qquiuc** [OfficeDev/office-js#366]
Hi Team,
I'm working on a office web add-in project, we have used the addHandlerAsync method to register the event in the add-in, 
### here is how we use the event
```
Office.initialize = function () {
$(document).ready(function () {
 Office.context.mailbox.item.addHandlerAsync(Office.EventType.RecipientsChanged, itemChanged, function (result) {
                    if (result.status === Office.AsyncResultStatus.Failed) {
                        $("#testMessage").html("failed");
                        Office.context.mailbox.item.notificationMessages.addAsync("errorMessage", {
                            type: "errorMessage",
                            message: "callbackFailed"
                        });
                    }
                });
}
}
```
 

### here is the callback method, just show the event called times on the html
```
var i = 0;
        function itemChanged(eventArgs) {
            i = i + 1;
            // Update UI based on the new current item
            $("#testMessage").html("event"+i);
            //UpdateTaskPaneUI(Office.context.mailbox.item);
        }
```

The test result from outlook client on windows shows the event called event time when i change the TO or CC in the outlook, but for outlook client on MAC the event could register successfully, **but the callback can not be called.**

Is this an bug for office.js?  or maybe i'm using wrong method on MAC?
Any help will be appreciate

Version of MAC system is 10.14.2
Outloook client version on MAC version is 16.20 (181208)
License: Office 365 Subscription
Here are the requirement sets supported by outlook on MAC
1.3,1.4,1.5,1.6,1.7

Thanks
## Product
Outlook, Outlook On MAC

**Comment by nrakochy** [comment]
I am facing a very similar issue.  In my case, the change handlers are getting called on 1st load, but subsequent changes are not invoking the callback.

Example code
```
var ITEM = Office.context.mailbox.item;
function _registerChangeHandler(event, callback){
	  var options = {};
	  var _ = function(r){ console.log("ITEM CHANGED HANDLER ", r);  return r; };
	  var cb = function _changeHandlerCB(r){
		    console.log("ITEM CHANGED CALLBACK ", r);
	  };
	  
	  ITEM.addHandlerAsync(event, _, options, cb);
  }
```

**Comment by qquiuc** [comment]
Hi @nrakochy 
I have open an same issue in the stack overflow you could add comments to this to double push the office js team.
https://stackoverflow.com/questions/54232201/outlook-web-add-in-event-recipientschanged-not-working-outlook-on-mac

**Comment by kbrandl** [comment]
@nrakochy and @qquiuc based on input from @macOutlookExtensibility within the related [Stack Overflow post](https://stackoverflow.com/questions/54232201/outlook-web-add-in-event-recipientschanged-not-working-outlook-on-mac), it sounds like API requirement set 1.7 is not yet supported on Outlook for Mac (and since the `RecipientsChanged` event is part of API requirement set 1.7, this means it won't yet work on Outlook for Mac). 

The [docs](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets) were recently updated to reflect that Outlook for Mac does not yet support API requirement set 1.7. We'll update the docs again as soon as Outlook for Mac does support API requirement set 1.7.
