### ISSUE TITLE
mailbox.getSelectedItemsAsync return Permission Denied

### ISSUE THREAD

**Issue by ekkuluri** [OfficeDev/office-js#3688]
While trying to get the selected emails data using Office.context.mailboax.getSelectedItemsAsync  I am getting the following error 
Permission Denied with code: 7000

## Expected Behavior
Expected should get the selected email itemID's

## Current Behavior
Now getting error with code 7000

## Steps to Reproduce, or Live Example
open outlook console and run Office.context.mailboax.getSelectedItemsAsync(asyncResuls => console.log(asyncResuls))

* Link to live example: ______
Please share the screenshot.
![image](https://github.com/OfficeDev/office-js/assets/3906782/16d066da-bfc2-4807-af06-da551c773716)

**Comment by exextoc** [comment]
Can you fill out the **Your Environment** section of the issue template so that we can better assist you here?

Also, error code 7000 means that the client you are using does not support the capability / API you are trying to use.

The `getSelectedItemsAsync` API was added as part of Requirement Set 1.13.
For Windows Outlook, for example, Requirement Set 1.13 is only supported in build 16.0.16327.20248 and above.
More information here: https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/outlook-api-requirement-sets?view=common-js-preview&tabs=xmlmanifest#outlook-client-support
