### ISSUE TITLE
Insert content control not working properly in paragraph

### ISSUE THREAD

**Issue by Alpesh-Chaudhari** [OfficeDev/office-js#3705]
Hello Team,
I am using Word API for developing word add-in.

My Environment
Platform : PC desktop
Host: Word
Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2308 Build 16.0.16731.20182) 64-bit 
Operating System: Windows 10 pro

 Snippet :
```
 Word.run(async (context) => {
    var range = context.document.getSelection();
    range.load("text");
    await context.sync();

    var ctrl = range.insertContentControl();
    ctrl.tag ="tempId";    
    ctrl.load();

    await context.sync();

});
```

When using the provided code snippet to insert content controls into a document, it appears to work correctly in most cases. However, there is an issue with certain paragraphs where selecting the entire paragraph and inserting a content control results in the control being applied only to a specific line within the paragraph, rather than the entire paragraph. How can i resolve this issue ?

Screen short for selected paragraph range:
Paragraph sample 1:
<img width="960" alt="ParagraphSample1" src="https://github.com/OfficeDev/office-js/assets/63895336/b2e002d0-00cb-45a8-ac25-3d8bf67e151d">

Paragraph sample 2:
<img width="960" alt="ParagraphSample2" src="https://github.com/OfficeDev/office-js/assets/63895336/045bcaa5-865c-4677-9e50-0cc46b828023">

Paragraph sample 3:
<img width="960" alt="ParagraphSample3" src="https://github.com/OfficeDev/office-js/assets/63895336/4733692e-02b6-43f2-8883-4e65447f615d">

Word document sample:
[document.docx](https://github.com/OfficeDev/office-js/files/12697175/document.docx)

To Reproduce steps:
- Select specified  the paragraphs
- Insert content control with above snippet

Could you please provide me with recommendations or solutions for this matter at your earliest convenience?
Thank you...

**Comment by Searion** [comment]
Thanks for reporting this issue. I think this is by design. This behavior is same as adding contentcontrol in UI.  if the range crosses several paragraphs, the range must contains the whole paragraphs to create a whole contentcontrol.
This doc is a little strange for the first line of (i), (ii), (iii) seems belong to the last paragraph. Notice the para mark.
![image](https://github.com/OfficeDev/office-js/assets/33591311/b175bc09-73e4-485b-8928-17c33d9f33d8)

If these first lines are the start of a new paragraph, it works.
![image](https://github.com/OfficeDev/office-js/assets/33591311/1b7087cf-f5bc-4a5c-83b2-9cbc659f869e)

**Comment by Alpesh-Chaudhari** [comment]
Thanks for response..
