### ISSUE TITLE
menu images don't show in manifest.xml

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#3707]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __PC desktop____
* Host [Excel, Word, PowerPoint, etc.]: ___Word、Excel___
* Office version number: ___Microsoft® Word 2019MSO (版本 2308 Build 16.0.16731.20052) 64 位___
* Operating System: __Windows 10____
* Browser (if using Office on the web): ___Edge___
 
## Expected behavior

menu images don't show in Word or Excel

[manifest.xml](https://financial.chengfeisoft.com/tmp/dfzq-prod.xml)
![Snipaste_2023-09-25_09-58-45](https://github.com/OfficeDev/office-js/assets/3182964/a88a8e18-9162-4fe5-b3b4-73688e1da279)

**Comment by ZYUN-MSFT** [comment]
Hi @hengchengfei ,

I try to sideload your manifest and I think the image can show well
![image](https://github.com/OfficeDev/office-js/assets/122421505/fddf3a5e-7ece-4763-9e77-766f4c8eb698)

Please check that:
1. whether the issue occurs broadly? or it only happen on 1 machine or the sepcific office version.
2. please make sure that the computer use the addin have a well network connect to https://financial.chengfeisoft.com/ (and the image URL), otherwise the image not loaded is the expected behavior.

Thanks.

**Comment by hengchengfei** [comment]
@ZYUN-MSFT thanks for your reply.

The issue happens over 2 machines in defferent network.

Now it's OK.

Thank you！
