### ISSUE TITLE
Office Add-in Desktop application

### ISSUE THREAD

**Issue by csreddyennam** [OfficeDev/office-js#372]
Developed office Add-in for desktop, this doesn't load the local office.js (we have same set of files and structure as in CDN) file, when we point to the CDN path it work fine. 
we don't see any error, tried to debug by F12 no luck

## Expected Behavior
Add-in should work with local path (relative path)

## Current Behavior
It should work for both relative path and absolute path

**Comment by JuaneloJuanelo** [comment]
why are you not using the CDN? also how are you getting your own copy of Office.js? and finally what products are you targeting with yout add-in?

**Comment by csreddyennam** [comment]
Hi, 
Thanks for your reply,
This is our on-premise solution. It may be possible that the customer may not have internet connection and they are operating in restricted environment. thats why we have provided the on-premise copy of officejs distributed by downloading it from NPM package from https://www.npmjs.com/package/@microsoft/office-js

we have also noticed that the version of office.js file in CDN (Version: 16.0.11215.10000 Office.js) and in the npm package is different (Version: 16.0.10203.10000) and much lower, similarly in nuget package its also lower than the npm package, can you please also help on getting the latest version. 

Moreover, the office package we have works on some machine but not on all machine.
Office.js is loading but looks like its not calling the office.initilization function

**Comment by JuaneloJuanelo** [comment]
@csreddyennam in order to help you i need more information. can you please make sure to use our template to report issues? that way we will be able to help you faster. 



## Expected Behavior


## Current Behavior



## Steps to Reproduce, or Live Example



* Link to live example: ______


* Additional details:
  1. ______
  2. ______
  3. ______

## Context



## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by csreddyennam** [comment]
Issue got resolved by removing add-in (we had a custom adding this was blocking the local files acquiring) from add-in dialog box and re-added the add-in gain. By UN-checking all the add-in restart the excel and add add-in again

Thanks,
