### ISSUE TITLE
Office.js is not working in new outlook

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/office-js#373]
## Expected Behavior
Office.js API should work in "new outlook" (web)

## Current Behavior
Office.js calls fail on new Outlook (web)

## Steps to Reproduce, or Live Example
1. Open web outlook https://outlook.office.com/owa/?path=/calendar/view/Day
1. Enable new outlook (look at top right corner) 
![image](https://user-images.githubusercontent.com/3139353/52205916-a9c95a80-289e-11e9-8835-bc36d3090f4b.png)
1. Open any addin which use [`saveAsync`](https://docs.microsoft.com/en-us/javascript/api/outlook/office.appointmentcompose?view=office-js#saveasync-options--callback-)
1. call `saveAsync`
1. call fails with following error:
    ```json
    {
       "code": 9021,
       "message": "Connection error occurred while trying to save the item on the server.",
       "name": "SaveError"
    }
    ```

## Your Environment

* Platform :ffice Online
* Host : Outlook
* Office version number: 1.6
* Operating System: windows 10
* Browser :Firefox, chrome

**Comment by exextoc** [comment]
This scenario occurs when calling Office.context.mailbox.item.saveAsync on a new Calendar item that has not been sent yet. This is a known issue and we are looking into a solution to resolve this so that the API can be used as designed. The API should behave as designed in Mail and on Existing Calendar items. Note that for existing Calendar items, an update may be sent out to attendees depending on the changes that the user or the add-in made in the compose form.
[Outlook Add-ins Engineering Team]

**Comment by exextoc** [comment]
Can you please try calling Office.context.mailbox.item.saveAsync on a new Calendar item again, it seems to be working now.

**Comment by abdulkareemnalband** [comment]
Yes it is working again
