### ISSUE TITLE
Cannot find module '@microsoft/office-js' or its corresponding type declarations.

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#3734]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___PC desktop___
* Host [Excel, Word, PowerPoint, etc.]: ___Word___
* Office version number: __Microsoft® Word 2019MSO (版本 2309 Build 16.0.16827.20130) 64 位____
* Operating System: __Windows____
* Browser (if using Office on the web): __Edge____
 
## Expected behavior

No Error

## Current behavior

Compile error in vscode
 
```js
import { Office } from "@microsoft/office-js";

```
![1](https://github.com/OfficeDev/office-js/assets/3182964/bc4a22d2-73f3-432c-8549-ea2acb561bdf)
![2](https://github.com/OfficeDev/office-js/assets/3182964/62e21ca6-4f66-4691-a19b-83eaf01bbfc4)

**Comment by Manas-Nagelia** [comment]
Same issue.

**Comment by jaredwri** [comment]
Same issue

**Comment by ZYUN-MSFT** [comment]
Hi @hengchengfei, @Manas-Nagelia and @jeremy-msft,
Sorry for the late reply here. This problem is not a real issue.

According to the [package page](https://www.npmjs.com/package/@microsoft/office-js) of `@microsoft/office-js`,\
the `@microsoft/office-js` is not designed for import use case.

> [Using the NPM package according to the instructions](https://www.npmjs.com/package/@microsoft/office-js#use-the-npm-package). \
> Do not import the NPM package as commonly done with other NPM packages.

---

If you want to active the TypeScript awareness of Office.js, please:
1. `npm i -D @types/office-js @types/office-runtime`
2. Make a new file called `office-env.d.ts` and put the following content in this file:
```ts
/// <reference types="@types/office-js" />
/// <reference types="@types/office-runtime" />
```

This [file](https://github.com/sigmarising/Office-Addin-Vue3-Vite-TS/blob/main/NOTES.md) may give you more inspirations of how to power the Vue project with Office JS API.

Thanks.
