### ISSUE TITLE
Unable to get property 'displayDialogAsync' of undefined or null reference

### ISSUE THREAD

**Issue by alirezastack** [OfficeDev/office-js#374]
I have used office js helpers module to implement login with Google and Facebook. The functionality works as expected in Office Online, but when I run the addin inside of Microsoft Word 2016 in Windows 10 it gives an error.

## Expected Behavior
Open a dialog box for authentication

## Current Behavior
gives the below error:
`Unable to get property 'displayDialogAsync' of undefined or null reference`

## Steps to Reproduce, or Live Example
Implement login with Google using office js helpers and then side-load your addin inside of `Word 2016` by clicking on Login with Google you would see the error and modal will not get opened.

## Context
login with Google/Facebook in word MAC/Windows

## Your Environment
* Platform: PC desktop, Mac
* Host Word
* Office version number: 1.1
* Operating System: Mac OS Mojave, Windows 10

## Useful logs
`Unable to get property 'displayDialogAsync' of undefined or null reference`

**Comment by Zlatkovsky** [comment]
From what you're describing, it sounds like it's an unpatched version of Office 2016 MSI.  You need a version that supports DialogApi 1.1.  See more at <https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/dialog-api-requirement-sets>.  You can either make this requirement set be a hard requirement in the manifest, or something that you query at runtime using `Office.context.requirements.isSetSupported`.

Closing the issue, since it's effectively by-design/by-limitation-of-version.
