### ISSUE TITLE
Missing Add-In from the "Apps" ribbon.

### ISSUE THREAD

**Issue by teejay001** [OfficeDev/office-js#3745]
# Provide required information needed to triage your issue

Add-Ins are missing from the "All Apps" ribbon for the new OWA update rolled out. The Add-Ins are not available on within the "built for your org" section nor via searching entire. The old OWA view does have the "Get Add-Ins" ribbon which does have the enterprise Add-In within the "Admin-Managed" section as expected. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: OWA
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

We should be able to get our enterprise Add-In when using OWA regardless of which version is being used.

## Current behavior

Missing Add-In within the Get App section of OWA

## Link to live example(s)

# Provide additional details

There seems to have been some update to OWA since there are 2 versions being circulated at this instant.

1. The "Get App" ribbon is presented instead of the "Get Add-In"
![image](https://github.com/OfficeDev/office-js/assets/99417649/5194751a-4e8c-4bbf-bc4b-cc62f68dab8c)
2. The Add-In  is missing from OWA and cannot be installed
![image](https://github.com/OfficeDev/office-js/assets/99417649/775d09e8-b92a-48d5-8629-d58806477fdb)

1. The "Get Add-In" exist on OWA
![image](https://github.com/OfficeDev/office-js/assets/99417649/8be73917-90d7-4a04-94b3-7e7ac5113929)
2. The Add-In  is within the Admin-Managed section and can be installed
![image](https://github.com/OfficeDev/office-js/assets/99417649/139e290d-6d43-40a1-b1f2-aee82178ee01)

## Context

We have multiple customers calling in and complaining on not being able to install the Add-In and can make use of service.

## Useful logs

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Get-Addins button has been removed, and we are recommending to sideload addins by going to this URL directly.  https://aka.ms/olksideload 
More details are available in the documentation here:  https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=web#sideload-manually 
Please note, Due to caching, it may take up to four hours for the sideloaded add-in to appear in your Outlook client on the web.

**Comment by carlosb1504** [comment]
These add-ins are not sideloaded, they are admin deployed, how are these add-ins managed in the absense of the Get Add-ins screen?

**Comment by exextoc** [comment]
@carlosb1504 Is your addin visible when you use https://aka.ms/olksideload?

**Comment by teejay001** [comment]
@exextoc, thanks for the response. I can confirm my Add-In is visible using the link "https://aka.ms/olksideload". It does show it's added but I still cannot make use of it on the outlook client. My Add-In ribbon are not present nor the launch event hooks triggered.

**Comment by cody-lettau** [comment]
The 4 hour delay due to caching needs to be fixed. This is a huge issue when trying to do development, testing, or debugging. We use different manifests to switch between environments and waiting up to 4 hours is just not feasible.

This was discussed at length on the community calls lately and we were told there would be urgent fixes prioritized for this issue. What is the status of those fixes?

**Comment by omar-pk** [comment]
Today the sideloading method for "Add from URL" has become greyed out on all platforms. This is happening for multiple users across multiple account configurations. Anybody experiencing the same? I hope this is temporary due to a fix being actively deployed for the 4 hours caching issue.

**Comment by cody-lettau** [comment]
@omar-pk we are seeing the same -- definitely expect this to be fixed soon.

**Comment by jlara005** [comment]
> Get-Addins button has been removed, and we are recommending to sideload addins by going to this URL directly. https://aka.ms/olksideload More details are available in the documentation here: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=web#sideload-manually Please note, Due to caching, it may take up to four hours for the sideloaded add-in to appear in your Outlook client on the web.

A few months ago, I was able to sideload and remove add-ins immediately no issue. This morning I removed two sideloaded add-ins from https://outlook.office.com/mail/inclientstore, it's almost 8PM EST and they are still there on both Outlook Client and Web. Definitely not 4 hours! This is definitely impacting development.

**Comment by exextoc** [comment]
The option to sideload addins from url has been deactivated and now only install from file option will be available to users. The documentation will be updated soon. Also, please clear cache / hard refresh and verify if the issue with sideloading addins is resolved now for any new installation.
For uninstall, the issue is in our backlog but we don't have any timelines to share at this point.

**Comment by cody-lettau** [comment]
@exextoc why would the install by URL be removed? What is going on? Now we have to ask customers to download the manifest and install it, instead of just pasting in a URL?

These are all major issues that impact how add-ins are developed, maintained, debugged, and deployed to customers. Things were working just fine before the switch to the "Apps" button. Since that, we have the following issues that little is being done to address:

- Add-ins that are sideloaded take hours to actually become available in the client
- Add-ins that were sideloaded and then removed take hours to be removed from the client
- No longer can we install add-ins via URL, causing anyone (or process like automated tests) to have to download the manifest and upload it to Outlook.
- No longer can a user actually sideload an addin from their mailbox -- instead they must know the specific url that opens the add-in management screen in the mailbox

How can the Office.js team see this as a feasible long term solution going forward? These changes are causing major issues when it comes to how we as developers build, maintain, and debug add-ins on this platform.

**Comment by omar-pk** [comment]
We totally agree with @cody-lettau. There's also been minimal communication about these changes, causing workflow disruptions. It is causing things to break (like automated tests) without any advance notice.

Can you please provide feedback on the 4 hour caching delay? Does the removal of "Load from URL" at least help to fix this issue? Otherwise things are only getting worse, especially for developers and QA.

**Comment by teejay001** [comment]
> @exextoc, thanks for the response. I can confirm my Add-In is visible using the link "https://aka.ms/olksideload". It does show it's added but I still cannot make use of it on the outlook client. My Add-In ribbon are not present nor the launch event hooks triggered.

Hi @exextoc, this issue is still in production. Please, could you address this. It's being over the 3 days now so it's definitely not an issue with cache refresh.

**Comment by johnkreagan** [comment]
I agree that this change is unnecessarily disruptive and creates testing and deployment challenges for users and dev teams. This should have been more carefully considered and communicated.

**Comment by clavx** [comment]
> The option to sideload addins from url has been deactivated and now only install from file option will be available to users. The documentation will be updated soon.

The documentation seems to have changed. https://github.com/OfficeDev/office-js-docs-pr/issues/4219

I think it was a sudden change of specifications, was there any prior notice?

**Comment by gauravziv** [comment]
> The option to sideload addins from url has been deactivated and now only install from file option will be available to users. The documentation will be updated soon. Also, please clear cache / hard refresh and verify if the issue with sideloading addins is resolved now for any new installation. For uninstall, the issue is in our backlog but we don't have any timelines to share at this point.

I tried with clearing the cache and  opening in incognito window as well. But still the removed extensions are there. I hope it will be fixed soon(since so many folks are facing it).

**Comment by exextoc** [comment]
@teejay001 To clarify on the original issue, could you please confirm the following.
1. The addin was installed using https://aka.ms/olksideload.
2. The addin installed in step 1 is not available in the flyout/Apps button even after 4 hours.
3. Is this still reproducible?

**Comment by geoffreyreemer** [comment]
@exextoc Hi there. Our company is also facing the issue where our M365 add-in, which was deployed by admins, isn't visible for users in the new layout (with "Apps" instead of "Get Add-ins").

**Things to know:**
- Our customers deploy the add-in through the M365 Admin Center: https://admin.microsoft.com/AdminPortal/Home#/Settings/AddIns
- The exact installation process that we recommend is documented here: https://docs.zivver.com/en/admin/owa/installation-manual.html
- Most times, the add-in is deployed for Everyone and Fixed, but the behavior also occurs when it's added for specific users and as "Optional"
- Users have waited over 24 hours, but are still not seeing the add-in
- The admin does appear as installed when we check the sideloading URL: https://aka.ms/olksideload
- Our manifest is https://owa-v6.zivver.com/manifest.xml

Let me know if more input is required. We do hope for a speedy resolution, since it affects dozens of high-profile with over 65,000 seats in total already.

**Comment by exextoc** [comment]
@geoffreyreemer Thanks for reporting the issue. Could you please create a new GH issue for this so that we can track it and close loop.

**Comment by teejay001** [comment]
> @teejay001 To clarify on the original issue, could you please confirm the following.
> 
> 1. The addin was installed using https://aka.ms/olksideload.
> 2. The addin installed in step 1 is not available in the flyout/Apps button even after 4 hours.
> 3. Is this still reproducible?

Thanks for getting back @exextoc.

1. The Add-In was installed via the MS Admin porta (https://admin.microsoft.com/) to sideloaded.
2. The Add-In is now on the flyout/Apps button and I can add/activate the Add-In via the "Add" button. It is reflected immediately on the mailbox. However, to remove/deactivate the Add-In I would need to go via the Desktop "Manage Add-Ins" where I am presented with another screen. This does take a while for the changes to reflect on the mailbox (less than 4 hours in my case)
3. I can confirm the initial issue of missing Add-Ins on the flyout/Apps button reported on the ticket isn't occurring anymore.
