### ISSUE TITLE
In Outlook on the web, add-ins do not enable in shared mailboxes.

### ISSUE THREAD

**Issue by t-ariyoshi30907** [OfficeDev/office-js#3769]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows OS
* Browser (if using Office on the web): Google Chrome, Microsoft Edge

## Expected behavior

1. Click on "Open another mailbox" in Outlook on the web to open a dedicated page for the shared mailbox.
2. Compose an email.
3. The onsend add-in activates and displays a dialog using the displayDialogAsync API.

## Current behavior

1.Click "Open another mailbox" in Outlook on the web to access a dedicated page for the shared mailbox.
2.Compose an email.
3.The onsend add-in does not activate, and the email is sent as is.

## Steps to reproduce

1. Access the following URL.　https://drive.google.com/file/d/1Xrc-HuBLSjBAwDmU7y7Pbi7amwegbPDY/view?usp=share_link
2. Download "sample.zip" and place it in your desired location.
3. Launch the command prompt and navigate to the corresponding directory.
4. Run "npm install".
5. Run "npm run dev-server".
6. Access the Microsoft Admin Center and perform centralized deployment of the add-in using the "manifest.xml."
　 (The XML file is stored in sample.zip)
7. Click "Open another mailbox" in Outlook on the web to access a dedicated page for the shared mailbox.
8. Compose an email.
9. click "Send" button.

## Link to live example(s)

This week, we received reports of this issue from multiple customers. Until this problem occurred, we had been confirming that add-ins deployed centrally were working on the dedicated page for shared mailboxes. Have there been any changes to Office add-ins or within Microsoft 365 that might have caused this?

**Comment by t-ariyoshi30907** [comment]
@exextoc 
Upon investigation, I noticed that my add-in's manifest file does not include the "SupportsSharedFolders" element. If I incorporate this element, will the add-in become active on the dedicated page for shared mailboxes, or is it not possible to use the add-in on the dedicated page for shared mailboxes?

The reference document I consulted is available here:
https://learn.microsoft.com/ja-jp/javascript/api/manifest/supportssharedfolders?view=outlook-js-1.13&preserve-view=true

**Comment by exextoc** [comment]
@t-ariyoshi30907 You need to set SuppotsSharedFolders element to true for add-ins to work on shared mailboxes. Please note that this element is valid only under VersionOverrides schema Mail 1.1

**Comment by t-ariyoshi30907** [comment]
@exextoc 
Thank you for your prompt response.

My manifest file already includes the "VersionOverrides Schema" as follows. Is it correct that the advice I received pertains to this section?

 ```
<VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">

```

Additionally, I have a follow-up question. When I look at the documentation, it mentions that support for shared mailboxes started from requirement set ver. 1.13. Apart from adding "SupportsSharedFolders" and "VersionOverrides Schema 1.1," is there any other required action? (Currently, "DefaultMinVersion" is set to "1.8." Is it safe to leave this unchanged?)

**Comment by t-ariyoshi30907** [comment]
@exextoc 
I apologize for the frequent questions. I have one more inquiry.

When was the last update made to the program related to this issue? We've been receiving inquiries from customers who reported that the add-in, which previously worked on the dedicated page for shared mailboxes, suddenly stopped functioning. If possible, I would like to know when the program was last updated.

Additionally, do you have a web page or source for receiving the latest information on Office add-in specification changes, such as newsletters or other resources?

**Comment by exextoc** [comment]
- Yes, the supportsSharedFolder element should be added under 1.1 Schema
- Shared folder support was introduced in [requirement set 1.8](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/requirement-set-1.8/outlook-requirement-set-1.8), while shared mailbox support was introduced in [requirement set 1.13](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/requirement-set-1.13/outlook-requirement-set-1.13).  Learn more about this [here]( https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?tabs=windows%2Cxmlmanifest#shared-mailboxes). If you update the requirement set to 1.13, then your add-in availability will be restricted to versions with 1.13 support or higher.  It is not required in this case.
- This change is essentially fixing an existing bug in Outlook web and not a feature change. The fix was rolled out in 1st week of October.
We keep our documentation up to date when there a feature change.

Let us know if you have more questions.
