### ISSUE TITLE
Unable to read values from NamedRange in OfficeJS when NamedRange is a single row (Sheet1:$28:$28)

### ISSUE THREAD

**Issue by hvamja04** [OfficeDev/office-js#3791]
I am trying to read a values from particular namedRange with help of officeJS. NamedRange contains whole row i.e. (Sheet1:$28:$28). I am getting null values in response.

Sample Named Range: 
![Screenshot 2023-10-27 185306](https://github.com/OfficeDev/office-js/assets/146839068/a52932db-9c05-46eb-93ba-af8ab2271f7d)

Sample ScriptLab Code to reproduce the isse:

```
$("#run").click(() => tryCatch(run));

async function run() {
  let cont = ""
  await Excel.run(async (context) => {
    //LongNamedRange = Sheet1!$28:$28
    let NamedRange = context.workbook.names.getItemOrNullObject("LongNamedRange");
    NamedRange.load({ arrayValues: {values: true} });
    await NamedRange.context.sync();
    //Trying to print values of NamedRange
    console.log(NamedRange.arrayValues.values)
  });
  return cont;
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}

```

Output: 
![image](https://github.com/OfficeDev/office-js/assets/146839068/acfa2ac7-dd7d-497e-b3ab-578759e922e3)

**Expected Behavior:
We shall get all the values present in that namedRange.**

Values in Range:
![image](https://github.com/OfficeDev/office-js/assets/146839068/fbd257dc-62dc-4e03-add4-67da8291d41d)

**Comment by xai-msft** [comment]
Hi, thanks for reporting the issue. It is under investigation. Internal tracking number: 8485179

**Comment by penglongzhaochina** [comment]
Hi , you can try to create a namerange by below parameter:
![image](https://github.com/OfficeDev/office-js/assets/106959323/ad7d2b74-1b52-42f4-9086-ef5245084abc)
Not selected the whole row, just set the column to maximum column.

**Comment by Heet-vamja** [comment]
Hi Thanks for reply. 
We need such functionality where we can use this format "Sheet1:$28:$28" of NamedRange to access whole Row, same as it is available in Microsoft Excel. 
Please add it as a Feature Request.

Thanks.

**Comment by adrianwu8516** [comment]
Hi @hvamja04, 

Thank you for bringing this up. We do not currently support such operations at the API level. If you are expecting such functionality, it would be very helpful if you could help us create a new post in [our technical forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) so that more people with similar requests can join the discussion and upvote for this idea so that we can better prioritize this request. 

Thanks again for your suggestion.

Microsoft 365 Developer Platform:
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
