### ISSUE TITLE
Office.js is loaded outside of Office client

### ISSUE THREAD

**Issue by markb-trustifi** [OfficeDev/office-js#382]
When opening dialog by `Office.context.ui.displayDialogAsync` form Outlook Client it doesn't open popup but opens a new window in a browser with empty `window.caller` and printing warning that appears in title.

```js
Office.context.ui.displayDialogAsync("https://login.microsoftonline.com/....", {height:50, width:60}, callback)
```

Add-in manifest contains domains:
```js
<AppDomains>
   <AppDomain>https://login.windows.net</AppDomain>
   <AppDomain>https://login.microsoftonline.com</AppDomain>
</AppDomains>
```

## Expected Behavior
Works well in OWA - Chrome and **Safari**
Open popup.
Dialog can send messages back to its parent.

## Current Behavior
Relevant to Outlook Desktop Client
Opens new window in browser disconnected from add-in.
Window cannot send messages back to its parent.
window.caller is null
`Office.initialize = function (reason) {...}` isn't called at all

The displayDialogAsync also throws error right away but continues acting with target URL as usually:
- message: An internal error has occurred.
- code: 5001

## Your Environment
* Platform: Mac
* Host: Outlook Client
* Office version number: 16.0.11215.10000
* Operating System: Mac OS High Sierra

**Comment by Rick-Kirkham** [comment]
@markb-trustifi The URL that you pass to displayDialogAsync must be in the same domain as the add-in. 
From [Dialog API in Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins):

> the page, controller method, or other resource that is passed to the displayDialogAsync method must be in the same domain as the host page.

Instead of passing login.microsoft.com directly, you must have a page in your add-in domain that redirects to login.microsoft.com. Then pass the URL of the page to displayDialogAsync

**Comment by markb-trustifi** [comment]
@Rick-Kirkham Then what about this example? Why they add microsoft endpoints to AppDomain?
https://github.com/OfficeDev/office-js-helpers#for-office-add-ins

**Comment by Rick-Kirkham** [comment]
@markb-trustifi 
The page you linked to does not show passing either of the URLs in the `AppDomains` as the first URL that is directly passed to `displayDialogAsync`. As the doc I linked to says, the _first_ URL must be in the same domain (including subdomain, protocol, portal (if any)) as the add-in. 

I'm not an expert on office-js-helpers, but I can tell you that `AppDomains` in the manifest is _not_ a list of **URLs-that-can-be-directly-passed-to-displayDialogAsync**. It is more like a list of **URLs-the-add-in-can-navigate-to**; but this isn't actually necessary in most situations. Moreover, restriction on what can be the _first_ page of a dialog is completely independent of what is or isn't listed in `AppDomains`.

I recommend that you first fix your add-in so that you are initially opening the dialog with a UI-less page in your add-in's domain. That page should immediately redirect to the desired login page. After you get that working, you can experiment by removing those `AppDomain` entries. They might not be needed.

**UPDATE**: I found this documentation too: 
[Specify domains you want to open in the add-in window](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?tabs=tabid-1#specify-domains-you-want-to-open-in-the-ad-in-window)

**Comment by markb-trustifi** [comment]
@Rick-Kirkham : I found a simple workaround:
- open dialog with just 
`var authwnd = window.open('https://login.microsoftonline.com/common/oauth2/v2.0/authorize?...', ...)`
- listen for window message events
- respond from popup window by:
`window.opener.postMessage(window.location.search, window.location.origin)`

**Comment by Rick-Kirkham** [comment]
We recommend that developers use our Dialog API, rather than window.open, but since you are happy with this solution, I will close the issue.

**Comment by JSteunou** [comment]
@Rick-Kirkham but unfortunately there is at least one issue with the Dialog API that is blocking, see #378

**Comment by Hamdan85** [comment]
@markb-trustifi this approach works in mac, but not in windows. In windows, windo.opener returns undefined.
