### ISSUE TITLE
[Excel] How can I get a list of standard Excel fonts?

### ISSUE THREAD

**Issue by Eclipse-Walker** [OfficeDev/office-js#3849]
## How can I get a list of standard Excel fonts?
I would like to know about the list of standard Excel fonts. Where can I find it? I've searched from the Officejs documentation but I can't find an API regarding the list of standard fonts.

I want to create some tools on the task pane to set the output format of data. Right now I can set the style, such as colour, italic, and bold, but I'm not sure about the list of standard Excel fonts.

Therefore, I would like to have a list of standard Excel fonts so that users can choose the format from within the task pane.

**Comment by adrianwu8516** [comment]
Hi @Eclipse-Walker, 

Thank you for your questions. We currently do not support such operations at the API level. If you are expecting such functionality, it would be very helpful if you could help us create a new post in our technical forum so that more people with similar request can join the discussion and upvote for this idea. 

Thanks again for your suggestion. 

**Microsoft 365 Developer Platform:** 
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
