### ISSUE TITLE
Track Changes in Excel.

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#3899]
My Environment
Platform : PC desktop
Host: Excel
Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2309 Build 16.0.16827.20166) 64-bit
Operating System: Windows 10 pro

Hi team,
I am creating track changes in excel using office-js that time I find 2 Scenario where I didn't get the Changes .
**(1)** Meanwhile I found that if some cell has formula  and I change the cell value that time I didn't get changes of formula cell.
Example  :
cell A1,B1,C1 is there
C1 has formula : =SUM(A1:B1)
First A1 has 5 and B1 has 3 so that value C1 is 8 but when I change the value of A1 or B1 cell that time I can get change of cell C1.

**(2)** when I copy range of cell and paste it to other range that time I didn't get the value of those cell
example
from sheet 2 I copied range from B1:D7
and paste it in sheet 1 that time I need  sheet 1 value(which is paste from sheet 2)in track changes.

I think I bind change event. In this 2 scenario my event is not trigger. 

Here is My code snippet.

```
    var changeEvent,

 let sheets = context.workbook.worksheets;
 changeEvent = sheets.onChanged.add(workSheetChange);

 function workSheetChange(eventArgs) {
     if (eventArgs.changeType == 'RowDeleted') {
         deletedRowFortbl.push(eventArgs.address);
     }
     if (eventArgs.changeType == 'RowInserted') {
         addRowFortbl.push(eventArgs.address)
     }
     // Log the changed cells to the console
     var worksheet;
     var range;
     var trailObj = {};
     // var range;
     Excel.run(function (context) {
         var workbook = context.workbook;
         context.load(workbook.worksheets);
         worksheet = context.workbook.worksheets.getActiveWorksheet();
         worksheet.load("name");
         if (eventArgs.changeType == "RangeEdited" && eventArgs.details != undefined) {
             range = eventArgs.getRange(context);
             range.load('formulas');
         }
         return context.sync().then(function () {
             let cell = worksheet.getRange(eventArgs.address);
             cell.load('values,address');
             trailObj["SheetName"] = worksheet.name;
             trailObj["ExcelId"] = documentId;
             trailObj["ChangeType"] = eventArgs.changeType;
             trailObj["ModifiedBy"] = MetaInfo.UserId.toLowerCase();
             if (eventArgs.changeType == "RangeEdited" || eventArgs.changeType == "CellInserted" || eventArgs.changeType == "CellDeleted") {
                 trailObj["Range"] = eventArgs.address;
                 if (eventArgs.details != undefined) {
                     var formulas = range.formulas;
                     console.log("Address:" + eventArgs.address + "Formula:" + formulas);
                     if (!(range.formulas[0][0]).toString().includes("=")) {
                         trailObj["NewValue"] = eventArgs.details.valueAfter;
                         trailObj["OldValue"] = eventArgs.details.valueBefore;
                     }
                     else {
                         trailObj["NewValue"] = eventArgs.details.valueAfter + " " + formulas;
                     }
                 }
                 if (eventArgs.changeDirectionState != undefined) {
                     trailObj["DirectionState"] = eventArgs.changeDirectionState.insertShiftDirection;
                 }

             }
             if (eventArgs.changeType == "CellDeleted" && eventArgs.changeDirectionState != undefined) {
                 trailObj["DirectionState"] = eventArgs.changeDirectionState.deleteShiftDirection;
             }
             else if (eventArgs.changeType != "Unknown") {
                 trailObj["Range"] = eventArgs.address;
             }
             if (eventArgs.details == undefined) {
                 ExcelTrail.push(trailObj);
             } else if (eventArgs.details.valueAfter != eventArgs.details.valueBefore)
                 ExcelTrail.push(trailObj);
             return context.sync().then(function () {
                 console.log(cell.values, cell.address);
             });

         }).catch(function (error) {
             console.log('Error: ' + JSON.stringify(error));
         });
     });
 }
```

**Comment by dingjin-ms** [comment]
Hi @Jayshiv1408Dev , thank you for reporting the issue.

For scenario 1 you mentioned, it's by design, the 'onChanged' event only catches the direct data changes of the cell.

For the calculated changes, please refer to [onCalculatedEvent](https://learn.microsoft.com/en-us/javascript/api/excel/excel.worksheetcollection?view=excel-js-preview#excel-excel-worksheetcollection-oncalculated-member).
`const calculatedEvent = sheets.onCalculated.add(worksheetChanged);`

For scenario 2 you mentioned, I cannot repro the problem using following steps:
  1. Register worksheets onchanged event.
  2. Copy data from ranges in sheet1 (from UI).
  3. Paste data in sheet2.

I can get the registed "rangeEdited" event seen as follow. Could you please provide more information about this scenario?
![image](https://github.com/OfficeDev/office-js/assets/80384052/675d192e-3aef-4b82-bf8e-73a738a82f28)

**Comment by Jayshiv-IRIS** [comment]
@dingjin-ms  Thanks for your Quick Response,
Here when  onChanged event trigger that time I got this object where value is not there
![image](https://github.com/OfficeDev/office-js/assets/133626379/c3b670c7-5da9-4a73-a35c-baa51f13ec96)

Now when I insert data in cell (before its empty and I enter 100) manually that time I am getting details in that I get the old value(valueBefore) and new Value(valueAfter).
![image](https://github.com/OfficeDev/office-js/assets/133626379/6454fc09-6475-4cde-935c-f5cb1d9f788b)


To display changes I want Latest value and old value for each cell which getting changed.

**Comment by dingjin-ms** [comment]
@Jayshiv1408Dev I now comprehend the issue you’re facing; however, this behavior is intentional by design. The 'undefined' details you’re encountering are not due to copying and pasting from a different sheet, but rather because the copied content isn’t just plain values—it includes **formulas**. Even if you were to copy a formula within the same sheet, the details would still appear as 'undefined'.

We regard this situation as a potential new feature request. If this functionality is significant to you, we encourage you to visit the [Microsoft 365 Developer Platform](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) to check if your question has already been addressed or to submit a new inquiry. We take such feature requests into consideration during our planning process.
