### ISSUE TITLE
Cannot set visible property

### ISSUE THREAD

**Issue by jkpieterse** [OfficeDev/office-js#3949]
I'm trying to change the visible property of a name, but this snippet does not work:

    Let nameName = "test"; //existing range name
    Let refersTo = "=1";
    Let namedItem = wb.names.getItemOrNullObject(nameName);
    namedItem.load();
    await context.sync();
    namedItem.set({ formula: refersTo, visible: false});
    await context.sync();

Only the formula gets updated, not the visible property. Why?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c053eb7-fa96-abb3-1367-bd4ffcbf35f6
* Version Independent ID: 0cf3de9b-a1c6-7d12-4f87-0ec03d46311f
* Content: [Excel.Interfaces.NamedItemUpdateData interface - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/excel/excel.interfaces.nameditemupdatedata?view=excel-js-preview)
* Content Source: [docs/docs-ref-autogen/excel/excel/excel.interfaces.nameditemupdatedata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel/excel.interfaces.nameditemupdatedata.yml)
* Service: **excel**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @jkpieterse.

@alison-mk, could you please investigate?

**Comment by AlexJerabek** [comment]
Hi @jkpieterse,

Sorry about the delayed response. I tried setting only the `visible` property to false for a named range. That didn't change the underlying `visible` property either. My guess is that property is supposed to be readonly, since I'm not sure what making a single cell invisible would actually do.

I'm going to send this issue over to the [office-js repo](https://github.com/OfficeDev/office-js), where a member of the feature crew can take a look. I'm hoping they can provide clarity on the expected behavior of this property so we can update the documentation accordingly.

**Comment by penglongzhaochina** [comment]
Where platform do you use? Desktop or Web?

**Comment by jkpieterse** [comment]
This is Desktop Excel. I've resolved the issue though:

    Let nameObj = wb.names.getItemOrNullObject("TheName");
    nameObj.visible = false;
    await context.sync();
