### ISSUE TITLE
Can't retrive text boxes (if I remove the placeholder text)

### ISSUE THREAD

**Issue by martinewald** [OfficeDev/office-js#3968]
The collection context.document.contentControls is empty even I have serveral text boxes in the document. But If I add a text box and don't remove the placeholder text, the content control is found. The following code is used:
`const contentControls = context.document.contentControls;
contentControls.load('id');
await context.sync();`

But as soon as I remove/overwrite the placeholder text, the text box vanishes from the collection. Not all, just the changed one. I can add text (and other content) additionaly to the placeholder and still find it but not remove the placeholder.

This is part of an Office Add-in created with the yo generator.

## Environment
* Platform : PC
* Host : Word
* Office version number: 365
* Operating System: 10/11 (tested on both)
 
## Expected behavior
The collection context.document.contentControls should be filled with all content controls.

## Current behavior
context.document.contentControls contains only text boxes which still have their placeholder text (Grab your readers's attention...)

## Steps to reproduce
1. Add a text box (Insert > Text Box > Simple Text Box)
2. Don't remove the placeholder
3. Get the context.document.contentControls collection -> The Text box is in the collection
4. Remove the placeholder
5. Get the context.document.contentControls collection -> The Text box is not in the collection

**Comment by xuruiyao-msft** [comment]
@martinewald Thanks for reaching out to us. The simple text box is by design created with a content control inside. The placeholder text is inside the content control which sets the property "Remove content control when contents are edited" true.
![simpleTextBox](https://github.com/OfficeDev/office-js/assets/5762929/bbde2640-b283-4f66-be3a-b8af74a5b64d)

So when you edit the content control content, it will be deleted. Then the simple text box is still in the document but the content control disappear which is as expected.

If you set the "remove content control when contents are edited" false, then you can edit the content control and the collection you get from 
`const contentControls = context.document.contentControls`
will always exist.

Tips: If you cannot find the content control, you need to set this property as this below picture:
![simpleTextBox2](https://github.com/OfficeDev/office-js/assets/5762929/1c1c1af7-efda-41c0-9581-22502460f7dd)

**Comment by martinewald** [comment]
@xuruiyao-msft Thanks for clarifying this! I thougt the whole box was the content control. Unfortunately this means that you have to change a lot of documents in order to make them work with our Add-in. 

Is there another way to access/change the content of a Simple Text Box?

**Comment by jipyua** [comment]
hi @martinewald, we haven't provided any textbox related APIs yet. If these apis are key for your business, We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum]( https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process. Thanks.
