### ISSUE TITLE
Opening a dialog in a dialog

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#403]
Trying to open a dialog in a dialog with displayDialogAsync results in error.

## Expected Behavior
I'm using the first dialog to display a form. When a user wants to save the form, a new dialog with another form should appear.

## Current Behavior
Executing displayDialogAsync in a dialog results in error "Office.context.ui.displayDialogAsync is not a function". Office.js is loaded in the HTML file of the dialog.

## Your Environment
* Platform: Office Online
* Host: Word
* Browser: Chrome

**Comment by Rick-Kirkham** [comment]
This is expected behavior. The only Office.js APIs that work in a dialog that is opened by `displayDialogAsync` are `isSetSupported` and `messageParent`. So you cannot call `displayDialogAsync` inside a dialog that was opened with `displayDialogAsync`. But your scenario is interesting. Consider making a request for this ability in [Office Developer Voice](https://officespdev.uservoice.com/).
