### ISSUE TITLE
Code works in Script Lab but not when copying over to a Powerpages Excel App.

### ISSUE THREAD

**Issue by mcpsmith** [OfficeDev/office-js#4054]
### Discussed in https://github.com/OfficeDev/office-js/discussions/4048

<div type='discussions-op-text'>

<sup>Originally posted by **mcpsmith** January 24, 2024</sup>
This code works fine in Script Lab (see gist [here:](https://gist.github.com/mcpsmith/6dfc93a9d1fc070121b958d4fb619168) but when I copy the same code into a PowerPages page's javascript I get the following errror: excel-win32-16.01.js:25  Uncaught (in promise) RichApi.Error: The argument is invalid or missing or has an incorrect format.
</div>

**Comment by dingjin-ms** [comment]
Hi @mcpsmith , thank you for raising the issue! 

I'm not sure how your use PowerPages with JS apis, could you provide more information about the repro steps so that we could repro by our side? 

And could you please try if your code work with the simplest demo add-in using the yeoman setup steps in [the document](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?view=excel-js-preview&tabs=yeomangenerator)?
