### ISSUE TITLE
What is the name of the Word.Developer Design Mode control (to use in a OfficeControl tag in a Word add-in manifest)?

### ISSUE THREAD

**Issue by KennieNP** [OfficeDev/office-js#4063]
According to docs
https://learn.microsoft.com/en-us/office/dev/add-ins/design/built-in-button-integration
I can *insert built-in Office buttons into your custom control groups on the Office ribbon by using markup in the add-in's manifest.*

To do so, I just need the id of the control: https://learn.microsoft.com/en-us/office/dev/add-ins/design/built-in-button-integration#insert-a-built-in-control-into-a-custom-group

  <Group id="Contoso.TabCustom2.group1">
        <Label resid="residCustomTabGroupLabel"/>
        <OfficeControl id="Superscript" />
        
    </Group>

According to the article, ids are available on a GH repo:
https://learn.microsoft.com/en-us/office/dev/add-ins/design/built-in-button-integration#find-the-ids-of-controls-and-control-groups

But the repo only has ids for PowerPoint.

I need the id for the "Design Mode" control from the Developer tab in Word.

How do I get that id?

**Comment by xiruatms** [comment]
@KennieNP , please be noted:

If your add-in is installed on a platform that doesn't support [requirement set AddinCommands 1.3](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/common/add-in-commands-requirement-sets), then the markup described in this article is ignored and the built-in Office controls/groups won't appear in your custom groups/tabs.

and 
https://learn.microsoft.com/en-us/javascript/api/requirement-sets/common/add-in-commands-requirement-sets?view=common-js-preview
The AddinCommands 1.3 requirement set introduces manifest markup that enables an add-in to customize the placement of a custom tab on the Office ribbon and to insert built-in Office ribbon controls into custom control groups. **At present, PowerPoint is the only Office client that supports this requirement set.**

That's why only ids for PowerPoint are list there.

Please correct me if I have misunderstanding here.
