### ISSUE TITLE
Outlook Web Addin cached for x days is not working after 24Hrs in Old Outlook Thick Client /New Outlook Thick Client 

### ISSUE THREAD

**Issue by geetamshukla** [OfficeDev/office-js#4129]
we are developing office web Addin for outlook using event based (Smart Alert) .The Addin is generated using office yo generator Task Pane add-in using the React framework 

**Is Outlook clearing up the cache more than 24hrs  ?? Not able to find any thing written in Microsoft documentation .**** 

****We have cached the Add-in for 15days  so that when the user is offline, we can validate the emails and save them in the user's draft folder But after 24Hrs we are getting message like  “Outlook Test Web Addin  is working on your request ” keeps on showing**  

<img width="743" alt="image" src="https://github.com/OfficeDev/office-js/assets/142812553/990761cc-b791-44b0-8729-49bc642624d5"> 

PFB details for outlook . 

![image](https://github.com/OfficeDev/office-js/assets/142812553/e151e29c-bc55-4aaf-8fee-38af223c9f8d)

 
![image](https://github.com/OfficeDev/office-js/assets/142812553/c8cf1a51-c19c-4aa7-a326-9bfc466cf001)

**Comment by zhngx1** [comment]
Can you help clarifying what cache are you referring to?

**Comment by geetamshukla** [comment]
> Can you help clarifying what cache are you referring to?

we have added a cache control in React Application for 15days  so that WebAddin can work in offline mode . The WebAddin is working for 23hrs and post that the Addin stops working in offline mode though cache is set for 15days 

<add name="Cache-Control" value="private,max-age=1296000 />

**Comment by millerds** [comment]
@geetamshukla I'm trying to understand your scenario a bit better and I have a few questions
- You talk about using the taskpane react yo office project and adding smart alert functionality to it.  The template provides react code for the taskpane UI, but are you using react for the smart alert (which doesn't have any UI) or just TypeScript?
- You added a react control in order to cache content for an extended period of time.  Are you seeing this take effect on the taskpane portion of you add-in?
- When you say "offline mode" what are you referring to?  (Note, we recently fixed the case where you have a Smart Alert with a "block" send mode specified in the manifest and you click the "work offline" button in Outlook . . . you won't be able to send the email in that case)
- Are you expecting emails in the draft folder to run or not run Smart Alerts when they are opened again?

**Comment by millerds** [comment]
@geetamshukla can you respond to my questions?
