### ISSUE TITLE
#NAME? Error on custom functions even everything is correct in it

### ISSUE THREAD

**Issue by bhattikashif** [OfficeDev/office-js#4185]
# Provide required information needed to triage your issue
We have a add-in using shared runtime and custom functions in it. Normally it works fine, but sometimes when user saves a workbook and open it again, it shows #NAME? error in cells containing custom function, which were working correct before saving. If user copies a cell with this error to new worksheet or cell, new cell also shows same NAME error. However if user types same formula or copies formula only, then it works fine. Also if user edit the cell, and without changing anything presses Enter, formula starts working correctly. Now user has hundreds/thousands of formulas entered and going to each cell and pressing F2 and Enter is not feasible. I tried to use Calculate and Calculate Sheet option, but it does not work. I also tried to calculate programmatically by calling setDirty(), Calculate on used range, Calculate(true) on worksheet and context.application.calculate(Excel.CalculationType.full), but nothing is working.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2401 Build 16.0.17231.20236)
* Operating System: Windows 10
* Browser (if using Office on the web): ______
 
## Expected behavior

Excel should not show #NAME? error on cells with correct formulas. Also if a cell is marked as ERROR, there should be some way to retry calculate it.

## Current behavior

Excel is showing #NAME? error on cells with correct formulas. and it prevents these cells from recalculation.

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ruijiaMS** [comment]
Hi @bhattikashif,
Thanks for letting us know this issue! Could you please provide the repro js script and the video if available? It will greatly help us to investigate the point of this issue.
For custom function re-calculation, it depends on how your custom functions defined. If the argument, including the argument of the reference cell, is changed or your are using the volatile function, the Calculation Now/Sheet on ribbon would trigger the recalculation of the given function. If it does not on your station, could you please provide the js script and the video as well? Thanks!

**Comment by 4tti** [comment]
Hello, our customer encountered this same behavior, after investigation it seems that somehow the **workbook got corrupted.**
The issue is that some cell definitions (sheetX.xml files within the *.xlsx ) got 'corrupted', i.e. instead of custom function ID it uses the caption of that formula.

Wrong definition:
`<c r="AN6" s="195" t="e" cm="1"><f t="array" aca="1" ref="AN6" ca="1">INFOR.READ.VALUE(Parameter!$B$1,Parameter!$B$2,"VALUE",Parameter!$B$3,Parameter!$I$7,Selection!$C$4,Selection!$C$12,Selection!$C$15,"[D001].[FX_OP_EUR_"&amp;'Sales PL Iso'!$B$5&amp;"]",$P6,Selection!$C$11)</f><v>#NAME?</v></c>`

The correct one:
`<c r="R7" s="261" cm="1"><f t="array" ref="R7">-_xldudf_INFOR_BP_OIS_READVALUE(Parameter!$B$1,Parameter!$B$2,"VALUE",Parameter!$B$3,Selection!$C$2,Selection!$C$4,Selection!$C$5,Selection!$C$15,"[D001].[FX_OP_EUR_"&amp;'Sales PL Iso'!$B$5&amp;"]",$P7,Selection!$C$10)</f><v>0</v></c>`

We are trying to get some more details how this could happen. 
Can you please reopen this ticket? I'll get back to you once I have more information.
@ruijiaMS, @Wenjun-Gong 
Thanks a lot in advance! 

Edit: the only way how to fix those cells is to manually edit them or run find/replace... where you will replace '=' with '=' ... that will fix it. However, customer has hundreds of reports and mentioned that this is happening from time to time and is extremely annoyed that he has to use this workaround.

**Comment by qinliuMSFT** [comment]
Hi @4tti , we have created an internal item for tracking this issue #9433004. I will remove the `Need Author Feedback` tag as it will trigger an automatic closure after a week of no response from you. Once you have more details on how this happened, please feel free to contact us and the product team will investigate further. Thank you for reporting this issue.

**Comment by 4tti** [comment]
Hello @qinliuMSFT, we are still not able to pinpoint the reason. Unfortunately, the customer is not very communicative, we only know that most likely it is caused by automation (see https://github.com/OfficeDev/office-js/issues/4833).

**Comment by qinliuMSFT** [comment]
Thank you @4tti for the information you provided. Can you confirm that #4833 is also caused by the workbook being damaged (instead of custom function ID it uses the caption of that formula)? If the reasons behind these two cases are the same, then it seems that we can assume that they are related and we can handle them together.
