### ISSUE TITLE
npm package 

### ISSUE THREAD

**Issue by nadeemAshfaq** [OfficeDev/office-js#4188]
I do not know if this is working already or not.

I am working on a project that needs to use a custom function in this function I need to use an npm package is that possible.

This is my code:
import numberToWords from "number-to-words";

export function TA(first1) {
  console.log(first1);

  // Convert the number to words
  const words = numberToWords.toWords(first1);

  return first1;
}

CustomFunctions.associate("TA", TA); 

code in json file:
{
   
    "functions": [
        {
            "description": "Add two numbers",
            "id": "TA",
            "name": "TA",
            "parameters": [
                {
                    "name": "first1",
                    "type": "any"
                }
            ]
           
        }
    ]
}

**Comment by AkhileshShah-MS** [comment]
Hi @nadeemAshfaq , Thanks for reaching out. We need more details to be able to triage this issue. Can you please provide the details as per following template. 


# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior


## Current behavior



## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)



1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context



## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by nadeemAshfaq** [comment]
thanks I created an API and used it in my custom function
