### ISSUE TITLE
An unexpected pop-up opens upon composing a new email disrupting the on-send flow.

### ISSUE THREAD

**Issue by MehakFatima24** [OfficeDev/office-js#4217]
# Unexpected pop-up on sending emails
We have an OWA add-in and recently we start getting this behaviour which is when a user sends a new message it goes to a new popup.

This disrupts the normal sending flow of the emails and our add-in and causes unexpected behavior for the end-users. This behavior is inconsistent among different users within same organization.

## Impact
We have a series of actions that get triggered when the on-send event is triggered but since a new popup now opens and closes immediately the series of actions that are required to be completed by the add-in are not triggered.  We have been encountering this behavior after the latest releases. 

This is very similar to this issue reported in the past (https://github.com/OfficeDev/office-js/issues/1381), In the past, this was related to the **OnSendAddinsEnabled** property, but it was then remedied. For the effected mailboxes in the current scenario this setting is set to false.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:  Office on the web
* Host [Excel, Word, PowerPoint, etc.]:Outlook
* Office version number: 2402
* Operating System: Mac
* Browser (if using Office on the web): Chrome
 
## Expected behavior

The user to be able to send messages with out an extra popup window opening.

## Current behavior

Whenever the user composes a new message a popup window opens. 

## Steps to reproduce

1. Go to outlook
2. Compose a new email
3. Click send

**Comment by DivyaPatidar** [comment]
@MehakFatima24  As mentioned in the #1381 and [On-send feature for Outlook add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=classic#install-outlook-add-ins-that-use-on-send:~:text=In%20Outlook%20on%20the%20web%2C%20when%20the%20on%2Dsend%20feature%20is%20triggered%20in%20a%20message%20being%20composed%20within%20the%20Outlook%20browser%20tab%2C%20the%20item%20is%20popped%20out%20to%20its%20own%20browser%20window%20or%20tab%20in%20order%20to%20complete%20validation%20and%20other%20processing.) this is expected behaviour.

**Comment by MehakFatima24** [comment]
Hi @DivyaPatidar this is not the expected behavior, kindly refer to the comment here (https://github.com/OfficeDev/office-js/issues/1381#issuecomment-709033995). 

We have a series of actions that get triggered when the on-send event is triggered but since a new popup now opens and closes immediately the series of actions that are required to be completed by the add-in are not triggered.  We have been encountering this behavior after the latest releases. 

Maybe https://learn.microsoft.com/en-us/officeupdates/current-channel#version-2402-february-28 & https://learn.microsoft.com/en-us/officeupdates/current-channel#version-2402-march-04 is worth taking a look at. 

Thank you for looking into this!

**Comment by designcode** [comment]
I can also reproduce this and it is also affecting our setup too.

**Comment by rickgoud** [comment]
Same here.. how can this happen again?! Please give high prio as it affects user experience very much!

**Comment by manaunl** [comment]
@DivyaPatidar we have verified the `OnSendAddinsEnabled` flag for our test tenant and it is set to FALSE as a default value. Despite this configuration, starting from March 4, the issue has sporadically affected various accounts within the tenant and also has a huge impact on our customers.

**Could you please review the latest releases to verify if any changes could have affected this functionality?**

**Comment by MehakFatima24** [comment]
Do we have any updates on this @DivyaPatidar ?

**Comment by ajays-msft** [comment]
We made some backend change and this behavior is not repro anymore.
Please try now and get back if you still see the issue.

**Comment by geoffreyreemer** [comment]
@ajays-msft Hi Ajay. We see a regression of this issue on some accounts since today.

Steps to reproduce:
1. Compose a new email with recipient, subject and body
2. Click Send

Actual behavior:
The email is sent in a new popped up window, which often doesn't load our add-in to check for secure sending. 

Expected behavior:
The email is sent in the same window.

All the information in the ticket applies to our add-in. We would appreciate you looking into this.
