### ISSUE TITLE
Mentimeter for Powerpoint add-in error: This add-in could not be started...

### ISSUE THREAD

**Issue by oleksiihopchenko** [OfficeDev/office-js#4228]
# Provide required information needed to triage your issue

Users are not able to fully use Mentimeter powerpoint plugin. 
![image](https://github.com/OfficeDev/office-js/assets/142214410/76154271-3737-4e7f-8e1d-e6ebaf1aba5f)
![image](https://github.com/OfficeDev/office-js/assets/142214410/22272a92-f1fe-4a4d-b2f9-975c83debac7)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: Version 2401 Build 16.0.17231.20236 and higher
* Operating System: Widnows 11
 
## Expected behavior
No error should be visible. Add-in starts without an issue

## Current behavior
Users are facing the following error. And have issues using add-in.
![image](https://github.com/OfficeDev/office-js/assets/142214410/f0c2f241-f843-4f20-8e0f-df9131133af2)

## Steps to reproduce

1. Use Powerpoint 2401 or higher
2. Install Mentimeter add-in
3. see the error

# Provide additional details
We've noticed that the issues started appear to our customers after the latest update 
Current Channel | 2402 | 17328.20162 | March 4, 2024 | March 4, 2024 | Version 2403 is released
Also we haven't done any changes from our side so far so the codebase is the same. But issue appeared.
Issue is not reproducing on MacOS

## Context
Some of our customers are unable to fully use the add-in and experience the following after dismissing an error 

- the menti slide starts changing the size of the letters when using it
- the speaker cannot start the menti with the slide presenter
- the speaker cannot go to the next slide with the slide presenter
- the speaker cannot show the results to the public with the slide presenter"

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by EsterBergen** [comment]
Thanks @oleksiihopchenko  for sharing this!  I can see it for Mentimeter on version 2404. Will look into this and will respond back here. Do you also see this on web, or just Win 32?

**Comment by oleksiihopchenko** [comment]
Hello @EsterBergen! Thanks for the quick response. We do not support web version. So it's just win 32

**Comment by oleksiihopchenko** [comment]
Hi @EsterBergen. Any insights on this issue? Our users are still experiencing it :(

**Comment by FilipStenbeck** [comment]
@EsterBergen Hi, has there been any progress with this issue?

**Comment by croicu** [comment]
The problem is the first page load returns HTTP error 500. This is treated by Office as an unrecoverable error and this is why we are displaying the error banner:

GET https://www.mentimeter.com/_integrations/entry/powerpoint?manifest_version=4.1&et=PAByACAAdgA9ACIAMQAiAD4APAB0ACAAYQBpAGQAPQAiAFcAQQAxADIAMwA0ADUANgA3ADgAOQAiACAAcABpAGQAPQAiAGMAZQAzADkAOQBlADIANQAtADIAYgA1ADYALQA0AGYAZQA3AC0AOABkADAAYwAtADAAZgBmAGUAMgA0ADYAZgAyADAANAAzACIAIABvAGkAZAA9ACIANABPAEsAQgAwADEAOABEAC0ASgBPADAANwAtADQANwBHAEcALQBBADIAOQAxAC0AWgBSADMAMABBADcAMQA4ADcAWgA0ADAAIgAgAHQAcwA9ACIAMAAiACAAcwBsAD0AIgB0AHIAdQBlACIAIABlAHQAPQAiAEYAcgBlAGUAIgAgAGEAZAA9ACIAMgAwADIAMgAtADAANgAtADIAOABUADIAMwA6ADUAOQA6ADUANwBaACIAIABzAGQAPQAiADIAMAAyADIALQAwADYALQAyADgAIgAgAHQAZQA9ACIAMgAwADIAMwAtADAANgAtADIAOABUADIAMwA6ADUAOQA6ADUAOABaACIAIABzAHMAPQAiADAAIgAgAC8APgA8AGQAPgA2AHgALwBEACsAZABHAE8AVQB5AEYAcgBsAEgAYgB0AFQAWQAvAGEAeABRAGoAYwBQAEwAZgA1AGEAYwA0ADIAdABXAEUAeQBXAFQAWQB5AFIAOQA2AD0APAAvAGQAPgA8AC8AcgA%2BAA%3D%3D&_host_Info=Powerpoint$Win32$16.01$en-US$$$$16 HTTP/1.1
Host: www.mentimeter.com
Connection: keep-alive
sec-ch-ua: "Microsoft Edge";v="123", "Not:A-Brand";v="8", "Chromium";v="123", "Microsoft Edge WebView2";v="123"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9


HTTP/1.1 500 Internal Server Error
Date: Thu, 28 Mar 2024 21:56:26 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
CF-Ray: 86badebe0a70ec60-SEA
Cache-Control: public, max-age=300, stale-while-revalidate=300, stale-if-error=86400
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Url, Accept-Encoding
content-security-policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' *
referrer-policy: strict-origin-when-cross-origin
x-content-type-options: nosniff
x-edge-runtime: 1
x-matched-path: /entry/powerpoint
x-permitted-cross-domain-policies: none
x-powered-by: Next.js
X-Robots-Tag: noindex, nofollow
Set-Cookie: __cf_bm=L1AlGCOPy6COP1jdZ5i5ID5NyvkebhBBOT8.OoGmhvs-1711662986-1.0.1.1-5t1klRnHrRHTL4jJwoHYWv1gUBjqEsselWg4i6nbJ.4V8sKGTF2f1Nr1_bqoVHojgWlhYb09I.qVDdqBDcuv6A; path=/; expires=Thu, 28-Mar-24 22:26:26 GMT; domain=.mentimeter.com; HttpOnly; Secure; SameSite=None
Server: cloudflare
alt-svc: h3=":443"; ma=86400
Content-Length: 10539

...

**Comment by croicu** [comment]
I believe that returning 200 will fix the error without the need for a client fix.

**Comment by EsterBergen** [comment]
@FilipStenbeck and @oleksiihopchenko - Can you try the proposed fix above and let us know if that resolves the issue?

**Comment by FilipStenbeck** [comment]
Thanks for reaching pout for us, we will investigate why we get a 500 error and see if there is a way to get around that error.

**Comment by FilipStenbeck** [comment]
We have deployed a fix and we have seen that now that we return 200, the integration loads. Thank you for your help!

**Comment by EsterBergen** [comment]
@FilipStenbeck - so glad it works now! @croicu - thank you for tackling this customer issue!
