### ISSUE TITLE
On-Send web addin does not load when mail is sent through GraphAPI.

### ISSUE THREAD

**Issue by sagar-sonawane9** [OfficeDev/office-js#4252]
Description -
On-Send web addin does not load when mail is sent through GraphAPI.

Steps to Reproduce -

Write an automation script to send mail on New Outlook OWA using graphAPI.
Run the script and check whether mail is getting sent.

Expected Result -
Operation initiated with GraphAPIs does not generate required callbacks (like ONSEND) for Outlook WebAddin, which causes failure to communicate operation details.

Can we generate required callbacks for operation initiated with GraphAPIs. 

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by ajays-msft** [comment]
@Sagar-lab1 This is by design. Office/js events are generated for client side operations only.

We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered when we go through our planning process.
