### ISSUE TITLE
Future of Sideloading with New Outlook

### ISSUE THREAD

**Issue by mwrouse** [OfficeDev/office-js#4257]
It looks like the "New Outlook" interface has been changed to match the web interface. Doing File > Manage Add-Ins is no longer an option with the New Outlook.

I understand that the New Outlook is still in preview, but with recent changes to make sideloading more difficult (no longer able to upload from URL and needing to use the URL to get to the dialog to upload a file) is sideloading at all going to continue to be supported? Using https://aka.ms/olksideload is the only option now.

Can you confirm if sideloading by uploading a file is going to continue to be supported or do us organizations with customers on different domains need to come up with an alternative solution to have an app in the app-store.

**Comment by shighosh-msft** [comment]
Thank you for your inquiry regarding sideloading apps in Outlook. I appreciate your interest, and I’m happy to provide some information.

**Sideloading on the Outlook Roadmap:** Sideloading is indeed part of our New Outlook roadmap. However, as of now, we do not have an ETA for its implementation, since we are currently investing in other core scenarios on New Outlook. Rest assured, our teams are actively working on this feature to enhance the Outlook experience.

**Admin-Side Controls for Sideloading:** We understand the importance of allowing end users to sideload apps to their Outlook clients. Currently, we are collaborating with the admin v-team to develop the necessary controls within the Microsoft 365 Admin Center. Once these controls are in place, we will enable the sideloading feature in the store.

Thank you for your patience, and please stay tuned for further updates. If you have any additional questions, feel free to reach out.
