### ISSUE TITLE
the office dialog API versus task panes

### ISSUE THREAD

**Issue by LewisPringle** [OfficeDev/office-js#426]
As near as I can tell, the office-js dialog class has these features

*Office.Dialog*

**Pros**:

 - it can be launched from script code

**Cons**:

 - it appears not to be able to access Excel.Run()
   [(stackoverflow)][1]
 - It doesn't appear to support modal dialogs
 - it appears you cannot constrain resizing (for fixed size dialogs - like alerts)
 - You can only have ONE at a time? Meaning if you use the dialog feature to implement a user-warning (classic modal dialog/alert) - then you cannot invoke that alert from a modeless dialog using the same Office.Dialog mechanism.

And office-js provides another mechanism - the task pane - which is ALMOST equivalent, except:

*Task Pane*

**Pros:**

- you can have multiple of them
- they do support Excel.run()

**Cons:**

- you cannot open one from code (only from special static entries in the function file)

**Question**

The ONLY advantage 'dialogs' appear to have over 'task panes' is that they can be invoked from code instead of just statically from the function-file, and perhaps that when invoked they start out 'detached' instead of glued docked to the excel app. But then they add all these huge disadvantages that seem pointless.

Does Office-js provide some third API that works better than these two? Or fills in some of the gaps? Are there any plans to unify these, and/or to fix some of these limitations?

  [1]: https://stackoverflow.com/questions/55172250/can-i-invoke-excel-run-in-a-page-hosted-inside-an-excel-dialog-using-office-j

**Comment by LewisPringle** [comment]
(note - originally on stackoverflow, but  Rick Kirkham  suggested moving it here.

**Comment by Rick-Kirkham** [comment]
Some thoughts and questions:
1. I don't think a dialog and a task pane should be thought of as alternatives to each other. They have different purposes. If you add-in needs a visible UI, you should use a [task pane](https://docs.microsoft.com/en-us/office/dev/add-ins/design/task-pane-add-ins). [Dialog](https://docs.microsoft.com/en-us/office/dev/add-ins/design/dialog-boxes)s are normally launched from the task pane, and they are generally meant to have a brief lifespan and only minimal user interaction. It is possible, however, to open a Dialog from an [Add-in Command](https://docs.microsoft.com/en-us/office/dev/add-ins/design/add-in-commands); that is, a custom ribbon button or menu item. But it should still have a limited purpose and lifespan. You can also open a task pane from an Add-in Command. This is configured in the manifest. 
2. I'm not familiar with the phrase "static entries in the function file". Could you explain and give an example?

**Comment by LewisPringle** [comment]
Please allow me to provide more detail as to what I tried to do, and how I failed.

My plugin needs what you can think of as an 'open' dialog. You essentially import data from a server into an excel spread sheet.

Typically, on windows, this sort of thing would be done with a modal dialog, hence I selected your dialog API.

Then - I discovered - sometimes network accesses fail - and so i need to be able to put up a modal dialog, telling the user 'oops that failed'.

Both of these two uses appear on the surface to meet your dialog usage criteria 'generally meant to have a brief lifespan and only minimal user interaction' - I think.

Both worked out HORRIBLY - essentially unusable because:

 > the dialogs were not modal
 > the dialog API was limited to one at a time (so an error in the open data dialog couldn't be reported using the modal dialog alert).

It is also quite awkward that the modal dialog to open a sheet (from the server side data) - cannot DO the logic of inserting stuff in the sheet, and must 'message' that request to another task pane (message parent) to do the insertion work. But this I have managed to workaround.

I see NO WAY around the problem of modality however. This is probably the most killer of the fatal flaws with the dialog API. Being modeless, it can EASILY get hidden behind excel and then the user doesn't know why the open data dialog didn't appear (one of the oldest bugs classic to the various microsoft platforms).

I may still be forced to use the dialog API only because there is SOME control that way over the default size of the window (which you cannot do with task panes), and because of the need of dynamic control flow through the application (your second question).

As for your question #2 - "static entries in the function file". The only way to launch a task pane is to bind it to a <Action xsi:type="ShowTaskpane"> element in the task pane. This is STATIC. You cannot dynamically create these in your application. They must be statically defined at application build time, and they cannot be used to invoke a window in response to a situation (like a network error, an authorization token timing out etc).

So for some sorts of interactions - ones that need to happen because something dynamic happened during the performance of some other action, you are FORCED to use the dialog API (despite all its limitations).

**Comment by Rick-Kirkham** [comment]
I think I understand better. 
1. Task panes are declared in the add-in's _manifest_, not a function file. (Task panes can be opened from ribbon buttons that are also declared in the manifest.) This was confusing because there is something called a FunctionFile.html (and FunctionFile.js) in Office add-ins, but these have a different purpose. They are not used to statically declare task panes. 
2. I don't know what lies behind your assertion that, with respect to importing data from a server, "on windows, this sort of thing would be done with a modal dialog," To me it seems that importing data to the Excel worksheet is the meat and potatoes of your add-in. I think it should be done from a UI on a task pane. That's where the main functionality of the add-in belongs. 
3. For error messages, such as network failures, you _could_ use the Dialog API (in which case the user would have to close it before there could be a second call of that API from the same task pane), but that might be overkill for a simple error message. I would recommend that you think about showing the error inside the task pane. It could be as simple as toggling the visibility of a `<div>`. There are also libraries that supply various ways of showing messages or getting user feedback. For example, There is this [Office UI Fabric library](https://github.com/OfficeDev/office-ui-fabric-js). It has components for [MessageBar](https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/components/MessageBar.md), [MessageBanner](https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/components/MessageBanner.md), and even [Dialog](https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/components/Dialog.md). And you can grey out the rest of the task pane with [Overlay](https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/components/Overlay.md). If you don't want to use the Office UI components, there are non-Microsoft libraries that have similar components, like [Bootstrap](https://getbootstrap.com/).

**Comment by LewisPringle** [comment]
For point #2, try using the excel open dialog. You'll note its a modal dialog. Try to find ANY application on windows where the open dialog is NOT a modal dialog. That's what 'lies behind your assertion'.

Also since I've seen my applicaiton, and you have not, you'll need to take my word for it (unless you'd like to see a demo) - the open / chart selecting/data import dialog is a very small part the application. And layout wise - it would work HORRIBLY as a task pane (because the dialog is wide and the way task panes are laid out wound't work/fit).

As for point#3, you are CORRECT, about using a floating DIV IF the alert happened to happen in the context of a task pane (or dialog). But the errors CAN be triggered from buttons in the ribbon bar. That means the javascript code - has to put up an alert one way if its launched from the ribbon bar(functionfile) and another way if launched from a task pane or dialog. That's needlessly complicates the programming, and its a bit of a weird choice for UI (sometimes error dialogs appear in the task pane you were operating in and sometimes they launch a new modeless dialog just to display that error).

Glad to see Microsoft takes these suggestions for how to improve their API/UI so seriously - just mark it as closed before bothering to understand it ;-). I guess that explains the state of office addins.
