### ISSUE TITLE
AutoSave is not triggered when only custom properties is added and nothing else has changed in document - Word add in

### ISSUE THREAD

**Issue by ManoharRTTR** [OfficeDev/office-js#4320]
When we tried to add a custom property through officeapi on a word addin by turning on AutoSave option. autosave is not initiated when a new custom property added and nothing else is changed in the document.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Desktop Word Addin
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Version 2401 (Build 17231 20290)
* Operating System: Windows 10
* Browser (if using Office on the web): ______
 
## Expected behavior
AutoSaved is initiated and document is saved with the custom property added.

## Current behavior

AutoSaved is not initiated and document is not saved with the custom property added.

## Steps to reproduce

 Word.run(async (context) => {
    context.document.properties.customProperties.add(key, value)
    return context
      .sync()
      .then(() => {
        console.log('Property saved')
      })
      .catch((e) => {
        console.log(`Error occured inserting property ${e.message}`)
      })
  })

**Comment by xuruiyao-msft** [comment]
@ManoharRTTR I cannot reproduce the issue on my local environment. I executed the code snippet after the autosave button is toggled. Then I close the document and reopen it again. The custom properties are saved successfully. I can get the custom properties :
`async function getCustomProperties() {
  Word.run(async (context) => {
    const customProperties = context.document.properties.customProperties;
    customProperties.load();
    await context.sync();

    for (let i = 0; i < customProperties.items.length; i++) {
      console.log(`${i}: ${customProperties.items[i].key}: ${customProperties.items[i].value}`);
    }
  });
}`
Did I miss some key information to reproduce the issue? What's the behavior from your side observing that AutoSaved is not initiated and document is not saved with the custom property added? How did you set the AutoSave option? If you can provide more detailed steps that would be helpful to relocate the root cause. Thanks again for reaching out to us.
