### ISSUE TITLE
Classic Outlook - Forwarding email from Shared Malbox corrupts 1 attachment per forward when in online, uncached mode

### ISSUE THREAD

**Issue by MrDaleQ** [OfficeDev/office-js#4331]
When forwarding an email with an attached image or PDF from a shared mailbox, this can result in one of the attachments being corrupted on the forwarded email. It is not possible to see the corruptedd attachment until the email is sent.

## Your Environment
* Platform: PC Desktop
* Host: Outlook Classic
* Office version number: 16.0.17425.20124
* Operating System: Windows 11
 
## Expected behavior
Attachments are not corrupted

## Current behavior
Currently, the best way to replicate is by taking a photo from a mobile device, and sending this to a shared mailbox via email.

-- Take jpeg image on phone
-- Send the image via email to shared mailbox
-- Ensure the shared mailbox is opened in Online mode
-- Forward email from Shared mailbox
-- attachment icons flicker and when received, recipient cannot open the attachment, although the attachment is shown on the email

I have a replicatable .msg file exhibiting the behaviour and am currently confirming with the customer that this can be shared.

**Comment by MrDaleQ** [comment]
https://github.com/MrDaleQ/MSShare/issues/3

Contains the email to replicate the issue

**Comment by MrDaleQ** [comment]
@exextoc are there any updates to this bug at all?

**Comment by zhngx1** [comment]
To confirm the repro steps, the first email is from mobile app to shared mailbox right?
The issue is when using classic desktop Outlook to forward the email? What if you use New Desktop Outlook or Outlook web to forward, is there any issue?

Does the final recipient for forwarding need to be a shared mailbox to repro?

**Comment by johnny-outreach** [comment]
@exextoc 

In our experience, the first email is from a mobile app to a shared mailbox yes.

The issue is when using classic desktop Outlook to forward the email, We have been unable to replicate the issue with New Desktop or Outlook Web 

The final recipient for forwarding does **not** need to be a shared mailbox, it can be a normal user mailbox.

Just to confirm here the shared mailbox where you are sending the email from **has** to be in Online mode (you do not encounter the issue with cached mode). I believe you have access to an example email which demonstrates this behaviour?

**Comment by ajays-msft** [comment]
Are you using office js in any of these steps? Or is it all via outlook UI?

**Comment by MrDaleQ** [comment]
hi @ajays-msft 

The customers in question are using our modern add-in, which calls the setsignatureasync method.

**Comment by ajays-msft** [comment]
@MrDaleQ
Is the attachment being added or modified in any of the flows using office js apis?

And, is the issue repro when addin is not installed?

I am trying to understand if office js is the cause of the bug.

**Comment by MrDaleQ** [comment]
@ajays-msft 

Thanks for the reply.

The add-in calls setsignatureasync to insert the signature - if any images are present these are embedded inline to the message body by the addin, but we cannot and do not modify existing attachments aside from this.

**Comment by zhngx1** [comment]
@MrDaleQ @johnny-outreach Just to clarify, if there is no add-in running, does it still repro? And if add-in does NOT call setSignature will it repro?

**Comment by johnny-outreach** [comment]
@zhngx1 If the add-in is not running you do not encounter the same issue.

If the add-in does NOT call setSignature it will not encounter the same issue.

I can replicate the issue here if you need to see the issue?

**Comment by zhngx1** [comment]
@johnny-outreach I cannot repro the issue. If you have recording of the repro that would be great.

**Comment by MrDaleQ** [comment]
please reopen this issue.

**Comment by MrDaleQ** [comment]
@zhngx1 please see a screen recording of the issue. I have invited you to the GH repo we use to share these issues.

https://github.com/MrDaleQ/MSShare/issues/5

just to clarify, this only occurs in Online mode.

**Comment by zhngx1** [comment]
@MrDaleQ I have tried on the lastest and the 16.0.17425 build, and still cannot repro. I am wondering if the first mail from the phone has anything to do with your issue. If the first mail is from desktop or Outlook web, do you still repro?

**Comment by johnny-outreach** [comment]
@zhngx1 We have only been able to replicate (consistently) if the original email is sent from a mobile device.

I will check internally if we have any firm cases where the first mail comes from a different source (other than mobile) and come back to you on this.

**Comment by MrDaleQ** [comment]
@zhngx1 please see Johnny's response above - he is one of the internal team here.

**Comment by RobertMatthieu** [comment]
@zhngx1, @MrDaleQ and @johnny-outreach,

The original issue was reported to Johnny-Outreach by me. 
I've just tested with Outlook 16.0.17911.20000 build from the beta channel and the issue is still there. 

@zhngx1 
The issue only happens when a person sends a picture made on their mobile phone and sends this picture with the Outlook for IOS or Android app to our customers shared mailbox. When you send the same picture with, in my case the IOS own mail app or Outlook on a Windows computer, everything works as it is supposed to be.

Let me know if you need any other information.

**Comment by zhngx1** [comment]
@RobertMatthieu Thanks for clarifying. I tried to send attachment from Outlook on iOS device to a shared mailbox but could not repro. What version of Outlook do you have on your iOS device?

**Comment by RobertMatthieu** [comment]
@zhngx1 No problem at all. I am using Outlook for IOS version 4.2428.0.

I just tested again and the problem looks to be solved with the new IOS and Windows Outlook versions on my test machine. The Windows client has been updated to version 2408 (build 17920.20000) of the beta channel.

I will keep monitoring this week if its really resolved and let you know.

@johnny-outreach Has there been any changes in de Signature software on your end that maybe helped with this issue? You can also reach me on my known business e-mail of you dont want to share that here.

**Comment by MrDaleQ** [comment]
please reopen this ticket - this has been closed incorrectly

**Comment by MrDaleQ** [comment]
@RobertMatthieu thanks for your previous update here - are you still seeing this issue as being resolved in the 2408 update?

Just to confirm, there have been no changes on our side that would affect this issue - the underlying API call that is causing this problem is Microsoft code that we call from inside the add-in.
