### ISSUE TITLE
Office Online add-in unable to communicate with dialog via BroadcastChannel

### ISSUE THREAD

**Issue by jim22k** [OfficeDev/office-js#4387]
# Provide required information needed to triage your issue
Dialogs opened using displayDialogAsync are unable to communicate back to the main add-in using a BroadcastChannel for Office Online.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Mac
* Browser (if using Office on the web): Chrome
 
## Expected behavior

1. Create a BroadcastChannel in Excel add-in and register a `channel.onmessage` listener.
2. Open a dialog using `Office.context.ui.displayDialogAsync(url, { promptBeforeOpen: false })` to a page in the same origin as the add-in (a requirement of displayDialogAsync).
3. Create a BroadcastChannel in the new dialog window with the same channel id that the add-in's broadcast listener has.
4. Call `channel.postMessage(msg)` from the dialog.
5. The add-in receives the message via the broadcast channel.

## Current behavior

The message is never received.
Note that the message is received when run in Excel for Mac. I have also verified that BroadcastChannel works

## Steps to reproduce

1. See Expected behavior section

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. A simple dialog page that *should* be able to communicate back with the add-in
```<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
</head>
<body>
<h2>Dialog</h2>
<script>
    const channel = new BroadcastChannel("DialogTestChannel");
    channel.postMessage("Can you hear me?");
</script>
</body>
</html>
```
2. Code to open the dialog from the taskpane
```
const channel = new BroadcastChannel("DialogTestChannel");
channel.onmessage = (e) => {
  console.log("GOT THE BROADCAST MESSAGE", e);
};
Office.context.ui.displayDialogAsync(
  "https://localhost:3000/dialog.html",
  { promptBeforeOpen: false },
);
```

## Context

Communicating using BroadcastChannel seems pointless given that Office.context.ui.messageParent exists. Why not just use that?

I tried that, but after going thru my OAuth redirect flow (cross-origin), it is no longer possible to communicate with the add-in because Office.js cannot be loaded. I suspect this is due to the fact that window.opener is null after all the redirects. See https://github.com/OfficeDev/office-js/issues/3673 (comments at the end) for other users who appear to be having this same issue with Office Online. I suspect that if my OAuth provider set the correct headers, the referrer and/or original window opener could be preserved and things would work, but I do not have control over that.

I wanted a workaround solution, and BroadcastChannel *should* work as a mechanism for communicating between a window and an iframe from the same origin. However, something about Office Online seems to be blocking the BroadcastChannel communication to and from the add-in.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by shanshanzheng-dev** [comment]
Hi @m-hellesen, Could you help take a look this issue? Thanks.

**Comment by mayurandhare13** [comment]
@jim22k @m-hellesen 

I tried out `Office.context.ui.messageParent` and it worked fine 👍🏻 

**taskpane.ts**

    Office.context.ui.displayDialogAsync(
      "https://localhost:3000/dialog.html",
      { height: 40, width: 30, promptBeforeOpen: false },
      (asyncResult) => {
        const dialog = asyncResult.value;
        dialog.addEventHandler(Office.EventType.DialogMessageReceived, (args) => {
          // message received from "messageParent"
          console.log("Dialog message received: ", args);
          // dialog.close();
        });

        dialog.addEventHandler(Office.EventType.DialogEventReceived, (args) => {
          dialog.close();
        });
      }
    );

**dialog.html**
I imported Office JS
    <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>

    Office.onReady((info) => {
        Office.context.ui.messageParent("Message to Parent");
    });


--

Console log in parent taskpane

![image](https://github.com/OfficeDev/office-js/assets/43421646/3ad813d8-73f5-4b0f-8c39-9f12bdd1a4e4)

**Comment by jim22k** [comment]
@mayurandhare13

Change dialog.html to be
```
Office.onReady((info) => {
    window.opener = null; // because this is the result after OAuth2 flow happens in the dialog
    Office.context.ui.messageParent("Message to Parent");
});
```

And then run this on [Excel Online](https://microsoft365.com) and you will see the issue. The message is never received by the parent taskpane.

The whole reason for opening this issue is because the normal `Office.context.ui.messageParent` doesn't work in the specific case of Excel Online + non-iframe dialog + OAuth2 flow which loses window.opener reference. For that *very* specific, but *very* important case, it doesn't work. I was hoping that BroadcastChannel would be a workaround, but it doesn't work for some reason.

I did find a workaround which requires opening a dialog window which then opens another dialog window. Code is in a repo [here](https://github.com/jim22k/OfficeOnlineDialog).

**Comment by mayurandhare13** [comment]
@jim22k Yes with `window.opener = null` we lose the reference to the parent iframe (taskpane) So, dialog communication also breaks. 
So, what you mean is in dialog window you are performing some kind of OAuth2 flow which results in `window.opener` to be null. Am I correct? Could you please clarify which API are you using for OAuth2? maybe code snippet? (asking because it shouldn't be null, as other authentication dialog flow also follows ui.messageParent)
So, you tried to use `BroadcastChannel.` I saw your code. BroadcastChannel doesn't seem to work between dialog and parent taskpane.
But as a workaround, you open new window from dialog. So, in that new window you are simulating OAuth flow. and this is where BroadcastChannel works. (between new window and dialog window)

**Comment by jim22k** [comment]
The OAuth2 flow is done by redirecting to an [Ory](https://ory.sh) page and after the user successfully logs in, it redirects back to a URL which I specify. I don't have control over the process, but during the redirects `window.opener` gets set to `null`. I agree the best solution would be to not lose a reference to `window.opener`, but it's what I've got to work with.

Things I have tried:

- Open the dialog in an iframe -- the Ory auth flow won't run in an iframe (understandable)
- BroadcastChannel -- the add-in iframe has the same domain as the redirected dialog, but something is blocking the communication

Your summary of my workaround is correct. I never redirect within the dialog window to avoid losing the `window.opener` reference. Instead, I open another window (so now we have 3 -- add-in, dialog, extra window) and do the redirect Ory auth flow there. And once the redirect back to my original domain happens, I can communicate between the dialog and extra window using `BroadcastChannel`. And then I can communicate from dialog to add-in via `ui.messageParent`.

So I'm not blocked anymore, but it feels very hacky and I believe others are dealing with the same issue and looking for solutions -- see #4376 which sounds suspiciously similar.

**Comment by mayurandhare13** [comment]
@jim22k @shanshanzheng-dev @m-hellesen 

All add-ins are third party iframes, because they are hosted in Office Online which is in different domain.

I tried opening the dialog in iframe mode, BroadcastChannel communication works there as both dialog and taskpane's are iframe and same origin. (_Since, you are doing Auth, you need window dialog_)

As an alternative, you are opening new window from the dialog, basically communication between 2 window of same origin works for Broadcast Channel.

But from window (dialog) to iframe (taskpane) is not possible via BroadcastChannel.
[Google Storage Partitioning](https://developers.google.com/privacy-sandbox/3pcd/storage-partitioning#communication-apis)

With reference to above link, I tried this, BroadcastChannel communication works between taskpane ( iframe ) with dialog ( window ) works _if you disable the Third Party Storage Partitioning flag._

I am closing this issue, but I'll discuss with my team your messageParent doesn't work after Auth redirect (_which is your primary issue_).
