### ISSUE TITLE
Office.context.mailbox.item.body.getAsync() not able to give fully body content in reply scenario

### ISSUE THREAD

**Issue by ayush-sopori** [OfficeDev/office-js#4462]
In the Outlook add-in, we use the Office.context.mailbox.item.body.getAsync() method to get the entire email body in the required format. However, there is no way we can get full body content of mail trail when in reply or forward flow.
We are able to get the trail body only if the user clicks somewhere in the mail trail content.
Is there any work around to get full body of mail trail without user clicking on old mail or ellipse(...).?

## Your Environment
* Browser (if using Office on the web): Chrome 
## Expected behavior
The Office.context.mailbox.item.body.getAsync() method shall return the entire body.

## Current behavior
The Office.context.mailbox.item.body.getAsync() method returns only
the latest present content and not the mail trail content.

**Comment by mmanjaree-msft** [comment]
Thanks for reporting this. It is a known issue and we had provided a fix for this issue which had to be reverted due to another issue. We are actively working on a solution but unfortunately we do not have any timelines to share at this point.

Meanwhile a workaround is to change the layout setting of owa mail. Go to settings->Layout and select show email as individual messages under Message organization or if user has selected show email grouped by conversation, then arrange the reading pane by show each message separately
