### ISSUE TITLE
Content add-ins for Powerpoint cannot export website inside an iframe in web version

### ISSUE THREAD

**Issue by biencluong** [OfficeDev/office-js#4488]
I am developing an add-in for Powerpoint. It's a content add-ins that display an external link in an Iframe.

In the desktop version of Powerpoint, everything works fine, including export and print. But in the web version, when I try to export the slides to PDF or print, the content is always blank.
I find that it happens with every website link, not just the website that I tried to display.

Does anyone know what might have caused this and how to resolve it?
Thanks

**Comment by quangnguyendss** [comment]
i have same question. Do anyone know this?

**Comment by EsterBergen** [comment]
Hi @bienluongdss and @quangnguyendss on web, this is a known issue. For content add-ins on web, the api used for snapshots when printing is "[html2canvas](https://www.npmjs.com/package/html2canvas)". This open source API is currently an experimental API and has limitations.

This works on Win32 and Mac Desktop because the approach is native.

We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process.
