### ISSUE TITLE
Outlook add-in is not opening for some users in new Outlook for Windows UI

### ISSUE THREAD

**Issue by gs-schaurasiya** [OfficeDev/office-js#4497]
The Outlook add-in that works in all other environments, including Outlook for Windows (not the new UI) will not open for some users when using the new UI.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft Outlook Version 1.2024.516.100 (Production) (Client Version is 20240510004.32)
* Operating System: Windows 11 Home (23H2 -- 22631.3447)
 
## Expected behavior

The add-in opens and loads like normal in the new Windows UI.

## Current behavior

The user will click to open our add-in via the Apps popup or a pinned action and the add-in does not open. It appears to do nothing at all.

## Steps to reproduce

I can provide our add-in's manifest if needed, but it is not a publicly available. It also does not happen for all users, so it's unknown if you would be able to reproduce the issue.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by rajjha-msft** [comment]
Hey @gs-schaurasiya 

Can you share a video of the repro ? 
Do you see any error in the console when you click the add-in ?
Is this a transient issue, happens once in a while ?

**Comment by gs-schaurasiya** [comment]
Hi @rajjha-msft 

- I am attaching the video but it needs to be protected as its our customer shared video and also we are not able to reproduce this issue.

- For the console error we will be requesting a call with our customer and will look for it.

- This issue is consistently happening with some of the users who are using new outlook but there are some other users as well who are using new outlook but not facing this issue at all.

https://github.com/OfficeDev/office-js/assets/110825043/b4bbe017-3d27-4eb2-878e-b77be392d9d7

**Comment by anjalitp** [comment]
@gs-schaurasiya  Could you please share network logs as well? Steps to gather network logs: [Collecting log files for Outlook Add-ins issues · OfficeDev/office-js Wiki (github.com)](https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues)

**Comment by gs-skujala** [comment]
@anjalitp I am sharing the network calls and console logs here
[GSAssistNW.zip](https://github.com/user-attachments/files/15801424/GSAssistNW.zip)
[GSAssistConsoleLogs.log](https://github.com/user-attachments/files/15801428/GSAssistConsoleLogs.log)

Since there were so many network calls we observed,
We cleared everything and again saved the calls and logs that occurred after we tried to open our Add in where are provided below.
[GSAssistConsoleLogs2.log](https://github.com/user-attachments/files/15801510/GSAssistConsoleLogs2.log)
[GSAssistNW2.har.zip](https://github.com/user-attachments/files/15801515/GSAssistNW2.har.zip)

Please help us with this issue since our clients are blocked
