### ISSUE TITLE
[Outlook] [REST] Properties set via REST API not returned by OfficeJS API (even after synch delay)

### ISSUE THREAD

**Issue by splinter** [OfficeDev/office-js#450]
We are noticing that custom properties that are created using the Outlook REST API[2] are not accessible with the OfficeJS API[1] using the loadCustomPropertiesAsync callback. This is happening even after we compensated for any possible synching time (~5 min).

## Expected Behavior

Any custom property that is created with the Outlook REST API[2] should be accessible with the loadCustomPropertiesAsync callback. 

## Current Behavior
The custom properties created using the Outlook REST API are not available when fetched using the loadCustomPropertiesAsync callback.

## Steps to Reproduce, or Live Example
1. Create a custom property using the following request to the REST API (v2.0) for  a mail item

> `PATCH https://outlook.office365.com/api/v2.0/me/messages('{mailItemId}')`

2. Fetch the custom property using the loadCustomPropertiesAsync [1] method for the same mail item. The custom property is not returned.
3. The same custom property is returned when it is queried using the REST API

> `GET https://outlook.office365.com/api/v2.0/me/messages('{mailItemId}')?$expand=SingleValueExtendedProperties($filter=PropertyId eq 'String {common-property-set-public-string-guid} Name cecp-{add-in-manifest-id}')`

Where common-property-set-public-string-guid=00020329-0000-0000-C000-000000000046 [3]

## Context
We are using both the Outlook REST API and OfficeJS API in order to handle mail switching scenarios for an add-in which supports a pinned taskpane.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop, Mac, Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Windows 10, Mac High Sierra
* Browser (if using Office Online): Firefox

## Useful logs
N/A

## References
[1] https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.4/office.context.mailbox.item?view=office-js#loadcustompropertiesasynccallback-usercontext 
[2] https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/extended-properties-rest-operations#extended-property-operations
[3] https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/commonly-used-property-sets

**Comment by exextoc** [comment]
Hi @splinter 
loadCustomPropertiesAsync: helps you access custom properties that were added by your specific add-in to the current item. Please refer to [this]( https://docs.microsoft.com/en-us/javascript/api/outlook/office.customproperties?view=office-js#saveasync-callback--asynccontext-).

The Graph API that is being used is setting the SingleValueExtendedProperties which is not a part of CustomProperties interface.

**Comment by exextoc** [comment]
Duplicate: https://o365exchange.visualstudio.com/O365%20Core/_queries/edit/1064572/?triage=true
________________________________

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding CustomProperties not being returned by REST API. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
Also, it would help us understand better if you can share your scenario, so that we can share any alternative approach

**Comment by exextoc** [comment]
@splinter - We tested this and could not reproduce the issue. We set custom properties like you suggested using REST. PATCH request to https://outlook.office.com/api/v2.0/me/messages/**itemId** with the following in the body:
 {
"SingleValueExtendedProperties": [
        {
            "PropertyId": "String {00020329-0000-0000-c000-000000000046} Name cecp-**addinId**",
            "Value": "{\"key1\":\"value1\",\"key2\":\"value2\"}"
        }
    ]
}

After this succeeds, we did a loadcustomprop from office.js and got the properties back. Try using the sample I pasted above and trying. If you call loadCustomProp from outlook desktop, try restarting the client and then doing a load prop. Sync time for outlook client (changes in exchange to be brought down to the client) are not guaranteed and could very well be over 5 mins. If calling loadCustom in OWA, refresh the page and then try calling load. This is exactly what we tried and could not reproduce the issue.

**Comment by splinter** [comment]
Based on your input I believe this is behaving as expected. 

How can we find out the synch time? Is there a setting that we can adjust to test this by reducing the synch time?

As a work around we are maintaining a cache  of REST calls made to update and read properties.

**Comment by Nagapito** [comment]
I also start having this issue yesterday. 
My addin was reading correctly custom properties added/changed by REST calls without issues (last 4-6 weeks) until yesterday.

Now, Outlook seems to be caching the custom property and can only read the new values if I restart Outlook. The moment the addin fetches the custom properties once, he will never be able to retrieve new values added/inserted via REST calls. 

If the addin changes the custom property, since it is done 'client side', these new values are saved on the Outlook cache and are retrieved if I try to load the custom properties.

Also, this is only happening on Office 365 desktop version for Windows (didnt tested on Mac yet). Web version works correctly.
I also have the idea of seeing my office giving some information of running some update, so maybe something changed in the Outlook client that is causing the issues?

**Comment by exextoc** [comment]
Sync time is just never guaranteed. It can change based on network, or how Outlook handles cached mode. Ideally all changes are only done on one side (either server or client) to avoid conflicts. Or some workaround has to be done to keep them in sync. Turning cached mode off to online mode in Outlook can eliminate these issues, but Cached mode is the default for most users.

**Comment by arturo3** [comment]
I've also experienced what @Nagapito has detailed. 

In my scenario, I'm using Office.js to set/retrieve custom properties. There is no problem saving but I do see the "caching" issue when retrieving properties in the Windows/Mac desktop client. I'm not able to retrieve new custom property values even after restarting either client.

**Comment by exextoc** [comment]
@Nagapito @arturo3 Is this issue reproducing when you turn cached mode off to online mode?

**Comment by Nagapito** [comment]
Yes, disabled cache mod still caused it.
I even tried to fully reinstall office, in the hopes it somehow would fix himself since I also started having other issues with outlook. (cant right click on the addin and see the context menu so I can attach a debugger and F12 tool stop detecting the add-in browser plugin...)
I had to setup another machine with a fresh installation of windows and office to be able to continue working.
Since then I never tested my machine again, so I do not know if the cache issue is still present. (the other issues are still there)

**Comment by arturo3** [comment]
@exextoc The issue is resolved when cached mode is turned off. At least for the Windows desktop client. After some research, I found out that Outlook for Mac always runs in cached mode. Are there any workarounds for the Mac client that you know of?

**Comment by exextoc** [comment]
@Nagapito could you share the scenario why you use REST instead of JS API? 
@arturo3 Turning off cached mode is only a workaround.

**Comment by Nagapito** [comment]
We am using both REST and JS API.  
Without entering into much details, we are syncing the Exchange calendars with our Room Reservation system. This is done trough the REST API.
Our room reservation system also allows extra services on the rooms. We created an addin for Outlook so the user could also boom these extra services. 
So, when the user chooses something in the addin, we store this information in the custom properties and this is synced to our system trough the REST API.
If the user books theses services in our system, we update these custom properties trough the REST API so the addin in outlook can retrieve them with the JS API and show the booked services. Is this part that is causing a lot of issues, since many times, the JS API retrieves outdated information.

**Comment by exextoc** [comment]
@Nagapito this is something that must be worked around. The data that is changed via REST does not sync down to clients immediately, (and will also not refresh until the item is refreshed). If that is data that is needed it should always be accessed and retrieved in the same way. (either REST or through OfficeJS). Additionally, you could store that data on your backend and access it that way too.

**Comment by Nagapito** [comment]
@exextoc Thanks for the feedback. From my latests researches, I was indeed expecting this behaviour. We will have to find another way to do this communication that does not involve the CustomProperties.
