### ISSUE TITLE
Office.AttachmentDetails.Id is not the exchange id and does not persist

### ISSUE THREAD

**Issue by matt24601** [OfficeDev/office-js#4528]
## Your Environment
* Platform: Mac
* Host: Outlook Client
* Office version number: 16.84.2
* Operating System: macOs Ventura - 13.2.1
 
## Expected behavior
When reading AttachmentDetails.Id from an attachment either in onAttachmentsChanged or onMessageSend, the id should be from the exchange and be unique and persistent, so that if you save the email as a draft and come back to it, the id does not change, as described in the docs: https://learn.microsoft.com/en-us/javascript/api/outlook/office.attachmentdetails?view=outlook-js-preview#outlook-office-attachmentdetails-id-member

This is true for Outlook Online and the Windows New Outlook Client, where the AttachmentDetails.Id will look like: `AAMkAGMyOGMxMjA0LTdjMTYtNGM0ZC1hZjFkLWJlMTFiYTkyMzdlOABGAAAAAAB+uRasGQVkTKXeV1MbnwoQBwA0gBaZa0vzTqN/+pbbr/2/AAAAAAEPAAA0gBaZa0vzTqN/+pbbr/2/AALwPr/KAAABEgAQAMbfPP5nWblOtK62XvfgXNM=`

## Current behavior
However in the New Outlook Client on Mac, AttachmentDetails.Id will look like:
`1AE06FF6-AC28-47BC-AFFF-6030987D9037`

And will change if the email is saved as a draft, and later sent.

**Comment by zhngx1** [comment]
@matt24601 The behavior is by design. The following is copied from the documentation:
`The attachment ID is valid only within the same session and isn't guaranteed to map to the same attachment across sessions. Examples of when a session is over include when the user closes the add-in, or if the user starts composing in an inline form and subsequently pops out the inline form to continue in a separate window.`

Link to documentation page: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/add-and-remove-attachments-to-an-item-in-a-compose-form

**Comment by matt24601** [comment]
@zhngx1 I believe that's a different attachment id, as the documentation is in reference to adding an attachment using the API, and the id is described as being an integer, rather than a uuid:
> The attachment ID is an integer which you can subsequently use to remove the attachment.

In the documentation I referenced, the attachment id is described as:
>  the Exchange attachment ID of the attachment
