### ISSUE TITLE
how to use the beta of office.js for npm

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#455]
hi

i want to use the beta of office.js by use npm

but the two npm command is 1.1 version of office.js 
npm install @microsoft/office-js --save
npm install @types/office-js --save-dev

**Comment by Zlatkovsky** [comment]
I think you should be able to use `npm install @microsoft/office-js@beta --save`.  Note the `@beta` suffixed to the end.
But @wandyezj might have a more definitive answer, and can also make sure that the beta was recently updated.

**Comment by dinglicoding** [comment]
thanks for your reply，i use  npm install @microsoft/office-js@beta --save . but it's also no shapes (shapes in beta api).
and no IntelliSense , i use angular for develop office add-ins ,it's any demo config for beta package.json?

**Comment by Zlatkovsky** [comment]
Hi @dinglicoding , could you try again?  We just published a new version of Beta that should contain the latest.

In terms of IntelliSense, please see the README instructions at https://github.com/officedev/office-js#intellisense-definitions.  You can either pull the IntelliSense from the `dist/office.d.ts`, or you can use the `@types/office-js-preview` package (npm install @types/office-js-preview --save-dev), though in case of the latter your local copy might diverge from what @types has.  In general, see the best practices for using the NPM package here:  https://github.com/officedev/office-js#best-practices

Closing the issue for now since it should be resolved; feel free to re-open if it's not working for you.
