### ISSUE TITLE
Powerpoint Add-in is not updating automatically without any notification

### ISSUE THREAD

**Issue by vanhock** [OfficeDev/office-js#4575]
## Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac, for some users on a PC desktop 
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: 16.86
* Operating System: Mac OS Sonoma 14.5 (23F79), Windows 11
* Browser (if using Office on the web): ______
 
## Expected behavior
After a new manifest.xml has arrived (Published via App Source), the Add-in should notify a user about an update or update automatically. 

## Current behavior
1. In Powerpoint on Mac OS nothing appears after a new Add-in with updated manifest.xml is arrived.
2. Some users got the notification I attached below, but others didn't. We check it after a few hours after publication in App Source.
<img width="1728" alt="Screenshot 2024-06-11 at 17 54 18" src="https://github.com/OfficeDev/office-js/assets/8645120/0bef6dbf-3bc5-4fb5-9086-37d53dfbb6db">

**Comment by EsterBergen** [comment]
@AkhileshShah-MS - Can you look into this? It looks like there is a bug between AppSource Updates and hosts.

**Comment by AkhileshShah-MS** [comment]
Hi @vanhock! Thanks for reaching out. A few quick questions for me to understand the issue better. 
- Was the app acquired by used from in-client store, or was it deployed to them admin admins? 
- Is the expectation that the update should be automatically available to the user or user should have a way to update to new version. And the issue is that both the options are not working correctly right? 
- Is the upgrade to new version not available only in Powerpoint mac, or it not available in Windows and Web version of PowerPoint too? 
Thanks!

**Comment by vanhock** [comment]
Hi @AkhileshShah-MS,
thank you for your reply.

- App used from the in-client store
- We have an issue where we don't get any update notifications on Mac OS. But for Windows, it works fine. 
We didn't test it for the Web.  

Update:
It has been working (we received an update notification on Mac OS) since the last update we performed a week ago.

Has something changed since I posted this issue?

**Comment by AkhileshShah-MS** [comment]
Thanks for the details @vanhock! 
@akshayta23 Can you please help with this issue related to user acquired PPT add-in no auto upgrading.

**Comment by akshayta23** [comment]
@vanhock Is this issue still repro for you? If yes, kindly re-open this item and we will investigate further. Tagging @LuyiH for awareness.
