### ISSUE TITLE
StreamingInvocation function will cause Volatile functions calculate

### ISSUE THREAD

**Issue by Edward-Zhou** [OfficeDev/office-js#4635]
If I use both custom Streaming function and Volatile functions, the Volatile functions will be calculate while Streaming function run.

Steps to reproduce:

- Open Script Lab and register custom functions below:
```
/**
 * Increments a value once a second.
 * @customfunction INC increment
 * @param {number} incrementBy Amount to increment
 * @param {CustomFunctions.StreamingInvocation<number>} invocation
 */
function increment(incrementBy, invocation) {
  let result = 0;
  const timer = setInterval(() => {
    result += incrementBy;
    invocation.setResult(result);
  }, 1000);

  invocation.onCanceled = () => {
    clearInterval(timer);
  };
}
```
- Entering `=SCRIPTLAB.STREAMINGFUNCTION.increment(1)` in A1 and `=NOW()` in B1
- Format B1 to show time value
- B1 will also update every second
![streaming](https://github.com/OfficeDev/office-js/assets/16079555/a106e0ed-90ca-43a8-9177-ee22de20a53c)

**Comment by adrianwu8516** [comment]
Hi @Edward-Zhou, 

Thank you for sharing this issue with us. It's a by-design behavior because the volatile function such as RAND or NOW is recalculated every time a cell is changed and every other time Excel recalculates. 

If you are expecting a different design, please submit a new Tech Community New Ideas item, this will give us visibility of the commonality and help us prioritize.  Thank you very much!!  [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)
