### ISSUE TITLE
Install manifest with setup.exe

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js#4636]
Do Outlook add-ins write any keys in the registry? If so, could you provide specific details on which keys are created and the exact registry paths where I can find them? Additionally, could you offer information on how these keys are used and if there are any best practices for managing them? Thank you in advance for your help.

**Comment by mattgeim** [comment]
@CodeCube0 is your question about how to persist settings?  or something else? 

Add-ins run in a webview / web browser and are sandboxed from accessing resources specific to a machine.  You may find some useful documentation here:  https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/privacy-and-security  and  https://learn.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings?view=common-js-preview#application-specific-settings-and-persistence

If that answers your question feel free to close this issue, otherwise please share additional details on the scenario you are looking to accomplish.

**Comment by CodeCube0** [comment]
I asked this question because I would like to try to create a setup.exe that allows you to install the add-in manifest directly into the client of the user running it, but I can't find anything on the internet or in the forums. I would like to know if there is some way to do it or if there is already some tool that allows you to do it. I know distribution is done through other processes but I would like to try a different approach if possible. @mattgeim

**Comment by mattgeim** [comment]
There are many options for installing add-in manifests - you can find the documentation on various options here:  https://learn.microsoft.com/en-us/office/dev/add-ins/publish/publish

you can also look at development options for testing add-ins:  https://learn.microsoft.com/en-us/office/dev/add-ins/testing/test-debug-office-add-ins#sideload-an-office-add-in-for-testing 

We don't support other approaches outside of our documentation - if you have a feature request please post it here: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform 

Please feel free to reopen if this didn't answer your question.

**Comment by CodeCube0** [comment]
I noticed that using the command "npx @microsoft/teamsapp-cli install --xml-path manifest.xml" it is possible to install the add-in manifest in sideload mode, there is the possibility of doing so without the form appearing entering user credentials? Maybe taking them from somewhere? @mattgeim
