### ISSUE TITLE
How to restrict worksheet deletion in excel using office js. 

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#4688]
My Environment
Platform : PC desktop
Host: Excel
Office version number:  Excel® for Microsoft 365 MSO (Version 2406 Build 16.0.17726.20078) 64-bit 
Operating System: Windows 11 Pro

Hi Team,
I want to restrict delete worksheet option from worksheet tab.
I couldn't find any thing about this so that I use one event which is available in office-js documentation.
**onDeleted** 
For that I use this code snippet.
    await Excel.run(async (context) => {
        const sheets = context.workbook.worksheets;
        sheetDelete = sheets.onDeleted.add(onSheetDeleted);
        await context.sync();
    });

but this event trigger after deletion of worksheet. Based on my  requirement I want to restrict this for some user.
So is there any way I can retrieve last deleted worksheet in this event Or Is there other event which is trigger before deletion of any worksheet so that I use that event so worksheet will not be delete.
Thanks.

**Comment by adrianwu8516** [comment]
Hi @Jayshiv1408Dev 

Thank you very much for your suggestion. We currently only support post-event, not pre-event. If you want to submit a feature request, please help create a post [here in our tech community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). It's a place where we collect feature requests and prioritize them based on their vote count. It would be very helpful if you could share your suggestion here so that more people can join the discussion and vote for it. 

Thank you very much!

**Comment by Jayshiv-IRIS** [comment]
@XuanZhouMSFT  Thanks, I understand this is not available , But there is other way I can undo that process so that I get that worksheet again. Base on my requirement I can decide I want to retrieve it or not (Just like undo Ctrl+Z event).
