### ISSUE TITLE
OfficeRuntime.auth.getAccessToken() throws an error on Firefox browser windows 64 bit

### ISSUE THREAD

**Issue by avisheknand** [OfficeDev/office-js#4695]
Making any call to getting the office access token on Firefox  browser (OfficeRuntime.auth.getAccessToken()) throws an unexpected error occurred in the client with code 13006 even when the requirement set is being supported

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number:
* Operating System: Windows 11
* Browser (if using Office on the web): FireFox 128.0 (64 bit) 
 
## Expected behavior
The call to OfficeRuntime.auth.getAccessToken() should return the access token

## Current behavior

The call to OfficeRuntime.auth.getAccessToken() throws the error
![image](https://github.com/user-attachments/assets/2d94ced4-184c-471c-a39b-18fe5198e9aa)

## Steps to reproduce

1.) Download Firefox and have the default settings setup
1.) Created a simple office app
2.) Make a call to get office access token (i.e. const accesstoken = await OfficeRuntime.auth.getAccessToken({ allowSignInPrompt: true, allowConsentPrompt: true});

How can we resolve this issue?

**Comment by neprasad-microsoft** [comment]
Hi @avisheknand, this is happening because of 3P cookie blocking on Safari. If you disable this from your Privacy settings it should work. The workaround for this is documented here - 
https://learn.microsoft.com/en-us/entra/identity-platform/reference-third-party-cookies-spas 

We would also suggest moving to NAA which is in Preview right now - 
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/enable-nested-app-authentication-in-your-add-in https://learn.microsoft.com/en-us/office/dev/add-ins/develop/enable-nested-app-authentication-in-your-add-in
