### ISSUE TITLE
Questions about add-in behavior of shared mailboxes

### ISSUE THREAD

**Issue by mailchecktool-admin** [OfficeDev/office-js#4706]
The Outlook add-in was not previously supported in shared mailboxes, but is now available through an update.
However, there appears to be some instability in its operation.

For example, if you add a shared mailbox to a folder on your personal Outlookontheweb screen,
the add-ins that the individual has installed will be applied, though,
If you click on the profile and open the shared mailbox in a new window from “Open Other Mailboxes”, the add-in will not appear.
We also confirmed that the add-in is not activated even when a shared mailbox is specified to the user of the relevant add-in in the integrated application from “Administration” in M365.

Does the add-in only apply on shared mailboxes if an individual has the add-in installed?
If I want to apply an add-in to a shared mailbox that belongs to multiple people in M365, is it not appropriate to select a user from the “Integrated Apps”?
If you have any detailed text documentation, please share.

The environment we are using is as follows
Version: 124.0.6367.208 (Official Build) (64 bit)

**Comment by neprasad-microsoft** [comment]
This is an unsupported scenario at this time. While shared mailboxes allow multiple users to access a common mailbox, our team does not provide official support for add-ins in shared mailboxes when opened in a new tab. As a temporary workaround, please re-deploy the add-in to the end user's mailbox and the shared mailbox, in case your add-in disappears from the Shared Mailbox.

**Comment by mailchecktool-admin** [comment]
https://github.com/OfficeDev/office-js/issues/3769#issuecomment-1774520501
From this reply, I was under the impression that the add-in supports opening a shared mailbox in a new window from “Open Other Mailbox”, but is it correct that the add-in does not work in this scenario?

**Comment by neprasad-microsoft** [comment]
We understand that the feature was available earlier, however due to technical challenges and an increased focus on security, we no longer support add-ins in shared mailbox on Outlook web. Please refer to the workarounds proposed above. We expect to have an ETA to address this issue in the coming months. Appreciate your patience on this!

**Comment by mailchecktool-admin** [comment]
Is it correct that “no longer supported” means that the add-in will no longer work (or be available) in shared mailboxes in the future?
Or does it mean that the current unstable state will continue?

If you know when support will end at this time, please let us know.

**Comment by neprasad-microsoft** [comment]
Add-ins will continue to work in shared mailboxes in Outlook web when opened in the same tab. However, for the scenario where users can “Open another mailbox” in a new tab, users may run into some of the issues outlined above. We are actively working on resolving this issue for the new tab scenario in the upcoming planning cycles. We appreciate your understanding and apologise for the inconvenience caused.

**Comment by mailchecktool-admin** [comment]
Am I correct in understanding that the resolution of this issue will take place within the next few months and no date has been set?
"We expect to have an ETA to address this issue in the coming months.” but where is this going to be shared?

**Comment by cody-lettau** [comment]
This is a pretty significant deprecation in functionality for shared mailboxes and add-ins. We have many customers who use shared mailboxes and open them in a new tab that expect our add-in to function as it has previously.

This needs to be prioritized. When can we expect this to be fixed and back in a working state? Having an update on ETA in months is not sufficient...

**Comment by akshayta23** [comment]
Please refer to our updated documentation that outlines how add-ins will work in shared mailboxes on Outlook web when opened in a new tab - https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?tabs=web%2Cjsonmanifest#supported-setups . 

We have also suggested a few workarounds to help reduce the impact to your organization and end users. At this time, due to our org's priorities, we cannot commit to a specific ETA. But rest assured that we are trying to address this issue soon, as we understand that this is a critical functionality for our users. Appreciate your understanding here.

**Comment by cody-lettau** [comment]
@akshayta23 if this is not being considered a bug and was planned removal of critical functionality (completely removing support for add-ins in shared mailboxes on one of your platforms), why was this not announced? This is a major pain point for our customers and not being able to communicate this is pretty poor customer service.

Communication of changes like this needs to improve going forward.

**Comment by jgibbs2680** [comment]
I was able to add the shared mailbox to Outlook mobile which allowed me to send an email.

**Comment by akshayta23** [comment]
This issue is only limited to opening shared mailboxes in a **new tab on Outlook web**. Add-ins will work in shared mailboxes on Outlook web when opened in the same panel and on other platforms too. For now, we are recommending users to add shared mailboxes in the same panel as the primary account on Outlook web. 

To clarify, this scenario was not officially tested by the team, however users were able to access their add-ins in shared mailboxes in a new tab on Outlook web. In light of that, we have updated our public docs to ensure that customers are aware that this is not a supported scenario at this time. This is not a deprecation, and we will be adding support for this in the coming months, as we understand that it's a critical scenario.

**Comment by mailchecktool-admin** [comment]
@akshayta23 
Thank you for sharing. 
Hoping for an improvement as soon as possible.

I saw the note on https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?tabs=web%2Cjsonmanifest#shared-mailboxes.
It says: “When opening a shared mailbox using the Open Another Mailbox option, it is recommended that you deploy the add-in to both the primary user mailbox and the shared mailbox.”
Is it necessary to deploy the add-in to both?
Am I correct in assuming that if I deploy the add-in to both, it will work fine?

**Comment by akshayta23** [comment]
@mailchecktool-admin Yes please deploy the add-in to the primary user and the shared mailbox. We are still recommending users to open the shared mailbox in the same tab as the primary user's account for add-ins to work as expected. We apologise for the inconvenience caused and we are actively working on addressing this issue in the coming months.

**Comment by mailchecktool-admin** [comment]
@akshayta23 @neprasad-microsoft 
As an additional question on shared mailboxes,
If two users access a shared mailbox with an add-in installed at the same time and launch the add-in at the same time, can there be a problem that causes the add-ins to work together?
If user A and user B access the add-in at the same time, when A closes that add-in, B will also close it in tandem. This is a problem that occurs.

**Comment by akshayta23** [comment]
We’re pleased to inform you that we’ve recently enhanced the behavior of Outlook add-ins in shared mailbox scenarios when accessed via a new tab in Outlook on the web. These improvements are designed to deliver a more reliable and seamless experience when working with shared mailboxes on a new tab in Outlook web. For more details. please refer to our updated documentation - https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?tabs=windows%2Cjsonmanifest#add-ins-in-shared-mailbox-scenarios
