### ISSUE TITLE
MS Excel Toolpak breaks javascript add-in custom functions

### ISSUE THREAD

**Issue by JEGUOCEAN** [OfficeDev/office-js#4811]
Hi,

We developed a Java scrip excel add-in that provides some functionalities with custom functions.
Our customesr are using these functions for a couple of years now and they began to face issues with interaction of MS toolpak add-in.
On computers where toolpack was not activated our formula, SAP.GetData for instance, was not working and user had this kind of formula instead:
'C:\Program Files\Microsoft Office\Root\Office16\LIBRARY\Analysis\FUNCRES.XLAM'!_xldudf_SAP_GETDATA
Loading toolpack add-in was a solution. We ask our end user either to activate toolpak on all or none of their computers. 
Many of them are used to work with toopak and kept it.

It was working perfectly like this one and half a year ago.

Starting Q3 2023 some customers contacted us with a new issue: even if the toolpak was activated formulas where incorrect (i.e., FUNCRES.XLAM'!_xldudf_SAP_GETDATA) when they open an existing workbook with a new instance of Excel.
A workaround was to open a blank workbook before and then open the existing workbook.

Since Office Version 2402 of the Semi-Annual Enterprise Channel this workaround does not work. They have the option between 2 workarounds:
-	Once the file is open, click on Home tab, Add-ins and re-select from their our add-in
-	Make a find and replace of the incorrect string FUNCRES.XLAM'!_xldudf_SAP_ to get SAP.

I made test on my computer, it seems that existing file can be “recovered” with this steps:
-	Go to option add-ins and unload toolpak => FUNCRES.XLAM'!_xldudf_SAPXXXX formulas are changed to 'C:\Program Files\Microsoft Office\Root\Office16\LIBRARY\Analysis\FUNCRES.XLAM'!_xldudf_SAP_XXXX
-	Search and replace 'C:\Program Files\Microsoft Office\Root\Office16\LIBRARY\Analysis\FUNCRES.XLAM'!_xldudf_SAP_ with SAP.
-	Save and close the file
After these steps I can reactivate/deactivate the toopak, formulas are still ok.
I do not know if this is working for customer that are sharing files across computers and Excel versions.

I cannot share any sample of files with the issue for reproduction steps as we have only customers files and cannot share them publicly.
Sample files I got have more than 17 000 formulas using javascript add-in custom functions. I’m not fully certain that this is a key factor, but it might.
All files were created before end of august 2023 but I do not know when the formulas were introduced.

We get in touch with MS Dev team directly for this issue, @adrianwu8516 asked us to trace the incident here in github.
A November fix that was deployed in semi annual release has been identified as the origin of current issue.

We expect you will be able to provide an Office fix for this shortly.

Best regards, Jérôme

**Comment by shanshanzheng-dev** [comment]
Hi @JEGUOCEAN Thanks for reaching us. We'll take a look and report back if we have a suggestion for you. Thanks for your patience.

**Comment by adrianwu8516** [comment]
Hi @JEGUOCEAN, This is a by-design behavior, and this issue actually stems from a fix that was released last November. The fix was intended to address the issue that a custom function would be erroneously persisted in the legacy add-in file (.xla, .xlam) and cause the source of truth to be parsed incorrectly. To work around this, there is a quick way to manually launch the required resource via Developer > Excel Add-ins > Select Add-ins to Launch. 

Please check the images below:
![image](https://github.com/user-attachments/assets/628aded3-03d1-441a-8815-2f2f220b8e2c)

**Comment by JEGUOCEAN** [comment]
![Capture d'écran 2024-08-28 104455](https://github.com/user-attachments/assets/bc4e8556-1aca-44ec-8805-306ea0e7bf29)
Hi,

I’ve tried your workaround, and this does not solve anything, finally formula remains incorrect even after save reopen : FUNCRES.XLAM!_xldudf_SAP_GETDATA
Additionally, it is hardly acceptable by end user to do such a manipulation, they mostly would not how to open developer tool and as it is not working….

Any transparent solution from MS is expected.

Regards

**Comment by XuanZhouMSFT** [comment]
Hi @JEGUOCEAN, thanks for reporting and test on your side.

For your steps to recover the files, yes, it should be the correct way to replace the text saved inside the cell. The first step to unload toolpak is not needed because it only changes the way it showing depends on if we can find the file or not. We'd suggest you to replace all the cells to recover the file. It's needed to be done once and it will never shows again later.

I can share more details here:
Before 2402 of the Semi-Annual, there is a issue you also mentions. It's caused by custom functions would be registered into the local .xla/.xlam as these file types are also considered as workbooks by mistake. So in some cases, if you re-open the workbook or sharing it to others, you will see "FUNCRES.XLAM'!_xldudf_". At that time, re-enable the toolpak should be a workaround because they could be find in the xlam file.

At 2402 of the Semi-Annual, we released a fix that it changed the way of custom function registration aiming to resolve the previous issue. And after the office version contain the fix, the new file you saved would never see the 'xlam!_xldudf' anymore. But if the old file opened, you need to replace the old cells with the right CF name.

We already released this fix this Jan from CC version. For more discussion, you can refer to: https://github.com/OfficeDev/office-js/issues/2051#issuecomment-2270464298

**Comment by JEGUOCEAN** [comment]
Hello,

Thank you, I will share with our customers this information.

I understand that current issue is from a change within Excel application.
Final solution is to correct manually or by any possible workaround incorrect formulas.
MS is not planning any other action.

The main expectation of our customer is that in future, this issue do not raise again.
I will re-route any of our incident to this git-hub entry so they can refer to this information and ask the correct publisher (MS) for assistance.

**Comment by XuanZhouMSFT** [comment]
@JEGUOCEAN  Thanks for the understanding. The aim of the change is to avoid any "_xldudf" issues in the future. Please feel free to let us know if you still encounter the issue, we will continue to fix it.

**Comment by evelyn-chrono** [comment]
@XuanZhouMSFT Our users are reporting extremely frequent `xldudf` errors, and I've seen it happen now with multiple different add-ins. Can you reopen this to investigate?

**Comment by XuanZhouMSFT** [comment]
Hi @evelyn-chrono, thanks for reporting it. Before I re-active this issue. Just want to double confirm with you about your issue with "_xdudf" because many scenarios will also result in the same error.

This GitHub issue is to help tracking the "_xldudf" started from Office Version 2402 of the Semi-Annual Enterprise Channel. And the root cause it is just as I said in this comment: https://github.com/OfficeDev/office-js/issues/4811#issuecomment-2316839735. If you are the same scenario, then please refer to my comments to help workaround.

If you share the different scenario and always hit the "_xldudf" error, could you help to open a new ticket and share with us your information like repro step, or any documents which could help us identify the reason. We can track it separately. Thanks in advance.
