### ISSUE TITLE
'Error Loading add-ins': Unexpected Resource Access to one of your manifest's resources is denied. Check the <Resources> listed in your XML manifest file.

### ISSUE THREAD

**Issue by me-DhanaHarsha** [OfficeDev/office-js#4816]
We have created a sample custom functions excel addin. When we run it in local, the addin is created successfully and it is working fine in task pane. We copied the compiled folder(dist) to our VM and tried to add it in Windows Excel desktop app, it encountered 'Error Loading add-ins' as shown in the screenshot. And the error is logged as 'Unexpected	Resource	Access to one of your manifest's resources is denied. Check the <Resources> listed in your XML manifest file.' Please help us how to fix this error.
![image](https://github.com/user-attachments/assets/51735188-6cfb-488d-8a25-dab515a1cae8)

**Comment by shanshanzheng-dev** [comment]
Hi @me-DhanaHarsha Thanks for reporting this issue. Could you share us your manifest? May I know what is your Excel desktop version? Thanks.

**Comment by me-DhanaHarsha** [comment]
[manifest.txt](https://github.com/user-attachments/files/16747411/manifest.txt)
Attached is our Manifest file, and we use Excel Office 16 Version.
When we deploy to IIS and try add-in, it is working. But when we try with Self hosting deployment, it is not working. Please let me know if you need any other details.

**Comment by shanshanzheng-dev** [comment]
Hi @me-DhanaHarsha Thanks. But the manifest seems not work. If possible, could you give us your test code repo? That will help us repro your issue.

**Comment by me-DhanaHarsha** [comment]
[TestRepos.zip](https://github.com/user-attachments/files/16762501/TestRepos.zip)
Hi @shanshanzheng-dev , please unzip this file and try to install node modules in this and test. Just to highlight, when we create a virtual directory in IIS and point to this, it is working as expected. But when we try to load it in Self hosting, it is not working. Please suggest us if any workaround or something.

**Comment by shanshanzheng-dev** [comment]
Thanks, we check the error message, seem it's not error for custom function. We're afraid it caused by VM network environment configuration~
We'd like to suggest you to try add-in through online environment. From there, you can see more specific error for which resource is not accessed. Or all the resource is not accessed.
There are some links you may check: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/testing-and-troubleshooting#when-installing-an-add-in-you-see-error-loading-add-ins-in-the-status-bar
https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging
