### ISSUE TITLE
Office JS addin Custom functions not working in compatibility mode

### ISSUE THREAD

**Issue by YogiGoodman** [OfficeDev/office-js#4895]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC, Web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Latest Office 365 stable build
* Operating System: Windows 11
* Browser (if using Office on the web): Edge and Chrome
 
## Expected behavior

We want to use XLL addin and it's custom functions when XLL addin is available and the same should switch to offices js addin custom functions when XLL addin is unavailable or workbook is open in Web or on Mac. 

## Current behavior
When we updated manifest xml with equivalent addin, the office js addin custom functions stopped working completely. 

Even if XLL addins file name is correct or incorrect, even if XLL addin is installed or not custom functions registered with office js addin are unavailable. 

## Steps to reproduce
We tried using this documentation on office js but it didn't help :
https://learn.microsoft.com/en-us/office/dev/add-ins/excel/make-custom-functions-compatible-with-xll-udf
1. Create office js addin with Yo generator with sample add custom function.
2. Create an XLL addin with same namespace and same custom function. The namespace, custom function name and its definition is exactly same in both the addins.
3. Update manifest xml to support compatibility using equivalent addin tag
4. Open an workbook with custom functions using office js. 
5. Try typing custom functions name using =AddinNameSpace.CustomFn(param1,param2)
6. Expected to above formula to work with office js addin, but Excel is not recognizing this formula. The custom fns are not registered, even though the XLL addin is unavailable.

## Context
We want to use XLL addin and it's custom functions when XLL addin is available and the same should switch to offices js addin custom functions when XLL addin is unavailable or workbook is open in Web or on Mac. 

Following this documentation :
https://learn.microsoft.com/en-us/office/dev/add-ins/excel/make-custom-functions-compatible-with-xll-udf

**Comment by shanshanzheng-dev** [comment]
Hi @YogiGoodman Thanks for reporting this issue, we'll take a look and report back if we have a suggestion for you.

**Comment by SiruiSun-MSFT** [comment]
Hi @YogiGoodman, do you mean the CF from JS side will be always disabled no matter whether you have a right XLL add-in?Even if the XLL file in the manifest XML is not correct or the XLL add-in is not installed at all?
Could you please provide the <EquivalentAddins> related manifest part and the XLL file to us? We will take a further investigation based on the resource. Thanks for your patience!

**Comment by YogiGoodman** [comment]
Hi, sorry for late reply.

Yes, that's correct. When we used the manifest equivalent addin tag with XLL file name, the custom functions stopped working from office js addin.

The relevant manifest part was exactly same as mentioned in the documentation 

<EquivalentAddins>
    <EquivalentAddin>
      <FileName>contosofunctions.xll</FileName>
      <Type>XLL</Type>
    </EquivalentAddin>
</EquivalentAddins>

Unfortunately, I won't be able to share the exact XLL here.

Is it possible for you to share a sample XLL and manifest part where CF compatibility feature is working as expected. It would be really helpful.

I have checked in Microsoft GitHub Repo, but couldn't find any demo example of compatibility mode. 

Thank you.

**Comment by SiruiSun-MSFT** [comment]
Hi @YogiGoodman, Thanks for your reporting! We could repro the issue you mentioned through your steps and expected to combine this issue with other Equivalent problems(such as #4014, #3037...) to do a deeply fix. Since this fix maybe complex which may take more time, please stay tuned! Thanks for your patience again! Will keep you posted here!

**Comment by SiruiSun-MSFT** [comment]
Re-open to track this issue. Thanks!

**Comment by SiruiSun-MSFT** [comment]
Hi @YogiGoodman, Based on our investigation, there seems have a by-design behavior which may need your attention. Since you have configured the Equivalent field, which means your JS Add-in will be treated as COM add-in in some scenario. To make COM and JS compatible, your CF in JS need to make some change.

With this setting in your manifest, your Custom Function in JS add-in may no longer need to add the namespace part in each function, since XLL Compatability mode doesn't use the namespace attribution. For example, your CF's namespace is “_Test_”, and the function in JS is "_=Test.addMore()_". After add the equivalent part in manifest, you need to change the function from "_=Test.addMore()_" to "_**=addMore()**_".

Please have a try to remove the namespace in each function and see whether all functions work well. Thanks again for your report!
