### ISSUE TITLE
Office.js not initialized inside dialog 

### ISSUE THREAD

**Issue by georgiik-welldone** [OfficeDev/office-js#491]
## Expected Behavior
Office.js is being initialized and API works inside dialog.

## Current Behavior
The library is never initialized.

## Steps to Reproduce, or Live Example
Open dialog (`window.Office.context.ui.displayDialogAsync`) and check whether `window.Office.initialize` has ever called.

## Your Environment
* Platform: Mac
* Host: PowerPoint
* Office version number: 16.24
* Operating System: 10.14.4 (18E226)

**Comment by danielgwilson** [comment]
Hi, thanks for your patience!

# Here's what I believe is happening:

1. Office JS appends `_host_info` to the Taskpane URL of an Add-in to help with cross-platform handling.
2. Certain partners are launching the Dialog API with the same URL as the Taskpane, but with a portion replaced (e.g. `const url = window.location.replace("Taskpane.html", "Dialog.html");`).
3. Because of this replacement approach, the `_host_info` query parameter isn't removed from the end of the URL.
4. Dialog doesn't use this `_host_info` parameter because it causes issues with some Auth servers. Instead, it makes a call to `GethostInfo()`—ONLY if it first doesn't see `_host_info` in the URL. This check is necessary for compatibility reasons.
5. Dialog fails to initialize correctly because either:
    a. The URL contains invalid characters (e.g. "|").
         i. This should just fail
    b. The Dialog sees `_host_info` which suggests a TaskPane context even though it's supposed to be a Dialog.
    i. This is what leads to a `Warning: Office.js is loaded outside of Office client` error; it's trying to load the full version of Office JS as if it were a TaskPane when it is not. It should instead be loading the Dialog version of Office JS which is limited to a few things like `messageParent()`.
    c. This query parameter addition can also cause problems with Webpack, as in GitHub issue 482 (https://github.com/OfficeDev/office-js/issues/482).

# The best way to resolve this

The best way to resolve this is to either

1. Store the full explicit URL for their Dialog or generate it from scratch rather than using the `replace()` shortcut
2. Continue to use `replace()`, but remember to remove the `_host_info` string from the URL passed to `displayDialogAsync()`.
