### ISSUE TITLE
Manifest ImageReference Id length is too restrictive (32 symbols?)

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#4910]
When I attempt to validate the manifest with reasonable icon names:

```
id: '432d95ab-aa94-4329-a37c-de84b2aeb401',
title: 'XML Schema Validation Error',
content: 'Error found during XML Schema validation.',
code: "The 'id' attribute is invalid - The value 'RemoveVelixoFormulasInCurrentFile.80x80' is invalid according to its datatype '[http://schemas.microsoft.com/office/officeappbasictypes/1.0:ImageReferenceId](http://schemas.microsoft.com/office/officeappbasictypes/1.0:ImageReferenceId)' - The actual length is greater than the MaxLength value.",
```

As you can see, our icon name is reasonable. We have many icons. 

From my perspective it doesn't make sense to have IDs so short, could it be at least 64 symbols?

We're using `office-addin-manifest` and `.validateManifest` function to validate the add-in manifest upon build.

**Comment by Rick-Kirkham** [comment]
@wh1t3cAt1k The error message is correct. If you would like to see the length limitation changed, please suggest this at [Microsoft 365 Developer Platform Ideas](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). Be sure to tag the suggestion with `office-js-dev` and `office-addins-dev`. 

In the meantime, I think your best strategy is to assign alphanumerical codes as the ImageReference IDs and keep a listing on your development computer that maps the codes to longer, more descriptive names. 

I will close this issue now, since it is not actionable at this time.

**Comment by wh1t3cAt1k** [comment]
Thank you. It has been filed as an idea, I hope someone reviews this on a regular basis...

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/increase-id-attribute-length-to-64-symbols-in-the-add-in/idi-p/4252675
