### ISSUE TITLE
Unable to SSO log into addin using personal devices when Microsoft MCAS policies are in place

### ISSUE THREAD

**Issue by mikey8808** [OfficeDev/office-js#4925]
## Summary
Users are unable to SSO log into addin using personal devices when Microsoft MCAS policies are in place

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: OWA (Chrome, Edge, FireFox)
* Host [Excel, Word, PowerPoint, etc.]: OWA
* Operating System: Windows and Mac
* Browser (if using Office on the web): (Chrome, Edge, FireFox)
 
## Expected behavior
Users can log into addin using personal devices when Microsoft MCAS policies are in place

## Current behavior
Users can't log into the addin with SSO. Fails due to the SSO redirect not having the .mcas.ms

## Steps to reproduce
1. In Microsoft Conditional Access Policies, configure a "Conditional Access app control" policy to prevent users from downloading and copying data onto their personal devices. i.e. it allows them to work only in the browser without removing data. More info on this here: https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-session
2. Once in place, use a personal device and sign into Outlook (OWA) in your browser
3. Try to send an email with the add-in enabled
4. Addin will try to sign you in using SSO but will result in a blank screen that will never load
5. This means you cannot ever sign into the addin when using Microsoft Conditional Access Policies that block downloading or copying/pasting data.

<img width="854" alt="image" src="https://github.com/user-attachments/assets/761581dd-4a05-4040-8db1-6a624dd5a336">

User can Initialise SSO login by signing in via the taskpane or by sending an email that would prompt the user to sign in.

# Provide additional details
1. https://techcommunity.microsoft.com/t5/microsoft-defender-for-cloud/mcas-with-outlook-web-app-add-ins/m-p/1503215

## Context
Microsoft has released additional Conditional Access Policies for personal devices, allowing organisations to prevent copying/pasting of Outlook emails when using personal devices.

Two controls cause an issue , one to block copy and paste and the other to block downloads. 

If either of these policies are in place and active, a user cannot sign into the add-in as the login redirect to the Single-Sign-On service never completes successfully, resulting in a blank page and no way to sign in.

**Comment by carlosb1504** [comment]
Hi, any update on this one please?

**Comment by shighosh-msft** [comment]
Hi @carlosb1504 apologies for the delay in response on this. Can you please check if <AppDomains> in your XML manifest and if adding the .mcas.ms suffixed URL helps resolve the issue?

**Comment by carlosb1504** [comment]
The suggestion from @shighosh-msft didn't work for us unfortunately.

**Comment by carlosb1504** [comment]
Through further internal testing, it has been determined that if organisations are using OpenID as the authentication method, this issue doesn’t present itself. Currently, the customer is using WSFED as its authentication method. In discussions with the team who manage the authentication piece, it has been explained that WS-FED/SAML do HTTP POST cross-site with the signed assertions, which also expects Javascript to work. OpenID passes a "code" in the URL, which is used by the backend to retrieve the assertions from IdP directly.

Moreover, OpenID works because the taskpane has an origin of [foo.com.mcas.ms](http://foo.com.mcas.ms/) and after OpenID finishes the authentication process the final URL in the prompt is also [foo.com.mcas.ms](http://foo.com.mcas.ms/) resulting in no issues with CORS (Cross-Origin Resource Sharing). Due to the current setup with WSFED, the final URL in the prompt is [foo.com](http://foo.com/) which means our current method of communication fails to pass the authentication token to the taskpane due to issues with CORS.

**Comment by JuaneloJuanelo** [comment]
reopening as this is not resolved

**Comment by DivyaPatidar** [comment]
@carlosb1504 Does this issue happens on Outlook desktop app as well?
Can you share network log as mentioned [here](https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues#outlook-web)

**Comment by JuaneloJuanelo** [comment]
re-opening issue
