### ISSUE TITLE
 Issue with Retrieving Updated Base64 After Using insertFileFromBase64 in Word Add-In

### ISSUE THREAD

**Issue by Piyush-IT** [OfficeDev/office-js#4928]
We are developing a Word add-in, and one of the key features is the ability to:
-Retrieve the Word document as a Base64 string (including OOXML content such as custom XML parts) and replace the document content using the method below:

// Insert the modified Base64 OOXML back into the document
[Retrving base64 code.txt](https://github.com/user-attachments/files/17145206/Retrving.base64.code.txt)
However, when we replace the content and save the document, retrieving the Base64 content again does not provide the updated or valid Base64 string.
 await context.document.insertFileFromBase64(base64Content, "Replace", {
     importTheme: true,
     importStyles: true,
     importParagraphSpacing: true,
     importPageColor: true,
     importChangeTrackingMode: true,
     importCustomProperties: true,
     importCustomXmlParts: true
 });

Here are my questions:

1. Are there any limitations with the insertFileFromBase64 method when inserting content? If so, is there any documentation or reference for this?
2. After replacing the content using the above method and saving the document, why does the Base64 retrieved afterward not reflect the updated content?
          This issue is a blocker for us, and I would appreciate your suggestions on how to resolve it.

**Comment by Piyush-IT** [comment]
is there any update because it is blocker for us.

Thanks in Advance.

**Comment by qinliuMSFT** [comment]
Hi @Piyush-IT , sorry for the late reply. To answer your questions,

- **Q:** Are there any limitations with the insertFileFromBase64 method when inserting content? If so, is there any documentation or reference for this?
**A:** Please refer to this [doc](https://learn.microsoft.com/en-us/javascript/api/word/word.document?view=word-js-preview#word-word-document-insertfilefrombase64-member(1)), the limitation is "_Insertion isn't supported if the document being inserted contains an ActiveX control (likely in a form field). Consider replacing such a form field with a content control or other option appropriate for your scenario._“

- **Q:** After replacing the content using the above method and saving the document, why does the Base64 retrieved afterward not reflect the updated content?
**A:**   The provided script retrieves the document content as a Base64 string and then re-inserts the same content back into the document without making any modifications. It's expected behavior the updated content should be same as the original content. Please correct me if I understood the question wrong.

Thank you for your patience.

**Comment by Piyush-IT** [comment]
Thank you for providing the answer .
