### ISSUE TITLE
Formatting lost while loading worksheet using base64.

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#4940]
My Environment
Platform : PC desktop
Host: Power Point
Office version number: Microsoft® PowerPoint® for Microsoft 365 MSO (Version 2404 Build 16.0.17531.20140) 64-bit
Operating System: Windows 11 pro
 
Hi team,
While loading excel using base64 using insertWorksheetsFromBase64 formatting is not retaining .
I'm attaching code snippets ,Expected output and Error output image.
Here is script Lab code 
[InsertWorksheet.txt](https://github.com/user-attachments/files/17256197/InsertWorksheet.txt)

My Excel File
[Testing.xlsx](https://github.com/user-attachments/files/17256207/Testing.xlsx)

Error output
![image](https://github.com/user-attachments/assets/4237344e-0d7d-4af3-8a21-44d5fd677eeb)

Expected Output
![image](https://github.com/user-attachments/assets/4f9d0482-6645-4a33-b882-31e5585ab2c4)

**Comment by EsterBergen** [comment]
@Jayshiv1408Dev -- Are you loading the table in PowerPoint or Excel? Looks like excel to me from the screen shot. Please confirm.

**Comment by Jayshiv-IRIS** [comment]
@EsterBergen  Yes in excel.I'm loading attached workbook in Excel .

**Comment by qinliuMSFT** [comment]
Hi @Jayshiv1408Dev , I tried your code snippet but could not reproduce. Here are the steps I took to try to reproduce, could you correct me if I am doing it wrong?

1. Download the Testing.xlsx you attached.
2. Copy your code snippet into Script Lab and run.

The result:
Three sheets identical to the existing sheets were created. After comparing them one by one, they are the same.
![image](https://github.com/user-attachments/assets/1900a96d-39d7-457c-b724-537c25857bdf)
![image](https://github.com/user-attachments/assets/cda83bfc-634f-424b-99e3-53c91236a7db)
![image](https://github.com/user-attachments/assets/e075dd1d-f414-4b82-835c-bc3bdd8d1bba)

We would be very grateful if you could try the above steps again, or point out where there is a discrepancy with your steps, so that we can have a solid repro step to help us with our investigation. Thank you for your assistance.

**Comment by Jayshiv-IRIS** [comment]
@qinliuMSFT Thanks for your response. But I'm still facing same issue is there anything related Excel version.

Here is my cdn file 
https://appsforoffice.microsoft.com/lib/1/hosted/office.js

Excel version Screenshot
![image](https://github.com/user-attachments/assets/0aa3c516-dfd1-4491-87f9-6f4e92059047)


Here is my demoVideo.
https://github.com/user-attachments/assets/6d3f63f9-f08d-4b23-9a81-c06b492ce07d

**Comment by qinliuMSFT** [comment]
Thanks @Jayshiv1408Dev for your additional information. I can now reproduce this issue when running script on a new created file. It has been put on our backlog #9418386,  the team will investigate and we will reply to you as soon as there is progress.

**Comment by XuanZhouMSFT** [comment]
Hi @Jayshiv1408Dev, thanks for the waiting. After investigation of the workbook and base64 string you provided. I assume it should be run into some specific scenario which I'm not sure how to generate a same workbook like you. But if you're working with the UI behavior like below to copy the worksheet to another workbook, it share the same behavior. But if you only copy the worksheet to the original workbook, it works well. So I assume there may have some workbook level setting there:
<img width="238" alt="image" src="https://github.com/user-attachments/assets/b03faac0-1ab8-4a8d-b74d-f3c817f4ed25">
<img width="316" alt="image" src="https://github.com/user-attachments/assets/2dac7201-0f5a-4a77-b7a1-6ef2e51bc2f4">

As our API will act as the same behavior with UI, we don't plan to change the behavior here. I would like to suggest you firstly manually changes the format for the workbook, then do the action, it will follow the new format setting you set. For example in below image, I only change the color, the copied result will use the new color. Hope it works for you.
<img width="890" alt="image" src="https://github.com/user-attachments/assets/0468d015-a6c0-40e3-ab08-595fc4b47003">
<img width="893" alt="image" src="https://github.com/user-attachments/assets/de0d7fb7-1632-434e-9e65-9137e13d72e2">
