### ISSUE TITLE
[NAA] Does NAA support office perpetual volume?

### ISSUE THREAD

**Issue by arifzaki95** [OfficeDev/office-js#4963]
Based on below documents, seems that NAA only support M365 office app
![image](https://github.com/user-attachments/assets/8bbaaaeb-7e67-423e-a2fc-5506e993cbe9)
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/enable-nested-app-authentication-in-your-add-in#naa-supported-accounts-and-hosts

Does NAA will be plan to support office perpetual volume as well?

**Comment by mattgeim** [comment]
It is not supported for Office Perpetual at this time and there is no plan to support Office 2016, 2019, or 2021 due to other required components being unavailable. You can find support for it via the updated requirement set:  https://learn.microsoft.com/en-us/javascript/api/requirement-sets/common/nested-app-auth-requirement-sets?view=common-js-preview

Please feel free to reopen if this doesn't answer your question.
