### ISSUE TITLE
Entra App Registration specifies signInAudience as AzureAdMultipleOrgs but App Source displays usage with Outlook accounts is possible leading to customer confusion

### ISSUE THREAD

**Issue by aduggleby** [OfficeDev/office-js#4964]
## Your Environment
* Platform: Platform independant
* Host: Outlook
* Office version number: 2409 (BUild 18025.20140)
* Operating System: Windows
 
## Expected behavior
If the add-in does not support Microsoft accounts then AppSource should not display that it can be acquired with Microsoft accounts.

## Current behavior
Our add-in for Outlook has a the signInAudience set to AzureADMultipleOrgs as you can see below:
![image](https://github.com/user-attachments/assets/03351483-4df8-4dbe-80ff-a5c1e83b884a)

But the AppSource listing still indicates it can be acquired using a Microsoft account, leading to customer confusion and bad reviews explicitly mentioning this issue:
<img width="750" alt="image" src="https://github.com/user-attachments/assets/592d0e01-7a58-41fb-a9e3-bf68ba3616b0">

## Steps to reproduce
1. Visit AppSource: https://appsource.microsoft.com/en-us/product/office/WA200005174?tab=DetailsAndSupport
2. Check the manifest of the associated client id in Entra

## Context
This was a Microsoft Support ticket (TrackingID#2409100040004913), but they request it be added here as they could not help

**Comment by DivyaPatidar** [comment]
The corresponding team has investigated the code, and by design, all such products are set to Microsoft Accounts, which the ISV currently cannot change. We understand that this Outlook add-in doesn’t support this type of account, leading to negative reviews for the product. Therefore, the ISV should be able to request the removal of these reviews, as there is good justification in this case. We also suggest the ISV adding a note in the product description indicating that it requires an organizational account.
