### ISSUE TITLE
Unable to remove the side loaded addin

### ISSUE THREAD

**Issue by mkondadg** [OfficeDev/office-js#4985]
# Provide required information needed to triage your issue
Unable to remove side loaded addin manually

## Your Environment
Windows desktop
Outlook
You have Microsoft Outlook Version 1.2023.1018.300 (Production).
Client Version is 20231027003.07 .
Windows 10 Enterprise 21H2 19044.2006
 
## Expected behavior
Able to remove side loaded addin instantly.

## Current behavior
It gives error and after few hours random retries, gives ability to remove addin.

## Steps to reproduce
Not consistently reproducible.

## Context
Cant do development quickly when in research mode of deploying / undeploying addin

**Comment by mkondadg** [comment]
![image](https://github.com/user-attachments/assets/c954ed01-b5f9-4eec-a26c-d17cb320b138)

Attached image for reference when this error happens.

**Comment by neprasad-microsoft** [comment]
Hi @mkondadg 
Does this happen on all platforms - Outlook on the Web/New Outlook on Windows/Mac.
Could you please share the har files with us for the scenario this happens? Start collecting the HAR before Outlook launch -https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues .
Also, could you send your manifest so that we can try the repro on our side.

**Comment by mkondadg** [comment]
We were able to reproduce this using both manifests from zip file
[manifest-localhost-mac-win.zip](https://github.com/user-attachments/files/17465914/manifest-localhost-mac-win.zip)

But manifest.xml is used for this scenario now when its reproducible (modified actual url in manifest)

Added console log + har file in zip
[console log-unable to remove addin.zip](https://github.com/user-attachments/files/17465902/console.log-unable.to.remove.addin.zip)

**Comment by mmanjaree-msft** [comment]
Closing this one as its  not an office js issue, please create post for relevant team
