### ISSUE TITLE
Excel js add-inmessage toast 

### ISSUE THREAD

**Issue by Nikodem98** [OfficeDev/office-js#4994]
Hello,
Is there any way to display a small toast in top right corner of the excel (want to display this toast without using the task pane). I know I can use dialogs for this but it's very annoying to users to close it every time they open a document and it prompts them with "you have to login before using the add-in"

**Comment by qinliuMSFT** [comment]
Thank you for reporting this issue. It has been put on our backlog #9471081 , the team will investigate and we will reply to you as soon as there is any progress. Thank you for your patience.

**Comment by adrianwu8516** [comment]
Hi @Nikodem98, Excel currently uses dialogs as the main interaction UI when the add-in wants to notify users. At some point, there's another item on our backlog to provide APIs to control the status bar like below (content/color can be customized), but there's no ETA for that. 
![image](https://github.com/user-attachments/assets/aa04edf2-fe5a-4df5-811b-12fa0c178ad1)
That said, we will continue to encourage developers to build such a toast within your task pane using JS, so that you can have a customized interface and logic. 

Please let us know if you have any other questions or concerns, thank you!
