### ISSUE TITLE
Long Delay Before Add-In Executes.

### ISSUE THREAD

**Issue by mailchecktool-admin** [OfficeDev/office-js#5064]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web, PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: -
* Operating System: Windows10
* Browser (if using Office on the web): Microsoft Edge, Google Chrome,
 
##Expected Behavior
After clicking the send button in Outlook, the add-in should execute immediately, typically within 1-2 seconds.

##Current Behavior
There is a significant delay before the add-in executes after clicking the send button in Outlook. When the issue occurs, it takes about 15-20 seconds for the add-in to execute and display the dialog.

##Steps to Reproduce
1. Download the sample add-in and save it in any directory.
2. Open Command Prompt and navigate to the directory.
3. Run npm install.
4. Run npm run dev-server.
5. Upload the manifest.xml to Outlook on the web and install the add-in (the XML file is stored in the sample.zip).
6. Create a new email, specify a recipient, and click the "Send" button.
7. The issue occurs during step 6 (sometimes it happens, sometimes it doesn't).
8. The network log during the issue shows delays with requests for outlook-web-16.01.js and office_strings.js.
![screenshot1](https://github.com/user-attachments/assets/419e1019-ab74-4acf-aca9-abc9e0a022da)

## Link to live example(s)
I am storing the sample add-in.

sample add-in program
https://github.com/mailchecktool-admin/Office-addin-sample/tree/main

**Comment by mailchecktool-admin** [comment]
@exextoc 
After conducting repeated investigations to reproduce the issue, we have made some progress and would like to update you. We confirmed that following the steps below results in a high probability of this issue occurring. (Please ensure the sample add-in is installed beforehand.)

**Steps to Reproduce:**

1. Launch a web browser in guest mode.
2. Access Outlook on the web.
3. Click on the "Compose Email" button.
4. Open the browser’s Developer Tools.
5. In the "Network" tab, enable "Disable Cache."
6. Specify a recipient and compose a test email.
7. Send the email.
   *Note: While the issue doesn’t occur 100% of the time, it does have a high likelihood of manifesting.*

**Comment by mobisw-msft** [comment]
Hey @mailchecktool-admin ,

Unfortunately I cannot reproduce the issue in the add-in you have provided. #4799 is a similar issue that we have tracked in our backlog, however it seems that issue is with the handler taking a lot of time, and in your scenario, you seem to report that the add-in takes a long time to start execution- unfortunately that scenario is not reproducible for us.

It would be great if you could provide us with additional logs that can help us debug this issue for you. Please follow this guide to collect logs for Outlook: https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues

**Comment by mailchecktool-admin** [comment]
@mobisw-msft 
Thank you for your reply. I appreciate your explanation regarding the possibility that the handler process might be taking time.

The issue has occurred again today. I have collected the HAR and log files and will provide them to you. Please investigate the cause based on these files.

・HAR
https://drive.google.com/file/d/1d_2hi7tGASpSLLrhIE6Z9EY7lnlhqfa6/view?usp=drive_link

・ConsoleLog
https://drive.google.com/file/d/1LdbVFKU2beJaQsfC9LeXAA9jfvlRDUDQ/view?usp=drive_link

**Comment by mobisw-msft** [comment]
Hey @mailchecktool-admin ,

Please do not share HAR files over public posts since they may contain sensitive information. Please add these to a private repository and give access to @exextoc  for the same. You may revoke access once your issue is answered.

Your comment has been deleted for privacy reasons.

**Comment by mailchecktool-admin** [comment]
@exextoc @mobisw-msft 
I apologize for uploading the files here. I have uploaded the data again to the GitHub remote repository. Please check it at your earliest convenience.
https://github.com/mailchecktool-admin/Office-addin-sample/tree/main

**Comment by mailchecktool-admin** [comment]
@mobisw-msft @exextoc 
I shared the logs with you the other day. Have you identified the cause of the issue?  
Could you update me on the status of your investigation?

**Comment by arpitsangwanmsft** [comment]
Hey @mailchecktool-admin !
We could see the delay in loading of office scripts in the uploaded network logs, but we could not repro the scenario using the provided addin. 
Also is there any specific user flow/ scenario where you can repro this delay because we could not repro anything close to the 10s delay pointed out even after multiple attempts.   
Can you please make required changes to the addin pointed out in #5026 and reconfirm if it's still a repro for you?

**Comment by mailchecktool-admin** [comment]
@arpitsangwanmsft 
We are still able to reproduce this issue in our environment. As mentioned previously, it occurs with a high probability when switching to a configuration that does not retain cache.

Additionally, we have confirmed that the same problem occurs with the sample add-in posted by @ nivgoldstein in this ticket:
https://github.com/OfficeDev/office-js/issues/4799

We considered the possibility that the network environment might be causing communication disruptions and made changes to the firewall’s whitelist settings, but the situation has not improved.

What potential factors could be causing the communication delays in this scenario?

We understand that you are unable to reproduce the issue in your environment. If there is any specific information required for further investigation, we will do our best to gather and provide it.

**Comment by mailchecktool-admin** [comment]
@arpitsangwanmsft 
Have you had a chance to read the post I shared a few days ago? I’d like to ask about the current status of your review on the matter. 

While the exact cause is unclear, the issue suddenly began occurring in early November. As mentioned before, the fact that it can also be reproduced with sample add-ins created by other developers suggests that some internal updates on microsoft365 end may be at least partially involved. 

We are receiving numerous complaints from users, so I kindly ask for your cooperation in investigating this matter.

**Comment by arpitsangwanmsft** [comment]
Hey @mailchecktool-admin!
"Stalled time" contributes to most of the time taken to fetch the delayed addin related files (office.js/outlook-web.js). In the attached logs out of 9.8s that it takes to load office.js, 9.77s are taken by browser to send the request.
Some environment or configuration problem might be contributing to the delays, might be caused by:

- A proxy server or VPN in the setup might be introducing delays. 
- Internal DNS resolver not being correctly configured.
- Firewalls adding delays in processing requests.
- Browser specific TCP socket limit for simultaneous connections.
- Some browser extension -ad blockers/privacy tools

Would be good to check this once because we are not observing any general issue pointing to delayed launch of addins.

**Comment by mailchecktool-admin** [comment]
@arpitsangwanmsft 
Could you please provide clarification on the following two points?

A proxy server or VPN in the setup might be introducing delays.
By "setup," are you referring to the entire network environment we’ve built on our end?
We don’t use a proxy server in our setup. If there’s a potential cause, it would likely be the VPN.
If that’s the case, what specific tests can we perform to identify the root cause?

Internal DNS resolver not being correctly configured.
Does this mean that the DNS resolver is not converting domain names to IP addresses efficiently, and that we should review its configuration to improve processing speed?
If this interpretation is correct, could you explain which specific configuration settings are typically associated with processing delays?

**Comment by mailchecktool-admin** [comment]
Could you confirm if these are the correct domains for retrieving "office.js" and "outlook-web.js"?
https://appsforoffice.microsoft.com

**Comment by rajjha-msft** [comment]
By "setup," we are referring to the entire network environment on your end.

This is beyond the scope of what we support, but in order to analyse the network, below are some things that you can try
- Check the VPN connection speed and latency.
- Test file transfer speeds with and without the VPN.
- Analyze network traffic to identify any bottlenecks.

The domain that you've mentioned is correct (https://appsforoffice.microsoft.com/l).

**Comment by mailchecktool-admin** [comment]
@rajjha-msft 
This issue has not been resolved yet. Please do not close it as I may seek assistance in the future.

**Comment by exextoc** [comment]
@mailchecktool-admin The Microsoft-github-policy-service bot adds the relevant tags when there is no ongoing conversation in the thread. Feel free to reopen the thread if you have any further questions in the future.

**Comment by Swathy-Mothilal** [comment]
@mailchecktool-admin The Microsoft-github-policy-service bot adds the relevant tags when there is no ongoing conversation in the thread. Feel free to reopen the thread if you have any further questions in the future.
