### ISSUE TITLE
[excel] how to add  point title for XYScatter chart 

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#508]
hi

 1、it's can set title of point tip?

![image](https://user-images.githubusercontent.com/3963826/57437095-aa91d400-7273-11e9-8fbb-d01c7ecfbec2.png)

series acos it's same when i move to other point. can change the tip title of different point?

**Comment by catchingyu** [comment]
Is it possible for you to provide us more information on this issue? Thanks a lot for the support.

Description :

Expected Behavior

Current Behavior

Steps to Reproduce, or Live Example

Context

Your Environment
Platform [PC desktop, Mac, iOS, Office Online]:
Host [Excel, Word, PowerPoint, etc.]:
Office version number:
Operating System:
Browser (if using Office Online):

**Comment by catchingyu** [comment]
will reopen it when customer provide more info.
