### ISSUE TITLE
Line spacing issue when using body.getHtml function 

### ISSUE THREAD

**Issue by tahseenmohd** [OfficeDev/office-js#5084]
Hi, When we are using body.getHtml() function of the JavaScript it is giving the line spacing and formatting getting changed. 
Everytime we are editing the content of document, extra line spacing getting added. Attached is the code snippet 
![Code_Si](https://github.com/user-attachments/assets/27946b3c-90d3-4956-bf79-eee2356fc745)

Quick response highly appreciated. 
![Original Content](https://github.com/user-attachments/assets/ae487871-456b-4a42-9936-003fb60c8b62)
![Same content after inserting for 2nd time](https://github.com/user-attachments/assets/f3561a7b-fddf-41ed-85d4-aefb45857ce3)
![Same content after inserting for 5th time](https://github.com/user-attachments/assets/8d5ed749-b488-44f7-bda6-0e1bb48cba72)

**Comment by RuizhiSunMS** [comment]
Hi @tahseenmohd, thx for reporting here. May I double confirm that, when you call getHtml(), the spacing and format would get changed together even you do nothing else?

**Comment by Jupiter644** [comment]
Hi
I am also facing this line spacing issue in WOPI word. Is there a fix to it??

**Comment by tahseenmohd** [comment]
Yes. We are fetching the html content using body.getHtml() and then encode by using EncodeURIComponent and saving it to .txt file 
please see the attached screenshot. Thanks.
![R4](https://github.com/user-attachments/assets/7bfe27de-24b7-4eea-8d9b-f22e926e21e4)

**Comment by Jupiter644** [comment]
Hi
I am also facing this line spacing issue in WOPI word. Is there a fix to it??

**Comment by RuizhiSunMS** [comment]
Hi @tahseenmohd and @Jupiter644 , would you please share your repro files (docs and code snippets) here? I did a quick try but found nothing unexpected.

**Comment by tahseenmohd** [comment]
Attched are the document and code files. 
[GS Seg.docx](https://github.com/user-attachments/files/17801103/GS.Seg.docx)
[taskpane.txt](https://github.com/user-attachments/files/17801402/taskpane.txt)
Please let us know if you have any questions.

**Comment by RuizhiSunMS** [comment]
Hi @tahseenmohd, thx for what you shared. But I'm afraid that you still have something else to share. 
Some definitions and declarations are hidden in or behind the code so that I can't run it. For example,:
1. I can only figure out that I need to execute `submitForm` but which step(s) should I execute before it?
2. got some errors saying `object is possibly to be null`, is here missing anything?
3. suppose you are using Angular?

No doubt I can go on my investigation without these, but I think these things could be very helpful for our investigations.
The only thing I can say is, after these days' try, only calling `getHtml` won't trigger such unexpected change. There should be some other step(s) taking effect as well.

**Comment by tahseenmohd** [comment]
Plase see the attached files.
[taskpane.txt](https://github.com/user-attachments/files/17828954/taskpane.txt)
[Encoded HTML.txt](https://github.com/user-attachments/files/17828956/Encoded.HTML.txt)

**Comment by RuizhiSunMS** [comment]
Hi @tahseenmohd, thx for what you shared.
Would you please confirm what I tried is similar to what you did?

1. change `insertHtml` by assigning `encodedHtmlContent` with the string in EncodedHtml.txt.
2. use changed function `insertHtml` to insert some contents.
3. execute `submitForm`. (after executing the function, the line space would get changed at your env).

If similar, then I have some questions:
1. I can't get `auth`, `Organizationid` and `UserId` since failed to call secureLS. 
2. no matter not to execute await response nor await response but not add header, the line space didn't get changed. Everything looks the same.
Suppose we need a stable and clear repro example. Or would you please confirm that how would it be if you:
1. don't call `await fetch` 
2. don't call `getHtml` but assign the value to it directly?


Or @Jupiter644 , would you like to share yours repro steps and files?

**Comment by Jupiter644** [comment]
Hey @RuizhiSunMS mine code is very similar to the one shared by @tahseenmohd .

**Comment by tahseenmohd** [comment]
Hi @RuizhiSunMS : When editing and saving the segments multiple times, the line spacing getting added.

don't call getHtml but assign the value to it directly?
Could you please explain this more in detail. How the value be assigned.?

**Comment by RuizhiSunMS** [comment]
Hi @tahseenmohd and @Jupiter644 ,
>> When editing and saving the segments multiple times, the line spacing getting added.
I'm more confused by this.. Which operation could trigger this from your side, calling gethtml, editing, saving or all of them?
Maybe we can make it more explicit, would you please share a series of steps indicating what you do to repro this. For example:
1. add content by inserting from base64
2. call gethtml
3. do some editing then save {N} times

**Comment by tahseenmohd** [comment]
@RuizhiSunMS : Here are the steps and attached Video 

1. open a blank word document using wopi
2. write some paragraphs to it manually through keyboard
3. call the function getHtml() to save it in html format

[LineSpacing_Media.zip](https://github.com/user-attachments/files/17976661/LineSpacing_Media.zip)

Can we setup a (meeting) call on this?

**Comment by RuizhiSunMS** [comment]
> @RuizhiSunMS : Here are the steps and attached Video
> 
> 1. open a blank word document using wopi
> 2. write some paragraphs to it manually through keyboard
> 3. call the function getHtml() to save it in html format
> 
> [LineSpacing_Media.zip](https://github.com/user-attachments/files/17976661/LineSpacing_Media.zip)
> 
> Can we setup a (meeting) call on this?

Hi @tahseenmohd. 
Sorry that I'm not the expert of WOPI, I can reach out to my colleagues knowing that tomorrow since they are off now. However, I think we may can do something else. 
For now, I have the doc and code snippet you shared. [
[GS.Seg.docx](https://github.com/user-attachments/files/17977667/GS.Seg.docx)
](url) 
And a code snippet extracted from the taskpane.txt.
```
$("#run").on("click", () => tryCatch(run));
async function run() {
  await Word.run(async (context) => {
    const body = context.document.body;
    context.load(body);
    const bodyHTML = body.getHtml();

    await context.sync();
    var HTMLContent = bodyHTML.value;
    var HTMLContent = bodyHTML.value.trim(); // Remove leading and trailing spaces
    HTMLContent = await handleTableShrinkChanges(HTMLContent);
    let encodedHtmlContent = encodeURIComponent(HTMLContent);
    console.log(bodyHTML);
  });
}
```
I can't repro this case based on these and what I have are different from what you showed in your video. It would be good if:
1. you could help try if you can repro it by just calling 'run' with my sharings
2. if you couldn't, then getHtml may not be the problem (at least not the only problem). Then would you please take extra try to narrow the problem.

After watching your video, my feelings are: 
1. submitForm is the only place calling getHtml
2. submitForm would submit and clear the doc
3. re-inserted content's format is unexpected

If my feelings are right, would you please help confirm:
1. inserted html are same all the time
2. extract the html code and insert it into a blank doc several times to see what happens
3. what's the difference between inserted html and what you would get calling gethtml

**Comment by tahseenmohd** [comment]
Hello @RuizhiSunMS

**Comment by RuizhiSunMS** [comment]
Hi @tahseenmohd, does this case still block you? If so, please prepare a stable repro guide for us, a file and code snippet should be good. If unable to repro stably, I'm afraid that it's hard for us to go ahead.
If you do have, please share here and feel free to re-activate this case.
In addition, I shall suggest you validate the repro guide at another device or env. And it could be very nice that you shared code is isolated with code calling you server. Some places in your previously shared code are close to your real business, which caused meaningless cost in understanding it. Maybe we can make it more straightforward. Looking forward to your response
