### ISSUE TITLE
[excel] sharp can add image by url

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#509]
hi

when i add a image sharp, it's only support image base64, so i use XMLHttpRequest to get a image base64.it's error in excel. my code below

toDataURL("http://ecx.images-amazon.com/images/I/41SUA08EIBL._SL75_.jpg", function(base64) {
    console.log(base64);
});

function toBase64DataURL(src, callback) {
 
  var xhttp = new XMLHttpRequest();
  xhttp.onload = function() {
    var fileReader = new FileReader();
    fileReader.onloadend = function() {
     
      callback(fileReader.result);
    };
    fileReader.readAsDataURL(xhttp.response);
  };

  xhttp.responseType = "blob";
  xhttp.open("GET", src, true);
  xhttp.send();
  
}

**Comment by catchingyu** [comment]
Is it possible for you to provide us more information on this issue? Thanks a lot for the support.

**Description** : 

**Expected Behavior**

**Current Behavior**

**Steps to Reproduce, or Live Example**


**Context**


**Your Environment**
Platform [PC desktop, Mac, iOS, Office Online]: 
Host [Excel, Word, PowerPoint, etc.]:
Office version number:
Operating System: 
Browser (if using Office Online):

**Comment by catchingyu** [comment]
will reopen it when customer provide more info.
