### ISSUE TITLE
Remove Addin support for Mac and Word on the web

### ISSUE THREAD

**Issue by eutychius** [OfficeDev/office-js#5090]
Hi,

I am creating an Office js Addin where I only want to support Word on premise and Word on Windows (Microsoft 365).
I spent a lot of time trying to adjust my manifest to exclude mac and word on the web (because they are haulting my publication of the addin), but I cannot find a way to do so.

A Consultant from MS found the following for me and said that this should exclude Mac:
```xml
<Requirements>
  <Sets>
    <Set Name="TableBindings" MinVersion="1.1"/>
    <Set Name="OOXML" MinVersion="1.1"/>
  </Sets>
  <Methods>
    <Method Name="Document.getSelectedDataAsync"/>
  </Methods>
</Requirements> 
```

However, when I try this, I get the following error:
Package acceptance validation error: No Supported Office Products There are no platforms which fulfil the requirements specified in the manifest. The most common reasons for this failure are issues in the Requirements section. Please review the manifest and try again.
Package acceptance validation error: No Supported Products found for the package

**How can I exclude support for Mac and Word on the web for my addin?**

Thanks in advance,
   Manuel Juran

**Comment by RuizhiSunMS** [comment]
@Rick-Kirkham would you please take a look at this?

**Comment by Rick-Kirkham** [comment]
I believe you are getting that error because they have misspelled a requirement. There is no requirement set named **OOXML**. There is one named [OoxmlCoercion](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/common/office-add-in-requirement-sets?view=common-js-preview#ooxmlcoercion). 

However, fixing that error will not block the add-in in Word on Mac. Both the **TableBindings** and the **OoxmlCoercion** requirement sets are supported in Word on Mac and Word on the web. The `Document.getSelectedDataAsync` method is also supported for Word on Mac and Word on the web. 

An intrinsic part of the philosophy of Office web add-ins is that they are cross platform. For that reason, there is no systematic way to exclude an add-in from a platform. It looks like the MS consultant that you worked with tried to find a combination of requirements that would effectively block the add-in from the Mac. This is a misuse of requirements. And as I explained above, I don't think it will work anyway.

Why do you want to exclude your add-in from these platforms? What harm would be done if someone used your add-in on a Mac or on the web?

**Comment by eutychius** [comment]
Our Addin relies on usage of the "ms-word:ofe|u|" url. This (to my knowledge) does not work on mac (error msg when opening, my guess is a restriction in security) and with office on web (it always opens the desktop version with the link).
Since from a business perspective (our customers use word as an application) we do not care about these two environments.

However, in the publification process the certification team checks them, because it says it is supported by the manifest.

**Comment by Rick-Kirkham** [comment]
I think the best you can do is to call [Office.context.platfrom](https://learn.microsoft.com/en-us/javascript/api/office/office.platformtype) in the `Office.onReady` or `Office.initialize` method. If the value returned is "OfficeOnline", then the add-in's UI should simply be a message telling the user they must reopen the file in desktop Word for Windows. For example, the content of a task pane could have this text and no other text or controls. If the value returned is "Mac", then the add-in's UI should simply be a message telling the user that they should uninstall the add-in from their Mac and reopen the file in desktop Word for Windows.

I will close this for now, but you can still add comments and we will see them.

**Comment by ManuelRauber** [comment]
@Rick-Kirkham I followed your advice and showing a UI to the user that the add-in does not work in Word for Web and must be used in a desktop variant. However, the certification team did not accept that and wrote me:

> If Your offer doesn't support on web, please remove the client version from the Metadata

But did they offer anything more or how to remove the client version from the metadata.

It's a bit frustrating that no one seems to be able to give an advice how to block Word for Web, especially if you're using APIs that are not available there.

In my use case I access `context.document.body.shapes`, which is only available in [Word for Desktop](https://learn.microsoft.com/en-us/javascript/api/word/word.shapecollection?view=word-js-preview), see the remarks:

> [ [API set: WordApiDesktop 1.2](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/word/word-api-requirement-sets) ]

However, the API set `WordApiDesktop` is not valid to be used in the `Requirements` [section](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/word/word-api-desktop-1.4-requirement-set?view=word-js-preview): 

> Your manifest cannot specify WordApiDesktop 1.4 as an activation requirement. It isn't a valid value to use in the [Set element](https://learn.microsoft.com/en-us/javascript/api/manifest/set).

So, what to do?
