### ISSUE TITLE
Outlook addin is not terminated after timeout

### ISSUE THREAD

**Issue by AtharvaDevSeclore** [OfficeDev/office-js#5098]
I am using an add-in that opens a `displayDialogAsync` to add a header and footer to an email in Outlook.

When I allow the email to timeout (by doing nothing while the dialog box is displayed), a warning notification appears stating:
"Outlook can't send this message because there's a problem with the add-in."
However, the notification stating "Add-in is working on your request" does not disappear.

After this, when I click on Send again and allow the add-in to finish executing, the header and footer are added twice.

I repeated this process, allowing the timeout to occur twice before sending, and the result was that the header and footer were added three times.

I am doing it on Mac, Outlook version 16.91, Classic UI

**Comment by mobisw-msft** [comment]
Hey @AtharvaDevSeclore ,

We are finding it difficult to reproduce the issue with the details provided. Can you please provide a repro using [Scriptlab](https://appsource.microsoft.com/en-us/product/office/WA200001603), or a hosted version of your add-in so that we can investigate further?

**Comment by AtharvaDevSeclore** [comment]
hey @mobisw-msft ,
I don't have the addin hosted and Scriptlab I couldn't find any way to open dialogbox on click of send button using scriptlab.

following is the snipped that might help:
```
Office.actions.associate("onMessageSendHandler", onMessageSendHandler);

function onMessageSendHandler(pEvent: any) {
  console.log("processing mail. . .");
  processMail(pEvent);
}

function processMail(pEvent) {
  Office.context.ui.displayDialogAsync(dialogBoxUrl, { width: 40, height: 40, displayInIframe: true }, (result) => {
    const dialog = result.value;
    dialog.addEventHandler(Office.EventType.DialogEventReceived, async () => {
      const footer = "<div><p>footer</p></div>";
      const mailBody = await new Promise<string>((resolve, reject) => {
        Office.context.mailbox.item.body.getAsync(Office.CoercionType.Html, (result) => {
          if (result.status == Office.AsyncResultStatus.Succeeded) {
            resolve(result.value);
          } else {
            reject(result.error);
          }
        });
      });
      const newBody = mailBody + footer;
      await new Promise<void>((resolve, reject) => {
        Office.context.mailbox.item.body.setAsync(newBody, { coercionType: Office.CoercionType.Html }, (result) => {
          if (result.status == Office.AsyncResultStatus.Succeeded) {
            resolve();
          } else {
            reject();
          }
        });
      });
    });
  });

  pEvent.completed({ allowEvent: true });

}

```

The dialogBoxUrl points to dialogBoxComponent. It just have a button and on click of button it closes the dialog

Hope it helps.

**Comment by arpitsangwanmsft** [comment]
Hey @AtharvaDevSeclore ! 
Unfortunately, we could not repro the mentioned scenario.

1) The snippet provided above calls pEvent.completed({ allowEvent: true}) right after calling the displayDialogAsync api and because it is an async api call event.completed does not wait for other addin execution to finish. So mail is sent as soon as displayDialogAsync api is called without any user interaction.
Can you please pass event as asyncContext while calling the displayDialogAsync api and call event.completed inside the eventHandler block something like this :
![image](https://github.com/user-attachments/assets/8e902aca-66a2-426d-9901-8f1e26ae5437)

Can you please make this change and re-validate the scenario, Also, if you could upload the locally hosted addin to a private repo and provide access to @exextoc, it would be really helpful in repro.
