### ISSUE TITLE
[Outlook] EWS REST API calls fail randomly

### ISSUE THREAD

**Issue by splinter** [OfficeDev/office-js#515]
We recently switched to performing loadAsyncProperties[1] and saveAsync[2] operations using the REST API and we have encountered the following behaviour:
1. The restUrl is empty the first time the mail is opened (happens randomly)
2. The following errors are returned by the EWS REST endpoint sporadically:

```json
{
    "error": {
        "code": "ErrorAccessDenied",
        "message": "The api you are trying to access does not support item scoped OAuth."
    }
}
```

```json
{
    "error": {
        "code": "ErrorAccessDenied",
        "message": "Access is denied. Check credentials and try again."
    }
}
```

```json
{
    "error": {
        "code": "ErrorItemNotFound",
        "message": "The specified object was not found in the store., The process failed to get the correct properties."
    }
}
```

When the same operation is performed again the expected response is returned.

3. The getCallbackTokenAsync will randomly return null

## Expected Behavior
1. The restUrl should be present
2. The errors should be returned consistently or not occur at all

## Steps to Reproduce, or Live Example
1. Obtain the REST URL by calling restUrl property
2. Obtain the REST token by calling getCallbackTokenAsync
3. Use the following request to retrieve custom properties
```
GET https://outlook.office365.com/api/v2.0/me/messages('<message>')?$expand=SingleValueExtendedProperties($filter=PropertyId eq 'String {00020329-0000-0000-C000-000000000046} Name <>')

```

## Context
We are failing to retrieve custom properties.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Windows, Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2016
* Operating System: Windows 10, Mac High Sierra

## Reference
[1] https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item?view=office-js#loadcustompropertiesasynccallback-usercontext
[2] https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item?view=office-js#saveasyncoptions-callback
[3] https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.5/office.context.mailbox?view=office-js#resturl-string

**Comment by exextoc** [comment]
Several clarifications:
- Are you trying to load and save addin custom properties?  Is there any reason you are using REST instead of using JS API?

- Could you clarify on the case when restUrl returns empty? Are you saying that while addin remains open, the first call to restUrl result in empty restUrl while later calls return the url?  If so, could you check that you are using restUrl after office.initialize has been called, and that you are handling itemChanged event if your addin can be pinned?

If not, could you describe the case (read/compose), and client (desktop in Windows, OWA, MAC, etc), version, and the scenario in which you are getting restUrl (during office.initilize, on user action, etc) that you are seeing empty restUrl?

**Comment by splinter** [comment]
- Yeap, we are trying to load and save custom properties. We encountered an issue where mixing OfficeJS and REST API calls resulted in a new version of the mail item been created [1].We store metadata on operations performed by the user in the mail item and then try to add a category label. The first operation was earlier performed by the OfficeJS API while the later was performed by the REST API. This caused a new version of the mail  to be created.

- The restUrl returning empty happens sporadically. This happens the first time we try to fetch this property immediately after the add-in loads. Any subsequent calls succeed. 

We are performing all add-in related operations in the Office.initialize method.

We do support pinning but this happens even without a mail item changed event (i.e. switching to another mail)

## Reference
[1] https://github.com/OfficeDev/office-js/issues/274

**Comment by exextoc** [comment]
Thanks for the reference.  
Let's focus on the REST issues.  The restUrl being empty in first call and work fine in subsequent calls of the same addin session is not expected.  Office.context.mailbox.restUrl simply returns a value from a dictionary that is initialized right before Office.initialize is called. As long as Office.context.mailbox.restUrl is called in Office.initialize or after, it returns the same value.  Could you double check and provide sample Office.initialize and the client and version that you see this with?

For the other REST errors:
Is the posted REST call in step 3 the only REST you call?  Could you include the code on how you are adding the bearer token in the headers?​
- the first error seems to indicate that a different REST method is being called.​
- the 2nd error is possible if the token is not correctly added as a bearer token or it expires (token can expire in 5 mins)​
- the 3rd error indicates the item is not on the server, could be due to sync issue or issue with the item id.  Based on the reference, I assume you are doing this in compose, how do you ensure that sync has happened?

**Comment by splinter** [comment]
The initialize code:
```js
window.Office.initialize = (reason) => {
    platformBrowserDynamic().bootstrapModule(AppModule);
};
```
We test on and use multiple Outlook client versions, a sampling is given below:
- Outlook for Mac 2016 - 16.23.1 (190326)
- Outlook 2016 Windows - Version 1904

We do make two other REST calls which oddly seem to always work:
- Get Message  - This is done to obtain categories
- Update Message - This is to add categories 

The code used to add the header:

```js
    const headers = new Headers();
    headers.append("Authorization", `Bearer ${token}`);
    headers.append("Content-Type", "application/json");
    return headers;
```

We are encountering issues in both modes (Read and Compose). 

> how do you ensure that sync has happened?

We do not currently have a way to check this

**Comment by kbrandl** [comment]
@splinter are you still having this problem, or can this issue be closed? Thanks!

**Comment by modestfake** [comment]
I'm experiencing the same issue.

**Comment by kbrandl** [comment]
@modestfake thanks for confirming that this issue is still present. @exextoc can you please re-engage with the customers to continue investigating this issue? Thanks!

**Comment by exextoc** [comment]
@modestfake Did you encounter all of these three errors, or some of them? What is your outlook version?

**Comment by modestfake** [comment]
@exextoc sorry to not clarifying it before. So I only see this:
>1. The `restUrl` is empty the first time the mail is opened (happens randomly)
Because of this, we can't send a request to get email attachments.

**Comment by exextoc** [comment]
@modestfake : We recommend openeing a new issue explaining exactly what you are facing. This helps us keep issues independent and have a quicker turn around time in responding to you. May we request you to open an independent issue regarding what you are facing. Mentioning the build numbers of the client will also be helpful

**Comment by modestfake** [comment]
Thanks @exextoc 
I've ended up creating one #721.
