### ISSUE TITLE
Inconsistent behavior when add new Excel tables

### ISSUE THREAD

**Issue by ChienHo** [OfficeDev/office-js#5151]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.18318.42301
* Operating System: windows 10
* Browser (if using Office on the web): chrome version 131.0.6778.86 (Official Build) (64-bit)
 
## Expected behavior

Adding new table doesn't push the sheet down 1 row randomly.

## Current behavior

Adding new table pushes the sheet down 1 row randomly, alters formulas as a result

## Steps to reproduce

1. Insert a formula to Sheet1 that refers to range A2:A100
2. Add new table to Sheet1 with the API sheet.tables.add("A2:F2", true)
3. Observe the formula changes

# Provide additional details

![screencast-2024_12_02-14_22_01](https://github.com/user-attachments/assets/54e7ec44-d5e4-4d56-9bb4-aed7ee895235)

## Context

Our add-in has a feature that inserts tables. This issue messes up the formulas when it happens.

**Comment by RuizhiSunMS** [comment]
Hi @ChienHo, thx for reaching out here. I can repro it. Put it as ADO #9589944 into our backlog. Will involve experts to go on investigation. Will reply here if any update.
Btw, I recognized two 'push'es:
1. cell A5 (take it as example) was pushed downward with one cell.
2. formulation in cell A1 referring to a3:a100 was changed to a4:a101

would you please confirm that, these two 'push'es are all what you think unexpected?

**Comment by ChienHo** [comment]
Thank you @RuizhiSunMS yes those are what I think unexpected. Because sometimes that doesn't happen.

**Comment by SiruiSun-MSFT** [comment]
Hi @ChienHo , Thanks for your reporting. However, the two inconsistent cases seem to be a By-design behavior.
Currently, when inserting a table into Excel, it must contain at least two rows. The first row is the table header, and the second row and the following are the table contents.
For this case:
![image](https://github.com/user-attachments/assets/36d0eeef-6597-46b0-8ba6-ce3a23125bfd)
The reason why all rows are shifted downwards is that there is insufficient space when inserting the table, leaving only space for Line2. Therefore, another row needs to be inserted, and the original content and references need to be shifted downwards to meet the space required for inserting the table. And you will get the followed sheet, that's because Line3 is inserted for the new table.
![image](https://github.com/user-attachments/assets/970e9ae7-5569-4d80-aa21-9e08fc5e30c9)
For the other case, you just deleted the content of Line2 and Line3, but keep these two rows as the remained space to insert new table:
![image](https://github.com/user-attachments/assets/b4c9d4f2-fc51-4d8f-ac38-87979b8d4414)
When the number of reserved blank rows is sufficient, the table will be inserted directly without moving other rows down.
