### ISSUE TITLE
Range.highlight() color is too light so very hard to recognize

### ISSUE THREAD

**Issue by isadovskiy-numatic** [OfficeDev/office-js#5177]
* Platform: PC desktop, Mac
* Host:  Word 
* Office version number: 16.93 (24112519)
* Operating System: MacOS

OfficeJS SDK recently introduced new feature for temporary texts highlighting: https://learn.microsoft.com/en-us/javascript/api/word/word.range?view=word-js-1.9#word-word-range-highlight-member(1)

The problem is the used highlight color is too light and very hard to recognize on the white background, especially for the people having vision problems. This make the entire feature not useful because of user's complaints on this color. They just having problems to find and recognize the highlighted text on the screen.

Need to make this color more prominent; or add the ability to configure it.

**Comment by RuizhiSunMS** [comment]
Hi @isadovskiy-numatic, thx for reaching out here. I did a try and found it is hard to figure out indeed with white background. Put it as #9614218. We will call experts to investigate. Will reply here if any update.

**Comment by RuizhiSunMS** [comment]
Hi @samantharamon, partner team's expert has completed the investigation and confirmed this is by-designed. The color used to highlight is shared with some places, not only highlight.
Consider this case could be a DCR rather than a bug, I suggest you submit request on https://techcommunity.microsoft.com/category/microsoft365/ideas/microsoft365developerplatform. PMs will review this regularly and add requests with high votes into our backlog.

**Comment by hinkik** [comment]
Also having issues with this! Having this be configurable would be extremely helpful. Ideally, I wanna be able to highlight two different ranges in two different colors
