### ISSUE TITLE
Office addin crashing Outlook

### ISSUE THREAD

**Issue by ArjunSureshKumar92** [OfficeDev/office-js#5197]
Every day outlook crashes while trying to load. For some reason, when i take a look at the events log, it shows outlook crashed because my office js addin. 

I find it difficult to understand how this is possible, since the addin only has scope within the task pane. The error message is "the addin could not load due to network connectivity issues". 

So my question is whether the addin could cause outlook crashes, or whether it was just a coincidence. Thanks.

**Comment by Oleg-O** [comment]
Hi @ArjunSureshKumar92 what Outlook version is this? Could you please also include the exact event log message? At what point does it crash exactly - when you open Outlook? When you click on add-in button on the ribbon?

**Comment by ArjunSureshKumar92** [comment]
I have a screenshot given by the customer to us. Unfortunately this is the only info i have at the moment. This is the errors 3 of their users are getting almost everyday.

[Emailgistics Troubleshooting Screenshots.docx](https://github.com/user-attachments/files/18169432/Emailgistics.Troubleshooting.Screenshots.docx)

**Comment by Oleg-O** [comment]
Thanks for sharing this. At least it helps clarify that this is for Windows Desktop (classic, not new) Outlook. 

The event logs likely indicate that occasionally the user can't load your add-in from their computer. This could happen due to network issues or availability of your add-in on their network.

But that should not be causing an application crash. Could you please clarify, what do you mean exactly when you say "crash"? Does the Outlook application close? Or does it go unresponsive? Or does the add-in pane display an error? Is it possible for them to share a screenshot of it (but please redact out all private information before sharing).

Also, at what point does it crash exactly - when they open Outlook? When they click on add-in button on the ribbon?
