### ISSUE TITLE
Office.context.diagnostics missing in Windows Outlook 2016 MSI

### ISSUE THREAD

**Issue by ShannonLCapper** [OfficeDev/office-js#541]
`Office.context` has several missing fields in the most recent version of Windows Outlook 2016 MSI than it does in the most recent version Windows Outlook 2016 click-to-run. This is not reflected in the [documentation](https://docs.microsoft.com/en-us/javascript/api/office/office.context?view=office-js) for the `Context` interface

## Expected Behavior

In Windows Outlook for Office 365 MSO (click to run), v16.0.11629.20192, `window.Office.context` has to following shape:
```
{
  auth: {...},
  commerceAllowed: 1,
  contentLanguage: "en-US",
  diagnostics: {...},
  displayLanguage: "en-US",
  host: "Outlook",
  isDialog: false,
  license: {...},
  mailbox: {...},
  officeTheme: {...},
  platform: "PC",
  requirements: {...},
  roamingSettings: {...},
  touchEnabled: 0,
  ui: {...},
}
```
I would expect the most recent version of Windows Outlook 2016 MSI to have the same shape (minus `auth`, which does not exist in requirement set 1.4)

## Current Behavior

We have a customer with Windows Outlook 2016 MSI, v16.0.4834.1000 (which is the [most recent patch](https://support.microsoft.com/en-us/help/4464502/april-2-2019-update-for-outlook-2016-kb4464502)), connected to an O365 account. Their `window.Office.context` has the following shape:
```
{
  commerceAllowed: undefined,
  contentLanguage: "en-US",
  displayLanguage: "en-US",
  license: {...},
  mailbox: {...},
  requirements: {...},
  roamingSettings: {...},
  ui: {...},
}
```
Notice how `auth`, `diagnostics`, `host`, `isDialog`, `officeTheme`, `platform`, and `touchEnabled` are missing.

I would expect `auth` to be missing since that is a Preview feature, and according to the documentation, Windows Outlook 2016 for one-time purchase [should support up to Requirement Set 1.4](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#clients).

However, `officeTheme` should be present since it was [added in Requirement Set 1.3](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.3/outlook-requirement-set-1.3?view=office-js).

Most importantly, we cannot find anywhere in the documentation that would suggest that `diagnostics`, `host`, `platform`, and `touchEnabled` are not available in all requirement sets.

## Context

Our plugin is not working for one of our customers because our code assumes that, after waiting for `window.Office.initialize` to be called, `window.Office.context.diagnostics` should be defined. Our code crashes when it tries to access the `host` and `platform` on an undefined object.

We were surprised to find this value missing since the documentation doesn't indicate that it was added in a particular requirement set. Is this a bug, or is this expected behavior? We can work around this particular issue, but we're now worried that we may make assumptions in the future about other fields in the OfficeJS object, without knowing that they may be missing in certain versions of Outlook.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.4834.1000
* Operating System: unknown
* Browser (if using Office Online): N/A

**Comment by exextoc** [comment]
For Outlook, please use the hostName property on the [Office.context.**mailbox.diagnostics**](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.7/office.context.mailbox.diagnostics?view=office-js) object in place of Office.**context**.diagnostics.platform (please note, the property name and values are different between the two objects). In particular, Office.context.diagnostics._platform_ corresponds to Office.context.mailbox.diagnostics._hostName_, and Office.context.diagnostics.host does not have a corresponding property, but would always be "Outlook" for Outlook add-ins.

Office.context.**mailbox**.diagnostics is part of **Mailbox requirement set 1.0**, so it will be available in all versions of Outlook.

[Office.context.diagnostics](https://docs.microsoft.com/en-us/javascript/api/office/office.context?view=office-js#diagnostics) is only available in newer versions of Outlook. Usually the documentation will specify which requirement set contains the API. I'll check to see if this can be added to the documentation.

Since you mentioned [officeTheme](https://docs.microsoft.com/en-us/javascript/api/office/office.officetheme?view=office-js) as another example, it's currently [in preview](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview) for Outlook for Windows. It may be a documentation bug that it's listed in requirement set 1.3. We'll get the documentation updated. Thanks for pointing that out.

For the other [Office.context](https://docs.microsoft.com/en-us/javascript/api/office/office.context?view=office-js) properties, in some cases the documentation will mention the supported Hosts or a requirement set version. For the properties that are objects, it may be documented on one of the child properties. If you rely any other properties that aren't documented, we can get the documentation updated. I can also open a documentation bug to get the rest of the properties updated. It may take time to get accurate documentation for all of them. Thanks for reporting this issue!
