### ISSUE TITLE
[Word] Bug when adding comments through OOXML manipulation

### ISSUE THREAD

**Issue by LeszekNie** [OfficeDev/office-js#559]
Inserting a comment into a Word document causes the Track Changes feature to register a deletion event.

## Expected Behavior
That inserting comments into a Word document behaves the same way as the native feature.

## Current Behavior
A comment added by manipulating the document XML causes Track Changes to register the event in the form of a “Deleted: [text being commented]" message and displaying it as an additional comment to the user.
The suggested solution is to add an API for commenting to the Office.js

## Steps to Reproduce, or Live Example

Here is the relevant code: https://gist.github.com/LeszekNie/d9fef6cf2fceecca03dc074e050bea30

## Context
Our Javascript add-in for Word helps users with inserting comments, speeding up the process by offering ready-to-reuse comments. The current behaviour is seen as a bug because the native feature does not behave the same.

## Your Environment
•	Platform: Mac/Win/Online
•	Host: Word
•	Office version number: Head.
•	Operating System: all supported
•	Browser (if using Office Online): IE11.

**Comment by JuaneloJuanelo** [comment]
This is by design. When it comes to insertion of OOXML or other insertions when using the  "replace" insert location (in this case replacing the range with OOXML), you are effectively deleting some content and adding new. (note this is different operation than inserting a comment through the UI).

OOXML insertion is super powerful because you can insert almost any word object in the document, but it comes with a few downsides like this.

We are very aware (in our backlog) to add comments support (no Data for this) but when we do this will be solved.
