### ISSUE TITLE
ContentControlCollection is corrupted when insertooxml() is called

### ISSUE THREAD

**Issue by oaltun** [OfficeDev/office-js#603]
I first asked this as a [question in the Stackoverflow](https://stackoverflow.com/questions/56905409). Rick Kirkham reproduced the behavior and suggested me to open this issue.

## Expected Behavior
I want to be able to hide/unhide contents of some content controls. For this, I get ooxml of the content, save and load the ooxml using customXmlParts, and insertOoxml() back. I want to be able to do this any number of times.

## Current Behavior
Currently I can hide and unhide once. On the second hide attempt, context.document.contentControls.getByTitle() gives me twice the number of content controls i see on the screen. Half of the id's are new. When I try to getOoxml() of these, the system produces an error with errorLocation of ContentControlCollection.getItem.

Please see the code in the Stackoverflow link.

## Steps to Reproduce, or Live Example
* Link to live example: a) Code in the [question in the Stackoverflow](https://stackoverflow.com/questions/56905409) b) or [Scriptlab](https://gist.github.com/oaltun/c0b914521bb1636979779688c3cd08f3).

## Context
I am trying to implement the hide/unhide feature, which apparently used to exist in earlier VBA/VSTO based add-in technology, but is missing in office-js apis. This is a show stopper as it is very important to the add-in I am writing.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2016.0.4849.1000
* Operating System: Windows 10

**Comment by JuaneloJuanelo** [comment]
Interesting case i just answered in stack, please go there for more details.. What you are describing is by design.
The main problem is that you are getting the OOXML of the entire content control. And by entire i mean what's within the content control plus the actual control. that's why you are getting a duplicate number of content controls.

my suggestion is that you get just the OOXML of whats within the cc and the critical line of code you need to change is this one:

```
     const ooxmlObj = ccs.items[i]
        .getRange("start")
        .expandTo(ccs.items[i].getRange("end"))
        .getOoxml(); // *
```

that should fix the issue, here is a working sample. just setup and then press on hide content and show content: 
https://gist.github.com/JuaneloJuanelo/4a78ab47b7df9594bc7d097842166cbf


also think about where you want to store the OOXML i am not sure i will use a custom xml part, i used an array in my sample. 

hope this helps you.

happy coding!!
