### ISSUE TITLE
[Excel] http get 302 do not support in office add-in?

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#637]
## Expected Behavior

http get with 302 , excel can go to the location address.

## Current Behavior

in excel dialog we use paypal . when finished pay.the paypal will use our Location address.

but it  display same message.

we have add a timetick like ?v=timetick. but it also not go to location address. how to solve it? 

thanks.

![image](https://user-images.githubusercontent.com/3963826/61839685-1b36ad00-aec1-11e9-9697-564006513585.png)

**Comment by catchingyu** [comment]
Is it possible for you to provide us more information on this issue? Thanks a lot for the support.

Description :

Expected Behavior

Current Behavior

Steps to Reproduce, or Live Example

Context

Your Environment
Platform [PC desktop, Mac, iOS, Office Online]:
Host [Excel, Word, PowerPoint, etc.]:
Office version number:
Operating System:
Browser (if using Office Online):

**Comment by dinglicoding** [comment]
@catchingyu  thanks for you quickly reply

Expected Behavior
http get 302  can support.

Current Behavior

in excel dialog we use paypal . when finished pay.the paypal will use our Location address.

but it display same message.

and i click Retry. it's fine.

![image](https://user-images.githubusercontent.com/3963826/61847462-53e47f80-aedd-11e9-8566-cde1ed7cb9bf.png)
![image](https://user-images.githubusercontent.com/3963826/61921213-ebee7180-af8e-11e9-99ed-1394feba1e69.png)

Your Environment
PC desktop

Host [Excel, Word, PowerPoint, etc.]:
Excel

Office version number:
version 1906 (build 11727.20244)

Operating System:
windows 10 (1903)
