### ISSUE TITLE
How to call Office JS from .Net/Java applications

### ISSUE THREAD

**Issue by AhmedVali** [OfficeDev/office-js#64]
Hello Experts,

I have an add in which will insert some text into Word  upon user action ( lets say simple button press)

Is it possible to call this method which inserts text into Word from outside office applications ?

Is it possible to build a web service layer on top of my add in and expose it so that other applications can consume it.

**Comment by sumurthy** [comment]
You may be looking for desktop or server level automation that is still not available using JavaScript technology. Even if it is possible the workflow would involve writing separate function/routine rather than calling into your add-in (though you should be able to re-use the function implementation). Excel offers this service access capability if the workbook is stored in OneDrive or SharePoint via Microsoft Graph REST API. Word `REST` APIs are not yet available. No timeline available for both technology. If you wish to be notified early, please log a request in Office Dev UserVoice.

**Comment by JuaneloJuanelo** [comment]
@AhmedVali  for future reference this type of question is more of a stackoverflow question (use tag 'office-js'

I am closing this case since, this is basically not supported.

**Comment by JuaneloJuanelo** [comment]
btw @AhmedVali  also will be very useful if you can start a discussion about this in our user voice channel as this might be a feature we could enable in the future. thanks!  https://officespdev.uservoice.com/
