### ISSUE TITLE
window.open does not work on Outlook Desktop

### ISSUE THREAD

**Issue by eneoli** [OfficeDev/office-js#643]
Using window.open to open an url in users default browser fails. Using window.open on OWA and Android/Mobile works perfectly.

## Expected Behavior
Open passed url in users default browser

## Current Behavior
window.open does not work. 
How to debug Office Desktop?

## Steps to Reproduce, or Live Example
window.open("https://google.de");

## Context
Our web app returns an url, that we want to open.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 1902 Build 11328.20368
* Operating System: Windows 8.1
* Browser (if using Office Online): X

**Comment by exextoc** [comment]
Hi EneOil,

I'm unable to reproduce your issue on any of my test machines, but [here's](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/attach-debugger-from-task-pane) the article on how to debug add-ins in Outlook Desktop. The article talks about Excel, but the same process is used for outlook, with 1 minor wrinkle: **Rather than clicking on the Personality Menu, right click anywhere in the pane and select `Attach Debugger`**

**Comment by exextoc** [comment]
If you do find an error message while debugging, please feel free to reply with the error message so we can help you further.

**Comment by eneoli** [comment]
I will try. Thank you
