### ISSUE TITLE
Content Controls Events/Callback to navigate specific Task Panes based on CC selections.

### ISSUE THREAD

**Issue by rake93** [OfficeDev/office-js#649]
**Requirement:** 
I have a requirement where my word plug-in needs to navigate Task-panes based on the selection of rich text controller. I have build word plug-in using Reactjs and have used react-router for navigation. I'm loading task panes based on the task pane menu selection. 

**Example scenarios:** Lets say I have (1) **Bookmarks**, (2) **Embed** and (3) **Grid** task-panes. Through our application, User insert's content controls related to these three and uploads the document in Application. If user tries to update those CC's and during this update process User clicks on any CC and I want to navigate to that selected CC Taskpane. Here, each content control is having unique CC Tag names.
**It would be great if you can provide sample code, if Office.js has any Events/Callbacks in Content Controls. Let me know how to implement this requirement, if Office.js doesn't have any callbacks.**

**Word-addin UI implementation**

![image](https://user-images.githubusercontent.com/823725/62461813-ceba5f80-b753-11e9-8d40-fc5697510b23.png)

**Expected flow of CC callbacks**

![image](https://user-images.githubusercontent.com/823725/62461871-fd383a80-b753-11e9-83bd-4a767e00b8c9.png)

**Comment by JuaneloJuanelo** [comment]
Hello @rake93  this is more of a question rather than an issue in our platform. I recommend you to use stackoverflow with #office-js tag for it.

That been said there is an event on rich text content control that gets triggered when the content control is selected.  check out my answer on this [similar stack question.](https://stackoverflow.com/questions/36704444/how-to-implement-onenter-and-onexit-event-on-contentcontrol-using-javascript-api/36724280#36724280)  

for that you need to create a binding (using the content control title) and then subscribe to the event...

btw i reccommend you to use a the tag property of the content control to help you find out if it was added from bookmark, embed, grid or whatever other task pane.

your code should look like

```
function CreateBindingAndAddEvent() {
        Office.context.document.bindings.addFromNamedItemAsync("TitleOfTheContentControl", { id: 'whateverIdForTheBinding' }, function (result) {
            if (result.status == 'succeeded') {
                result.value.addHandlerAsync(Office.EventType.BindingSelectionChanged, handler);
            }
        });
       
    }

    function handler() {
       console.log("Event Triggered!");
    }
```
