### ISSUE TITLE
New PowerPoint Add-in project gives me a 'This add-in could not be started' when it starts

### ISSUE THREAD

**Issue by NickDarvey** [OfficeDev/office-js#66]
# Repro
1. In Visual Studio, File --> New Project
1. Select 'PowerPoint Web Add-in'
1. Select 'Add new functionalities to PowerPoint'
1. Tap 'OK'
1. Tap Start (F5) and wait for PowerPoint to open
1. Open the app by tapping 'Show Taskpane'

Same deal for Word Add-In.

## Expected
App starts.

## Actual
```
ADD-IN ERROR
This add-in could not be started. Close this dialog to ignore the problem or click "Restart" to try again.
```
![image](https://user-images.githubusercontent.com/6076697/36304079-7af05f3a-1362-11e8-83bf-b2d3a48cdd1b.png)

# System Info

## Visual Studio
```
Microsoft Visual Studio Professional 2017 
Version 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Professional


JavaScript Language Service   2.0
JavaScript Language Service

Office Developer Tools for Visual Studio 2017 ENU   15.0.27005.00
Microsoft Office Developer Tools for Visual Studio 2017 ENU

TypeScript Tools   15.5.11025.1
TypeScript Tools for Microsoft Visual Studio
```

## PowerPoint
Version 1801 (Build 9001.2171 Click-to-Run)
Monthly Channel

## Windows
Windows 10 Pro
Version 1709
OS Build 16299.248

# Things I've tried
https://support.microsoft.com/en-us/help/2761180/apps-for-office-don-t-start-if-you-disable-protected-mode-for-the-rest

**Comment by JuaneloJuanelo** [comment]
Hello thanks for reporting this issue, we are investigating internally.

**Comment by JuaneloJuanelo** [comment]
Couple of questions for @NickDarvey 
I was trying to repro your situation without success. So, I have a few questions: 
1. Question: did you trusted the certificates when running the adding the first time?
2. Is this the first add-in you are trying to create on this environment?
3. Did you tried re-installing VS and Office Deverloper Tools?

**Comment by NickDarvey** [comment]
Hi @JuaneloJuanelo,

1. I ran these steps on another machine and got a prompt to trust IISExpress's TLS cert but I didn't get that prompt on the machine with this issue. I can browse to the site in Edge and it loads correctly, with a trusted connection (and I can see a 'IIS Express Development Certificate' installed into 'Trusted Root Certification Authorities' which is still valid).
1. I am pretty sure this is the first time on this environment.
1. I re-installed the Office Developer Tools, but not Visual Studio.

**Comment by JuaneloJuanelo** [comment]
Thanks, I am following up with our Visual Studio team and we concur that it might be a lack of trust certificate issue.
follow up questions.
1. In the other machine you were able to restore the project and run it successfully?
2. is the issue fixed on the original machine? and if not can you reinstall VS and retry?

thanks!

**Comment by JuaneloJuanelo** [comment]
@NickDarvey  can you please confirm that you not longer have the issue?

**Comment by NickDarvey** [comment]
>we concur that it might be a lack of trust certificate issue.

maybe, except

>I can browse to the site in Edge and it loads correctly, with a trusted connection (and I can see a 'IIS Express Development Certificate' installed into 'Trusted Root Certification Authorities' which is still valid).

The issue is not fixed on the original machine. I can't reinstall Visual Studio because that's my workstation and can't have that kinda downtime right now.

**Comment by mlafleur** [comment]
What does your manifest.xml look like?

**Comment by kbrandl** [comment]
@NickDarvey -- FWIW, I recently experienced the exact same issue that you've reported -- although In my case, I had inadvertently caused the issue myself by manually removing all `localhost` certs from my machine's Trusted Store (in the process of troubleshooting something different altogether). Because the 'IIS Express Development Certificate' was amongst the certs I removed, Visual Studio was no longer able to successfully start/run my add-ins.

In my case, I was able to resolve the issue by simply *updating* Visual Studio to the latest available version (using the Visual Studio Installer). The update only took a few minutes of my time, and then the next time I tried to create/run an add-in project, Visual Studio gave me the series of "trust the cert" prompts and after that, everything worked for me again.

I realize that my scenario is slightly different than your situation (because you still see that cert in the trusted store and can browse to the site using Edge), but if you have a few minutes to spare, you might try just *updating* Visual Studio to the latest version, to see if that resolves your issue.

**Comment by ghost** [comment]
I have a similar issue with Visual Studio 2017 and Excel 2016. I tried reinstalling Office and Visual Studio, but with no luck. In the Event Viewer I have the following error:
![image](https://user-images.githubusercontent.com/29251745/52779633-d91f5a80-3048-11e9-97e2-669cb23e43fa.png)

And before that the following information event:
![image](https://user-images.githubusercontent.com/29251745/52779672-ea686700-3048-11e9-9af9-997648c5a22c.png)

If I side-load the plugin by sharing the folder with the manifest and adds the plugin manually, it works. It is only when I try to debug from Visual Studio 2017.

Any pointers to what I can do? (cc @JuaneloJuanelo)
