### ISSUE TITLE
Compatibility with windows 10

### ISSUE THREAD

**Issue by sebisebo** [OfficeDev/office-js#661]
I have an issue with my Excel add-in on windows 10. I catch my Excel.Run() and always receive an error "AccessDenied". I don't understand because it worked fine on windows 8. Is there any reason ? I'm on 1.1.0.14 version. 
Try to update to 1.1.0.15 but that create me a lot of error during compilation. (namespace office in double in office.d.ts)

**Comment by lumine2008** [comment]
Thanks @sebisebo for your post, could you please share a bit more information about repro steps? therefore we could have a try in our side.

**Comment by sebisebo** [comment]
Hi, 
What type of information do you need ?

**Comment by lumine2008** [comment]
could you please share us your code or your gist (preferred) or provide us the following information. therefore we can have a local repro. thanks

Description :

Expected Behavior

Current Behavior

Steps to Reproduce, or Live Example

Context

Your Environment
Platform [PC desktop, Mac, iOS, Office Online]:
Host [Excel, Word, PowerPoint, etc.]:
Office version number:
Operating System:
Browser (if using Office Online):

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
