### ISSUE TITLE
Selecting Addin while editing text in FormulaBar Crashes Excel

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#688]
## Steps to Reproduce, or Live Example

1. Insert the Addin to Excel File
2. Click on Formula Bar add some text
3. Then try selecting the Addin.

Excel Crashes with error "Reference isn't valid"

## Your Environment
Excel Desktop 11929.20182 Click-to-Run
Windows 64 Bit.

## Useful logs

The following dialog shows up as we navigate through the excel and makes Excel completely unusable until we finally ‘Terminate the Excel app’ through Task manager (even trying to close the Excel doesn’t work)

![123](https://user-images.githubusercontent.com/53947200/63549614-64c0f900-c54e-11e9-96c9-84e8d93a8e2c.png)

**Comment by catchingyu** [comment]
Is it possible for you to provide us more information on this issue? Which AddIn you are using?
Thanks a lot for the support.

Description :

Expected Behavior

Current Behavior

Steps to Reproduce, or Live Example

Context

Your Environment
Platform [PC desktop, Mac, iOS, Office Online]:
Host [Excel, Word, PowerPoint, etc.]:
Office version number:
Operating System:
Browser (if using Office Online):
