### ISSUE TITLE
[Perf] AddIn infra goes in inconstant state on adding multiple AddIns

### ISSUE THREAD

**Issue by 3dot1four** [OfficeDev/office-js#691]
## Expected Behavior

We are developing an AddIn for Excel. On Adding multiple instances of AddIn on different sheets the AddIn infra kind of crashes and keeps restarting all the AddIn instances. I believe there should be some optimization which can give more cycles to AddIns which are in view and do lazy load of AddIns which are not in view.

## Current Behavior

All the AddIns starts to load together and keeps crashing and restarting.
## Steps to Reproduce, or Live Example

Take a DOM heavy AddIn and add ~15-20 instances of it in an Excel sheet.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 12023.2000
* Operating System: Windows
* Browser (if using Office Online): NA

**Comment by lumine2008** [comment]
@rohitrewa , we would like to have local repro for this issue. so could you please share us your code or your gist (preferred) or provide us the following information. thanks

Description :

Expected Behavior

Current Behavior

Steps to Reproduce, or Live Example

Context

Your Environment
Platform [PC desktop, Mac, iOS, Office Online]:
Host [Excel, Word, PowerPoint, etc.]:
Office version number:
Operating System:
Browser (if using Office Online):
