### ISSUE TITLE
Excel-addin- Office API Javascript - office.js warning and telemetryproxy.html not found

### ISSUE THREAD

**Issue by gch1234567** [OfficeDev/office-js#696]
0

I tried to load my excel-addin on chrome browser.

I have added office.js api and I am getting warning and error in console as warning: Warning: Office.js is loaded outside of Office client Error: Failed to load resource: the server responded with a status of 404 (Not Found) telemetryproxy.html

I checked in the network tab and the error: https://telemetryservice.firstpartyapps.oaspapps.com/telemetryservice/telemetryproxy.html 404- file or directory not found.

Can someone help me to fix it?

Thanks

**Comment by lumine2008** [comment]
Thanks @gch1234567 , i am not sure if i understand your issue. 
as i replied your post in stackoverflow. looks like this URL has problem? it cannot open in browser. 

could you please share us your code or your gist (preferred) or provide us the following information.  therefore we can have a local repro. thanks

Description :

Expected Behavior

Current Behavior

Steps to Reproduce, or Live Example

Context

Your Environment
Platform [PC desktop, Mac, iOS, Office Online]:
Host [Excel, Word, PowerPoint, etc.]:
Office version number:
Operating System:
Browser (if using Office Online):

**Comment by TheSamsterZA** [comment]
Hi @gch1234567,

> I tried to load my excel-addin on chrome browser.

That's your problem right there. When the OfficeJS script runs, one of the first things it does is detect the Office host it is running in (Excel, Word, Outlook, etc). If no host is found, it logs the warning you saw:

`Warning: Office.js is loaded outside of Office client`

Try to load your add-in on Excel Online.

**Comment by Rick-Kirkham** [comment]
The error about the telemetry file refers to a file that can only be loaded by add-ins that are created internally by Microsoft employees. The error has no effect on your add-in. If you are trying to open your add-in directly in Chrome, then what @TheSamsertZA says is correct. You must sideload the addin to either desktop Excel or Excel Online.
