### ISSUE TITLE
Outlook 2016: API v1.5 no longer supported with newest release.

### ISSUE THREAD

**Issue by JefCurtis** [OfficeDev/office-js#725]
Hello folks 👋 

After updating Outlook 2016 using [this update](https://support.microsoft.com/en-us/help/4475580/september-3-2019-update-for-office-2016-kb4475580) it seems that the version of OfficeJS has changed and removed support for Office API `v1.5` and above?

Some of our Outlook add-in functionality was dependent on `v1.5` and up so there is a conditional check in the code to confirm that the version of Outlook the add-in is running in does support this version before toggling this feature on. I've been recently receiving reports from some of our users that their version of Outlook (2016) no longer support this functionality even though, before updating, it did work. Testing the same functionality in the browser and Outlook 2019 still works as expected. 

I can confirm this:
```javascript
// before Sept 3rd update
Office.context.requirements.isSetSupported("Mailbox", 1.5); ==> true
```

```javascript
// After Sept 3rd update
Office.context.requirements.isSetSupported("Mailbox", 1.5); ==> false
```

Current version of Outlook 2016 |
-- |
![image](https://user-images.githubusercontent.com/3892972/64806737-a0952000-d548-11e9-86a4-4c39cc6eab2f.png) |

Is this expect behavior? Was there is change to the supported version of OfficeJS with this update? 

## Your Environment
* Platform [PC desktop]
* Host [Outlook]
* Outlook version number: See above image. Stand alone installation.
* Operating System: [Win10]

**Comment by JefCurtis** [comment]
@jargil Pinging you here.

**Comment by exextoc** [comment]
This is the expected behavior. Outlook 2016 MSI versions (which is the one you are on) only supports uptil requirement set 1.4. Documentation [here](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets). If before this update it was sending true for supporting 1.5 that would have been a bug. What APIs are you dependent on that requires you to use requirement sets 1.5 and above? Requirement sets > 1.4 are only supported for outlook through office 365 subscription installations.

**Comment by JuaneloJuanelo** [comment]
@JefCurtis  as previously commented, in that version of Office that's expected (1.5 is not supported there and if you call any 1.5 API will fail).What functionality of 1.5 are you using in your Add-in? Can you confirm such APIs fail in the cited build?
