### ISSUE TITLE
about Office URI Schemes

### ISSUE THREAD

**Issue by hoshizorayuuta** [OfficeDev/office-js#729]
When using the OFFICE URI to open the word, powerpoint, excel, use "?" to bring the parameters, powerpoint and excel can normally pass the parameters back to the server, but the word will not bring the parameters back.
Word:ms-word:ofe|u|uri?parameters
Powerpoint:ms-powerpoint:ofe|u|uri?parameters
Excel:ms-excel:ofe|u|uri?parameters

**Comment by keyur32** [comment]
Hi there, thank you for this issue. This question seems to be different than the office-js api. @davidchesnut  - can you help me route?  I'm unsure of the correct repo for this, but seems to be specific to client.   @catchingyu - fyi

**Comment by keyur32** [comment]
@davidchesnut  - assigning to you to redirect to right repo. We may have to ask poster to redirect to a location outside of github but not clear where it fits under.

**Comment by kbrandl** [comment]
@keyur32 seems like this issue belongs in the [MicrosoftDocs/office-developer-client-docs](https://github.com/MicrosoftDocs/office-developer-client-docs) repo -- which contains documentation about [Office URI Schemes](https://docs.microsoft.com/en-us/office/client-developer/office-uri-schemes). 

@hoshizorayuuta can you please open this issue in the [MicrosoftDocs/office-developer-client-docs](https://github.com/MicrosoftDocs/office-developer-client-docs) repo instead?  (Closing this issue here in **OfficeDev/office-js**, since it's not relevant to Office Add-ins | Office JS.)
