### ISSUE TITLE
Who should use office.js?

### ISSUE THREAD

**Issue by sirius1024** [OfficeDev/office-js#748]
I need to build an internal website to process Excel(xls/csv/xlsx)

e.g. 
- Upload an xlsx file work with its data and output charts with our logic, then put charts into xlsx file as pictures and download it.
- Read xlsx data then count/filter lines/columns with user custom conditions and show reports.
- Something like above that R/W excel files and operate it.

Should I use office-js or OpenXML SDK or something else? any suggestions please?

**Comment by JuaneloJuanelo** [comment]
Hello! this question is a really good candidate to be in stack overflow (#office-js) since its not really  an issue in out platform, I recommend you to use that resource in the future.

That been said, without looking into the details on what exactly you mean by custom conditions, sounds like you could choose either technology, it will boil down to the experience you want to provide.

So, if you want the in-app experience of doing this business processes within Excel my recommendation will be to implement an Excel Add-in using Office.js.  if you want to do this separate from Excel (i.e. like in a backend document automation) then you should do OOXML SDK.
