### ISSUE TITLE
Outlook API 1.3 version not showing on Outlook Desktop Professional Plus 2016

### ISSUE THREAD

**Issue by bohap** [OfficeDev/office-js#75]
Hello
On this page https://github.com/OfficeDev/office-js-docs/blob/master/reference/outlook/tutorial-api-requirement-sets.md it is specified that both Outlook 2016 (MSI) for Windows and Outlook 2013 for Windows support Outlook API up to Version 1.4, but when we try to increase the minimal version in the manifest from 1.1 to 1.3, the addin works fine on web but does not show on both desktop versions. 

Currently I am working on Outlook Professional Plus 2016 with build number 16.0.4312.100, 64bit on Windows 10.

I am trying a simple addin generated by yeoman office-generator, with only change is the minimal version from 1.1 to 1.3

Thanks.

**Comment by maxpaj** [comment]
I'm in a similar situation.

I have a customer who wants to use our addin in their Outlook. They run an Exchange Server 2013 solution and can install addins through Exchange Admin Center. But when they try to install our addin it says:

> The API version (1.3) required by this app isn't supported by the Exchange Server version (15.0.1236.3) that you're connecting to

The version number indicates that they are using Exchange Server 2013 CU14.

I've dug through loads and loads of documentation to try to find version of Exchange they need in order to install it. It says in some places that they need Exchange 2013 or later to run addins - which they have. But what about this specific API version?

**Comment by kbrandl** [comment]
@exextoc -- just a heads-up that this issue has been assigned to you for investigation. Also FYI, other related posts can be found here:

- https://github.com/OfficeDev/office-js-docs/issues/1371
- https://stackoverflow.com/questions/49667055/microsoft-office-javascript-add-in-platform-compability

**Comment by maxpaj** [comment]
@kbrandl is this a confirmed issue?

Check out my comment on the other thread please: https://github.com/OfficeDev/office-js-docs/issues/1371#issuecomment-379670841

**Comment by kbrandl** [comment]
@maxpaj I unfortunately am not a subject matter expert in Outlook add-ins; I've assigned @exextoc to this issue, as they should be able to provide feedback.

**Comment by bohap** [comment]
Is there any progress to this issue?

**Comment by exextoc** [comment]
@bohap can you provide a sample manifest, that we can test? 

Are you using version overrides in your manifest? If so there was a bug where if the Version Overrides supported a higher API set version than supported by the base client, then it would not fall back to older version overrides sections that were supported. (the version mentioned in your original post did not have this fix). This fix only affected 2016 MSI, not 2013 MSI or currently Office365 / C2R versions. 

The fix is here: 
https://support.microsoft.com/en-us/help/4018369/may-1-2018-update-for-office-2016-kb4018369

(but upgrading to the latest 2016 MSI bits would ensure you are on the latest product)

**Comment by bohap** [comment]
@exextoc updating to the latest Office build fixed the problem.
Thanks.
