### ISSUE TITLE
[Content Addin]On saveAsync(callback) call, settings property bag is persisted but API's status reports not succeeded

### ISSUE THREAD

**Issue by sajsarka** [OfficeDev/office-js#761]
## Expected Behavior
API should never report failure if data is persisted.

## Current Behavior

API call successfully persists settings property but gives error in async result.
ErrorCode : 5001
ErrorMessage : An internal error has occurred

## Steps to Reproduce, or Live Example
This is intermittent in nature.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Excel Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: (x-officeversion: 16.0.12204.31875)

**Comment by XiangGaoMSFT** [comment]
Thanks for reporting it to us.
I tried to reproduce it but failed. Could you provide more details?
* Sample code which can reproduce this issue. We suggest to create a snippet by ScriptLab and [share it to us](https://github.com/OfficeDev/script-lab/blob/master/README.md#import).
* Session ID. Please reproduce this issue in Excel Online and provide the Session ID to us. You can find the Session ID from File -> About -> Session ID.

**Comment by ravikmrsingh8** [comment]
Hi @XiangGaoMSFT 
We got the  Excel Online Session ID where this issue was reproduced. 
**Session ID "03592158-e2a6-4f6e-8ca7-153abf5c31e8"**

Following error we get in AsyncResult:  Error Code: 5004Error Message: Invalid API call in the current context.Error Name: Invalid API Call

We donot have consistent repro, This settings.saveAsync() function fails in both PC and XLO intermittently.

**Comment by ravikmrsingh8** [comment]
Another Excel Online Session with issue
041ea613-09f5-4ac8-a3ab-f4cd0b83f135

**Comment by XiangGaoMSFT** [comment]
@ravikmrsingh8 , I checked the log but didn't find much useful info. But it could be caused by data validation as I saw some data validation failures. Could you provide more info like
* Does the workbook contain data validation?
* Could you try to simplify your code/workbook to figure out a way that can reproduce it?

**Comment by ravikmrsingh8** [comment]
Another Excel Session ID
7c0c7846-659e-498a-a0c0-023eeed6a7d5

**Comment by ravikmrsingh8** [comment]
Hi @XiangGaoMSFT ,
We have data validation rules added in code but we have done the error handling. after validation rules are added we have context.sync() method inside try catch block which did not throw any error.

The code to save office settings is below, but it didnot fail always, in our telemetry log we see that the error is reported in  2-3% of all the sessions we  have.   
<pre><code>
public static async saveSettings(): Promise < any > {
	return new Promise(function (resolve, reject) {
		Office.context.document.settings.saveAsync(function (asyncResult: any) {
			if (asyncResult.status == Office.AsyncResultStatus.Succeeded) {
				// Add log statement and remove console logs
				console.log("OfficeAPIWrapper:saveSettings:Office settings saved");
				resolve(asyncResult);
			} else {
				console.log("Metadata save failed Error Code: " + asyncResult.error.code + "Error Message: " + asyncResult.error.message + "Error Name: " + asyncResult.error.name);
				reject(asyncResult.error);
			}
		});
	});
}</code></pre>

**Comment by ravikmrsingh8** [comment]
Excel Session ID having issue
ed4ac56d-0bf2-409a-8431-08b305feb90e

**Comment by ravikmrsingh8** [comment]
@XiangGaoMSFT  Another Excel online Session Where save Settings failed 
"d3bc8d3b-9389-4822-b881-0cc4449dba10"

**Comment by XiangGaoMSFT** [comment]
@ravikmrsingh8 , thanks for providing the session ids. I checked the new sessions you provided but still didn't see any failures related to settings.saveAsync.

Since you don't have a consistent repro, I may still need your help to identify the root cause.

It seems saveAsync would report different errors, but actually the settings are persisted. Am I right?

When you hit error in XLO next time
* Could you clarify the error code since you mentioned two errors before?
* Could you provide the UTC time of the error, so we can narrow down the related logs?
* Could you provide the Fiddler/Chrome trace when you hit the error?

**Comment by ravikmrsingh8** [comment]
Hi @XiangGaoMSFT 
We get two type of errors in log.
[2019-10-24T11:26:59.411Z] Metadata save failed Error Code: 5004Error Message: Invalid API call in the current context.Error Name: Invalid API Call
[2019-10-24T15:02:20.744Z] Metadata save failed Error Code: 5001Error Message: An internal error has occurred.Error Name: Internal Error
 
We are also not sure whether the settings are actually saved even if API throws the error.

**Comment by XiangGaoMSFT** [comment]
@ravikmrsingh8 , the log you provided is helpful since they clarifies the time and the error code. One more question, is it UTC time?
When you hit the failures next time, please attach them with XLO session id.

Due to Microsoft's privacy policy, we may not have full logs for some sessions. So it would be helpful if you could provide multiple sessions.

**Comment by XiangGaoMSFT** [comment]
Remove tags so customer could have more time to get logs.

**Comment by ravikmrsingh8** [comment]
Hi @XiangGaoMSFT 

Excel Online Session(Edge Dev browser) 
e29586d3-adb5-44d6-818a-ff8d47e16910

Below error log we got in the Addin session, 
[2019-10-29T09:02:04.972Z] Metadata save failed Error Code: 5004Error Message: Invalid API call in the current context.Error Name: Invalid API Call
Time mentioned in above log is UTC time.

**Comment by ravikmrsingh8** [comment]
Excel Session ID 
376a5f3b-ba5f-4323-91a8-22f74c5e0237
Build 16.0.12228.35900
Browser : Chrome 77.0.3865.120 (Official Build) (64-bit)
Addin log[2019-10-29T09:32:51.965Z] Metadata save failed Error Code: 5004Error Message: Invalid API call in the current context.Error Name: Invalid API Call

**Comment by XiangGaoMSFT** [comment]
@ravikmrsingh8 , the two Invalid API call errors could be caused by cell edit mode. We forbid API call explicitly when user enters cell edit mode (i.e. user inputs in formula bar or in a cell).

 I've logged an internal task 3748104 to provide more explicit error message for it.

For Excel APIs, you can [use the `delayForCellEdit` option to delay API call until user exits from cell edit mode](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-core-concepts#excelrun).
For Common APIs, we don't support the `delayForCellEdit` option. You may need to handle this error specifically, like showing an error message to your user and ask them to retry after exit from cell edit mode.

**Comment by XiangGaoMSFT** [comment]
Please let me know when you get XLO session IDs which are related to Error 5001.
