### ISSUE TITLE
Log files for OnSend events are lost

### ISSUE THREAD

**Issue by adam-harwood** [OfficeDev/office-js#802]
If an addin logs an error message to the console during an OnSend event, then there is no way to retrieve these logs from Outlook desktop

## Expected Behavior
The log messages for OnSend events running on Outlook desktop should be somehow retrievable, so that issues can be debugged.

## Current Behavior
The console logs are lost when the OnSend event completes, since the instance of the add-in is killed.

## Steps to Reproduce, or Live Example
1. Write an addin that uses `console.log` as part of it's OnSend event handler.
2. Send an email from Outlook Desktop with this addin enabled
3. You will have no way of retrieving those log messages.

## Context
We have an addin that asynchronously sends some information to our server on email send (with the user's consent). We have an intermittent issue where the information fails to transmit. We cannot get the helpful information in the log files, because our users have no way of accessing them.

## Your Environment
Outlook Desktop, monthly update channel.

**Comment by exextoc** [comment]
@adam-harwood If you have the code for the add-in that you are running, you should be able to add a `debugger;` statement before the add-in exits so that you can inspect the console, get what you need and then allow the add-in to continue running and exit. Can you try that to see if it works?

**Comment by adam-harwood** [comment]
Not sure if you understand the issue: these are my end-customers using the add-in who are experiencing issues. I can't really ask them to allow a debugger to continue running, they're not technical. 

I'd like to be able to provide them with something like a button they can click which captures diagnostic information (most crucially the logs) and then email it to me. So I just need some way to be able to read the log files for the OnSend events. I feel this is going to become a pretty widespread need once more people use OnSend events with Office JS add-ins. I can understand why you sandbox the add-in for OnSend, but providing no way for a customer to send the log files generated makes them near impossible to debug without replication steps.

**Comment by exextoc** [comment]
There are currently no logging-specific APIs in Office.js.

One way to communicate errors to the user in Outlook is through the [notificationMessages API](https://docs.microsoft.com/en-us/javascript/api/outlook/office.item?view=outlook-js-1.8#notificationmessages), but this API will only display short messages to the user.

I would also normally suggest sending diagnostics information to a backend service, but you mentioned the add-in is already sending information to a service and this is what's failing.

In case the failure is a network error, and since the error occurs on a customer's machine, it may be helpful to collect a Fiddler trace from the customer since the error available to the browser may not contain all of the relevant information about the failure.

Even though an OnSend add-in command can run without UI, there are some ways an OnSend add-in can communicate information to the user. Here are some suggestions:

- For short errors, the notificationsMessages API.
- OnSend add-ins can show a dialog with the [displayDialog API](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins). This dialog is another webpage, so it can show any information that you wish.
- If your add-in also has a task pane command, it could save information in the browser and then show it in the task pane (but a user would have to know to launch the task pane after a failure).
- You could open a dialog to allow the user to email you diagnostics information. This email could be pre-populated with the information. This is most easily accomplished with the [displayNewMessageForm API](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.8/office.context.mailbox#displaynewmessageformparameters).

If you would like to suggest a new API to help with this scenario, please [open a suggestion](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback) in the Office Developer UserVoice, or add to [an existing suggestion](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/10693698-add-the-ability-for-an-office-add-in-to-persist-di).

**Comment by adam-harwood** [comment]
Thank you! Your third suggestion, around using localStorage, is a great idea and has solved the problem for me.

For reference for others, we already have a centralised logging class which all of our logs go through. They are logged using `console.log`, but also the last 100 are kept in memory. There's a button users can click to view those last 100 and send it to us for diagnosis. With the above suggestion, I've enhanced it to persist the last 10 error messages to browser storage (using `window.localStorage` specifically). This persists across sessions, and can be used to transmit messages from OnSend to a regular task pane, where a user can view them. A little more work than expected, but works well.
