### ISSUE TITLE
event type for global event for functions file for typescript

### ISSUE THREAD

**Issue by daniel-white** [OfficeDev/office-js#81]
There doesn't seem to be a typing for function file's global `Event` that has the `completed` method. Here's the object: https://github.com/OfficeDev/office-js-docs/blob/master/reference/shared/event.completed.md

```
function doSomething(e: ???) {
    e.completed();
}
```

## Expected Behavior
That I would be able to give `e` a type for TypeScript.

## Current Behavior
I'm not sure what to give typescript.

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Context
It would be great if I could keep this event in typescript land other than using `any`.

## Your Environment
N/A.

**Comment by michahell** [comment]
indeed. @daniel-white how we solved this:
```
export interface OnSendEvent {
  source: {
    id: any
  };
  completed: (args: { allowEvent: boolean }) => {};
}
```

**Comment by JuaneloJuanelo** [comment]
@daniel-white  : is this issue solved? can we close it?
@exextoc : can you please follow up to closure?

**Comment by exextoc** [comment]
The definition you provide is a working definition that should be suffice for `ItemSend` event. The `id` is a string that represents the name of the control in the manifest and the completed function definition looks right.

We have not updated our typings for this API yet because the API is still in Preview. We will look into updating our typings soon.
