### ISSUE TITLE
Word: insertHTML on Windows inserts space for trailing newline

### ISSUE THREAD

**Issue by htryggva** [OfficeDev/office-js#827]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When inserting html like this:

```
insertHTML('some text\n', 'replace')
```

then Word for Windows will insert it like this:

```
'some text ' // notice the trailing space
```

## Expected Behavior
Word should not replace the newline character with a space:

```
'some text'
```

**Note**: This is the behavior on Word on the web.

## Current Behavior
It appears that Word on Windows replaces all newlines with a space, without trimming the value first. 

## Live Example
[Script Lab Gist](https://gist.github.com/htryggva/35f189ce3340581a69fd79777f9aa8eb)

## Context
Users of our add-in define themselves the HTML that should be inserted. The inconsistency between Word on the web and Word for Windows is confusing to them.

## Your Environment

* Platform: PC desktop
* Host: Word
* Office version number: Version 1910 (Build 12130.20272)
* Operating System: Windows

**Comment by mscharlock** [comment]
Hi @weshi - this may be something you can address?. @htryggva I think you may also want to put this on UserVoice, which is where we track requests from customers about features. This strikes me as a bug, which is why I have assigned someone but if it is an intentional choice, this feedback would be great to get on the User Voice site. You can do that on our [UserVoice page](https://officespdev.uservoice.com/). Also thank you for your patience, Microsoft had a major conference this week so responses have been somewhat delayed. Thanks!

**Comment by weshi** [comment]
@shaofengzhu The post says the platform is Word for PC desktop.

**Comment by MartinSSeifert** [comment]
@weshi This is an inconsistency in using insertHTML('some text\n', 'replace') between **Word for the Browser** and **Word for Windows**. In this case, we believe **Word for the Browser is doing it correctly** and Word for Windows has a bug and is doing it incorrectly. For solutions to work cross-platform we need consistency across all hosts!

**Comment by AbidRahman-MSFT** [comment]
Internally tracking the issue with 4818602. Will provide an update as soon as we know more. Thanks for the patience.
