### ISSUE TITLE
getEntitiesByType function is undefined

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#835]
when i use the example:
`
var item = Office.context.mailbox.item;
var urls = item.getEntitiesByType(Office.MailboxEnums.EntityType.Url);
`
i found that: the getEntitiesByType function is undefined

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8297edd-d7f5-e490-fec8-b7f478eab4d5
* Version Independent ID: b828821a-2bc7-9da4-ab3e-769f2e033bf3
* Content: [Office.Entities interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.entities?view=outlook-js-preview)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.entities.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.entities.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
Which Outlook client are you testing with?

Is your add-in running in Read mode or Compose mode? (The API is only defined in Read mode).

**Comment by hello-chenchen** [comment]
Hi @exextoc , thanks for your reply.
I am using chrome browser in my add-on iframe js context environment.
I am running in Compose mode.
```
<FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:8081/schedule"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>

  <Permissions>ReadWriteItem</Permissions> 
  <Rule xsi:type="RuleCollection" Mode="Or">
  <Rule xsi:type="ItemIs" ItemType="Message" FormType="Edit" />
  <Rule xsi:type="ItemIs" ItemType="Appointment" FormType="Edit" />
  <Rule xsi:type="ItemHasKnownEntity" EntityType="MeetingSuggestion" />
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>
```

But actually, i change **<Rule xsi:type="ItemIs" ItemType="Appointment" FormType="Edit" />** to **FormType="Read"** But it is still not worked.

Can you give me some suggestion about the Read mode in mainfast.xml? Or some worked exapmle?
Thanks~

**Comment by exextoc** [comment]
The undefined error is expected in Compose mode because the API is only defined in Read mode.

Compose mode is when the user is composing a new email or editing a draft in Outlook. Read mode is when the user is reading a message that was sent to them. The add-in will only appear in the modes it's defined to run in, and you can use a different `SourceLocation` URL to distinguish between the two modes.

For more information, see [Create Outlook add-ins for read forms](https://docs.microsoft.com/en-us/outlook/add-ins/read-scenario) and [Create Outlook add-ins for compose forms](https://docs.microsoft.com/en-us/outlook/add-ins/compose-scenario).

Since you mentioned testing with Chrome, do you know which version of Exchange is hosting the mailbox you are testing with? Or is it a mailbox in Office 365?

In your manifest, your contextual activation rules are defined in the base part of the manifest. For new add-ins, we also recommend defining the rules in a [DetectedEntity extension point](https://docs.microsoft.com/en-us/outlook/add-ins/contextual-outlook-add-ins) in the VersionOverridesV1_1 section of the manifest. If you are testing with OWA in Office 365, this may be required for the contextual entry point to appear. Or, are you launching the add-in through a different extension point, like a task pane?

**Comment by hello-chenchen** [comment]
Hi @exextoc , thank you so much for your explanation about the read mode.
Now i am sure that my add-on is on the compose mode.

So i have another question in the compose mode.
when i was in the compose mode, is there any way for developer to use the appointment api by sync way instead of async way.
For example:
sync way:
```
var start = Office.context.mailbox.item.start.getSync();
```
instead of the async way:
```
Office.context.mailbox.item.start.getAsync( xxxxx).then(xxxxxx)
```
actually, some times, i  don't need to do any complex operation. i just want to get the start time in appointment. i think sync way is enough.(simple and intuitive).

But unfortunately, from the document, you and @ElizabethSamuel-MSFT 's  answer[why Office.context.mailbox.item.start.getAsync is async, can i get the start time for sync method?](https://github.com/OfficeDev/office-js-docs-pr/issues/1427#issuecomment-552404627). I think the result maybe is no.

Thanks~

**Comment by exextoc** [comment]
No, there is no synchronous equivalent for asynchronous APIs in compose mode.

**Comment by hello-chenchen** [comment]
All right. thanks
