### ISSUE TITLE
Loading multiple content control through loop creating nested relationship

### ISSUE THREAD

**Issue by biswanathc** [OfficeDev/office-js#866]
I created a project using Office js and word Api 1.3,which loads the Ooxml data of the content controls stored in database into the document. i am facing an issue while loading the Ooxml data which has content controls into document

for example: if i am loading 3 content controls into the document

my requirement is to load content controls one after another in the document like velow
![CC1](https://user-images.githubusercontent.com/43954679/69399877-c5123300-0d15-11ea-9d16-49fbddaf7126.png)

but it loads first content control and inside that second content control and inside that third content control

![cc2](https://user-images.githubusercontent.com/43954679/69399898-dce9b700-0d15-11ea-9d4b-d4030a7e7e8b.png)

Code used to store the Ooxml data of the content controls into Database:

        // Create a proxy object for the ConentControl body.
        var ConentControl = context.document.contentControls.getByTag('FirstControl').getFirst();

        // Queue a commmand to get the OOXML contents of the body.
        var OOXML = ConentControl.getOoxml(); 

i am storing this OOXML in Database as an xml field

Code used to retrieve

function GetTemplateData() {

    var apiurl = 'Service Url'

    $.ajax({
        url: apiurl,
        type: 'GET',
        dataType: 'json',
        //contentType: 'application/json',
        //data: JSON.stringify(searchDetails),
        async: false,
        success: function (data) {
            $.each(data, function (index, element) {
                var ControlName = element.ControlName;
                var ControlContent = element.ContentData;
                InsertOoxml(ControlName, ControlContent);

            });

        },
        error: function (d) {
            write("Error please try again");
        }
    });
}

function InsertOoxml(ControlName, ControlContent) {
    Word.run(function (context) {

        // Create a proxy object for the content controls collection that contains a specific tag.
        currentOOXML = ControlContent;
        if (currentOOXML != "" && currentOOXML != null) {
            // Create a proxy object for the document body.
            var DocBody = context.document.body;

            // Queue a commmand to insert OOXML in to the beginning of the body.
            DocBody.insertOoxml(currentOOXML, Word.InsertLocation.end);

            // Synchronize the document state by executing the queued commands, 
            // and return a promise to indicate task completion.
            return context.sync().then(function () {

                // Tell the user we succeeded and then clear the message after a 2 second delay
                report.innerText = "Section Loaded succeeded!";
                setTimeout(function () {
                    report.innerText = "";
                }, 2000);
            });
        }
        else {
            return context.sync().then(function () {

                // Tell the user we succeeded and then clear the message after a 2 second delay
                report.innerText = 'Data not available for the control in Database.';
                setTimeout(function () {
                    report.innerText = "";
                }, 2000);
            });
        }
    })
        .catch(function (error) {
            console.log('Error: ' + JSON.stringify(error));
            if (error instanceof OfficeExtension.Error) {
                console.log('Debug info: ' + JSON.stringify(error.debugInfo));
            }
        });
}

Please suggest what is the issue that is causing nesting content control instead of loading one after other.

**Comment by yihuax-zz** [comment]
You need to reload DocBody, since after you insert each content control, the body needs to be updated.

**Comment by biswanathc** [comment]
@yihuax  Could you please share a code snipped on how do I do that? I am writting the entire load logic under initial load function only.

Also, isn't it possible to move the cursor out of content control followed by a vertical space? There will be many content controls to be loaded during initialization and after every load, refreshing body will slow down the entire initialization.

Please suggest

**Comment by yihuax-zz** [comment]
Suppose you already have a content control in Word, you can run the following code and it adds three more copies of the content control at the end of the file, and they are not nested:
Word.run(function (ctx) {
    var ooxml = ctx.document.body.contentControls.getFirst().getOoxml();
    return ctx.sync().then( function() {
        for (var i = 0; i < 3; i++) {
            ctx.document.body.insertOoxml(ooxml.value, "End");
        }
        return ctx.sync();
    });
}).catch(function (error) {
	console.log("Error = " + error.message + JSON.stringify(error));
});

**Comment by JuaneloJuanelo** [comment]
hello @biswanathc , this is an interesting case, and to some degree what you are experiencing is by design, let me explain.

The key to understand this problem is how the insertLocation parameter works. There are 5 options: replace (self-explanatory), start/end and before/after.  Start/End will insert content within the boundaries of the object, whereas before/after insert content outside the boundaries of the object.
To complicate a bit, not all objects support before/after, thats the case of the body object.

So, basically what happens here is that you are inserting the OOXML using body.insertOoxml("ooxml", "end") , so the first insertOoxml will insert the OOXML within the boundaries of the body, thats why subsequent inserts with "end" insertLocation will be inserted within the boundaries of the previous content control, thats why you end up with concatenated content controls.

One approach you can do to insert one content control AFTER the previous one is  to insert paragraphs and then replace each paragraph with your OOXMLs, this sample extracts such concept:

```
async function run() {
  await Word.run(async (context) => {
    const body = context.document.body;

    console.log("Your code goes here");
    for(var i=0;i<3;i++){
     var par = context.document.body.insertParagraph("text", "end");
     par.insertContentControl();
     await context.sync();
    }
  });
}
```
The above code is inserting 3 paragraphs each of them with a content control, please follow that approach and you will enable your scenario. Note that for your scenario you will have to use "replace" for each paragraph (i.e. paragraph.insertOoxml("your ooxml", "replace").

Let us know outcomes.

**Comment by biswanathc** [comment]
@yihuax  @JuaneloJuanelo  Thanks both!! Worked like a charm!
