### ISSUE TITLE
Single signon from Office addin not working with edge viewer

### ISSUE THREAD

**Issue by nsakar** [OfficeDev/office-js#867]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
We expect our excel addin built using angular 2 and tested on office 1908 and windows 1809 where the webviewer is IE 11 to work seamlessly on Edge on windows 1903

## Current Behavior
Single signon is not working in localhost
Windows integrated authentication is failing when hosting apps on IIS web sites
We need windows authentication to work seamlessly just like in IE11 for the excel apps

## Steps to Reproduce, or Live Example
Create an Excel addin using angular 2 and host it on IIS with windows integrated authentication
Launch it from a windows 1903 /Office 1908 client

Edge viewer is unable to connect and fiddler reports  401 windows integrated authentication failure

## Context
I am almost about to deploy my apps to production. We developed it on windows 1809 with office 1908 and now we are upgrading to windows 1903 and all hell has broken loose
## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: _PC destop_____
* Host [Excel, Word, PowerPoint, etc.]: ____Excel__
* Office version number: _____1908_
* Operating System: ___windows 1903___
* Browser (if using Office Online): __Microsoft edge____

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by DC959** [comment]
Having the same issue here, not entirely sure if circumstances are the exact same, but sounds similar.

Using dialog api in outlook, IE 11 webview would happily use the integrated authentication to log into an azure sso application using the correct url, but in edge webviewer the page tries to redirect to the sign in screen instead of using integrated authentication causing the add in to not sign in and redirect to the correct page.

All browsers (Edge, Edge Chromium, Chrome, Firefox, IE) all log in fine using outlook online and the same code, only Edge webview within an add in can't log in with integrated authentication.

Operating System: windows 1909
Office version number: 1908
Host [Excel, Word, PowerPoint, etc.]: Outlook
Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
