### ISSUE TITLE
[Excel] Activating XLL UDF compatibility removes or alters custom functions, namespaces and names

### ISSUE THREAD

**Issue by SWDevB** [OfficeDev/office-js#877]
Currently I want to activate XLL UDF compatibility in my Excel Office-Add-In. When I add the respective area in the manifest file (even with not matching identifiers for the XLL to use) the functions provided by auto completion are removed, renamed or have their namespace removed.

## Expected Behavior
I would expect, that the functions are either the same or if some conventions or technical issues prevent that, I would prefer an error message, failing validation or anything like that to learn about these issues.

## Current Behavior
So if I create a new Excel custom funtions project and debug it in Excel desktop, there are the default functions listed for the namespace CONTOSO.
If I now add a (not even matching) equivalent add ins section in the manifest, the functions are completely gone. This might be the case because they use features not available in XLL compatible custom functions.

But if I replace the functions in functions.ts by some simple ones there are two things happening.

1. If I provided a namespace in the manifest, the namespace isn't used for the functions any more
2. If a function contains a dot/period it is replaced by an underscore. So this renaming is a problem since multiple namespaces are only possible when included in the names

Is this expected behavior or a bug?

So for me it looks like XLL compatible custom functions don't support namespaces and have certain restrictions regarding the names of the functions.

## Steps to Reproduce 
1. Create a new Excel custom functions project (ts) via yo office 
2. Debug it -> functions available and have the namespace
3. Add below listed EquivalentAddins snippet before closing of VersionOverrides to the manifest file
4. Debug it -> functions not available
5. Replace functions.ts by below listed snippet
6. Debug it -> functions available without namespace and underscores
7. Remove EquivalentAddins from the manifest
8. Debug it -> functions available with namespaces and unchanged name

**Manifest change**
```
    <EquivalentAddins>
      <EquivalentAddin>
        <ProgId>willnotmatch</ProgId>
        <Type>COM</Type>
      </EquivalentAddin>
      <EquivalentAddin>
        <FileName>willnotmatch.xll</FileName>
        <Type>XLL</Type>
      </EquivalentAddin>
    </EquivalentAddins>
```
**Alternative functions.ts**
```
/** 
 * Get func1
 * @customfunction CONTOSO.FUNC1
 * @param p1 param 1
 * @param p2 param 2
 * @returns result
 */
function func1(p1: string, p2: string) {
  return `you called MYNS.FUNC1(${p1}, ${p2})`;
}

CustomFunctions.associate("MYNS.FUNC1", func1);

/** 
 * Get func2
 * @customfunction FUNC2
 * @param p1 param 1
 * @param p2 param 2
 * @returns result
 */
function func2(p1: string, p2: string) {
  return `you called FUNC2(${p1}, ${p2})`;
}

CustomFunctions.associate("FUNC2", func1);
```

## Context
We already have a COM add-in which provides custom functions. We would like to become compatible, this existing add-in has functions with and without namespaces (realized via name by descriptor)

## Your Environment
Platform: PC
Host: Excel
Office version number: 365 ProPlus, 1906 (Build 11727.20210 Click-to-Run)
Operating System: Windows 10 Enterprise 10.0.18362

**Comment by zakhan4** [comment]
Hello,
I face the same issue and my configuration is:

Platform: PC
Host: Excel
Office version number: 365 ProPlus, 1912 (Build 12307.20000 Click-to-Run)
Operating System: Windows 10 Enterprise 10.0.18362

**Comment by xiaochunms** [comment]
@SWDevB your steps are valid. And in general, the current behavior of custom function XLL compatible is by design. Prior to custom functions, XLL runs well in Excel on Windows. You may notice XLL runs without namespace, which is the convention for XLL in Excel. No namespace for XLL compatible custom function follows the same convention. The design as such is not to break the conventions that XLL user is used to. Hope it can answer your questions.

**Comment by SWDevB** [comment]
Thanks for your reply, so if compatibility is declared in the manifest:

- If there is a namespace, it is removed
- If there are not supported characters in the function names they are replaced by underscores

An additional issue regarding this is: When I add the yo office example function increment back in the functions.ts, all functions are gone. That's the case because XLL compatible functions don't support streaming?  Is there a way to exclude a function from the compatibility declaration?

**Comment by SWDevB** [comment]
An additional question I would like to ask regarding this issue.

We have an Add-In which implements custom functions by using Add-In-Express' ADXXLLModule and we were able to create custom functions having a dot in their names and so having kind of a namespace. 

As you wrote, XLL doesn't support this. Of course Add-In-Express isn't your problem and I don't know how they managed to do that, but from your perspective there is no way to give XLL functions such names in a valid way and that's why you think it's the best solution replacing the dots?

**Comment by xiaochunms** [comment]
Thanks for your questions. Please let me list all questions below to make sure each one can be addressed well.
1. Namespace for XLL compatible mode,
2. Not supported characters in the function names,  
3. When I add the yo office example function increment back in the functions.ts, all functions are gone. That's the case because XLL compatible functions don't support streaming?
4. Add-In-Express's ADXXLLModule having a dot in their names, which is a kind of a namespace, what's the solution.

May you please check the list above to cover all your questions? #1 I explained the reason why namespace disappears in CF XLL compatible mode. 

Sorry I missed to answer #2 in my last reply, i.e. #If a function contains a dot/period it is replaced by an underscore. So this renaming is a problem since multiple namespaces are only possible when included in the names#. Suppose the functions are XLL functions, not CF defined ones in function.ts, right? I think #2 can be combined with #4 together. It would be very helpful if you can share ADXXLLModule which has a dot in their names and I can try at my side and get back to you.

Regarding to #3, may you please explain further on "all functions are gone"? Does that mean functions defined in functions.ts cannot be executed any more or other effects?  And may you please explain further what makes you think "all functions are gone" and "That's the case because XLL compatible functions don't support streaming?" are related?

**Comment by SWDevB** [comment]
Thanks for your reply. It seems all issues are tackled right now.

#3 This is about my Step 4 of the initial steps to reproduce. None of the defined functions is available in Excel any more, after `increment `is added while XLL equivalent is configured. That for me makes it impossible to provide this function for example in a XLL compatible. So is it possible to provide an add-in which contains XLL compatible functions and pure Excel add-in custom function? This seem to be a pretty normal use case, provide a add-in using new technology, stay compatible to existing functions and customer files, but of course provide additional functionality (where compatibility isn't needed)

#4 Can you provide an email or any way to not publicly provide the requested files?

**Comment by xiaochunms** [comment]
Thanks for your explanation. You really raised valid comments and provided good practices for XLL compatible. Thank you! 

May you please drop the file to my private mailbox: xcliang72@yahoo.com? I'll get back to you once I do some tries.

**Comment by xiaochunms** [comment]
@SWDevB you may can contact with me via xiliang@microsoft.com too. I am sorry for any confusion for you with my private mailbox.
