### ISSUE TITLE
Calling Range.expandTo followed by Range.search inserts unexpected OBJ characters

### ISSUE THREAD

**Issue by dtao** [OfficeDev/office-js#899]
I have a Word add-in that stores a list of defined terms in a document along with paragraph ranges where those terms are found. One of the features I'm trying to implement is selecting the range where a term is defined. The code supporting this feature in its current form calls `Range.expandTo` to select the full range comprising a particular _section_ of the document, then calls `Range.search` on the resulting range to find the occurrence of the term, and finally calls `Range.select` to select the search result as a way of highlighting it.

## Expected Behavior
The document should scroll to the target range, with the term selected, without making any modifications to the document.

## Current Behavior
I do see the expected behavior, except that the document appears to be modified: I see that some unexpected OBJ characters appear both before the paragraph and around the selection:

<img width="609" alt="Screen Shot 2019-12-15 at 10 55 31 AM" src="https://user-images.githubusercontent.com/409328/70866073-ad038d00-1f2a-11ea-89a7-70b05a98ddc4.png">

## Steps to Reproduce, or Live Example
Unfortunately I am not currently able to produce a minimal example demonstrating this problem in ScriptLab. I'll work on that and update this issue if/when I am able to do that.

## Context
Explained above.

## Your Environment

* Platform: Mac, Office Online
* Host: Word
* Operating System: macOS 10.14.6 (Mojave)
* Browser (if using Office Online): Firefox

**Comment by JuaneloJuanelo** [comment]
@dtao Thank you very much for taking the time to send us this issue.  I wrote a code snippet that implements what you are describing (basically a search within an expanded range.), please see the snippet [here](https://gist.github.com/JuaneloJuanelo/0bafab8f408f9e9516eb59d1612954e9).  that snippet basically expands from the selection till the end of the document and tries to find the word "hello". (so if you want to try it, just make sure you are using a document who has this text and you make a selection before it :)) 

And i was not able to repro your issue in Online. 

We have, however,  a similar case reported [here](https://social.msdn.microsoft.com/Forums/office/en-US/d2f3dd66-b3ef-4db2-b032-49e9f4851c2a/obj-characters-get-inserted-in-a-document-having-tracked-changes-on?forum=worddev). long time ago. In order to repro that issue you need to be working with a document having track changes active. (basically creating a document in windows, enable track changes, then upload to one drive, open in Online and run the code).

So, question for you: Are you having this issue in a "Track Changes" context?

If so, this is a known issue and we have a bug tracking.


Otherwise please send a script lab snippet and concrete repro steps.

Thank you!
