### ISSUE TITLE
Outlook Desktop: getAttachmentContentAsync "5000 the operation is not supported"

### ISSUE THREAD

**Issue by rsalehi2013** [OfficeDev/office-js#909]
## Expected Behavior
Office.context.mailbox.item.getAttachmentContentAsync() executes the passed in callback function with the attachment contents

## Current Behavior
Office.context.mailbox.item.getAttachmentContentAsync executes the passed in callback function with an error of 5000 - the operation is not supported

## Steps to Reproduce, or Live Example
1. Take an Office outlook add-in that utilizes the getAttachmentContentAsync function to retrieve email attachment contents.
2. Execute the function while on OWA -> notice how it works properly
3. Execute the function on Outlook desktop 365 -> observe error

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop - windows 10
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 365 ProPlus Build 11328.20492
* Operating System: Windows 10
* Browser (if using Office Online): N/A

**Comment by JuaneloJuanelo** [comment]
Hello! The cited API was released as part of our 1.8 Release starting on the Office 365monthly sku released ~ early November 2019  (starting with build 16.0.12130.xxxx). 

The reason why its not available in your build is because you are on the Office Semi-Annual channel (who gets updates 2 times a year). So its not yet available for that sku, yet.

1.8 will be included in the next update to the Semi Annual Channel during the first semester of next year. 

thanks!

**Comment by rsalehi2013** [comment]
Thank you! I was not aware of the release channels, but have now located the documentation on it. Looks like the default channel for ProPlus is semi-annual, and this part of the API will be available Jan 2020 for those users?

**Comment by rsalehi2013** [comment]
on second look, it may be the case that November 2019 features wouldn't be included in the Jan 2020 update, but rather July 2020.
