### ISSUE TITLE
Issue with CustomeProperties get() 

### ISSUE THREAD

**Issue by ZinatWali** [OfficeDev/office-js#914]
I am using code based on this page:
 
function customPropsCallback(asyncResult) {
    var customProps = asyncResult.value;
    console.log(customProps);
    var myProp = customProps.get("myProp");
    console.log(myProp);
    customProps.set("otherProp", "value");
    customProps.saveAsync(saveCallback);
}

myProp is always coming as undefined. But customProps has the value previously stored in myProp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bae5b9e-dce2-82ce-2693-d61952ea0127
* Version Independent ID: 7f2296ec-40a4-7a0e-831c-e8343b438ddb
* Content: [Office.Item interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.item?view=outlook-js-preview#feedback)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.item.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.item.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc This seems to be a product bug. If you set myProp elsewhere then run the sample code, myProp comes back as undefined. Can you investigate?

[A similar code example in the docs](https://docs.microsoft.com/en-us/javascript/api/outlook/office.customproperties?view=outlook-js-preview#saveasync-callback--asynccontext-)

Thanks.

**Comment by exextoc** [comment]
Hey,

From the code snippet that you've provided, I can see that "myProp" is not being set or saved anywhere to the custom properties. Only "otherProp" is being set, and then saveAsync is being called. Are you setting `myProp` and then saving using  `saveAsync`, the value of myProp on doing a `loadCustomPropertiesAsync` after it still returns nothing for myProp when you call it?

Just making sure some points are ticked when dealing with custom properties.
1. That you're doing a `loadCustomPropertiesAsync` and the API returns success before you use a custom property.
2. That you're doing a `saveAsync` after setting any new custom property.
3. That you're trying to retrieve custom properties for the same email/calendar item that you've saved the properties for, since custom properties are specific to items.

Do tell me if you're still facing issues, and on which Outlook client (Web, Mac, Win32, etc) you're facing it on.
