### ISSUE TITLE
Potential issue with missing Outlook attachments

### ISSUE THREAD

**Issue by mlafleur** [OfficeDev/office-js#94]
Reported on Stack Overflow:  [Missing attachment from Outlook JS Api](https://stackoverflow.com/questions/49860461/missing-attachment-from-outlook-js-api)

It looks like Office.js is not returning certain attachments, specifically `.msi` files (although I expect this would include any "executable"  file type). While this makes sense from a safety and security standpoint, the API shouldn't actively mask the existence of any attachment.  

Ideally, the [`AttachmentDetails`](https://dev.office.com/reference/add-ins/outlook/1.5/simple-types.htm#attachmentdetails) object should include a flag if an attachment is blocked for some reason.

**Comment by exextoc** [comment]
Sorry this is by design we have updated our documentation here to reflect this: 

https://docs.microsoft.com/en-us/javascript/api/outlook_1_6/office.messageread?view=office-js

Certain types of files are blocked by Outlook due to potential security issues and are therefore not returned. For more information, see [Blocked attachments in Outlook](https://support.office.com/en-us/article/blocked-attachments-in-outlook-434752e1-02d3-4e90-9124-8b81e49a8519?ui=en-US&rs=en-US&ad=US).
