### ISSUE TITLE
Encrypt excel with password using office js

### ISSUE THREAD

**Issue by betheman** [OfficeDev/office-js#940]
I'm creating an Excel add-in using office js. I want to encrypt excel with a password using office js. I know how to do this using macro but I need to do this using office js only.

**Comment by erayc-msft** [comment]
Thanks for your question, however this forum is for issues with our product or documentation, not for programming questions about your code. We typically suggest going to [Stack Overflow](https://stackoverflow.com/questions/tagged/office-js) <change tag if appropriate> and see if your question has already been asked or ask a new question; and it looks like you've done so already.  

Thanks, Office Platform team

https://stackoverflow.com/questions/59784399/encrypt-microsoft-excel-with-password-using-office-js

**Comment by lumine2008** [comment]
Hello @betheman,  I am sorry office.js current do not provide the password protection in file level, because Excel Online does not support Password feature. When the workbook encrypted in win32, and Excel online cannot open it. So we will support after Excel Online support password feature.

You could submit your request in uservoice and upvote for this feature for Excel online at https://officespdev.uservoice.com/
