### ISSUE TITLE
The addin is not working when it is built to production mode. (developed using angular)

### ISSUE THREAD

**Issue by Vrushi007** [OfficeDev/office-js#944]
I have created a addin for outlook using angular. When I publish the project. The addin is not working.
Is there any problem with build process?

**Comment by exextoc** [comment]
I attempted to reproduce this, and in both localhost and in production, I never saw a `#` in the requested URL. This is because the `#` (or _fragment_) part of the URL is never included in a request to a web server and is only seen locally by the web client.

Once `taskpane.html` loaded, I also verified that `location.hash` in JavaScript returned the last part of the URL (i.e. `#cc/0`).

Could you check a network or Fiddler trace to verify that the web server is able to returned the requested page in both the local and production cases?

Is the `/` in your SourceLocation URLs in-between taskpane.html and `#cc/0` intentional? It's in both your localhost and production manifests, but I had to remove it in both cases to load taskpane.html.

**Comment by ragavanrajan** [comment]
Kindly confirm the Angular Version. So that we can able to assist you further

**Comment by Vrushi007** [comment]
Then angular version is ^8.0.0

**Comment by exextoc** [comment]
Were you able to check the Fiddler trace and the `/` in your SourceLocation URLs?
