### ISSUE TITLE
Text Content controls in tables are rendering as FieldRange instead of Content Controls

### ISSUE THREAD

**Issue by tpasi** [OfficeDev/office-js#950]
If a word document created using the desktop version of Word, contains a table with content controls in it, all of the content controls are no longer rendered as a content controls but rather as a field (gray disabled text).

Content controls outside of the table are rendering correctly.

## Expected Behavior
All of the content controls in the document should be rendered as content controls.

## Current Behavior
Cells with content controls are now rendered with a gray disabled text.

## Steps to Reproduce, or Live Example
[table with content control issue.docx](https://github.com/OfficeDev/office-js/files/4117434/table.with.content.control.issue.docx)

* Additional details:
  1. Insert a table 
  2. insert a rich text content control into one of the table's cells
  3. save.
  4. open the file in Word in browser 
  5.  observe that none of the content controls are editable as content controls.

## Context
We are trying to have templates with multiple content controls in it, and we wish to be able to use these templates on Word on browser and on mobile devices

## Your Environment

Windows.
Chrome Browser
Office 365.

**Comment by XiangGaoMSFT** [comment]
Hi @tpasi, thanks for reaching out.

It's a known behavior of Content Controls on Word for the web.
Please be noted that content control in table cell is not fully supported on Word for the web yet.

There are two kinds of content controls when you create them in table cell.

One is the content control containing the whole table cell, which is the ones you created in your document. They are not supported in Word for the web yet. That's why they are rendered as FieldRange.

The other one is the content control containing the content of table cell, rather than the table cell itself. They are supported in Word for the web and should work as you expected.

So as a workaround, you could
* Carefully select only the content rather than the whole cell, and then insert the content control
OR
* Open the document in desktop.
* Insert some text after content controls in table cell, and delete them.
* Then the content controls will only contain the content in table cell, and should work on Word for the web.

Below is the file created based on your document. It should work on Word for the web.
[ContentControlInTable.docx](https://github.com/OfficeDev/office-js/files/4157642/ContentControlInTable.docx)
