### ISSUE TITLE
Outlook add-in keeps cache even though last-modified header from CDN is updated

### ISSUE THREAD

**Issue by esegcy** [OfficeDev/office-js#953]
We store our html and javascript files on CloudFront CDN. When we update our code, we see that CloudFront successfully updates the `last-modified` HTTP response header, but nevertheless, at some occasions Outlook (on all device types) will show a blank page and only clearing cache would show the updated code.

## Expected Behavior
When we update our code, Outlook will show the most recent version and not a blank page.

## Steps to Reproduce
1. Deliver your add-in's HTML+javascript code from CloudFront CDN.
1. Update your code.
1. Test that cloudfront delivers the latest code with up-to-date HTTP response headers (specifically `last-modified`). Example of headers (please excuse my replacements with `<I_hid_this>`):
```
content-length: 1771813
content-type: application/javascript
date: Tue, 28 Jan 2020 14:01:29 GMT
etag: "34c30b36188c68a41d8e0ac4292d479d"
last-modified: Tue, 28 Jan 2020 13:55:03 GMT
server: AmazonS3
status: 200
via: 1.1 <I_hid_this>.cloudfront.net (CloudFront)
x-amz-cf-id: <I_hid_this>
x-amz-cf-pop: <I_hid_this>
x-cache: Miss from cloudfront
```
4. Launch Outlook on any device (tested on Windows, Mac, and outlook.office.com OWA) and show the add-in. *Sometimes* Outlook will not show the updated version, and instead show a blank screen!

## Context
Our add-in is updated frequently, so we need Outlook to show the most recent version. 

## Your Environment
* Platform: Tested on PC desktop Outlook, Mac Outlook, Android Outlook and Office Online Outlook
* Host: Outlook
* Office version number: latest on all platforms
* Operating System: latest on all platforms (except Android)
* Browser (if using Office Online): Chrome

**Comment by exextoc** [comment]
When the blank page is shown, are there any errors in the console? Does Outlook only show the blank page until the cache is manually cleared, or will the add-in eventually load after some time?

**Comment by esegcy** [comment]
No errors in console. 
The blank screen will be shown until clearing cache. It will not eventually load, even after retrying, closing apps completely, waiting more than an hour, and so on.

**Comment by exextoc** [comment]
Is your add-in reaching the correct pages when the blank page is displayed? One possible way to prevent files from being cached is to add the no-cache header.

**Comment by esegcy** [comment]
Yes to the question, and I will try the "no-cache" header and update here.

**Comment by exextoc** [comment]
Do you get the blank page if loading add-in in browsers?

**Comment by esegcy** [comment]
Yes, of course by "Office Online Outlook" I meant that it happens using browsers. Tested with Firefox & Chrome for Windows.

**Comment by exextoc** [comment]
To clarify the previous question, do you get a blank page after updating the CDN and then simply navigating to the SourceLocation/webpage of your add-in in a browser? So NOT using "Office Online Outlook", but simply copy/pasting your add-in's webpage into the address bar of a browser.

**Comment by esegcy** [comment]
No blank page when navigating directly in a browser to the url of SourceLocation/webapge.

**Comment by exextoc** [comment]
Try getting a fiddler/network trace to investigate any server errors. Look for the source url of your add-in and check the request is reaching the server as you expect.

**Comment by esegcy** [comment]
Ok, tried that now: everything seems to work okay and no server errors. I can now also update that the `no-cache` header was added and doesn't help either :(

**Comment by exextoc** [comment]
When you say everything seems to work okay, do you mean you no longer repro the issue?  Or are you still seeing the occasional blank add-ins?

Also, to confirm your use of no-cache, header, are you including the cache-control header in the http response?  https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

Outlook add-ins rely on browser caches and does not implement its cache.  Since you are seeing the blank page in your add-ins in Windows/Mac Outlook and OWA, it seems unlikely the cache behavior would cause a blank page.  Even when the cache is used, it would mean that an older version of your resource is loaded, and that should not result in a blank page.  Have you also tried to debug your addin and check that your addin is loaded correctly? https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-in-office-online

**Comment by lindalu-MSFT** [comment]
@esegcy Has this issue been resolved to your satisfaction?

**Comment by esegcy** [comment]
Hi @lindalu-MSFT,
Thanks for your reply. Actually the issue is not fixed after setting the `cache-control: no-cache` header.
As said, we don't experience issues when using the browser directly to go to the hosted address (in SourceLocation) so I'm not sure about @exextoc last suggestions regarding network issues. Plus we're talking about CloudFront CDN so I expect reaching it to be pretty flawless...
And of course it is unexpected that a networking issue will be resolved with clearing browser cache (which is what we do to resolve this issue when experienced).
So this is still pending resolution please.

**Comment by exextoc** [comment]
Sorry, it is a bit unclear what issue you are still facing. 

- Your Add-in is showing a *blank* page sometimes? Or is it showing out of date pages sometimes?

- This is happening Across all devices and clients. (Mac, Win32, iOS, and OWA (browsers). Version for Windows, and Office matters on Win32 due to your add-in will load in either IE or Edge.

- Clearing the Cache, fixes the issue. How are you clearing the cache on the native clients? 

- In general, across all clients the browser cache will be respected. So it's not unexpected that an older version of your file is loaded, until the cache naturally clears out. 

We are guessing this is a network/server issue because it's happening across all clients and platforms. At this point though, it may be helpful for you to look a Fiddler trace from a working scenario, and a Fiddler trace from a not working scenario, and compare the two to see if there are any differences.

**Comment by lindalu-MSFT** [comment]
@esegcy In Chrome, whenever I have cache issues, I type **CTRL + F5**. Alternatively, you can clear you cache manually from **More tools > Clear browsing data** (**CTRL + Shift + Del**).

**Comment by esegcy** [comment]
*Our* practice of clearing cache per env:
**IOS**: Settings app > Safari > Clear History and Website Data
**Android**: Settings app > Apps & notifications > Outlook > Storage & cache > Clear cache
**OWA with chrome**: as @lindalu-MSFT said exactly (important to say we choose the time frame to all-time).
**Win64** (no win32 available to test):
1. Open IE11
2. Click the tools gear wheel icon
3. Choose "Internet Options"
4. In the "General" tab in the "Browse history" section click "Delete..."
5. New window will open "Delete Browsing History"
6. Make sure "Cookies and website data" is marked
7. Click "Delete"

Checking with Fiddler, and I will update here.

**Comment by exextoc** [comment]
On Windows it is important to note that the [most recent builds](https://developer.microsoft.com/en-us/office/blogs/microsoft-edge-webview-for-office-add-ins/) will use Edge WebView. The only way to clear the cache there, is to do a Ctrl-F5 when the focus is on the taskpane.

**Comment by cody-lettau** [comment]
We are seeing this same issue. Our application is a React application built using webpack. The blank pane we see is likely because the HTML page is cached and it refers to JS files that no longer exist and therefore it cannot finish loading.

We have customers struggling to use our add-in due to this and it's a major issue. We have tried every way we could find in the documentation to clear caches. We can successfully clear caches for most users following one of the recommended ways to do so, but there are some users who it does not work for (i.e. CTRL + F5 does not work, they have no right-click > inspect -> clear caches via dev tools, etc).

We are adding metatags to our HTML pages to not be cached:

```
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
```

Are there other recommendations as to what we can do to mitigate this issue when we deploy updates (served by CDN)? This is a major issue that we cannot have occurring after each release of our add-in.

In addition, many of our users have the add-in installed via a Managed deployment, so there is no way they can remove the add-in and reinstall it or update the manifest to point at HTML file urls that contain hashes that change for each release. It is not feasible to have them deploy a new manifest every release since that can take 24 hours to propagate to all users (plus our customer service team has found that this does not solve the issue in some cases as the cache persists through re-install).

@exextoc @JuaneloJuanelo

**Comment by aldrashan** [comment]
> We are seeing this same issue. Our application is a React application built using webpack. The blank pane we see is likely because the HTML page is cached and it refers to JS files that no longer exist and therefore it cannot finish loading.
> 
> We have customers struggling to use our add-in due to this and it's a major issue. We have tried every way we could find in the documentation to clear caches. We can successfully clear caches for most users following one of the recommended ways to do so, but there are some users who it does not work for (i.e. CTRL + F5 does not work, they have no right-click > inspect -> clear caches via dev tools, etc).
> 
> We are adding metatags to our HTML pages to not be cached:
> 
> ```
> <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
> <meta http-equiv="Pragma" content="no-cache">
> <meta http-equiv="Expires" content="0">
> ```
> 
> Are there other recommendations as to what we can do to mitigate this issue when we deploy updates (served by CDN)? This is a major issue that we cannot have occurring after each release of our add-in.
> 
> In addition, many of our users have the add-in installed via a Managed deployment, so there is no way they can remove the add-in and reinstall it or update the manifest to point at HTML file urls that contain hashes that change for each release. It is not feasible to have them deploy a new manifest every release since that can take 24 hours to propagate to all users (plus our customer service team has found that this does not solve the issue in some cases as the cache persists through re-install).
> 
> @exextoc @JuaneloJuanelo

Same issue here. Added those metatags, old webpage still gets loaded from cache, new versions never get checked. Only way to get the new version is to ctrl + F5. This applies to content loaded in iframes inside your add-in as well (even from different domains). Cache meta tags are completely ignored.

**Comment by cody-lettau** [comment]
@aldrashan we fixed this issue by adding cache headers to our HTML resources in our S3 buckers (this will depend on how your storage and CDN are configured to serve the resources though).

```Cache-Control:no-cache, no-store```

In addition, we added those metatags to our HTML pages and also are adding a version parameter to the end of the URLs (i.e. ```?version=v1.2.3```)
