### ISSUE TITLE
 OfficeJS getResourceFieldAsync(Project) is failing on significant fields and not completing properly

### ISSUE THREAD

**Issue by ragavanrajan** [OfficeDev/office-js#966]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Our project add-in was running properly so far but not on the recent build which is using traditional edge browser. To confirm Add-in using edge browser

![image](https://user-images.githubusercontent.com/6369107/73688922-f81f6c80-4731-11ea-951b-84667ca3db47.png)

```
 window.navigator.userAgent
    
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64; WebView/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363"
```

## Expected Behavior
[getResourceFieldAsync](https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=common-js#getresourcefieldasync-resourceid--fieldid--options--callback-) should successfully return field values ( Ex: resource Name or Guid)

## Current Behavior
Instead it is incomplete or some times failing. (Promise is not complete). Screenshot below. 

![image](https://user-images.githubusercontent.com/6369107/73689221-9f9c9f00-4732-11ea-8067-c76f829b3c2e.png)

Expecting three resources but printed only two: 

Following are the fields which we are using
```
 1. Office.ProjectResourceFields.Name, 
 2. Office.ProjectResourceFields.ResourceGUID
```

## Steps to Reproduce, or Live Example

* Link to live example: ______
1. Create empty project 
2. Add three or more resources and assign it to the task 
3. call [[getResourceFieldAsync]](https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=common-js#getresourcefieldasync-resourceid--fieldid--options--callback-) by passing the (name, resourceGuid) 
4. Check in console- only few resources are fetched for sure the last resource is incomplete. 

## Your Environment

* Host: Project
1.Windows 10 : Version 1909 (OS Build 18363.628)
2.Microsoft Project Online Desktop Client MSO(16.0.12430.20172) 64 bit, Version 2001 (Build 12430.20184 Click to Run) 

## Useful logs

- [x] Console errors
- [x] Screenshots
Also reported on StackOverflow. Please [click ](https://stackoverflow.com/questions/60046963/officejs-getresourcefieldasync-is-failing-on-significant-fields-and-not-completi)here.

**Comment by ragavanrajan** [comment]
Dear Microsoft, Kindly update on this please.

**Comment by girazuzta** [comment]
same thing happening to me
it fails constantly (result.status === Office.AsyncResultStatus.Failed)
when I get this result I re run the query, but fails over and over again to get the same resource data.

**Comment by girazuzta** [comment]
Problem solved
The promise returns "failed" when several promises are hold at the same time and one function is trying to handle all the resolutions at once. For instance, you use a loop from the first resource to getResourceMaxIndexAsync to iterate getResourceByIndexAsync and getResourceFieldAsync for each field that you need using Promise.all, at the end of the iteration you handle the resolution before passing to the other, for example pushing the data to an array. The problem is that the loop continues before getting the resolution and promises start to stack generating the issues. 
I solve this creating a custom function that invoques getResourceFieldAsync, then directly searchs for the index in a previously generated resource array and update the corresponding property with the returned value. The loop that iterates through all the  resources just invoque this function, it doesn´t handle the promise resolution.
