### ISSUE TITLE
Word Online Search not working as expected with terms starting with '@' or '#' and 'matchWholeWord'

### ISSUE THREAD

**Issue by leoseccia** [OfficeDev/office-js#985]
The context.document.body.search API doesn't work if matchWholeWord is set to true in SearchOptions and the search term starts with the symbol `@` or `#`. It works in Windows Desktop Word application. Did not test with other symbols but this issue would seem related to: #218 

## Expected Behavior
The search should return results even if the search term starts with a symbol such as `@` or `#`.

## Current Behavior
The search does not return results even if the search term starts with a symbol such as `@` or `#`.

## Steps to Reproduce, or Live Example
1. Open Word Online
2. Add some text using `=rand(3)`
3. Insert the terms `@userhandle` and `#topic` anywhere in the text
4. Run the following [Script Lab gist](https://gist.github.com/leoseccia/cbebc6b427d56d28fec93b920e14e304)

## Context
I am working on an add-in that looks for mentions and user handles. 
**NB.** It works as expected in the Windows Desktop Word application. 

## Your Environment
Platform: Office Online
Host: Word
Operating System: Windows
Browser (if using Office Online): Chrome

**Comment by XiangGaoMSFT** [comment]
@leoseccia thanks for reaching out.
It's by-design behavior currently because the API's behavior is the same as the UI feature of Word on the web. You can try the UI feature by pressing Ctrl+F with "Find whole words only" option enabled.

If you think the behavior is not correct, you may provide feedback to Word on the web team by clicking the "Give feedback to Microsoft" button on the bottom right.
![image](https://user-images.githubusercontent.com/38523755/74700062-735a4580-523d-11ea-9f75-d375dbf69c95.png)
